function MessageItem(strCode, strText)
{
	var data    = new Array;
	data.Code  = strCode;
	data.Text  = strText;
	return(data);
}

function SetMessage()
{
	var i=0;
	gMSG[i++]=MessageItem("M0001","Can not specification word.");
	gMSG[i++]=MessageItem("M0002","$1 not found.");
	gMSG[i++]=MessageItem("M0003","Title not found\n");
	gMSG[i++]=MessageItem("M0004","Search title is $1 records.\n\nContinue Search ?");
	gMSG[i++]=MessageItem("M1001","Search title count is $1 titles.");
	gMSG[i++]=MessageItem("M1002","Processing:$1%.");
	gMSG[i++]=MessageItem("M1003","Processing completed.");
	gMSG[i++]=MessageItem("M1004","Data Loading from '$1'.");
	gMSG[i++]=MessageItem("M1005","ESM Initialize Completed.");
	gMSG[i++]=MessageItem("M9001","Unknow request; param='$1'");
	gMSG[i++]=MessageItem("M9990","Execute the Microsoft Internet Explorer.");
	gMSG[i++]=MessageItem("M9991","Execute Internet Explorer Version more than 5.0.");
	gMSG[i++]=MessageItem("M9992","Execute under the Win32 only.");
}
