with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" src=\"../img/S3YYA00F18100000000BBAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:16px;top:113px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:1px;top:137px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>STEERING WHEEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:85px;top:275px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGNITION<br>SWITCH<br>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:361px;top:143px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>0.3 sec.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:3px;top:224px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Turned to straight<br>ahead driving<br>position and released<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:416px;top:275px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGNITION<br>SWITCH<br>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:166px;top:123px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Within<br>4 sec.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:235px;top:123px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Within<br>4 sec.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:296px;top:124px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Within<br>4 sec.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:74px;top:155px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:101px;top:258px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:171px;top:219px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:233px;top:158px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:297px;top:219px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:442px;top:259px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:348px;top:52px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>0.3 sec.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:3px;top:36px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EPS INDICATOR LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:118px;top:62px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4 sec.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:3px;top:179px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Turned 45° to the<br>left and held<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:16px;top:72px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:245px;top:62px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4 sec.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:186px;top:186px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4 sec.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:313px;top:186px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4 sec.<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}