with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:575px;\" coordsize=\"950,575\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:575px;\">");
write("<img id=\"img1\" src=\"../img/S3YYE00J32300016301FHAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:575px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:330px;top:45px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>Terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:101px;top:98px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:377px;top:159px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:673px;top:72px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:380px;top:274px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:749px;top:72px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:83px;top:201px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>CEILING LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:406px;top:389px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:412px;top:332px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:99px;top:418px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>SPOTLIGHTS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:519px;top:72px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:351px;top:217px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>MIDDLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:355px;top:475px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:355px;top:360px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:406px;top:504px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:412px;top:447px;font-weight:normal;font-size:18.5pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}