with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:836px;\" coordsize=\"950,836\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:836px;\">");
write("<img id=\"img1\" src=\"../img/S6M2E00H46400000000AAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:836px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:544px;top:578px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:557px;top:264px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:544px;top:500px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:330px;top:185px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:559px;top:185px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:543px;top:107px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:544px;top:28px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:344px;top:28px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:224px;top:500px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:222px;top:28px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:425px;top:62px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>CABLE<br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:402px;top:161px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>DASHBOARD WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:401px;top:236px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>FLOOR<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:400px;top:394px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>ENGINE COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:401px;top:472px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>SRS FRONT SENSOR<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:148px;top:431px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>SRS<br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:659px;top:64px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>DRIVER'S<br>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:659px;top:135px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>FRONT<br>PASSENGER'S<br>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:659px;top:212px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>LEFT SIDE<br>SEAT BELT<br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:660px;top:291px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>RIGHT SIDE<br>SEAT BELT<br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:670px;top:369px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>LEFT<br>FRONT<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:671px;top:449px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>RIGHT<br>FRONT<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:661px;top:532px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>DRIVER'S<br>SIDE AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:660px;top:604px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>FRONT<br>PASSENGER'S<br>SIDE AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:669px;top:683px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>DRIVER'S<br>SIDE IMPACT<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:670px;top:753px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>FRONT<br>PASSENGER'S<br>SIDE IMPACT<br>SENSOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}