with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" src=\"../img/SAA2E00000000000000EBA301.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:307px;top:212px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:9px;top:569px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:143px;top:569px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:276px;top:569px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:276px;top:235px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:144px;top:235px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:11px;top:235px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:47px;top:215px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ECM/PCM ‹19−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:396px;top:279px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:397px;top:440px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:308px;top:246px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:308px;top:279px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:14px;top:331px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:63px;top:432px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:41px;top:279px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:128px;top:279px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:175px;top:279px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:196px;top:432px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:128px;top:440px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:147px;top:331px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:107px;top:289px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>IGPLS2E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:241px;top:289px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>IGPLS1E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:281px;top:331px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:261px;top:440px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:330px;top:432px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:271px;top:279px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:261px;top:774px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:281px;top:665px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:241px;top:623px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>IGPLS1I<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:107px;top:623px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>IGPLS2I<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:147px;top:665px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:128px;top:774px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:196px;top:763px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:175px;top:613px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:128px;top:613px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:41px;top:613px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:63px;top:763px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:14px;top:665px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:47px;top:548px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ECM/PCM ‹19−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:271px;top:613px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:330px;top:763px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:308px;top:613px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:487px;top:330px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:551px;top:78px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:513px;top:79px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.1 (80A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:451px;top:112px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:453px;top:134px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:440px;top:188px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:473px;top:281px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" class=\"drag\" style=\"position:absolute;left:421px;top:189px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>(15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" class=\"drag\" style=\"position:absolute;left:421px;top:180px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" class=\"drag\" style=\"position:absolute;left:332px;top:180px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" class=\"drag\" style=\"position:absolute;left:332px;top:189px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>(15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" class=\"drag\" style=\"position:absolute;left:473px;top:164px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>*1 :<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" class=\"drag\" style=\"position:absolute;left:473px;top:183px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>*2 :<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" class=\"drag\" style=\"position:absolute;left:557px;top:144px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" class=\"drag\" style=\"position:absolute;left:513px;top:146px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>No.16 (7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" class=\"drag\" style=\"position:absolute;left:351px;top:188px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" class=\"drag\" style=\"position:absolute;left:578px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" class=\"drag\" style=\"position:absolute;left:461px;top:146px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" class=\"drag\" style=\"position:absolute;left:513px;top:134px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" class=\"drag\" style=\"position:absolute;left:513px;top:123px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" class=\"drag\" style=\"position:absolute;left:513px;top:112px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" class=\"drag\" style=\"position:absolute;left:513px;top:68px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" class=\"drag\" style=\"position:absolute;left:453px;top:123px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" class=\"drag\" style=\"position:absolute;left:346px;top:349px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>REAR <br>IGNITION <br>COILS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" class=\"drag\" style=\"position:absolute;left:480px;top:355px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>OPDS <br>UNIT <br>‹16−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" class=\"drag\" style=\"position:absolute;left:341px;top:483px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>SPARK <br>PLUGS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" class=\"drag\" style=\"position:absolute;left:491px;top:164px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>UNDER−HOOD<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" class=\"drag\" style=\"position:absolute;left:491px;top:183px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>UNDER−DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" class=\"drag\" style=\"position:absolute;left:346px;top:677px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>FRONT <br>IGNITION <br>COILS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" class=\"drag\" style=\"position:absolute;left:341px;top:816px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>SPARK <br>PLUGS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" class=\"drag\" style=\"position:absolute;left:348px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}