with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:735px;\" coordsize=\"950,735\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:735px;\">");
write("<img id=\"img1\" src=\"../img/SAA2E0AJ46127053901MFAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:735px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:513px;top:99px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SEAT CUSHION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:622px;top:312px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOOK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:393px;top:112px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOOKS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:397px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Release the seat cushion<br>cover from the cushion<br>frame spring.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:172px;top:43px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SEAT-BACK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:31px;top:61px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEADREST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:259px;top:611px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOOK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:41px;top:217px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>47 N·m <br>(4.8 kgf·m, 35 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:728px;top:241px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOOKS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:599px;top:125px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOOKS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:78px;top:390px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE AIRBAG <br>HARNESS<br>(For some models)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:643px;top:339px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CENTER COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:745px;top:181px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SLIDE CABLE<br>(With dive down assist)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:590px;top:429px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:600px;top:569px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SEAT CUSHION <br>FRAME/SEAT<br>TRACKS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:536px;top:704px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SLIDE CABLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:264px;top:391px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:421px;top:576px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:79px;top:521px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RECLINE COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:126px;top:596px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RECLINE KNOB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:106px;top:467px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOOK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:598px;top:511px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SLIDE <br>CABLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:575px;top:634px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SLIDE CABLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:38px;top:318px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HANGER SPRING<br>(With side airbag)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:770px;top:289px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SLIDE CABLE<br>(With dive down assist)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:485px;top:334px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLIP<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}