with(document) {
write("<v:group id=\"group14\" class=\"drag\" style=\"position:relative; width:950px; height:1085px;\" coordsize=\"950,1085\">");
write("<v:rect id=\"rect14\"class=\"drag\"  style=\"width:950px;height:1085px;\">");
write("<img id=\"img14\" src=\"../img/SAA2EA2A20300047201CAAD17.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1085px;border-color:#ffffff\">");
write("<p id=\"p14_1\" class=\"drag\" style=\"position:absolute;left:297px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_2\" class=\"drag\" style=\"position:absolute;left:297px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p14_3\" class=\"drag\" style=\"position:absolute;left:297px;top:163px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_4\" class=\"drag\" style=\"position:absolute;left:297px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p14_5\" class=\"drag\" style=\"position:absolute;left:297px;top:206px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p14_6\" class=\"drag\" style=\"position:absolute;left:270px;top:206px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p14_7\" class=\"drag\" style=\"position:absolute;left:270px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p14_8\" class=\"drag\" style=\"position:absolute;left:270px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p14_9\" class=\"drag\" style=\"position:absolute;left:270px;top:163px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p14_10\" class=\"drag\" style=\"position:absolute;left:270px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p14_11\" class=\"drag\" style=\"position:absolute;left:184px;top:235px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p14_12\" class=\"drag\" style=\"position:absolute;left:211px;top:206px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p14_13\" class=\"drag\" style=\"position:absolute;left:211px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p14_14\" class=\"drag\" style=\"position:absolute;left:211px;top:235px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p14_15\" class=\"drag\" style=\"position:absolute;left:297px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p14_16\" class=\"drag\" style=\"position:absolute;left:297px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p14_17\" class=\"drag\" style=\"position:absolute;left:184px;top:206px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p14_18\" class=\"drag\" style=\"position:absolute;left:185px;top:221px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p14_19\" class=\"drag\" style=\"position:absolute;left:270px;top:120px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p14_20\" class=\"drag\" style=\"position:absolute;left:270px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p14_21\" class=\"drag\" style=\"position:absolute;left:184px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p14_22\" class=\"drag\" style=\"position:absolute;left:184px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p14_23\" class=\"drag\" style=\"position:absolute;left:184px;top:163px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p14_24\" class=\"drag\" style=\"position:absolute;left:184px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p14_25\" class=\"drag\" style=\"position:absolute;left:184px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p14_26\" class=\"drag\" style=\"position:absolute;left:211px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p14_27\" class=\"drag\" style=\"position:absolute;left:211px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p14_28\" class=\"drag\" style=\"position:absolute;left:211px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p14_29\" class=\"drag\" style=\"position:absolute;left:211px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p14_30\" class=\"drag\" style=\"position:absolute;left:101px;top:235px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p14_31\" class=\"drag\" style=\"position:absolute;left:101px;top:220px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p14_32\" class=\"drag\" style=\"position:absolute;left:101px;top:206px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p14_33\" class=\"drag\" style=\"position:absolute;left:101px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p14_34\" class=\"drag\" style=\"position:absolute;left:184px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p14_35\" class=\"drag\" style=\"position:absolute;left:125px;top:206px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p14_36\" class=\"drag\" style=\"position:absolute;left:125px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p14_37\" class=\"drag\" style=\"position:absolute;left:211px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_38\" class=\"drag\" style=\"position:absolute;left:101px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p14_39\" class=\"drag\" style=\"position:absolute;left:132px;top:57px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p14_40\" class=\"drag\" style=\"position:absolute;left:132px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p14_41\" class=\"drag\" style=\"position:absolute;left:150px;top:57px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p14_42\" class=\"drag\" style=\"position:absolute;left:150px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p14_43\" class=\"drag\" style=\"position:absolute;left:169px;top:52px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p14_44\" class=\"drag\" style=\"position:absolute;left:169px;top:71px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p14_45\" class=\"drag\" style=\"position:absolute;left:169px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p14_46\" class=\"drag\" style=\"position:absolute;left:187px;top:52px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p14_47\" class=\"drag\" style=\"position:absolute;left:187px;top:71px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p14_48\" class=\"drag\" style=\"position:absolute;left:187px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p14_49\" class=\"drag\" style=\"position:absolute;left:206px;top:71px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p14_50\" class=\"drag\" style=\"position:absolute;left:206px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p14_51\" class=\"drag\" style=\"position:absolute;left:225px;top:53px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p14_52\" class=\"drag\" style=\"position:absolute;left:225px;top:71px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p14_53\" class=\"drag\" style=\"position:absolute;left:225px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p14_54\" class=\"drag\" style=\"position:absolute;left:246px;top:52px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p14_55\" class=\"drag\" style=\"position:absolute;left:264px;top:52px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p14_56\" class=\"drag\" style=\"position:absolute;left:283px;top:52px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_57\" class=\"drag\" style=\"position:absolute;left:283px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p14_58\" class=\"drag\" style=\"position:absolute;left:264px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p14_59\" class=\"drag\" style=\"position:absolute;left:387px;top:377px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_60\" class=\"drag\" style=\"position:absolute;left:411px;top:378px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p14_61\" class=\"drag\" style=\"position:absolute;left:416px;top:324px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_62\" class=\"drag\" style=\"position:absolute;left:375px;top:280px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C373<sup>*2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p14_63\" class=\"drag\" style=\"position:absolute;left:758px;top:413px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p14_64\" class=\"drag\" style=\"position:absolute;left:758px;top:370px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_65\" class=\"drag\" style=\"position:absolute;left:783px;top:371px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p14_66\" class=\"drag\" style=\"position:absolute;left:758px;top:385px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_67\" class=\"drag\" style=\"position:absolute;left:758px;top:399px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p14_68\" class=\"drag\" style=\"position:absolute;left:761px;top:317px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_69\" class=\"drag\" style=\"position:absolute;left:747px;top:273px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C375<sup>*2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p14_70\" class=\"drag\" style=\"position:absolute;left:613px;top:428px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p14_71\" class=\"drag\" style=\"position:absolute;left:244px;top:377px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_72\" class=\"drag\" style=\"position:absolute;left:268px;top:378px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p14_73\" class=\"drag\" style=\"position:absolute;left:244px;top:392px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_74\" class=\"drag\" style=\"position:absolute;left:273px;top:319px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_75\" class=\"drag\" style=\"position:absolute;left:232px;top:280px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C372<sup>*2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p14_76\" class=\"drag\" style=\"position:absolute;left:89px;top:280px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C371<sup>*2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p14_77\" class=\"drag\" style=\"position:absolute;left:104px;top:324px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_78\" class=\"drag\" style=\"position:absolute;left:101px;top:406px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p14_79\" class=\"drag\" style=\"position:absolute;left:101px;top:392px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_80\" class=\"drag\" style=\"position:absolute;left:125px;top:378px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p14_81\" class=\"drag\" style=\"position:absolute;left:101px;top:377px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_82\" class=\"drag\" style=\"position:absolute;left:101px;top:420px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p14_83\" class=\"drag\" style=\"position:absolute;left:444px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_84\" class=\"drag\" style=\"position:absolute;left:468px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p14_85\" class=\"drag\" style=\"position:absolute;left:468px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p14_86\" class=\"drag\" style=\"position:absolute;left:444px;top:120px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_87\" class=\"drag\" style=\"position:absolute;left:482px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_88\" class=\"drag\" style=\"position:absolute;left:463px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_89\" class=\"drag\" style=\"position:absolute;left:432px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C302<sup>*2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p14_90\" class=\"drag\" style=\"position:absolute;left:590px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C303<sup>*2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p14_91\" class=\"drag\" style=\"position:absolute;left:639px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_92\" class=\"drag\" style=\"position:absolute;left:601px;top:120px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_93\" class=\"drag\" style=\"position:absolute;left:625px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p14_94\" class=\"drag\" style=\"position:absolute;left:601px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_95\" class=\"drag\" style=\"position:absolute;left:615px;top:413px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p14_96\" class=\"drag\" style=\"position:absolute;left:615px;top:399px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p14_97\" class=\"drag\" style=\"position:absolute;left:615px;top:385px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p14_98\" class=\"drag\" style=\"position:absolute;left:615px;top:370px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p14_99\" class=\"drag\" style=\"position:absolute;left:530px;top:428px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p14_100\" class=\"drag\" style=\"position:absolute;left:601px;top:314px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p14_101\" class=\"drag\" style=\"position:absolute;left:638px;top:314px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p14_102\" class=\"drag\" style=\"position:absolute;left:530px;top:413px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p14_103\" class=\"drag\" style=\"position:absolute;left:554px;top:428px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p14_104\" class=\"drag\" style=\"position:absolute;left:554px;top:399px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_105\" class=\"drag\" style=\"position:absolute;left:530px;top:399px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p14_106\" class=\"drag\" style=\"position:absolute;left:530px;top:385px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_107\" class=\"drag\" style=\"position:absolute;left:554px;top:385px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p14_108\" class=\"drag\" style=\"position:absolute;left:530px;top:370px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_109\" class=\"drag\" style=\"position:absolute;left:583px;top:314px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_110\" class=\"drag\" style=\"position:absolute;left:518px;top:273px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C374<sup>*2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p14_111\" class=\"drag\" style=\"position:absolute;left:758px;top:120px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_112\" class=\"drag\" style=\"position:absolute;left:783px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p14_113\" class=\"drag\" style=\"position:absolute;left:783px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_114\" class=\"drag\" style=\"position:absolute;left:758px;top:134px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_115\" class=\"drag\" style=\"position:absolute;left:758px;top:148px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p14_116\" class=\"drag\" style=\"position:absolute;left:783px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p14_117\" class=\"drag\" style=\"position:absolute;left:806px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p14_118\" class=\"drag\" style=\"position:absolute;left:787px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_119\" class=\"drag\" style=\"position:absolute;left:768px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_120\" class=\"drag\" style=\"position:absolute;left:747px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C304<sup>*2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p14_121\" class=\"drag\" style=\"position:absolute;left:102px;top:949px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: RHD<br></b></nobr>");
write("</p>");
write("<p id=\"p14_122\" class=\"drag\" style=\"position:absolute;left:77px;top:949px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_123\" class=\"drag\" style=\"position:absolute;left:89px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C301<sup>*2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p14_124\" class=\"drag\" style=\"position:absolute;left:101px;top:120px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_125\" class=\"drag\" style=\"position:absolute;left:125px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p14_126\" class=\"drag\" style=\"position:absolute;left:101px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_127\" class=\"drag\" style=\"position:absolute;left:101px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p14_128\" class=\"drag\" style=\"position:absolute;left:125px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p14_129\" class=\"drag\" style=\"position:absolute;left:125px;top:163px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_130\" class=\"drag\" style=\"position:absolute;left:101px;top:163px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p14_131\" class=\"drag\" style=\"position:absolute;left:152px;top:1033px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with female terminals (single outline) : View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p14_132\" class=\"drag\" style=\"position:absolute;left:152px;top:1019px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with male terminals (double outline) : View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p14_133\" class=\"drag\" style=\"position:absolute;left:77px;top:1019px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p14_134\" class=\"drag\" style=\"position:absolute;left:133px;top:1047px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>· <br></b></nobr>");
write("</p>");
write("<p id=\"p14_135\" class=\"drag\" style=\"position:absolute;left:171px;top:1047px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to PCM control.<br></b></nobr>");
write("</p>");
write("<p id=\"p14_136\" class=\"drag\" style=\"position:absolute;left:132px;top:1033px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>· <br></b></nobr>");
write("</p>");
write("<p id=\"p14_137\" class=\"drag\" style=\"position:absolute;left:132px;top:1019px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>· <br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}