with(document) {
write("<v:group id=\"group11\" class=\"drag\" style=\"position:relative; width:950px; height:767px;\" coordsize=\"950,767\">");
write("<v:rect id=\"rect11\"class=\"drag\"  style=\"width:950px;height:767px;\">");
write("<img id=\"img11\" src=\"../img/SAA2EA0A20300000000DBAD38.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:767px;border-color:#ffffff\">");
write("<p id=\"p11_1\" class=\"drag\" style=\"position:absolute;left:221px;top:14px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASH BOARD<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p11_2\" class=\"drag\" style=\"position:absolute;left:71px;top:115px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p11_3\" class=\"drag\" style=\"position:absolute;left:17px;top:231px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p11_4\" class=\"drag\" style=\"position:absolute;left:118px;top:427px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C256<br></b></nobr>");
write("</p>");
write("<p id=\"p11_5\" class=\"drag\" style=\"position:absolute;left:94px;top:697px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C257<br></b></nobr>");
write("</p>");
write("<p id=\"p11_6\" class=\"drag\" style=\"position:absolute;left:247px;top:691px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p11_7\" class=\"drag\" style=\"position:absolute;left:340px;top:717px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C255<br></b></nobr>");
write("</p>");
write("<p id=\"p11_8\" class=\"drag\" style=\"position:absolute;left:398px;top:729px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C351<br></b></nobr>");
write("</p>");
write("<p id=\"p11_9\" class=\"drag\" style=\"position:absolute;left:455px;top:737px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C352<br></b></nobr>");
write("</p>");
write("<p id=\"p11_10\" class=\"drag\" style=\"position:absolute;left:542px;top:737px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C353<br></b></nobr>");
write("</p>");
write("<p id=\"p11_11\" class=\"drag\" style=\"position:absolute;left:555px;top:693px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BACK SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p11_12\" class=\"drag\" style=\"position:absolute;left:820px;top:639px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C211<br></b></nobr>");
write("</p>");
write("<p id=\"p11_13\" class=\"drag\" style=\"position:absolute;left:840px;top:592px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C212<br></b></nobr>");
write("</p>");
write("<p id=\"p11_14\" class=\"drag\" style=\"position:absolute;left:857px;top:522px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C354<br></b></nobr>");
write("</p>");
write("<p id=\"p11_15\" class=\"drag\" style=\"position:absolute;left:877px;top:454px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C252<br></b></nobr>");
write("</p>");
write("<p id=\"p11_16\" class=\"drag\" style=\"position:absolute;left:866px;top:409px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C254<br></b></nobr>");
write("</p>");
write("<p id=\"p11_17\" class=\"drag\" style=\"position:absolute;left:392px;top:82px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C253<br></b></nobr>");
write("</p>");
write("<p id=\"p11_18\" class=\"drag\" style=\"position:absolute;left:638px;top:79px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C251<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}