with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img1\" src=\"../img/SAA2EK0J54260400000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:559px;top:377px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>POSITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:738px;top:826px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Blower motor (Via blower motor relay)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:766px;top:884px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:766px;top:895px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(To page 22−57)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:766px;top:873px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:766px;top:644px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:766px;top:667px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(To page 22−59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:766px;top:655px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:242px;top:991px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>22−55<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:242px;top:980px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>To page<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:77px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>22−56<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:73px;top:414px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:73px;top:402px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:766px;top:341px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:766px;top:352px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(To page 22−59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:766px;top:330px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:766px;top:227px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:738px;top:498px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Horn switch (Via cable reel)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:579px;top:283px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:645px;top:340px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:559px;top:388px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Closed : Pedal pressed)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:559px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRAKE PEDAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:735px;top:227px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:766px;top:215px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:766px;top:238px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(To page 22−58)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:581px;top:226px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:318px;top:211px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.14 (10A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:738px;top:170px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ABS modulator−control unit (MR+B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:239px;top:112px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:582px;top:55px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:766px;top:764px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IGNITION SWITCH (+B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:766px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(To page 22−56)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:73px;top:380px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.16 (7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:738px;top:284px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ABS modulator−control unit  (FSR+B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:77px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>From page<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:96px;top:183px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:81px;top:112px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:154px;top:30px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:738px;top:55px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Starter motor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:738px;top:427px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Horn<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:318px;top:325px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.16 (15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:320px;top:868px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.6 (40A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:320px;top:811px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.5 (40A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:320px;top:754px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.3 (50A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:320px;top:697px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.2 (40A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:735px;top:885px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:593px;top:884px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:582px;top:827px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:735px;top:770px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:593px;top:770px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:582px;top:712px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:735px;top:656px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:735px;top:342px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:270px;top:471px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:270px;top:482px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(80A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:738px;top:712px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>EPS control unit (+B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:581px;top:655px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:353px;top:613px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ELD UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:73px;top:391px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:94px;top:691px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:91px;top:755px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:97px;top:456px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:93px;top:512px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:170px;top:512px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:147px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ALTERNATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:402px;top:394px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>HORN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:338px;top:130px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:318px;top:268px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.15 (30A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:515px;top:341px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:593px;top:498px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:580px;top:427px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:580px;top:169px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:320px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.4 (40A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:256px;top:949px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}