with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:911px;\" coordsize=\"950,911\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:911px;\">");
write("<img id=\"img1\" src=\"../img/SAA2E02E15100000000CAAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:911px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:476px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:411px;top:70px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PGM-FI Control System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:327px;top:130px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Correction of intake air temperature<br>sensor signal data and others<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:364px;top:190px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CVT Control System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:393px;top:286px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Judgment of<br>driving mode<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:380px;top:419px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Fail-safe control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:383px;top:611px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Decision of start<br>clutch control<br>pressure<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:379px;top:787px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Fail-safe control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:37px;top:577px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Engine RPM Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:21px;top:526px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>Manifold Absolute<br>Pressure Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:21px;top:616px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CVT Drive Pulley Speed<br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:23px;top:664px;font-weight:normal;font-size:8.0pt;\">");
write("<nobr><b>CVT Driven Pulley Speed<br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:30px;top:412px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Transmission Range<br>Switch Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:21px;top:329px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Throttle Position<br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:33px;top:754px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CVT Speed Sensor<br>Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:600px;top:757px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Current<br>feedback<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:774px;top:759px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Start Clutch Pressure<br>Control Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:29px;top:246px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Brake Pedal Position<br>Switch Signal<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}