with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:639px;\" coordsize=\"950,639\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:639px;\">");
write("<img id=\"img1\" src=\"../img/SAA2E00D14300014711LAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:639px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:783px;top:163px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 x 1.25 mm<br>108 N·m (11.0 kgf·m,<br>80 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:730px;top:131px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CALIPER PIN B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:556px;top:201px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PISTON BOOT<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:541px;top:146px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PISTON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:505px;top:89px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PISTON SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:358px;top:78px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CALIPER BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:312px;top:18px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.0 mm<br>22 N·m (2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:19px;top:147px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BANJO BOLT<br>3.4 N·m<br>(3.5 kgf·m,<br>25 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:68px;top:225px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SEALING<br>WASHERS<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:186px;top:242px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLEED SCREW<br>8 N·m<br>(0.8 kgf·m, 6 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:369px;top:294px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WEAR INDICATOR<br></b>Install inner pad with<br>its wear indicator upward.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:424px;top:356px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRAKE PADS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:183px;top:480px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INNER PAD SHIMS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:186px;top:593px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PAD SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:367px;top:561px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PAD SHIM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:851px;top:472px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CALIPER<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:727px;top:533px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PAD RETAINERS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:668px;top:610px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BOOTS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:512px;top:429px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CALIPER PIN A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:104px;top:27px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>:Rubber greese<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:104px;top:58px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>:Silicone greese<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}