with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:319px;\" coordsize=\"950,319\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:319px;\">");
write("<img id=\"img2\" src=\"../img/SAA2EA2E15117700000CAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:319px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:477px;top:284px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>62 mph (100 km/h)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:661px;top:284px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Vehicle speed<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:245px;top:153px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3,000<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:184px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Engine RPM<br>rpm (min<sup>−1</sup>)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:413px;top:218px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>AUTOMATIC DOWNSHIFTING AREA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:411px;top:25px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>AUTOMATIC UPSHIFTING AREA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:358px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1st<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:412px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2nd<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:457px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3rd<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:498px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4th<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:551px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5th<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:609px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6th<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:689px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>7th<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}