with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:831px;\" coordsize=\"950,831\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:831px;\">");
write("<img id=\"img1\" src=\"../img/SAA2E02E15100000000CAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:831px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:332px;top:798px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FINAL DRIVEN GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:409px;top:14px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STEEL BELT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:334px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVE<br>PULLEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:170px;top:14px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REVERSE BRAKE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:77px;top:45px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PLANETARY CARRIER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:112px;top:89px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PLANETARY<br>PINION GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:109px;top:170px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INPUT SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:132px;top:254px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SUN GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:126px;top:303px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RING GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:110px;top:340px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FORWARD CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:110px;top:450px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVEN PULLEY SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:222px;top:528px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVEN PULLEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:235px;top:568px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY DRIVE GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:262px;top:631px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY DRIVEN GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:681px;top:588px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FINAL DRIVE GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:745px;top:534px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FINAL DRIVE SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:740px;top:447px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>START CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:727px;top:37px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLYWHEEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:503px;top:56px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVE PULLEY<br>SHAFT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}