with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:565px;\" coordsize=\"950,565\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:565px;\">");
write("<img id=\"img1\" src=\"../img/SAA2E00H46400000000CAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:565px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:648px;top:521px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:648px;top:502px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RIGHT SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:648px;top:512px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SEAT BELT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:568px;top:512px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SEAT BELT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:568px;top:502px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LEFT SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:568px;top:521px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:165px;top:149px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:739px;top:192px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:431px;top:502px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:431px;top:512px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:431px;top:521px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:491px;top:521px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:491px;top:512px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:491px;top:502px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RIGHT <br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:301px;top:334px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>MICROPROCESSOR and DIAGNOSTIC CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:729px;top:29px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DRIVER'S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:739px;top:183px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CABLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:254px;top:168px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:254px;top:158px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>OPDS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:248px;top:133px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:248px;top:124px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>OPDS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:729px;top:39px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:729px;top:48px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>FIRST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:729px;top:57px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:645px;top:57px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:645px;top:48px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SIDE AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:645px;top:39px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DRIVER'S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:806px;top:39px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PASSENGER'S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:806px;top:48px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:806px;top:57px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:806px;top:29px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:566px;top:48px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SIDE AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:566px;top:29px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:566px;top:57px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:566px;top:39px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PASSENGER'S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:180px;top:253px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:180px;top:244px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>POWER SUPPLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:234px;top:79px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:234px;top:88px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PASSENGER'S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:234px;top:97px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SEAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:165px;top:158px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:165px;top:168px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CUTOFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:165px;top:177px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:383px;top:151px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:312px;top:154px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DRIVER'S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:312px;top:163px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SIDE IMPACT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:312px;top:172px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:383px;top:178px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:383px;top:169px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SIDE IMPACT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:383px;top:160px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PASSENGER'S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:165px;top:367px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:165px;top:357px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IMPACT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:165px;top:348px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:165px;top:302px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>FRONTAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:148px;top:200px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SRS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:70px;top:334px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IMPACT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:365px;top:478px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:365px;top:488px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:125px;top:395px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:684px;top:334px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>TRIGGER CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:394px;top:451px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IDC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:351px;top:451px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:323px;top:451px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>MES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:289px;top:451px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DLC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:280px;top:394px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DATA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:280px;top:403px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LINK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:280px;top:412px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:223px;top:399px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>MEMORY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:223px;top:408px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:165px;top:312px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IMPACT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:165px;top:321px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:41px;top:238px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:41px;top:248px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>FUSE/RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:41px;top:257px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:132px;top:253px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>VA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:132px;top:224px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>VB<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}