with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SAA2E00J34300000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:172px;top:312px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MIRROR HOLDER<br><a href=\"javascript:parent.Cts('000000000000275','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:808px;top:75px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER MIRROR<br><a href=\"javascript:parent.Cts('000000000000278','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:557px;top:492px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCK BOLT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:183px;top:563px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCK WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:177px;top:710px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STAY BASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:681px;top:670px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MIRROR HOLDER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:120px;top:915px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REARVIEW MIRROR<br><a href=\"javascript:parent.Cts('000000000000274','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:603px;top:1072px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEADLINER CAP<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}