with(document) {
write("<v:group id=\"group6\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect6\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img6\" src=\"../img/SAA2E00J54230100000EAAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p6_1\" class=\"drag\" style=\"position:absolute;left:302px;top:304px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" class=\"drag\" style=\"position:absolute;left:274px;top:304px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" class=\"drag\" style=\"position:absolute;left:668px;top:334px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left back−up light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" class=\"drag\" style=\"position:absolute;left:668px;top:320px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" class=\"drag\" style=\"position:absolute;left:668px;top:306px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" class=\"drag\" style=\"position:absolute;left:790px;top:320px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(LHD)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" class=\"drag\" style=\"position:absolute;left:862px;top:529px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(RHD)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" class=\"drag\" style=\"position:absolute;left:487px;top:890px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" class=\"drag\" style=\"position:absolute;left:460px;top:890px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" class=\"drag\" style=\"position:absolute;left:274px;top:890px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" class=\"drag\" style=\"position:absolute;left:302px;top:890px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" class=\"drag\" style=\"position:absolute;left:668px;top:891px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear super locking actuator<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" class=\"drag\" style=\"position:absolute;left:668px;top:848px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear super locking actuator<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" class=\"drag\" style=\"position:absolute;left:302px;top:847px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" class=\"drag\" style=\"position:absolute;left:274px;top:847px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" class=\"drag\" style=\"position:absolute;left:460px;top:847px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" class=\"drag\" style=\"position:absolute;left:487px;top:847px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" class=\"drag\" style=\"position:absolute;left:668px;top:806px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear fog light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" class=\"drag\" style=\"position:absolute;left:668px;top:820px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear wiper intermittent control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p6_20\" class=\"drag\" style=\"position:absolute;left:302px;top:804px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p6_21\" class=\"drag\" style=\"position:absolute;left:274px;top:804px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_22\" class=\"drag\" style=\"position:absolute;left:294px;top:1026px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p6_23\" class=\"drag\" style=\"position:absolute;left:311px;top:1025px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p6_24\" class=\"drag\" style=\"position:absolute;left:318px;top:1027px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p6_25\" class=\"drag\" style=\"position:absolute;left:318px;top:1005px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p6_26\" class=\"drag\" style=\"position:absolute;left:311px;top:1004px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p6_27\" class=\"drag\" style=\"position:absolute;left:293px;top:1005px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p6_28\" class=\"drag\" style=\"position:absolute;left:668px;top:720px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Tailgate lock actuator (with super locking)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_29\" class=\"drag\" style=\"position:absolute;left:668px;top:734px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Tailgate key cylinder switch (with super locking)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_30\" class=\"drag\" style=\"position:absolute;left:668px;top:677px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>High mount brake light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_31\" class=\"drag\" style=\"position:absolute;left:668px;top:691px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear wiper motor<br></b></nobr>");
write("</p>");
write("<p id=\"p6_32\" class=\"drag\" style=\"position:absolute;left:668px;top:706px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear window defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p6_33\" class=\"drag\" style=\"position:absolute;left:675px;top:769px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>License plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_34\" class=\"drag\" style=\"position:absolute;left:668px;top:749px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Tailgate latch switch<br></b></nobr>");
write("</p>");
write("<p id=\"p6_35\" class=\"drag\" style=\"position:absolute;left:668px;top:620px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p6_36\" class=\"drag\" style=\"position:absolute;left:668px;top:634px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_37\" class=\"drag\" style=\"position:absolute;left:668px;top:649px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left back−up light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_38\" class=\"drag\" style=\"position:absolute;left:487px;top:676px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p6_39\" class=\"drag\" style=\"position:absolute;left:460px;top:676px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_40\" class=\"drag\" style=\"position:absolute;left:274px;top:676px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_41\" class=\"drag\" style=\"position:absolute;left:302px;top:676px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p6_42\" class=\"drag\" style=\"position:absolute;left:274px;top:619px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_43\" class=\"drag\" style=\"position:absolute;left:302px;top:619px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p6_44\" class=\"drag\" style=\"position:absolute;left:302px;top:562px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p6_45\" class=\"drag\" style=\"position:absolute;left:274px;top:562px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_46\" class=\"drag\" style=\"position:absolute;left:668px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear wiper intermittent control unit (LHD)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_47\" class=\"drag\" style=\"position:absolute;left:274px;top:461px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_48\" class=\"drag\" style=\"position:absolute;left:302px;top:461px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p6_49\" class=\"drag\" style=\"position:absolute;left:797px;top:377px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(LHD)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_50\" class=\"drag\" style=\"position:absolute;left:783px;top:241px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(LHD)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_51\" class=\"drag\" style=\"position:absolute;left:668px;top:363px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p6_52\" class=\"drag\" style=\"position:absolute;left:668px;top:377px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_53\" class=\"drag\" style=\"position:absolute;left:668px;top:391px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right back−up light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_54\" class=\"drag\" style=\"position:absolute;left:302px;top:419px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p6_55\" class=\"drag\" style=\"position:absolute;left:274px;top:419px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_56\" class=\"drag\" style=\"position:absolute;left:460px;top:419px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_57\" class=\"drag\" style=\"position:absolute;left:487px;top:419px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p6_58\" class=\"drag\" style=\"position:absolute;left:274px;top:361px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_59\" class=\"drag\" style=\"position:absolute;left:302px;top:361px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p6_60\" class=\"drag\" style=\"position:absolute;left:668px;top:277px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Tailgate latch switch<br></b></nobr>");
write("</p>");
write("<p id=\"p6_61\" class=\"drag\" style=\"position:absolute;left:675px;top:255px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>License plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_62\" class=\"drag\" style=\"position:absolute;left:668px;top:234px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear window defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p6_63\" class=\"drag\" style=\"position:absolute;left:668px;top:220px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear wiper motor<br></b></nobr>");
write("</p>");
write("<p id=\"p6_64\" class=\"drag\" style=\"position:absolute;left:668px;top:206px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>High mount brake light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_65\" class=\"drag\" style=\"position:absolute;left:487px;top:204px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p6_66\" class=\"drag\" style=\"position:absolute;left:460px;top:204px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_67\" class=\"drag\" style=\"position:absolute;left:274px;top:204px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_68\" class=\"drag\" style=\"position:absolute;left:302px;top:204px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p6_69\" class=\"drag\" style=\"position:absolute;left:668px;top:463px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear fog light (LHD)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_70\" class=\"drag\" style=\"position:absolute;left:302px;top:161px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p6_71\" class=\"drag\" style=\"position:absolute;left:274px;top:161px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_72\" class=\"drag\" style=\"position:absolute;left:274px;top:76px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_73\" class=\"drag\" style=\"position:absolute;left:301px;top:76px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p6_74\" class=\"drag\" style=\"position:absolute;left:93px;top:1005px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p6_75\" class=\"drag\" style=\"position:absolute;left:111px;top:1004px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p6_76\" class=\"drag\" style=\"position:absolute;left:118px;top:1005px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>EPS wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p6_77\" class=\"drag\" style=\"position:absolute;left:668px;top:34px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>EPS control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p6_78\" class=\"drag\" style=\"position:absolute;left:79px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p6_79\" class=\"drag\" style=\"position:absolute;left:668px;top:77px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>EPS motor relay<br></b></nobr>");
write("</p>");
write("<p id=\"p6_80\" class=\"drag\" style=\"position:absolute;left:668px;top:591px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right back−up light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_81\" class=\"drag\" style=\"position:absolute;left:79px;top:961px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p6_82\" class=\"drag\" style=\"position:absolute;left:668px;top:577px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p6_83\" class=\"drag\" style=\"position:absolute;left:668px;top:563px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p6_84\" class=\"drag\" style=\"position:absolute;left:94px;top:1047px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p6_85\" class=\"drag\" style=\"position:absolute;left:111px;top:1047px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p6_86\" class=\"drag\" style=\"position:absolute;left:118px;top:1048px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Tailgate wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p6_87\" class=\"drag\" style=\"position:absolute;left:79px;top:525px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p6_88\" class=\"drag\" style=\"position:absolute;left:668px;top:420px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>OPDS unit (KQ)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_89\" class=\"drag\" style=\"position:absolute;left:668px;top:163px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat belt switch<br></b></nobr>");
write("</p>");
write("<p id=\"p6_90\" class=\"drag\" style=\"position:absolute;left:118px;top:1027px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Floor wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p6_91\" class=\"drag\" style=\"position:absolute;left:111px;top:1025px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p6_92\" class=\"drag\" style=\"position:absolute;left:95px;top:1026px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p6_93\" class=\"drag\" style=\"position:absolute;left:301px;top:33px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p6_94\" class=\"drag\" style=\"position:absolute;left:274px;top:33px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}