with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:1130px;\" coordsize=\"950,1130\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:1130px;\">");
write("<img id=\"img2\" src=\"../img/SAA2E00J20100000000LEA290.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1130px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:62px;top:72px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ9 (0.35)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:62px;top:97px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ11 (0.43)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:61px;top:122px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ13 (0.51)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:42px;top:97px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>p<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:43px;top:122px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>q<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:43px;top:72px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>o<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:43px;top:23px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>m<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:62px;top:23px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ13 (0.51)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:43px;top:48px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>n<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:62px;top:48px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ26.2 (1.03)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:299px;top:72px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Trailing arm mount (inside)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:298px;top:97px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ17 (0.51)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:298px;top:122px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ26.2 (1.03)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:278px;top:97px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>s<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:278px;top:122px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>t<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:278px;top:72px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>r2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:278px;top:22px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>r<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:298px;top:22px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Trailing arm mount (center)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:278px;top:48px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>r1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:298px;top:48px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Trailing arm mount (outside)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:532px;top:22px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>u<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:552px;top:23px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Rear damper center φ20 (0.79)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:531px;top:48px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>v<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:552px;top:48px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ13 (0.51)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:531px;top:72px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>v<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:552px;top:73px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ20 (0.79)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:63px;top:243px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT m<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:120px;top:243px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT n<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:124px;top:220px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT p<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:147px;top:204px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT o<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:206px;top:212px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT r2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:275px;top:165px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT r<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:297px;top:229px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT q<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:366px;top:183px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT s<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:377px;top:211px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT t<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:287px;top:194px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT r1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:399px;top:237px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT u<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:473px;top:231px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT v<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:543px;top:246px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT w<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:737px;top:767px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>POINT r<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:673px;top:920px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>SECTION BB<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:314px;top:740px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:263px;top:648px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:181px;top:754px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>55 (2.17)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:181px;top:768px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>92 (3.62)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:181px;top:782px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>108 (4.3)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:181px;top:796px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>136 (5.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:267px;top:812px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>327 (12.9)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:267px;top:825px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>340 (13.9)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:267px;top:840px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>392 (15.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:370px;top:858px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>624 (24.6)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:370px;top:876px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>855 (33.7)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:790px;top:751px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>81 (3.19)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("<v:line id=\"bl2_1\" class=\"drag\" from=\"89,507\" to=\"88,416\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_1\" class=\"drag\" on=\"true\" string=\"737 (29.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.4pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_2\" class=\"drag\" from=\"117,506\" to=\"116,421\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_2\" class=\"drag\" on=\"true\" string=\"760 (29.9)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.4pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_3\" class=\"drag\" from=\"159,506\" to=\"158,390\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_3\" class=\"drag\" on=\"true\" string=\"946 (37.2)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.4pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_4\" class=\"drag\" from=\"178,537\" to=\"177,470\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_4\" class=\"drag\" on=\"true\" string=\"385 (15.2)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.4pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_5\" class=\"drag\" from=\"317,503\" to=\"316,407\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_5\" class=\"drag\" on=\"true\" string=\"1156 (45.51)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.4pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_6\" class=\"drag\" from=\"392,503\" to=\"391,405\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_6\" class=\"drag\" on=\"true\" string=\"1125 (44.29)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.4pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_7\" class=\"drag\" from=\"575,498\" to=\"574,433\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_7\" class=\"drag\" on=\"true\" string=\"210 (8.3)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.4pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_8\" class=\"drag\" from=\"589,491\" to=\"588,397\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_8\" class=\"drag\" on=\"true\" string=\"336 (13.2)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.4pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_9\" class=\"drag\" from=\"599,495\" to=\"598,384\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_9\" class=\"drag\" on=\"true\" string=\"960 (37.8)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.4pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_10\" class=\"drag\" from=\"611,494\" to=\"610,380\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_10\" class=\"drag\" on=\"true\" string=\"989 (38.9)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.4pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_11\" class=\"drag\" from=\"578,596\" to=\"577,527\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_11\" class=\"drag\" on=\"true\" string=\"310 (12.2)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.4pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_12\" class=\"drag\" from=\"589,595\" to=\"588,521\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_12\" class=\"drag\" on=\"true\" string=\"332 (13.1)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.4pt;\"/>");
write("</v:line>");
write("</v:group>");
}