with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" src=\"../img/SAA2E00000000000000EBA313.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:417px;top:188px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:434px;top:188px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: With entry light control system<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:425px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:495px;top:701px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>51<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:394px;top:771px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>UN−<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:394px;top:780px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:226px;top:780px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:114px;top:717px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:91px;top:717px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:367px;top:878px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:374px;top:822px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:375px;top:717px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:103px;top:822px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:95px;top:878px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:82px;top:780px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:30px;top:703px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>KEY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:81px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:104px;top:667px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:375px;top:667px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:248px;top:667px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:247px;top:822px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:239px;top:878px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:226px;top:700px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:509px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.6 (40A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:547px;top:100px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:553px;top:155px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:509px;top:157px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.17 (7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:447px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:458px;top:146px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:449px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:547px;top:89px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:509px;top:90px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.8 (15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:553px;top:144px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:509px;top:68px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:509px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:509px;top:146px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.16 (7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:509px;top:79px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.1 (80A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:547px;top:77px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:434px;top:179px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:417px;top:179px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:434px;top:170px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:417px;top:170px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*1 <br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:509px;top:134px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.22 (7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:553px;top:133px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:578px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:123px;top:770px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>UN−<br>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:267px;top:770px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>UN−<br>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:16px;top:754px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>DOOR <br>KEY <br>CYLINDER <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:154px;top:759px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TAILGATE <br>KEY <br>CYLINDER <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" class=\"drag\" style=\"position:absolute;left:299px;top:754px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S <br>DOOR <br>LOCK <br>KNOB <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" class=\"drag\" style=\"position:absolute;left:182px;top:699px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DOOR <br>LOCK KNOB<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" class=\"drag\" style=\"position:absolute;left:321px;top:699px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DOOR <br>LOCK KNOB<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" class=\"drag\" style=\"position:absolute;left:426px;top:759px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>DOOR LOCK <br>KNOB SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" class=\"drag\" style=\"position:absolute;left:466px;top:724px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" class=\"drag\" style=\"position:absolute;left:466px;top:743px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" class=\"drag\" style=\"position:absolute;left:348px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" class=\"drag\" style=\"position:absolute;left:473px;top:724px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>REAR DOOR LOCK <br>KNOB SWITCH ‹14−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" class=\"drag\" style=\"position:absolute;left:473px;top:743px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TAILGATE LOCK <br>KNOB SWITCH ‹14−A›<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}