with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:911px;\" coordsize=\"950,911\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:911px;\">");
write("<img id=\"img1\" src=\"../img/SAA2EA2E15111412282MFAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:911px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:718px;top:21px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LEVER KNOB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:763px;top:246px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/T GEAR POSITION<br>INDICATOR PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:770px;top:673px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LEVER COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:678px;top:781px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/T GEAR POSITION<br>INDICATOR<br>PANEL LIGHT BULB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:298px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SCREW<br>3 N·m (0.3 kgf·m, 2 lbf·ft)<br></b>Apply non-hardening thread<br>lock sealant.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:158px;top:243px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SILICONE<br>GREASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:72px;top:403px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LEVER ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:264px;top:880px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LOCK SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:142px;top:849px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PLUNGER SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:84px;top:791px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT LOCK<br>SOLENOID PLUNGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:43px;top:553px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SILICONE<br>GREASE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}