with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\" coordsize=\"950,554\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:554px;\">");
write("<img id=\"img2\" src=\"../img/SAA2EK0J22100000000EAAD91.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:576px;top:223px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:566px;top:240px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:566px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:799px;top:33px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:809px;top:33px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: Without super locking<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:799px;top:27px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:809px;top:27px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: With super locking<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:809px;top:22px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: Without entry light control system<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:741px;top:280px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FOG LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:741px;top:286px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:741px;top:292px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:741px;top:275px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:741px;top:298px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:733px;top:177px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:726px;top:151px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:721px;top:101px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:721px;top:113px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:721px;top:107px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FOG LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:668px;top:107px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FUSE/RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:668px;top:113px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:668px;top:101px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:566px;top:223px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:670px;top:151px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:683px;top:177px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:691px;top:298px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:691px;top:275px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:691px;top:292px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:691px;top:286px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:691px;top:280px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FOG LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:515px;top:229px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:515px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ENGINE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:599px;top:282px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:599px;top:276px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SRS INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:787px;top:109px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HAZARD SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:787px;top:104px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TURN SIGNAL/<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:516px;top:478px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Open<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:533px;top:478px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: Engine running<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:533px;top:473px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: Engine stopped<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:516px;top:473px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Closed<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:515px;top:461px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:515px;top:455px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ENGINE OIL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:515px;top:467px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:515px;top:240px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:515px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:515px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:515px;top:212px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LOW<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:515px;top:223px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>OIL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:641px;top:341px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:791px;top:280px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TURN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:791px;top:286px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SIGNAL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:791px;top:292px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:791px;top:275px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:791px;top:298px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" class=\"drag\" style=\"position:absolute;left:865px;top:113px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>fuse/relay box<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" class=\"drag\" style=\"position:absolute;left:862px;top:101px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.13 (20A) FUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" class=\"drag\" style=\"position:absolute;left:865px;top:107px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>In the under−hood<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" class=\"drag\" style=\"position:absolute;left:799px;top:22px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" class=\"drag\" style=\"position:absolute;left:809px;top:16px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: With entry light control system<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" class=\"drag\" style=\"position:absolute;left:799px;top:16px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" class=\"drag\" style=\"position:absolute;left:496px;top:411px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" class=\"drag\" style=\"position:absolute;left:508px;top:373px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" class=\"drag\" style=\"position:absolute;left:841px;top:298px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" class=\"drag\" style=\"position:absolute;left:824px;top:533px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" class=\"drag\" style=\"position:absolute;left:633px;top:177px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C27<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" class=\"drag\" style=\"position:absolute;left:841px;top:275px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" class=\"drag\" style=\"position:absolute;left:841px;top:292px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" class=\"drag\" style=\"position:absolute;left:841px;top:286px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SIGNAL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" class=\"drag\" style=\"position:absolute;left:841px;top:280px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TURN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" class=\"drag\" style=\"position:absolute;left:641px;top:330px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" class=\"drag\" style=\"position:absolute;left:552px;top:411px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" class=\"drag\" style=\"position:absolute;left:541px;top:445px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>OPDS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" class=\"drag\" style=\"position:absolute;left:546px;top:390px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" class=\"drag\" style=\"position:absolute;left:558px;top:373px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" class=\"drag\" style=\"position:absolute;left:566px;top:229px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CUTOFF<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" class=\"drag\" style=\"position:absolute;left:566px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" class=\"drag\" style=\"position:absolute;left:566px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" class=\"drag\" style=\"position:absolute;left:621px;top:113px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SRS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" class=\"drag\" style=\"position:absolute;left:626px;top:151px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" class=\"drag\" style=\"position:absolute;left:826px;top:411px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" class=\"drag\" style=\"position:absolute;left:834px;top:373px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" class=\"drag\" style=\"position:absolute;left:641px;top:335px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" class=\"drag\" style=\"position:absolute;left:641px;top:324px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SRS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" class=\"drag\" style=\"position:absolute;left:523px;top:177px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" class=\"drag\" style=\"position:absolute;left:869px;top:150px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" class=\"drag\" style=\"position:absolute;left:884px;top:177px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" class=\"drag\" style=\"position:absolute;left:884px;top:373px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" class=\"drag\" style=\"position:absolute;left:870px;top:411px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" class=\"drag\" style=\"position:absolute;left:867px;top:450px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" class=\"drag\" style=\"position:absolute;left:867px;top:445px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>COMBINATION<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" class=\"drag\" style=\"position:absolute;left:834px;top:177px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" class=\"drag\" style=\"position:absolute;left:819px;top:150px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" class=\"drag\" style=\"position:absolute;left:770px;top:151px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" class=\"drag\" style=\"position:absolute;left:783px;top:177px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" class=\"drag\" style=\"position:absolute;left:890px;top:220px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HIGH BEAM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" class=\"drag\" style=\"position:absolute;left:890px;top:238px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" class=\"drag\" style=\"position:absolute;left:890px;top:232px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" class=\"drag\" style=\"position:absolute;left:890px;top:226px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" class=\"drag\" style=\"position:absolute;left:141px;top:538px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: RHD <br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" class=\"drag\" style=\"position:absolute;left:127px;top:538px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" class=\"drag\" style=\"position:absolute;left:127px;top:533px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" class=\"drag\" style=\"position:absolute;left:141px;top:533px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: LHD <br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" class=\"drag\" style=\"position:absolute;left:137px;top:444px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" class=\"drag\" style=\"position:absolute;left:421px;top:278px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" class=\"drag\" style=\"position:absolute;left:421px;top:261px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SEAT BELT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_105\" class=\"drag\" style=\"position:absolute;left:421px;top:267px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ALARM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_106\" class=\"drag\" style=\"position:absolute;left:421px;top:284px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(KK, KU)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_107\" class=\"drag\" style=\"position:absolute;left:421px;top:273px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INPUT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_108\" class=\"drag\" style=\"position:absolute;left:309px;top:226px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_109\" class=\"drag\" style=\"position:absolute;left:416px;top:238px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_110\" class=\"drag\" style=\"position:absolute;left:416px;top:232px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_111\" class=\"drag\" style=\"position:absolute;left:416px;top:221px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SEAT BELT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_112\" class=\"drag\" style=\"position:absolute;left:416px;top:226px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>REMINDER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_113\" class=\"drag\" style=\"position:absolute;left:409px;top:373px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_114\" class=\"drag\" style=\"position:absolute;left:417px;top:487px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Closed : Belt<br></b></nobr>");
write("</p>");
write("<p id=\"p2_115\" class=\"drag\" style=\"position:absolute;left:396px;top:450px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_116\" class=\"drag\" style=\"position:absolute;left:401px;top:533px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p2_117\" class=\"drag\" style=\"position:absolute;left:402px;top:501px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_118\" class=\"drag\" style=\"position:absolute;left:407px;top:465px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_119\" class=\"drag\" style=\"position:absolute;left:407px;top:486px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_120\" class=\"drag\" style=\"position:absolute;left:417px;top:493px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>unbuckled<br></b></nobr>");
write("</p>");
write("<p id=\"p2_121\" class=\"drag\" style=\"position:absolute;left:415px;top:476px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SEAT BELT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_122\" class=\"drag\" style=\"position:absolute;left:415px;top:470px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVER'S<br></b></nobr>");
write("</p>");
write("<p id=\"p2_123\" class=\"drag\" style=\"position:absolute;left:415px;top:481px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_124\" class=\"drag\" style=\"position:absolute;left:226px;top:228px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_125\" class=\"drag\" style=\"position:absolute;left:362px;top:473px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_126\" class=\"drag\" style=\"position:absolute;left:363px;top:496px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Door open<br></b></nobr>");
write("</p>");
write("<p id=\"p2_127\" class=\"drag\" style=\"position:absolute;left:363px;top:490px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Closed :<br></b></nobr>");
write("</p>");
write("<p id=\"p2_128\" class=\"drag\" style=\"position:absolute;left:362px;top:478px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_129\" class=\"drag\" style=\"position:absolute;left:362px;top:467px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_130\" class=\"drag\" style=\"position:absolute;left:362px;top:484px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_131\" class=\"drag\" style=\"position:absolute;left:308px;top:484px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_132\" class=\"drag\" style=\"position:absolute;left:308px;top:467px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_133\" class=\"drag\" style=\"position:absolute;left:308px;top:478px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_134\" class=\"drag\" style=\"position:absolute;left:309px;top:490px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Closed :<br></b></nobr>");
write("</p>");
write("<p id=\"p2_135\" class=\"drag\" style=\"position:absolute;left:309px;top:496px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Door open<br></b></nobr>");
write("</p>");
write("<p id=\"p2_136\" class=\"drag\" style=\"position:absolute;left:308px;top:473px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_137\" class=\"drag\" style=\"position:absolute;left:251px;top:473px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PASSENGER'S<br></b></nobr>");
write("</p>");
write("<p id=\"p2_138\" class=\"drag\" style=\"position:absolute;left:252px;top:496px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Door open<br></b></nobr>");
write("</p>");
write("<p id=\"p2_139\" class=\"drag\" style=\"position:absolute;left:252px;top:490px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Closed :<br></b></nobr>");
write("</p>");
write("<p id=\"p2_140\" class=\"drag\" style=\"position:absolute;left:251px;top:478px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_141\" class=\"drag\" style=\"position:absolute;left:251px;top:467px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_142\" class=\"drag\" style=\"position:absolute;left:251px;top:484px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_143\" class=\"drag\" style=\"position:absolute;left:151px;top:481px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_144\" class=\"drag\" style=\"position:absolute;left:201px;top:481px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_145\" class=\"drag\" style=\"position:absolute;left:338px;top:451px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_146\" class=\"drag\" style=\"position:absolute;left:284px;top:451px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_147\" class=\"drag\" style=\"position:absolute;left:227px;top:415px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_148\" class=\"drag\" style=\"position:absolute;left:309px;top:232px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LAMP (MIL)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_149\" class=\"drag\" style=\"position:absolute;left:309px;top:221px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MALFUNCTION<br></b></nobr>");
write("</p>");
write("<p id=\"p2_150\" class=\"drag\" style=\"position:absolute;left:309px;top:238px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_151\" class=\"drag\" style=\"position:absolute;left:362px;top:238px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_152\" class=\"drag\" style=\"position:absolute;left:48px;top:363px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>page<br></b></nobr>");
write("</p>");
write("<p id=\"p2_153\" class=\"drag\" style=\"position:absolute;left:48px;top:358px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>previous<br></b></nobr>");
write("</p>");
write("<p id=\"p2_154\" class=\"drag\" style=\"position:absolute;left:48px;top:352px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>From<br></b></nobr>");
write("</p>");
write("<p id=\"p2_155\" class=\"drag\" style=\"position:absolute;left:48px;top:187px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>From<br></b></nobr>");
write("</p>");
write("<p id=\"p2_156\" class=\"drag\" style=\"position:absolute;left:48px;top:193px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>previous<br></b></nobr>");
write("</p>");
write("<p id=\"p2_157\" class=\"drag\" style=\"position:absolute;left:48px;top:199px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>page<br></b></nobr>");
write("</p>");
write("<p id=\"p2_158\" class=\"drag\" style=\"position:absolute;left:77px;top:281px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CONTROL CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_159\" class=\"drag\" style=\"position:absolute;left:77px;top:275px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>POWER DOOR LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_160\" class=\"drag\" style=\"position:absolute;left:256px;top:245px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_161\" class=\"drag\" style=\"position:absolute;left:256px;top:198px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_162\" class=\"drag\" style=\"position:absolute;left:226px;top:222px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CONTROL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_163\" class=\"drag\" style=\"position:absolute;left:226px;top:216px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ENTRY LIGHT <br></b></nobr>");
write("</p>");
write("<p id=\"p2_164\" class=\"drag\" style=\"position:absolute;left:87px;top:379px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TAILGATE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_165\" class=\"drag\" style=\"position:absolute;left:87px;top:384px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_166\" class=\"drag\" style=\"position:absolute;left:194px;top:177px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_167\" class=\"drag\" style=\"position:absolute;left:184px;top:113px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_168\" class=\"drag\" style=\"position:absolute;left:184px;top:107px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CEILING<br></b></nobr>");
write("</p>");
write("<p id=\"p2_169\" class=\"drag\" style=\"position:absolute;left:181px;top:150px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_170\" class=\"drag\" style=\"position:absolute;left:287px;top:420px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_171\" class=\"drag\" style=\"position:absolute;left:302px;top:373px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_172\" class=\"drag\" style=\"position:absolute;left:287px;top:386px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_173\" class=\"drag\" style=\"position:absolute;left:342px;top:386px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_174\" class=\"drag\" style=\"position:absolute;left:355px;top:373px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C26<br></b></nobr>");
write("</p>");
write("<p id=\"p2_175\" class=\"drag\" style=\"position:absolute;left:86px;top:418px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_176\" class=\"drag\" style=\"position:absolute;left:137px;top:501px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_177\" class=\"drag\" style=\"position:absolute;left:131px;top:450px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/RED*<sup>4</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_178\" class=\"drag\" style=\"position:absolute;left:143px;top:486px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_179\" class=\"drag\" style=\"position:absolute;left:143px;top:465px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_180\" class=\"drag\" style=\"position:absolute;left:187px;top:450px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_181\" class=\"drag\" style=\"position:absolute;left:194px;top:373px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_182\" class=\"drag\" style=\"position:absolute;left:201px;top:470px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVER'S<br></b></nobr>");
write("</p>");
write("<p id=\"p2_183\" class=\"drag\" style=\"position:absolute;left:201px;top:476px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_184\" class=\"drag\" style=\"position:absolute;left:202px;top:487px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Closed :<br></b></nobr>");
write("</p>");
write("<p id=\"p2_185\" class=\"drag\" style=\"position:absolute;left:202px;top:493px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Door open<br></b></nobr>");
write("</p>");
write("<p id=\"p2_186\" class=\"drag\" style=\"position:absolute;left:227px;top:451px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_187\" class=\"drag\" style=\"position:absolute;left:244px;top:373px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_188\" class=\"drag\" style=\"position:absolute;left:153px;top:493px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Tailgate open<br></b></nobr>");
write("</p>");
write("<p id=\"p2_189\" class=\"drag\" style=\"position:absolute;left:153px;top:487px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Closed :<br></b></nobr>");
write("</p>");
write("<p id=\"p2_190\" class=\"drag\" style=\"position:absolute;left:151px;top:476px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LATCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_191\" class=\"drag\" style=\"position:absolute;left:151px;top:470px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TAILGATE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_192\" class=\"drag\" style=\"position:absolute;left:144px;top:373px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_193\" class=\"drag\" style=\"position:absolute;left:129px;top:415px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_194\" class=\"drag\" style=\"position:absolute;left:151px;top:240px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_195\" class=\"drag\" style=\"position:absolute;left:151px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DOOR/<br></b></nobr>");
write("</p>");
write("<p id=\"p2_196\" class=\"drag\" style=\"position:absolute;left:334px;top:426px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_197\" class=\"drag\" style=\"position:absolute;left:334px;top:420px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>EPS CONTROL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_198\" class=\"drag\" style=\"position:absolute;left:151px;top:223px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TAILGATE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_199\" class=\"drag\" style=\"position:absolute;left:151px;top:229px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_200\" class=\"drag\" style=\"position:absolute;left:151px;top:235px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_201\" class=\"drag\" style=\"position:absolute;left:362px;top:221px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>EPS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_202\" class=\"drag\" style=\"position:absolute;left:362px;top:226px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_203\" class=\"drag\" style=\"position:absolute;left:362px;top:232px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_204\" class=\"drag\" style=\"position:absolute;left:287px;top:177px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_205\" class=\"drag\" style=\"position:absolute;left:75px;top:193px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_206\" class=\"drag\" style=\"position:absolute;left:75px;top:357px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}