with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img1\" src=\"../img/SAA2EK2E15117300000LCAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:533px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLYWHEEL HOUSING<br>MOUNTING BOLTS, 21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:646px;top:200px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SNAP RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:688px;top:240px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COTTERS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:709px;top:298px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>START<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:733px;top:351px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY<br>DRIVE/PARK<br>GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:491px;top:332px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SEALING<br>RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:696px;top:461px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SLEEVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:836px;top:405px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FINAL<br>DRIVE SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:833px;top:534px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY<br>DRIVEN GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:802px;top:578px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PAWL SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:780px;top:617px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PAWL SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:758px;top:657px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PARK PAWL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:726px;top:747px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CVT SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:719px;top:806px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CVT DRIVEN<br>PULLEY SPEED<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:787px;top:1032px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CONTROL<br>VALVE BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:596px;top:1006px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:478px;top:958px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSMISSION<br>RANGE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:386px;top:1029px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF DIPSTICK<br>GUIDE PIPE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:295px;top:997px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>JOINT<br>BOLT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:215px;top:1042px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF<br>COOLER LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:105px;top:1040px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>JOINT<br>BOLT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:29px;top:978px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF COOLER LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:79px;top:795px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CVT DRIVE PULLEY<br>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:84px;top:716px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF MAGNET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:49px;top:627px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLYWHEEL HOUSING<br>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:102px;top:571px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ATF FILTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:17px;top:349px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DIFFERENTIAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:23px;top:266px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INHIBITOR SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:161px;top:58px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLYWHEEL HOUSING<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}