with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:571px;\" coordsize=\"475,571\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:571px;\">");
write("<img id=\"img1\" src=\"../img/SAA2E00J18573958551KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:571px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:333px;top:395px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:207px;top:286px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:225px;top:427px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:38px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Fastener Locations<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:72px;top:48px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>: Bolt, 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:38px;top:48px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:185px;top:48px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>: Bolt, 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:152px;top:48px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:216px;top:304px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:240px;top:433px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:313px;top:299px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m, <br>7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:339px;top:474px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m, <br>7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}