with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:694px;\" coordsize=\"950,694\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:694px;\">");
write("<img id=\"img2\" src=\"../img/SAA2E02E15100000000CAAD24.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:694px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:113px;top:18px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>START CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:146px;top:98px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>START CLUTCH<br>ACCUMULATOR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:146px;top:153px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SHIFT INHIBITOR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:55px;top:181px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:124px;top:178px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:134px;top:178px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:90px;top:237px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:142px;top:270px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>CR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:152px;top:275px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:163px;top:277px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:153px;top:287px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>CVT START CLUTCH<br>PRESSURE CONTROL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:382px;top:500px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:426px;top:506px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:448px;top:460px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>START CLUTCH<br>BACK-UP VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:428px;top:526px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>LUB''<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:457px;top:526px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>LUB<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:311px;top:143px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>FORWARD<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:418px;top:173px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>RVS'<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:468px;top:174px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>RI<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:409px;top:210px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:419px;top:205px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RVS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:406px;top:229px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>RVS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:436px;top:223px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:444px;top:209px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:437px;top:265px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:383px;top:224px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>FWD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:343px;top:223px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:343px;top:262px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:328px;top:273px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>MANUAL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:401px;top:262px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>CR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:413px;top:370px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:400px;top:379px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>CR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:409px;top:410px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>PH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:385px;top:413px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:337px;top:413px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:277px;top:376px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>CLUTCH REDUCING<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:487px;top:105px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>CR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:506px;top:106px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>RI<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:528px;top:110px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:488px;top:59px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>INHIBITOR<br>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:43px;top:494px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>PLANETARY CARRIER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:68px;top:510px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>START CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:51px;top:527px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>CLUTCH CANCELER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:85px;top:544px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>STEEL BELT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:61px;top:560px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>NEEDLE BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:17px;top:577px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>DRIVEN PULLEY CANCELER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:205px;top:521px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>DRIVEN PULLEY SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:205px;top:485px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>DRIVE PULLEY SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:168px;top:632px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>LUBRICATION VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:327px;top:621px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:346px;top:672px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>ATF COOLER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:423px;top:673px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>ATF FILTER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:641px;top:549px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>ATF PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" class=\"drag\" style=\"position:absolute;left:631px;top:508px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>PH REGULATOR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" class=\"drag\" style=\"position:absolute;left:566px;top:458px;font-weight:normal;font-size:3.8pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" class=\"drag\" style=\"position:absolute;left:680px;top:393px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>PH CONTROL SHIFT VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" class=\"drag\" style=\"position:absolute;left:731px;top:300px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>CVT SPEED CHANGE<br>CONTROL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" class=\"drag\" style=\"position:absolute;left:592px;top:284px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" class=\"drag\" style=\"position:absolute;left:609px;top:285px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" class=\"drag\" style=\"position:absolute;left:618px;top:274px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>CR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" class=\"drag\" style=\"position:absolute;left:643px;top:278px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" class=\"drag\" style=\"position:absolute;left:627px;top:251px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DNC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" class=\"drag\" style=\"position:absolute;left:661px;top:243px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" class=\"drag\" style=\"position:absolute;left:606px;top:191px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>PH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" class=\"drag\" style=\"position:absolute;left:638px;top:193px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" class=\"drag\" style=\"position:absolute;left:646px;top:197px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" class=\"drag\" style=\"position:absolute;left:637px;top:158px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>DN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" class=\"drag\" style=\"position:absolute;left:668px;top:196px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>DNC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" class=\"drag\" style=\"position:absolute;left:758px;top:192px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" class=\"drag\" style=\"position:absolute;left:750px;top:198px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" class=\"drag\" style=\"position:absolute;left:780px;top:198px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" class=\"drag\" style=\"position:absolute;left:811px;top:197px;font-weight:normal;font-size:3.8pt;\">");
write("<nobr><b>SI<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" class=\"drag\" style=\"position:absolute;left:824px;top:197px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>DRC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" class=\"drag\" style=\"position:absolute;left:758px;top:161px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>DR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" class=\"drag\" style=\"position:absolute;left:529px;top:289px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>CVT PULLEY<br>PRESSURE CONTROL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" class=\"drag\" style=\"position:absolute;left:789px;top:285px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" class=\"drag\" style=\"position:absolute;left:818px;top:276px;font-weight:normal;font-size:3.8pt;\">");
write("<nobr><b>CR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" class=\"drag\" style=\"position:absolute;left:809px;top:285px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" class=\"drag\" style=\"position:absolute;left:827px;top:251px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DRC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" class=\"drag\" style=\"position:absolute;left:843px;top:245px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" class=\"drag\" style=\"position:absolute;left:873px;top:244px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" class=\"drag\" style=\"position:absolute;left:403px;top:573px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>START CLUTCH<br>SHIFT VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" class=\"drag\" style=\"position:absolute;left:633px;top:18px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>DRIVEN PULLEY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" class=\"drag\" style=\"position:absolute;left:757px;top:11px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>DRIVE PULLEY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" class=\"drag\" style=\"position:absolute;left:803px;top:145px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>DRIVE PULLEY<br>CONTROL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" class=\"drag\" style=\"position:absolute;left:527px;top:171px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>DRIVEN PULLEY<br>CONTROL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" class=\"drag\" style=\"position:absolute;left:135px;top:128px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" class=\"drag\" style=\"position:absolute;left:403px;top:146px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>REVERSE<br>INHIBITOR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" class=\"drag\" style=\"position:absolute;left:263px;top:18px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>REVERSE BRAKE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("<v:line id=\"bl2_1\" class=\"drag\" from=\"105,148\" to=\"104,110\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_1\" class=\"drag\" on=\"true\" string=\"SC\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.0pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_2\" class=\"drag\" from=\"80,189\" to=\"79,151\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_2\" class=\"drag\" on=\"true\" string=\"DRC\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.8pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_3\" class=\"drag\" from=\"92,189\" to=\"91,151\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_3\" class=\"drag\" on=\"true\" string=\"CCB\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.8pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_4\" class=\"drag\" from=\"105,189\" to=\"104,151\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_4\" class=\"drag\" on=\"true\" string=\"CC\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.0pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_5\" class=\"drag\" from=\"114,189\" to=\"113,151\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_5\" class=\"drag\" on=\"true\" string=\"CR\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.0pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_6\" class=\"drag\" from=\"122,189\" to=\"121,151\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_6\" class=\"drag\" on=\"true\" string=\"SI\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.0pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_7\" class=\"drag\" from=\"395,513\" to=\"394,492\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_7\" class=\"drag\" on=\"true\" string=\"LUB'\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.0pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_8\" class=\"drag\" from=\"394,477\" to=\"393,457\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_8\" class=\"drag\" on=\"true\" string=\"CCB\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:5.0pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_9\" class=\"drag\" from=\"424,516\" to=\"423,496\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_9\" class=\"drag\" on=\"true\" string=\"LUB''\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.0pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_10\" class=\"drag\" from=\"368,479\" to=\"367,459\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_10\" class=\"drag\" on=\"true\" string=\"SI\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.1pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_11\" class=\"drag\" from=\"266,628\" to=\"265,605\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_11\" class=\"drag\" on=\"true\" string=\"RCC\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.8pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_12\" class=\"drag\" from=\"311,628\" to=\"310,605\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_12\" class=\"drag\" on=\"true\" string=\"COL\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.8pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_13\" class=\"drag\" from=\"282,587\" to=\"281,564\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_13\" class=\"drag\" on=\"true\" string=\"LUB'\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.8pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_14\" class=\"drag\" from=\"326,589\" to=\"325,566\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_14\" class=\"drag\" on=\"true\" string=\"RI\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.8pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_15\" class=\"drag\" from=\"621,517\" to=\"620,494\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_15\" class=\"drag\" on=\"true\" string=\"PH\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.8pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_16\" class=\"drag\" from=\"604,523\" to=\"603,500\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_16\" class=\"drag\" on=\"true\" string=\"LUB\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.8pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_17\" class=\"drag\" from=\"641,473\" to=\"640,450\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_17\" class=\"drag\" on=\"true\" string=\"PHC\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.8pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_18\" class=\"drag\" from=\"660,428\" to=\"659,392\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_18\" class=\"drag\" on=\"true\" string=\"PHC\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.8pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_19\" class=\"drag\" from=\"651,385\" to=\"650,350\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_19\" class=\"drag\" on=\"true\" string=\"DRC\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.1pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_20\" class=\"drag\" from=\"636,388\" to=\"635,353\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_20\" class=\"drag\" on=\"true\" string=\"DNC\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.1pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_21\" class=\"drag\" from=\"621,385\" to=\"620,349\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_21\" class=\"drag\" on=\"true\" string=\"DNC\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.1pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_22\" class=\"drag\" from=\"666,388\" to=\"665,353\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_22\" class=\"drag\" on=\"true\" string=\"DRC\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.1pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_23\" class=\"drag\" from=\"512,585\" to=\"511,514\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_23\" class=\"drag\" on=\"true\" string=\"LUB'\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.1pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_24\" class=\"drag\" from=\"540,586\" to=\"539,513\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_24\" class=\"drag\" on=\"true\" string=\"LUB\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.0pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_25\" class=\"drag\" from=\"542,575\" to=\"541,503\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_25\" class=\"drag\" on=\"true\" string=\"SI\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.0pt;\"/>");
write("</v:line>");
write("</v:group>");
}