with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img1\" src=\"../img/SAA2EKAA14600000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:720px;top:45px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CYLINDER HEAD COVER<br><a href=\"javascript:parent.Cts('000000000000492','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000000493','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:593px;top:820px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAM CHAIN<br>GUIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:151px;top:955px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT PULLEY<br><a href=\"javascript:parent.Cts('000000000000029','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:20px;top:871px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT<br>PULLEY BOLT<br><a href=\"javascript:parent.Cts('000000000000029','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:246px;top:380px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CHAIN CASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:213px;top:475px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:539px;top:908px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IDLER PULLER<br></b>(With A/C COMPRESSOR)<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:748px;top:274px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAM CHAIN<br><a href=\"javascript:parent.Cts('000000000000028','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000000502','i000')\">Installation, <br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:648px;top:705px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAMSHAFT SPROCKET<br><a href=\"javascript:parent.Cts('000000000000496','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000000497','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:309px;top:319px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAM CHAIN<br>TENSIONER SLIDER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:444px;top:387px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAM CHAIN<br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:793px;top:174px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEAD COVER <br>GASKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:88px;top:441px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CYLINDER HEAD PLUG<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}