with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:738px;\" coordsize=\"475,738\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:738px;\">");
write("<img id=\"img1\" src=\"../img/SAA2E00J54400048101KBAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:738px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:174px;top:21px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>3 mm<br>(0.12 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:343px;top:42px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:378px;top:112px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:316px;top:45px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:263px;top:155px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:232px;top:189px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:59px;top:274px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:153px;top:541px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:198px;top:583px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:142px;top:86px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:42px;top:102px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:37px;top:168px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>30.5 mm<br>(1.2 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:285px;top:193px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>3 mm<br>(0.12 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:42px;top:592px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:293px;top:612px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:309px;top:508px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:393px;top:594px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:342px;top:467px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>3 mm<br>(0.12 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:327px;top:441px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Inside<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:164px;top:59px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Inside<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:191px;top:80px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>12.5 mm<br>(0.49 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:165px;top:700px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>12.5 mm (0.49 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:368px;top:658px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>32.5 mm <br>(1.28 in.)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}