with(document) {
write("<v:group id=\"group5\" class=\"drag\" style=\"position:relative; width:950px; height:1093px;\" coordsize=\"950,1093\">");
write("<v:rect id=\"rect5\"class=\"drag\"  style=\"width:950px;height:1093px;\">");
write("<img id=\"img5\" src=\"../img/SAA2EA0A20300000000EAAD27.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1093px;border-color:#ffffff\">");
write("<p id=\"p5_1\" class=\"drag\" style=\"position:absolute;left:106px;top:989px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM/PCM A(31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" class=\"drag\" style=\"position:absolute;left:385px;top:965px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TERMINAL LOCATIONS<br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" class=\"drag\" style=\"position:absolute;left:695px;top:989px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM/PCM E(31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" class=\"drag\" style=\"position:absolute;left:319px;top:989px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM/PCM B(24P)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" class=\"drag\" style=\"position:absolute;left:518px;top:989px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PCM C(22P)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" class=\"drag\" style=\"position:absolute;left:58px;top:50px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" class=\"drag\" style=\"position:absolute;left:58px;top:74px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" class=\"drag\" style=\"position:absolute;left:58px;top:96px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" class=\"drag\" style=\"position:absolute;left:101px;top:665px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" class=\"drag\" style=\"position:absolute;left:100px;top:687px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" class=\"drag\" style=\"position:absolute;left:100px;top:708px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" class=\"drag\" style=\"position:absolute;left:100px;top:728px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" class=\"drag\" style=\"position:absolute;left:100px;top:750px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" class=\"drag\" style=\"position:absolute;left:354px;top:713px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATPS<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" class=\"drag\" style=\"position:absolute;left:352px;top:669px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATPD<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" class=\"drag\" style=\"position:absolute;left:355px;top:577px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATPR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" class=\"drag\" style=\"position:absolute;left:346px;top:486px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATPNP<br></b></nobr>");
write("</p>");
write("<p id=\"p5_18\" class=\"drag\" style=\"position:absolute;left:82px;top:370px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p5_19\" class=\"drag\" style=\"position:absolute;left:29px;top:250px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p5_20\" class=\"drag\" style=\"position:absolute;left:29px;top:819px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TRANSMISSION<br>RANGE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p5_21\" class=\"drag\" style=\"position:absolute;left:243px;top:853px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p5_22\" class=\"drag\" style=\"position:absolute;left:58px;top:119px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p5_23\" class=\"drag\" style=\"position:absolute;left:100px;top:772px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p5_24\" class=\"drag\" style=\"position:absolute;left:385px;top:772px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C11<br></b></nobr>");
write("</p>");
write("<p id=\"p5_25\" class=\"drag\" style=\"position:absolute;left:354px;top:757px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATPL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_26\" class=\"drag\" style=\"position:absolute;left:388px;top:728px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C9<br></b></nobr>");
write("</p>");
write("<p id=\"p5_27\" class=\"drag\" style=\"position:absolute;left:385px;top:683px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C20<br></b></nobr>");
write("</p>");
write("<p id=\"p5_28\" class=\"drag\" style=\"position:absolute;left:385px;top:592px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C10<br></b></nobr>");
write("</p>");
write("<p id=\"p5_29\" class=\"drag\" style=\"position:absolute;left:384px;top:501px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C12<br></b></nobr>");
write("</p>");
write("<p id=\"p5_30\" class=\"drag\" style=\"position:absolute;left:356px;top:284px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DIND<br></b></nobr>");
write("</p>");
write("<p id=\"p5_31\" class=\"drag\" style=\"position:absolute;left:385px;top:299px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E11<br></b></nobr>");
write("</p>");
write("<p id=\"p5_32\" class=\"drag\" style=\"position:absolute;left:540px;top:412px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C22<br></b></nobr>");
write("</p>");
write("<p id=\"p5_33\" class=\"drag\" style=\"position:absolute;left:564px;top:399px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VEL1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_34\" class=\"drag\" style=\"position:absolute;left:798px;top:361px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CVT SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_35\" class=\"drag\" style=\"position:absolute;left:541px;top:279px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C15<br></b></nobr>");
write("</p>");
write("<p id=\"p5_36\" class=\"drag\" style=\"position:absolute;left:564px;top:265px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>NDN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_37\" class=\"drag\" style=\"position:absolute;left:800px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CVT DRIVEN PULLEY<br>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_38\" class=\"drag\" style=\"position:absolute;left:544px;top:610px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p5_39\" class=\"drag\" style=\"position:absolute;left:545px;top:638px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_40\" class=\"drag\" style=\"position:absolute;left:828px;top:656px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CVT PULLEY<br>PRESSURE<br>CONTROL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p5_41\" class=\"drag\" style=\"position:absolute;left:563px;top:596px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>HLCLS+<br></b></nobr>");
write("</p>");
write("<p id=\"p5_42\" class=\"drag\" style=\"position:absolute;left:564px;top:626px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>HLCLS−<br></b></nobr>");
write("</p>");
write("<p id=\"p5_43\" class=\"drag\" style=\"position:absolute;left:542px;top:705px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B16<br></b></nobr>");
write("</p>");
write("<p id=\"p5_44\" class=\"drag\" style=\"position:absolute;left:544px;top:733px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C8<br></b></nobr>");
write("</p>");
write("<p id=\"p5_45\" class=\"drag\" style=\"position:absolute;left:811px;top:750px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CVT START CLUTCH<br>PRESSURE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p5_46\" class=\"drag\" style=\"position:absolute;left:563px;top:690px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SCLS+<br></b></nobr>");
write("</p>");
write("<p id=\"p5_47\" class=\"drag\" style=\"position:absolute;left:564px;top:720px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SCLS−<br></b></nobr>");
write("</p>");
write("<p id=\"p5_48\" class=\"drag\" style=\"position:absolute;left:542px;top:516px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B24<br></b></nobr>");
write("</p>");
write("<p id=\"p5_49\" class=\"drag\" style=\"position:absolute;left:542px;top:544px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C16<br></b></nobr>");
write("</p>");
write("<p id=\"p5_50\" class=\"drag\" style=\"position:absolute;left:813px;top:561px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CVT SPEED CHANGE<br>CONTROL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p5_51\" class=\"drag\" style=\"position:absolute;left:563px;top:502px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHLS+<br></b></nobr>");
write("</p>");
write("<p id=\"p5_52\" class=\"drag\" style=\"position:absolute;left:564px;top:532px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHLS−<br></b></nobr>");
write("</p>");
write("<p id=\"p5_53\" class=\"drag\" style=\"position:absolute;left:544px;top:145px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C7<br></b></nobr>");
write("</p>");
write("<p id=\"p5_54\" class=\"drag\" style=\"position:absolute;left:564px;top:132px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>NDR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_55\" class=\"drag\" style=\"position:absolute;left:800px;top:83px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CVT DRIVE PULLEY<br>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_56\" class=\"drag\" style=\"position:absolute;left:849px;top:832px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INHIBITOR<br>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p5_57\" class=\"drag\" style=\"position:absolute;left:544px;top:800px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C6<br></b></nobr>");
write("</p>");
write("<p id=\"p5_58\" class=\"drag\" style=\"position:absolute;left:562px;top:785px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INHSOL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_59\" class=\"drag\" style=\"position:absolute;left:759px;top:887px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p5_60\" class=\"drag\" style=\"position:absolute;left:28px;top:17px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_61\" class=\"drag\" style=\"position:absolute;left:755px;top:99px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C112<br></b></nobr>");
write("</p>");
write("<p id=\"p5_62\" class=\"drag\" style=\"position:absolute;left:755px;top:233px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C107<br></b></nobr>");
write("</p>");
write("<p id=\"p5_63\" class=\"drag\" style=\"position:absolute;left:756px;top:366px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C106<br></b></nobr>");
write("</p>");
write("<p id=\"p5_64\" class=\"drag\" style=\"position:absolute;left:813px;top:503px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C109<br></b></nobr>");
write("</p>");
write("<p id=\"p5_65\" class=\"drag\" style=\"position:absolute;left:813px;top:597px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C110<br></b></nobr>");
write("</p>");
write("<p id=\"p5_66\" class=\"drag\" style=\"position:absolute;left:813px;top:692px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C111<br></b></nobr>");
write("</p>");
write("<p id=\"p5_67\" class=\"drag\" style=\"position:absolute;left:813px;top:782px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C113<br></b></nobr>");
write("</p>");
write("<p id=\"p5_68\" class=\"drag\" style=\"position:absolute;left:633px;top:40px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p5_69\" class=\"drag\" style=\"position:absolute;left:716px;top:412px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_70\" class=\"drag\" style=\"position:absolute;left:665px;top:48px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p5_71\" class=\"drag\" style=\"position:absolute;left:669px;top:611px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_72\" class=\"drag\" style=\"position:absolute;left:670px;top:639px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_73\" class=\"drag\" style=\"position:absolute;left:669px;top:733px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_74\" class=\"drag\" style=\"position:absolute;left:669px;top:517px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_75\" class=\"drag\" style=\"position:absolute;left:669px;top:544px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_76\" class=\"drag\" style=\"position:absolute;left:717px;top:144px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_77\" class=\"drag\" style=\"position:absolute;left:694px;top:40px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p5_78\" class=\"drag\" style=\"position:absolute;left:668px;top:800px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_79\" class=\"drag\" style=\"position:absolute;left:727px;top:278px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_80\" class=\"drag\" style=\"position:absolute;left:680px;top:705px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_81\" class=\"drag\" style=\"position:absolute;left:795px;top:813px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_82\" class=\"drag\" style=\"position:absolute;left:717px;top:380px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_83\" class=\"drag\" style=\"position:absolute;left:719px;top:445px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_84\" class=\"drag\" style=\"position:absolute;left:717px;top:246px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_85\" class=\"drag\" style=\"position:absolute;left:719px;top:311px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_86\" class=\"drag\" style=\"position:absolute;left:717px;top:112px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_87\" class=\"drag\" style=\"position:absolute;left:719px;top:177px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_88\" class=\"drag\" style=\"position:absolute;left:157px;top:51px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_89\" class=\"drag\" style=\"position:absolute;left:156px;top:96px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_90\" class=\"drag\" style=\"position:absolute;left:168px;top:73px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_91\" class=\"drag\" style=\"position:absolute;left:111px;top:502px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_92\" class=\"drag\" style=\"position:absolute;left:205px;top:793px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_93\" class=\"drag\" style=\"position:absolute;left:179px;top:729px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_94\" class=\"drag\" style=\"position:absolute;left:338px;top:593px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_95\" class=\"drag\" style=\"position:absolute;left:168px;top:751px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_96\" class=\"drag\" style=\"position:absolute;left:164px;top:665px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_97\" class=\"drag\" style=\"position:absolute;left:164px;top:707px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_98\" class=\"drag\" style=\"position:absolute;left:177px;top:686px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_99\" class=\"drag\" style=\"position:absolute;left:178px;top:773px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_100\" class=\"drag\" style=\"position:absolute;left:167px;top:644px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_101\" class=\"drag\" style=\"position:absolute;left:319px;top:300px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_102\" class=\"drag\" style=\"position:absolute;left:180px;top:119px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_103\" class=\"drag\" style=\"position:absolute;left:313px;top:503px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_104\" class=\"drag\" style=\"position:absolute;left:156px;top:475px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C201<br></b></nobr>");
write("</p>");
write("<p id=\"p5_105\" class=\"drag\" style=\"position:absolute;left:211px;top:475px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C101<br></b></nobr>");
write("</p>");
write("<p id=\"p5_106\" class=\"drag\" style=\"position:absolute;left:149px;top:617px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C108<br></b></nobr>");
write("</p>");
write("<p id=\"p5_107\" class=\"drag\" style=\"position:absolute;left:185px;top:35px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C201<br></b></nobr>");
write("</p>");
write("<p id=\"p5_108\" class=\"drag\" style=\"position:absolute;left:240px;top:35px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C101<br></b></nobr>");
write("</p>");
write("<p id=\"p5_109\" class=\"drag\" style=\"position:absolute;left:139px;top:212px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C208<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}