with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:844px;\" coordsize=\"950,844\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:844px;\">");
write("<img id=\"img1\" src=\"../img/SAA2E00D14300014832EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:844px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:640px;top:95px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:458px;top:103px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGNITION<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:476px;top:135px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:153px;top:107px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:117px;top:21px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:156px;top:133px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No.1 (80A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:401px;top:147px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:540px;top:146px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:647px;top:133px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No.16 (7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:770px;top:147px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:257px;top:133px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No.3 (50A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:398px;top:320px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE<br>SYSTEM<br>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:392px;top:268px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GAUGE<br>ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:357px;top:746px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:338px;top:801px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LHD: 301<br>RHD: 201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:397px;top:687px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE FLUID<br>LEVEL SWITCH<br>CLOSED: Float down<br>OPEN: Float up<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:614px;top:688px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PARKING BRAKE<br>SWITCH<br>CLOSED: Lever up<br>OPEN: Lever down<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:555px;top:633px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:338px;top:634px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:338px;top:430px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:322px;top:494px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MULTIPLEX<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}