with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:495px;\" coordsize=\"950,495\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:495px;\">");
write("<img id=\"img1\" src=\"../img/SAA2E0AA20326927801KBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:495px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:108px;top:288px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:528px;top:466px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:732px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:801px;top:255px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:797px;top:297px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:795px;top:337px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:804px;top:375px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:804px;top:417px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}