with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:911px;\" coordsize=\"950,911\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:911px;\">");
write("<img id=\"img1\" src=\"../img/SAA2EA2E15117700000CAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:911px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:478px;top:21px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:413px;top:74px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PGM-FI Control System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:481px;top:121px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Correction of engine<br>torque signal data<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:449px;top:168px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CVT Control System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:469px;top:194px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>Judgment of<br>shift lever position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:708px;top:185px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/T Gear Position<br>Indicator<br>Position Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:388px;top:263px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>Calculation of drive belt<br>transfer torque<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:388px;top:313px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Fail-safe control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:366px;top:373px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Decision of minimum required pulley pressure<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:387px;top:477px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Fail-safe control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:387px;top:426px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>Calculation of<br>pulley ratio<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:566px;top:444px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Current<br>feedback<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:388px;top:631px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Calculation of<br>master target<br>of drive<br>pulley RPM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:533px;top:597px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Decision of<br>controlling<br>solenoid<br>current<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:385px;top:825px;font-weight:normal;font-size:8.0pt;\">");
write("<nobr><b>Fail-safe control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:538px;top:807px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Decision of<br>driving pulley<br>pressure<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:704px;top:477px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>Driven Pulley Control Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:707px;top:432px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>Drive Pulley Control Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:76px;top:261px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Engine RPM Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:76px;top:299px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>Manifold Absolute Pressure<br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:76px;top:418px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>CVT Drive Pulley Speed<br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:76px;top:464px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>CVT Driven Pulley Speed<br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:76px;top:538px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>Transmission Range<br>Switch Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:76px;top:651px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>Throttle Position Sensor<br>Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:76px;top:688px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>CVT Drive Pulley Speed<br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:76px;top:725px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>CVT Driven Pulley Speed<br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:76px;top:769px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>CVT Speed Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:76px;top:844px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Vehicle Speed Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:76px;top:576px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>Main Switch<br>(7Speed Mode) Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:76px;top:613px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>Steering Shift Switch<br>Signal<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}