with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:623px;\" coordsize=\"950,623\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:623px;\">");
write("<img id=\"img1\" src=\"../img/SAA2EA0A20323400000CAAD22.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:623px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:55px;top:238px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL<br>FILL<br>CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:15px;top:64px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL TANK<br>VAPOR/LIQUID<br>SEPARATION<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:139px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EVAP TWO WAY VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:359px;top:117px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EVAP<br>CANISTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:214px;top:254px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL TANK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:347px;top:298px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:520px;top:297px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:580px;top:262px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RED/<br>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:647px;top:49px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:817px;top:42px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>From No.16<br>(7.5A) fuse<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:802px;top:152px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VARIOUS<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:788px;top:253px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:649px;top:156px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:609px;top:313px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EVAP<br>CANISTER<br>PURGE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:765px;top:576px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1 : KG, KE, KR models<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:766px;top:593px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*2 : KU model<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}