with(document) {
write("<v:group id=\"group23\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\" coordsize=\"950,863\">");
write("<v:rect id=\"rect23\"class=\"drag\"  style=\"width:950px;height:863px;\">");
write("<img id=\"img23\" src=\"../img/SAA2EA2A20300047201CAAD26.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p23_1\" class=\"drag\" style=\"position:absolute;left:371px;top:24px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASH BOARD<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p23_2\" class=\"drag\" style=\"position:absolute;left:657px;top:25px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p23_3\" class=\"drag\" style=\"position:absolute;left:805px;top:164px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>COMPARTMENT<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p23_4\" class=\"drag\" style=\"position:absolute;left:844px;top:369px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C256<br></b></nobr>");
write("</p>");
write("<p id=\"p23_5\" class=\"drag\" style=\"position:absolute;left:865px;top:425px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C253<br></b></nobr>");
write("</p>");
write("<p id=\"p23_6\" class=\"drag\" style=\"position:absolute;left:877px;top:480px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C251<br></b></nobr>");
write("</p>");
write("<p id=\"p23_7\" class=\"drag\" style=\"position:absolute;left:879px;top:540px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C254<br></b></nobr>");
write("</p>");
write("<p id=\"p23_8\" class=\"drag\" style=\"position:absolute;left:882px;top:599px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C213<br></b></nobr>");
write("</p>");
write("<p id=\"p23_9\" class=\"drag\" style=\"position:absolute;left:871px;top:638px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C252<br></b></nobr>");
write("</p>");
write("<p id=\"p23_10\" class=\"drag\" style=\"position:absolute;left:864px;top:699px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C212<br></b></nobr>");
write("</p>");
write("<p id=\"p23_11\" class=\"drag\" style=\"position:absolute;left:864px;top:749px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C211<br></b></nobr>");
write("</p>");
write("<p id=\"p23_12\" class=\"drag\" style=\"position:absolute;left:819px;top:788px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C351<br></b></nobr>");
write("</p>");
write("<p id=\"p23_13\" class=\"drag\" style=\"position:absolute;left:734px;top:811px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C353<br></b></nobr>");
write("</p>");
write("<p id=\"p23_14\" class=\"drag\" style=\"position:absolute;left:653px;top:829px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C352<br></b></nobr>");
write("</p>");
write("<p id=\"p23_15\" class=\"drag\" style=\"position:absolute;left:478px;top:823px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C351<br></b></nobr>");
write("</p>");
write("<p id=\"p23_16\" class=\"drag\" style=\"position:absolute;left:407px;top:793px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C255<br></b></nobr>");
write("</p>");
write("<p id=\"p23_17\" class=\"drag\" style=\"position:absolute;left:126px;top:734px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C257<br></b></nobr>");
write("</p>");
write("<p id=\"p23_18\" class=\"drag\" style=\"position:absolute;left:310px;top:731px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p23_19\" class=\"drag\" style=\"position:absolute;left:567px;top:730px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BACK<br>SIDE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}