with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1039px;\" coordsize=\"950,1039\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1039px;\">");
write("<img id=\"img1\" src=\"../img/SAA2E00A20326428001MAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1039px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:574px;top:71px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:309px;top:62px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:645px;top:325px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:104px;top:100px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BASE<br>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:558px;top:407px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL<br>PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:83px;top:281px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To FUEL<br>RAIL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:18px;top:415px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To EVAPORATIVE<br>EMISSION (EVAP)<br>CANISTER PURGE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:703px;top:797px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>mark<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:143px;top:804px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>There should be<br>no clearance.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:27px;top:915px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:27px;top:564px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:512px;top:564px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:697px;top:576px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>There should be no<br>clearance.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:872px;top:632px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>90°<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:242px;top:991px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>40mm<br>(1.57 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:459px;top:963px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>90°<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:253px;top:695px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>90°<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:153px;top:544px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>When instelling the<br>fuel fill tube,<br>align the marks on the<br>tube and the pipe.<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}