with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:385px;\" coordsize=\"475,385\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:385px;\">");
write("<img id=\"img1\" src=\"../img/SAA2E00G10100012111FEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:385px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:18px;top:61px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:41px;top:189px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:121px;top:45px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:182px;top:44px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:242px;top:44px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:364px;top:44px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:425px;top:45px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:44px;top:116px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:190px;top:268px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A/C Switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:24px;top:26px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:18px;top:61px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:41px;top:189px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:121px;top:45px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:182px;top:44px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:242px;top:44px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:364px;top:44px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:425px;top:45px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:44px;top:116px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:190px;top:268px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A/C Switch<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}