with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:542px;\" coordsize=\"950,542\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:542px;\">");
write("<img id=\"img1\" src=\"../img/SAA2EA2E15117700000CAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:542px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:702px;top:405px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CVT DRIVE PULLEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:702px;top:414px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CONTROL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:702px;top:410px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:765px;top:405px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>INHIBITOR SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:834px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:742px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:689px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:698px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:674px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:571px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:609px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:586px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:579px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:572px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:564px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:557px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:549px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:542px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:540px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:546px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:553px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:571px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:590px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:596px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:602px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:608px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:602px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:596px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:590px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:583px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:553px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:546px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:623px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:630px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:638px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:645px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:653px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:668px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:675px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:654px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:661px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:674px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:628px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:622px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:654px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:743px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:735px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:690px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:742px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:690px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:704px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:719px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:712px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:719px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:815px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:821px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:864px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:858px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:840px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:825px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:855px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:877px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:809px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:840px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:877px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:670px;top:471px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PCM Connector Terminal Locations<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:808px;top:522px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E (31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:688px;top:522px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C (22P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:619px;top:522px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B (24P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:536px;top:522px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A (31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:840px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:821px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:815px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:559px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:668px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:648px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:641px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:635px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:648px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:727px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:811px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:833px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:870px;top:491px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:871px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:877px;top:498px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:858px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:852px;top:505px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:594px;top:193px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:565px;top:57px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>S−DN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:587px;top:65px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>S−UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:515px;top:107px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:542px;top:107px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:565px;top:107px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:596px;top:107px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:596px;top:125px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:596px;top:133px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:521px;top:125px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:547px;top:125px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:570px;top:125px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:565px;top:133px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:542px;top:133px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:516px;top:133px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:552px;top:65px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>S−UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:530px;top:57px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>S−DN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:596px;top:158px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:596px;top:150px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:570px;top:150px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:547px;top:150px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:521px;top:150px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:516px;top:158px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:542px;top:158px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:566px;top:158px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:563px;top:187px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:547px;top:187px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:522px;top:187px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:588px;top:223px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>To 5V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:639px;top:414px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:639px;top:405px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CVT START CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:639px;top:410px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PRESSURE CONTROL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:576px;top:410px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:885px;top:54px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CVT SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:827px;top:54px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:827px;top:49px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CVT DRIVEN PULLEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:769px;top:54px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PRESSURE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:769px;top:49px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>MANIFOLD ABSOLUTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:715px;top:49px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CVT DRIVE PULLEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:715px;top:54px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:668px;top:54px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:668px;top:45px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ENGINE COOLANT <br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:668px;top:49px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>TEMPERATURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:615px;top:54px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:615px;top:49px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>THROTTLE POSITION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:917px;top:193px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:906px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VEL1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:906px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:896px;top:187px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:914px;top:113px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:880px;top:113px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:901px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:884px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:919px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:844px;top:187px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:849px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:849px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>NDN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:861px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:827px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:844px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:823px;top:113px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:857px;top:113px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:783px;top:198px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:766px;top:187px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:792px;top:224px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(PB)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:775px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VCC1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:775px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:792px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>MAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:792px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:809px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:809px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:804px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:770px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:787px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:766px;top:113px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:799px;top:187px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:742px;top:113px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:708px;top:113px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:730px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:818px;top:364px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:793px;top:373px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:770px;top:373px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:702px;top:329px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:725px;top:329px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" class=\"drag\" style=\"position:absolute;left:735px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" class=\"drag\" style=\"position:absolute;left:712px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" class=\"drag\" style=\"position:absolute;left:707px;top:373px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" class=\"drag\" style=\"position:absolute;left:730px;top:373px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" class=\"drag\" style=\"position:absolute;left:735px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DR LS+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" class=\"drag\" style=\"position:absolute;left:712px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DR LS−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" class=\"drag\" style=\"position:absolute;left:649px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SC LS−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" class=\"drag\" style=\"position:absolute;left:672px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SC LS+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" class=\"drag\" style=\"position:absolute;left:609px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DN LS+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" class=\"drag\" style=\"position:absolute;left:552px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>S−UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" class=\"drag\" style=\"position:absolute;left:552px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" class=\"drag\" style=\"position:absolute;left:849px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" class=\"drag\" style=\"position:absolute;left:849px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" class=\"drag\" style=\"position:absolute;left:845px;top:329px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" class=\"drag\" style=\"position:absolute;left:824px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" class=\"drag\" style=\"position:absolute;left:824px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" class=\"drag\" style=\"position:absolute;left:843px;top:455px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" class=\"drag\" style=\"position:absolute;left:819px;top:329px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" class=\"drag\" style=\"position:absolute;left:845px;top:375px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" class=\"drag\" style=\"position:absolute;left:896px;top:375px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" class=\"drag\" style=\"position:absolute;left:576px;top:414px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CONTROL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" class=\"drag\" style=\"position:absolute;left:576px;top:405px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CVT DRIVEN PULLEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" class=\"drag\" style=\"position:absolute;left:690px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" class=\"drag\" style=\"position:absolute;left:673px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" class=\"drag\" style=\"position:absolute;left:735px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>NDR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" class=\"drag\" style=\"position:absolute;left:735px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" class=\"drag\" style=\"position:absolute;left:726px;top:187px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" class=\"drag\" style=\"position:absolute;left:713px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" class=\"drag\" style=\"position:absolute;left:747px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" class=\"drag\" style=\"position:absolute;left:695px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ECT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" class=\"drag\" style=\"position:absolute;left:695px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" class=\"drag\" style=\"position:absolute;left:685px;top:187px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" class=\"drag\" style=\"position:absolute;left:667px;top:373px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" class=\"drag\" style=\"position:absolute;left:644px;top:373px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" class=\"drag\" style=\"position:absolute;left:871px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" class=\"drag\" style=\"position:absolute;left:900px;top:455px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" class=\"drag\" style=\"position:absolute;left:586px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DN LS−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" class=\"drag\" style=\"position:absolute;left:775px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SOL INH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" class=\"drag\" style=\"position:absolute;left:881px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" class=\"drag\" style=\"position:absolute;left:586px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" class=\"drag\" style=\"position:absolute;left:609px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" class=\"drag\" style=\"position:absolute;left:649px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" class=\"drag\" style=\"position:absolute;left:672px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" class=\"drag\" style=\"position:absolute;left:775px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" class=\"drag\" style=\"position:absolute;left:881px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" class=\"drag\" style=\"position:absolute;left:677px;top:252px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>POWERTRAIN CONTROL MODULE (PCM)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" class=\"drag\" style=\"position:absolute;left:581px;top:373px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" class=\"drag\" style=\"position:absolute;left:604px;top:373px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" class=\"drag\" style=\"position:absolute;left:576px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" class=\"drag\" style=\"position:absolute;left:599px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" class=\"drag\" style=\"position:absolute;left:667px;top:329px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" class=\"drag\" style=\"position:absolute;left:640px;top:329px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" class=\"drag\" style=\"position:absolute;left:765px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" class=\"drag\" style=\"position:absolute;left:897px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_226\" class=\"drag\" style=\"position:absolute;left:906px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_227\" class=\"drag\" style=\"position:absolute;left:906px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_228\" class=\"drag\" style=\"position:absolute;left:645px;top:187px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_229\" class=\"drag\" style=\"position:absolute;left:655px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_230\" class=\"drag\" style=\"position:absolute;left:655px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_231\" class=\"drag\" style=\"position:absolute;left:650px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_232\" class=\"drag\" style=\"position:absolute;left:633px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_233\" class=\"drag\" style=\"position:absolute;left:616px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_234\" class=\"drag\" style=\"position:absolute;left:628px;top:198px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_235\" class=\"drag\" style=\"position:absolute;left:611px;top:187px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_236\" class=\"drag\" style=\"position:absolute;left:638px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_237\" class=\"drag\" style=\"position:absolute;left:638px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>TPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_238\" class=\"drag\" style=\"position:absolute;left:621px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_239\" class=\"drag\" style=\"position:absolute;left:621px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VCC2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_240\" class=\"drag\" style=\"position:absolute;left:575px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_241\" class=\"drag\" style=\"position:absolute;left:575px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>S−DN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_242\" class=\"drag\" style=\"position:absolute;left:526px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_243\" class=\"drag\" style=\"position:absolute;left:526px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>M−SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_244\" class=\"drag\" style=\"position:absolute;left:508px;top:60px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_245\" class=\"drag\" style=\"position:absolute;left:508px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7SPEED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_246\" class=\"drag\" style=\"position:absolute;left:505px;top:23px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>MAIN SWITCH(7SPEED MODE)/<br></b></nobr>");
write("</p>");
write("<p id=\"p1_247\" class=\"drag\" style=\"position:absolute;left:505px;top:27px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>STEERING SHIFT SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_248\" class=\"drag\" style=\"position:absolute;left:25px;top:307px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_249\" class=\"drag\" style=\"position:absolute;left:41px;top:315px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_250\" class=\"drag\" style=\"position:absolute;left:58px;top:306px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_251\" class=\"drag\" style=\"position:absolute;left:368px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VABS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_252\" class=\"drag\" style=\"position:absolute;left:368px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_253\" class=\"drag\" style=\"position:absolute;left:359px;top:190px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_254\" class=\"drag\" style=\"position:absolute;left:414px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_255\" class=\"drag\" style=\"position:absolute;left:414px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_256\" class=\"drag\" style=\"position:absolute;left:410px;top:190px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_257\" class=\"drag\" style=\"position:absolute;left:381px;top:190px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_258\" class=\"drag\" style=\"position:absolute;left:391px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_259\" class=\"drag\" style=\"position:absolute;left:391px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>K−LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_260\" class=\"drag\" style=\"position:absolute;left:358px;top:145px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ABS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_261\" class=\"drag\" style=\"position:absolute;left:358px;top:149px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CONTROL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_262\" class=\"drag\" style=\"position:absolute;left:358px;top:154px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_263\" class=\"drag\" style=\"position:absolute;left:388px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DATA LINK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_264\" class=\"drag\" style=\"position:absolute;left:388px;top:151px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_265\" class=\"drag\" style=\"position:absolute;left:35px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_266\" class=\"drag\" style=\"position:absolute;left:35px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LED A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_267\" class=\"drag\" style=\"position:absolute;left:53px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LED B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_268\" class=\"drag\" style=\"position:absolute;left:53px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_269\" class=\"drag\" style=\"position:absolute;left:70px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LED C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_270\" class=\"drag\" style=\"position:absolute;left:70px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_271\" class=\"drag\" style=\"position:absolute;left:75px;top:332px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_272\" class=\"drag\" style=\"position:absolute;left:99px;top:338px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_273\" class=\"drag\" style=\"position:absolute;left:99px;top:334px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>INPUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_274\" class=\"drag\" style=\"position:absolute;left:97px;top:464px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_275\" class=\"drag\" style=\"position:absolute;left:97px;top:459px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SHIFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_276\" class=\"drag\" style=\"position:absolute;left:200px;top:338px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_277\" class=\"drag\" style=\"position:absolute;left:225px;top:341px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_278\" class=\"drag\" style=\"position:absolute;left:225px;top:356px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_279\" class=\"drag\" style=\"position:absolute;left:200px;top:352px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_280\" class=\"drag\" style=\"position:absolute;left:200px;top:324px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_281\" class=\"drag\" style=\"position:absolute;left:225px;top:327px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_282\" class=\"drag\" style=\"position:absolute;left:225px;top:313px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_283\" class=\"drag\" style=\"position:absolute;left:200px;top:310px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_284\" class=\"drag\" style=\"position:absolute;left:273px;top:321px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_285\" class=\"drag\" style=\"position:absolute;left:284px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_286\" class=\"drag\" style=\"position:absolute;left:284px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>M IND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_287\" class=\"drag\" style=\"position:absolute;left:258px;top:335px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_288\" class=\"drag\" style=\"position:absolute;left:267px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_289\" class=\"drag\" style=\"position:absolute;left:267px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>S IND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_290\" class=\"drag\" style=\"position:absolute;left:15px;top:412px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_291\" class=\"drag\" style=\"position:absolute;left:42px;top:390px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_292\" class=\"drag\" style=\"position:absolute;left:218px;top:449px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_293\" class=\"drag\" style=\"position:absolute;left:200px;top:447px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_294\" class=\"drag\" style=\"position:absolute;left:160px;top:449px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p1_295\" class=\"drag\" style=\"position:absolute;left:325px;top:90px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_296\" class=\"drag\" style=\"position:absolute;left:308px;top:90px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_297\" class=\"drag\" style=\"position:absolute;left:291px;top:90px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_298\" class=\"drag\" style=\"position:absolute;left:262px;top:184px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_299\" class=\"drag\" style=\"position:absolute;left:22px;top:184px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_300\" class=\"drag\" style=\"position:absolute;left:151px;top:346px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>KEY INTERLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_301\" class=\"drag\" style=\"position:absolute;left:151px;top:350px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_302\" class=\"drag\" style=\"position:absolute;left:138px;top:322px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SHIFT LOCK CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_303\" class=\"drag\" style=\"position:absolute;left:15px;top:416px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.16 (7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_304\" class=\"drag\" style=\"position:absolute;left:132px;top:405px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DIMMING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_305\" class=\"drag\" style=\"position:absolute;left:132px;top:409px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_306\" class=\"drag\" style=\"position:absolute;left:410px;top:405px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_307\" class=\"drag\" style=\"position:absolute;left:287px;top:415px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_308\" class=\"drag\" style=\"position:absolute;left:268px;top:389px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_309\" class=\"drag\" style=\"position:absolute;left:316px;top:415px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_310\" class=\"drag\" style=\"position:absolute;left:253px;top:201px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_311\" class=\"drag\" style=\"position:absolute;left:199px;top:190px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_312\" class=\"drag\" style=\"position:absolute;left:253px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GAUGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_313\" class=\"drag\" style=\"position:absolute;left:253px;top:206px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_314\" class=\"drag\" style=\"position:absolute;left:291px;top:110px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_315\" class=\"drag\" style=\"position:absolute;left:158px;top:12px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_316\" class=\"drag\" style=\"position:absolute;left:158px;top:17px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_317\" class=\"drag\" style=\"position:absolute;left:58px;top:157px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_318\" class=\"drag\" style=\"position:absolute;left:58px;top:143px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRAKE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_319\" class=\"drag\" style=\"position:absolute;left:75px;top:350px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_320\" class=\"drag\" style=\"position:absolute;left:75px;top:312px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_321\" class=\"drag\" style=\"position:absolute;left:75px;top:407px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_322\" class=\"drag\" style=\"position:absolute;left:15px;top:403px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_323\" class=\"drag\" style=\"position:absolute;left:15px;top:407px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FUSE/RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_324\" class=\"drag\" style=\"position:absolute;left:63px;top:409px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_325\" class=\"drag\" style=\"position:absolute;left:244px;top:321px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_326\" class=\"drag\" style=\"position:absolute;left:250px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>D IND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_327\" class=\"drag\" style=\"position:absolute;left:250px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_328\" class=\"drag\" style=\"position:absolute;left:384px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>NP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_329\" class=\"drag\" style=\"position:absolute;left:370px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_330\" class=\"drag\" style=\"position:absolute;left:384px;top:280px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ATP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_331\" class=\"drag\" style=\"position:absolute;left:370px;top:280px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ATP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_332\" class=\"drag\" style=\"position:absolute;left:160px;top:427px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_333\" class=\"drag\" style=\"position:absolute;left:223px;top:438px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_334\" class=\"drag\" style=\"position:absolute;left:218px;top:427px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_335\" class=\"drag\" style=\"position:absolute;left:218px;top:401px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_336\" class=\"drag\" style=\"position:absolute;left:222px;top:389px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_337\" class=\"drag\" style=\"position:absolute;left:219px;top:378px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_338\" class=\"drag\" style=\"position:absolute;left:200px;top:435px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_339\" class=\"drag\" style=\"position:absolute;left:200px;top:424px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_340\" class=\"drag\" style=\"position:absolute;left:200px;top:412px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_341\" class=\"drag\" style=\"position:absolute;left:200px;top:398px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_342\" class=\"drag\" style=\"position:absolute;left:200px;top:387px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_343\" class=\"drag\" style=\"position:absolute;left:200px;top:375px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_344\" class=\"drag\" style=\"position:absolute;left:160px;top:438px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_345\" class=\"drag\" style=\"position:absolute;left:160px;top:401px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_346\" class=\"drag\" style=\"position:absolute;left:160px;top:389px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_347\" class=\"drag\" style=\"position:absolute;left:160px;top:378px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_348\" class=\"drag\" style=\"position:absolute;left:160px;top:411px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_349\" class=\"drag\" style=\"position:absolute;left:291px;top:105px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_350\" class=\"drag\" style=\"position:absolute;left:342px;top:133px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p1_351\" class=\"drag\" style=\"position:absolute;left:344px;top:107px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_352\" class=\"drag\" style=\"position:absolute;left:338px;top:73px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_353\" class=\"drag\" style=\"position:absolute;left:339px;top:56px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_354\" class=\"drag\" style=\"position:absolute;left:261px;top:107px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_355\" class=\"drag\" style=\"position:absolute;left:256px;top:169px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_356\" class=\"drag\" style=\"position:absolute;left:295px;top:158px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_357\" class=\"drag\" style=\"position:absolute;left:294px;top:135px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_358\" class=\"drag\" style=\"position:absolute;left:366px;top:93px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_359\" class=\"drag\" style=\"position:absolute;left:366px;top:70px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_360\" class=\"drag\" style=\"position:absolute;left:366px;top:53px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_361\" class=\"drag\" style=\"position:absolute;left:278px;top:155px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_362\" class=\"drag\" style=\"position:absolute;left:278px;top:133px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_363\" class=\"drag\" style=\"position:absolute;left:366px;top:30px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_364\" class=\"drag\" style=\"position:absolute;left:16px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GAUGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_365\" class=\"drag\" style=\"position:absolute;left:227px;top:33px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_366\" class=\"drag\" style=\"position:absolute;left:168px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.20 (15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_367\" class=\"drag\" style=\"position:absolute;left:313px;top:173px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_368\" class=\"drag\" style=\"position:absolute;left:313px;top:177px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p1_369\" class=\"drag\" style=\"position:absolute;left:313px;top:168px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SHIFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_370\" class=\"drag\" style=\"position:absolute;left:404px;top:40px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>KEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_371\" class=\"drag\" style=\"position:absolute;left:404px;top:82px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>KEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_372\" class=\"drag\" style=\"position:absolute;left:404px;top:44px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>INTERLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_373\" class=\"drag\" style=\"position:absolute;left:404px;top:86px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_374\" class=\"drag\" style=\"position:absolute;left:404px;top:49px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p1_375\" class=\"drag\" style=\"position:absolute;left:167px;top:38px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.16 (7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_376\" class=\"drag\" style=\"position:absolute;left:168px;top:49px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.11 (15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_377\" class=\"drag\" style=\"position:absolute;left:167px;top:26px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.17 (7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_378\" class=\"drag\" style=\"position:absolute;left:147px;top:48px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_379\" class=\"drag\" style=\"position:absolute;left:147px;top:37px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_380\" class=\"drag\" style=\"position:absolute;left:363px;top:455px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_381\" class=\"drag\" style=\"position:absolute;left:364px;top:335px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_382\" class=\"drag\" style=\"position:absolute;left:370px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_383\" class=\"drag\" style=\"position:absolute;left:370px;top:482px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_384\" class=\"drag\" style=\"position:absolute;left:356px;top:473px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_385\" class=\"drag\" style=\"position:absolute;left:16px;top:206px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_386\" class=\"drag\" style=\"position:absolute;left:16px;top:201px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_387\" class=\"drag\" style=\"position:absolute;left:410px;top:401px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_388\" class=\"drag\" style=\"position:absolute;left:410px;top:396px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>STARTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_389\" class=\"drag\" style=\"position:absolute;left:53px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BK SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_390\" class=\"drag\" style=\"position:absolute;left:53px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_391\" class=\"drag\" style=\"position:absolute;left:40px;top:121px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_392\" class=\"drag\" style=\"position:absolute;left:41px;top:190px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_393\" class=\"drag\" style=\"position:absolute;left:58px;top:152px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>POSITION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_394\" class=\"drag\" style=\"position:absolute;left:58px;top:147px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PEDAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_395\" class=\"drag\" style=\"position:absolute;left:54px;top:59px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_396\" class=\"drag\" style=\"position:absolute;left:54px;top:64px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(10A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_397\" class=\"drag\" style=\"position:absolute;left:375px;top:321px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_398\" class=\"drag\" style=\"position:absolute;left:384px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_399\" class=\"drag\" style=\"position:absolute;left:113px;top:40px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_400\" class=\"drag\" style=\"position:absolute;left:313px;top:280px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ATP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_401\" class=\"drag\" style=\"position:absolute;left:341px;top:280px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ATP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_402\" class=\"drag\" style=\"position:absolute;left:313px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_403\" class=\"drag\" style=\"position:absolute;left:341px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_404\" class=\"drag\" style=\"position:absolute;left:356px;top:294px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_405\" class=\"drag\" style=\"position:absolute;left:356px;top:280px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ATP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_406\" class=\"drag\" style=\"position:absolute;left:341px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_407\" class=\"drag\" style=\"position:absolute;left:306px;top:321px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_408\" class=\"drag\" style=\"position:absolute;left:335px;top:335px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_409\" class=\"drag\" style=\"position:absolute;left:344px;top:321px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_410\" class=\"drag\" style=\"position:absolute;left:414px;top:455px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_411\" class=\"drag\" style=\"position:absolute;left:393px;top:440px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_412\" class=\"drag\" style=\"position:absolute;left:356px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_413\" class=\"drag\" style=\"position:absolute;left:313px;top:285px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_414\" class=\"drag\" style=\"position:absolute;left:62px;top:512px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_415\" class=\"drag\" style=\"position:absolute;left:64px;top:484px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_416\" class=\"drag\" style=\"position:absolute;left:75px;top:387px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_417\" class=\"drag\" style=\"position:absolute;left:75px;top:464px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_418\" class=\"drag\" style=\"position:absolute;left:117px;top:28px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_419\" class=\"drag\" style=\"position:absolute;left:84px;top:299px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_420\" class=\"drag\" style=\"position:absolute;left:103px;top:402px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_421\" class=\"drag\" style=\"position:absolute;left:292px;top:455px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_422\" class=\"drag\" style=\"position:absolute;left:306px;top:455px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_423\" class=\"drag\" style=\"position:absolute;left:321px;top:455px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_424\" class=\"drag\" style=\"position:absolute;left:335px;top:455px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_425\" class=\"drag\" style=\"position:absolute;left:349px;top:455px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_426\" class=\"drag\" style=\"position:absolute;left:378px;top:455px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_427\" class=\"drag\" style=\"position:absolute;left:390px;top:455px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_428\" class=\"drag\" style=\"position:absolute;left:298px;top:482px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_429\" class=\"drag\" style=\"position:absolute;left:313px;top:473px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_430\" class=\"drag\" style=\"position:absolute;left:327px;top:468px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_431\" class=\"drag\" style=\"position:absolute;left:287px;top:519px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>TRANSMISSION RANGE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_432\" class=\"drag\" style=\"position:absolute;left:341px;top:468px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_433\" class=\"drag\" style=\"position:absolute;left:384px;top:465px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_434\" class=\"drag\" style=\"position:absolute;left:399px;top:465px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_435\" class=\"drag\" style=\"position:absolute;left:83px;top:61px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.6 (40A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_436\" class=\"drag\" style=\"position:absolute;left:15px;top:34px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_437\" class=\"drag\" style=\"position:absolute;left:44px;top:28px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_438\" class=\"drag\" style=\"position:absolute;left:212px;top:234px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>To 12V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_439\" class=\"drag\" style=\"position:absolute;left:188px;top:252px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>POWERTRAIN CONTROL MODULE (PCM)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_440\" class=\"drag\" style=\"position:absolute;left:54px;top:38px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.1 (80A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_441\" class=\"drag\" style=\"position:absolute;left:195px;top:154px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_442\" class=\"drag\" style=\"position:absolute;left:195px;top:150px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>MAIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_443\" class=\"drag\" style=\"position:absolute;left:195px;top:145px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PGM−FI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_444\" class=\"drag\" style=\"position:absolute;left:153px;top:190px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_445\" class=\"drag\" style=\"position:absolute;left:176px;top:190px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_446\" class=\"drag\" style=\"position:absolute;left:164px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>MRLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_447\" class=\"drag\" style=\"position:absolute;left:164px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_448\" class=\"drag\" style=\"position:absolute;left:187px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_449\" class=\"drag\" style=\"position:absolute;left:187px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IGP1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_450\" class=\"drag\" style=\"position:absolute;left:210px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_451\" class=\"drag\" style=\"position:absolute;left:210px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IGP2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_452\" class=\"drag\" style=\"position:absolute;left:238px;top:211px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_453\" class=\"drag\" style=\"position:absolute;left:227px;top:190px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_454\" class=\"drag\" style=\"position:absolute;left:238px;top:219px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_455\" class=\"drag\" style=\"position:absolute;left:83px;top:38px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.3 (50A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_456\" class=\"drag\" style=\"position:absolute;left:242px;top:225px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>To 5V<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}