with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" src=\"../img/SAA2E00000000000000EBA202.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:424px;top:534px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:581px;top:683px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:502px;top:683px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:184px;top:452px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BEEPER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:356px;top:314px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:566px;top:633px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:488px;top:633px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:1px;top:284px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:237px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:163px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:166px;top:633px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:14px;top:240px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>46<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:1px;top:208px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TAILLIGHT <br>RELAY<br>‹4−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:73px;top:414px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LCD <br>BACK <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:134px;top:420px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BACK <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:90px;top:528px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS<br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:184px;top:525px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TRIP/<br>RESET <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:267px;top:381px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>COOLANT HIGH <br>TEMPERATURE <br>WARNING <br>LIGHT<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:356px;top:381px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>COOLANT LOW <br>TEMPERATURE <br>INDICATOR <br>LIGHT<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:444px;top:387px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LOW FUEL <br>INDICATOR <br>LIGHT<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:522px;top:387px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IMMOBILIZER <br>INDICATOR <br>LIGHT<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:600px;top:387px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CHARGING <br>SYSTEM <br>LIGHT<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:395px;top:559px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A/T GEAR POSITION <br>DIMMING CIRCUIT <br>‹3−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:478px;top:708px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IMMOBILIZER <br>CONTROL <br>UNIT − RECEIVER<br>‹19−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:555px;top:708px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ALTERNATOR <br>‹1−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:91px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:535px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}