with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img2\" src=\"../img/SAA2EK0J54260400000EAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:495px;top:963px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LIGHT SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:716px;top:913px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:716px;top:924px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(To page 22−59)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:716px;top:901px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:716px;top:344px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:716px;top:367px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(To page 22−58)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:716px;top:355px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:80px;top:315px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.22 (7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:84px;top:373px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>22−56<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:80px;top:327px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:84px;top:361px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>From page<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:80px;top:338px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:80px;top:350px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:716px;top:270px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:716px;top:281px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(To page 22−59)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:716px;top:258px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:180px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>From page<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:180px;top:87px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>22−54<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:458px;top:469px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:458px;top:541px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:687px;top:884px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left headlight<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:613px;top:984px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:580px;top:927px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:495px;top:974px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Closed:switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:495px;top:951px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>COMBINATION<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:332px;top:870px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.13 (20A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:687px;top:784px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM/PCM (ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:345px;top:668px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>COMPRESSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:687px;top:167px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Via sunroof open/close relay)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:687px;top:184px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power mirror defogger (Via defogger relay)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:687px;top:155px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof motor<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:687px;top:327px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Taillight relay<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:263px;top:311px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.9 (10A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:685px;top:356px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:518px;top:327px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:230px;top:823px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:230px;top:811px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>HEADLIGHT <br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:687px;top:856px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right headlight<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:687px;top:556px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM/PCM (FANC)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:519px;top:613px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:687px;top:613px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Condenser fan motor<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:217px;top:597px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.11 (30A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:345px;top:504px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CONDENSER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:687px;top:541px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Radiator fan switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:345px;top:515px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:529px;top:541px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:687px;top:398px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Radiator fan motor<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:344px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:344px;top:354px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RADIATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:519px;top:399px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:687px;top:713px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/C compressor clutch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:345px;top:657px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:345px;top:680px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" class=\"drag\" style=\"position:absolute;left:530px;top:784px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" class=\"drag\" style=\"position:absolute;left:518px;top:713px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" class=\"drag\" style=\"position:absolute;left:260px;top:383px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.10 (20A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" class=\"drag\" style=\"position:absolute;left:685px;top:913px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" class=\"drag\" style=\"position:absolute;left:454px;top:927px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" class=\"drag\" style=\"position:absolute;left:332px;top:840px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.12 (20A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" class=\"drag\" style=\"position:absolute;left:530px;top:855px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" class=\"drag\" style=\"position:absolute;left:518px;top:885px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" class=\"drag\" style=\"position:absolute;left:516px;top:270px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" class=\"drag\" style=\"position:absolute;left:685px;top:271px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" class=\"drag\" style=\"position:absolute;left:263px;top:254px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.8 (15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" class=\"drag\" style=\"position:absolute;left:166px;top:33px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" class=\"drag\" style=\"position:absolute;left:518px;top:156px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" class=\"drag\" style=\"position:absolute;left:263px;top:140px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.7 (30A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" class=\"drag\" style=\"position:absolute;left:199px;top:106px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" class=\"drag\" style=\"position:absolute;left:88px;top:441px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" class=\"drag\" style=\"position:absolute;left:104px;top:392px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" class=\"drag\" style=\"position:absolute;left:585px;top:974px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}