with(document) {
write("<v:group id=\"group6\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect6\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img6\" src=\"../img/SAA3ECAA20300000000DBAD33.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p6_1\" class=\"drag\" style=\"position:absolute;left:41px;top:17px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>13P CONNECTOR (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" class=\"drag\" style=\"position:absolute;left:229px;top:16px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>6P CONNECTOR<br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" class=\"drag\" style=\"position:absolute;left:413px;top:17px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>GAUGE B (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" class=\"drag\" style=\"position:absolute;left:702px;top:17px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>GAUGE A (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" class=\"drag\" style=\"position:absolute;left:59px;top:151px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>IGNITION SWITCH<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" class=\"drag\" style=\"position:absolute;left:204px;top:152px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SERVICE CHECK<br>CONNECTOR (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" class=\"drag\" style=\"position:absolute;left:382px;top:151px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR (7)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" class=\"drag\" style=\"position:absolute;left:570px;top:138px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SECONDARY HO2S<br>(SENSOR 2) (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" class=\"drag\" style=\"position:absolute;left:730px;top:138px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>FUEL PUMP (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" class=\"drag\" style=\"position:absolute;left:92px;top:273px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION SWITCH<br>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" class=\"drag\" style=\"position:absolute;left:244px;top:285px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (11)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" class=\"drag\" style=\"position:absolute;left:468px;top:287px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" class=\"drag\" style=\"position:absolute;left:249px;top:422px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>RELAY BLOCK<br>(15)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" class=\"drag\" style=\"position:absolute;left:686px;top:286px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" class=\"drag\" style=\"position:absolute;left:46px;top:420px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" class=\"drag\" style=\"position:absolute;left:396px;top:407px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>RELAY BLOCK<br>(PGM-FI MAIN<br>RELAY 2) (16)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" class=\"drag\" style=\"position:absolute;left:535px;top:407px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>RELAY BLOCK<br>(PGM-FI MAIN<br>RELAY 1) (17)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" class=\"drag\" style=\"position:absolute;left:684px;top:422px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>RELAY BLOCK<br>(18)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" class=\"drag\" style=\"position:absolute;left:819px;top:408px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX (19)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_20\" class=\"drag\" style=\"position:absolute;left:86px;top:542px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX (20)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_21\" class=\"drag\" style=\"position:absolute;left:212px;top:556px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (21)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_22\" class=\"drag\" style=\"position:absolute;left:429px;top:555px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (22)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_23\" class=\"drag\" style=\"position:absolute;left:656px;top:555px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (23)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_24\" class=\"drag\" style=\"position:absolute;left:52px;top:691px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (24)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_25\" class=\"drag\" style=\"position:absolute;left:277px;top:677px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX (25)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_26\" class=\"drag\" style=\"position:absolute;left:595px;top:690px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>14P CONNECTOR (27)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_27\" class=\"drag\" style=\"position:absolute;left:785px;top:690px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM CONNECTOR<br>No.1 (9P) (28)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_28\" class=\"drag\" style=\"position:absolute;left:416px;top:690px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>3P CONNECTOR (26)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_29\" class=\"drag\" style=\"position:absolute;left:106px;top:817px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM CONNECTOR<br>No.3 (52P) (29)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_30\" class=\"drag\" style=\"position:absolute;left:577px;top:816px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM CONNECTOR<br>No.5 (9P) (31)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_31\" class=\"drag\" style=\"position:absolute;left:743px;top:816px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>INERTIA SWITCH<br>(32)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_32\" class=\"drag\" style=\"position:absolute;left:371px;top:818px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM CONNECTOR<br>No.4 (40P) (30)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_33\" class=\"drag\" style=\"position:absolute;left:15px;top:1018px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p6_34\" class=\"drag\" style=\"position:absolute;left:15px;top:1036px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p6_35\" class=\"drag\" style=\"position:absolute;left:15px;top:999px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p6_36\" class=\"drag\" style=\"position:absolute;left:34px;top:1018px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Connector with male terminals (double outline): view from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p6_37\" class=\"drag\" style=\"position:absolute;left:34px;top:1036px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Connector with female terminals (single outline): view from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p6_38\" class=\"drag\" style=\"position:absolute;left:15px;top:1054px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>**: Connector with female terminals (single outline): view from terminal side<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}