with(document) {
write("<v:group id=\"group15\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\" coordsize=\"950,863\">");
write("<v:rect id=\"rect15\"class=\"drag\"  style=\"width:950px;height:863px;\">");
write("<img id=\"img15\" src=\"../img/SAA3ECAA20300000000DBAD26.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p15_1\" class=\"drag\" style=\"position:absolute;left:24px;top:296px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C204<br></b></nobr>");
write("</p>");
write("<p id=\"p15_2\" class=\"drag\" style=\"position:absolute;left:51px;top:124px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C205<br></b></nobr>");
write("</p>");
write("<p id=\"p15_3\" class=\"drag\" style=\"position:absolute;left:235px;top:24px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p15_4\" class=\"drag\" style=\"position:absolute;left:350px;top:77px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C208<br></b></nobr>");
write("</p>");
write("<p id=\"p15_5\" class=\"drag\" style=\"position:absolute;left:455px;top:59px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C207<br></b></nobr>");
write("</p>");
write("<p id=\"p15_6\" class=\"drag\" style=\"position:absolute;left:596px;top:53px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C206<br></b></nobr>");
write("</p>");
write("<p id=\"p15_7\" class=\"drag\" style=\"position:absolute;left:725px;top:102px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C210<br></b></nobr>");
write("</p>");
write("<p id=\"p15_8\" class=\"drag\" style=\"position:absolute;left:785px;top:167px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C209<br></b></nobr>");
write("</p>");
write("<p id=\"p15_9\" class=\"drag\" style=\"position:absolute;left:865px;top:611px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C215<br>C305<br></b></nobr>");
write("</p>");
write("<p id=\"p15_10\" class=\"drag\" style=\"position:absolute;left:819px;top:322px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>COMPARTMENT<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p15_11\" class=\"drag\" style=\"position:absolute;left:869px;top:550px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C214<br>C306<br></b></nobr>");
write("</p>");
write("<p id=\"p15_12\" class=\"drag\" style=\"position:absolute;left:53px;top:714px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C217<br></b></nobr>");
write("</p>");
write("<p id=\"p15_13\" class=\"drag\" style=\"position:absolute;left:186px;top:733px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C218<br></b></nobr>");
write("</p>");
write("<p id=\"p15_14\" class=\"drag\" style=\"position:absolute;left:139px;top:78px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C251*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p15_15\" class=\"drag\" style=\"position:absolute;left:17px;top:824px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1: HONDA CVT + 7 SPEED MODE System<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}