with(document) {
write("<v:group id=\"group7\" class=\"drag\" style=\"position:relative; width:950px; height:815px;\" coordsize=\"950,815\">");
write("<v:rect id=\"rect7\"class=\"drag\"  style=\"width:950px;height:815px;\">");
write("<img id=\"img7\" src=\"../img/SAA3ECAA20300000000DBAD45.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:815px;border-color:#ffffff\">");
write("<p id=\"p7_1\" class=\"drag\" style=\"position:absolute;left:269px;top:47px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C208<br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" class=\"drag\" style=\"position:absolute;left:25px;top:268px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C216<br>C307<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" class=\"drag\" style=\"position:absolute;left:93px;top:142px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C214<br>C306<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" class=\"drag\" style=\"position:absolute;left:18px;top:200px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" class=\"drag\" style=\"position:absolute;left:337px;top:36px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C207<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" class=\"drag\" style=\"position:absolute;left:410px;top:30px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C206<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" class=\"drag\" style=\"position:absolute;left:493px;top:29px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C210<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" class=\"drag\" style=\"position:absolute;left:839px;top:67px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C204<br></b></nobr>");
write("</p>");
write("<p id=\"p7_9\" class=\"drag\" style=\"position:absolute;left:627px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_10\" class=\"drag\" style=\"position:absolute;left:38px;top:607px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p7_11\" class=\"drag\" style=\"position:absolute;left:425px;top:568px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C215<br>C305<br></b></nobr>");
write("</p>");
write("<p id=\"p7_12\" class=\"drag\" style=\"position:absolute;left:504px;top:576px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C209<br></b></nobr>");
write("</p>");
write("<p id=\"p7_13\" class=\"drag\" style=\"position:absolute;left:778px;top:776px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C218<br></b></nobr>");
write("</p>");
write("<p id=\"p7_14\" class=\"drag\" style=\"position:absolute;left:866px;top:761px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C217<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}