with(document) {
write("<v:group id=\"group6\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\" coordsize=\"950,1071\">");
write("<v:rect id=\"rect6\"class=\"drag\"  style=\"width:950px;height:1071px;\">");
write("<img id=\"img6\" src=\"../img/SAA3ECAA20300000000EAAD15.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p6_1\" class=\"drag\" style=\"position:absolute;left:133px;top:967px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PCM A(31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" class=\"drag\" style=\"position:absolute;left:386px;top:943px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TERMINAL LOCATIONS<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" class=\"drag\" style=\"position:absolute;left:709px;top:966px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PCM E(31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" class=\"drag\" style=\"position:absolute;left:340px;top:967px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PCM B(24P)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" class=\"drag\" style=\"position:absolute;left:518px;top:967px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PCM C(22P)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" class=\"drag\" style=\"position:absolute;left:544px;top:676px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" class=\"drag\" style=\"position:absolute;left:544px;top:704px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C1<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" class=\"drag\" style=\"position:absolute;left:564px;top:662px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DNLS+<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" class=\"drag\" style=\"position:absolute;left:564px;top:692px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DNLS−<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" class=\"drag\" style=\"position:absolute;left:385px;top:477px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B16<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" class=\"drag\" style=\"position:absolute;left:388px;top:505px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C8<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" class=\"drag\" style=\"position:absolute;left:29px;top:524px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CVT START CLUTCH<br>PRESSURE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" class=\"drag\" style=\"position:absolute;left:343px;top:462px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SCLS+<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" class=\"drag\" style=\"position:absolute;left:341px;top:492px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SCLS−<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" class=\"drag\" style=\"position:absolute;left:541px;top:478px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B24<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" class=\"drag\" style=\"position:absolute;left:542px;top:506px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C16<br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" class=\"drag\" style=\"position:absolute;left:802px;top:524px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CVT DRIVE PULLEY<br>CONTROL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" class=\"drag\" style=\"position:absolute;left:563px;top:463px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DRLS+<br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" class=\"drag\" style=\"position:absolute;left:564px;top:493px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DRLS−<br></b></nobr>");
write("</p>");
write("<p id=\"p6_20\" class=\"drag\" style=\"position:absolute;left:30px;top:699px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INHIBITOR<br>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p6_21\" class=\"drag\" style=\"position:absolute;left:388px;top:665px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C6<br></b></nobr>");
write("</p>");
write("<p id=\"p6_22\" class=\"drag\" style=\"position:absolute;left:344px;top:648px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INHSOL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_23\" class=\"drag\" style=\"position:absolute;left:160px;top:752px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p6_24\" class=\"drag\" style=\"position:absolute;left:813px;top:465px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C109<br></b></nobr>");
write("</p>");
write("<p id=\"p6_25\" class=\"drag\" style=\"position:absolute;left:812px;top:663px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C110<br></b></nobr>");
write("</p>");
write("<p id=\"p6_26\" class=\"drag\" style=\"position:absolute;left:108px;top:463px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C111<br></b></nobr>");
write("</p>");
write("<p id=\"p6_27\" class=\"drag\" style=\"position:absolute;left:107px;top:646px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C113<br></b></nobr>");
write("</p>");
write("<p id=\"p6_28\" class=\"drag\" style=\"position:absolute;left:669px;top:676px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p6_29\" class=\"drag\" style=\"position:absolute;left:670px;top:705px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_30\" class=\"drag\" style=\"position:absolute;left:221px;top:506px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p6_31\" class=\"drag\" style=\"position:absolute;left:669px;top:478px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p6_32\" class=\"drag\" style=\"position:absolute;left:669px;top:506px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_33\" class=\"drag\" style=\"position:absolute;left:220px;top:665px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_34\" class=\"drag\" style=\"position:absolute;left:245px;top:477px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_35\" class=\"drag\" style=\"position:absolute;left:798px;top:722px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CVT DRIVEN PULLEY<br>CONTROL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p6_36\" class=\"drag\" style=\"position:absolute;left:545px;top:139px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E9<br></b></nobr>");
write("</p>");
write("<p id=\"p6_37\" class=\"drag\" style=\"position:absolute;left:542px;top:170px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E22<br></b></nobr>");
write("</p>");
write("<p id=\"p6_38\" class=\"drag\" style=\"position:absolute;left:564px;top:126px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p6_39\" class=\"drag\" style=\"position:absolute;left:564px;top:158px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BKSW<br></b></nobr>");
write("</p>");
write("<p id=\"p6_40\" class=\"drag\" style=\"position:absolute;left:610px;top:170px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p6_41\" class=\"drag\" style=\"position:absolute;left:543px;top:260px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E28<br></b></nobr>");
write("</p>");
write("<p id=\"p6_42\" class=\"drag\" style=\"position:absolute;left:566px;top:249px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ACS<br></b></nobr>");
write("</p>");
write("<p id=\"p6_43\" class=\"drag\" style=\"position:absolute;left:640px;top:260px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p6_44\" class=\"drag\" style=\"position:absolute;left:791px;top:251px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To A/C<br>PRESSURE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p6_45\" class=\"drag\" style=\"position:absolute;left:542px;top:330px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E25<br></b></nobr>");
write("</p>");
write("<p id=\"p6_46\" class=\"drag\" style=\"position:absolute;left:565px;top:319px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VSSOUT<br></b></nobr>");
write("</p>");
write("<p id=\"p6_47\" class=\"drag\" style=\"position:absolute;left:639px;top:330px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_48\" class=\"drag\" style=\"position:absolute;left:791px;top:326px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To<br>SPEEDOMETER<br></b></nobr>");
write("</p>");
write("<p id=\"p6_49\" class=\"drag\" style=\"position:absolute;left:611px;top:139px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_50\" class=\"drag\" style=\"position:absolute;left:388px;top:99px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E7<br></b></nobr>");
write("</p>");
write("<p id=\"p6_51\" class=\"drag\" style=\"position:absolute;left:386px;top:168px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E10<br></b></nobr>");
write("</p>");
write("<p id=\"p6_52\" class=\"drag\" style=\"position:absolute;left:251px;top:100px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_53\" class=\"drag\" style=\"position:absolute;left:348px;top:83px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MRLY<br></b></nobr>");
write("</p>");
write("<p id=\"p6_54\" class=\"drag\" style=\"position:absolute;left:251px;top:168px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_55\" class=\"drag\" style=\"position:absolute;left:361px;top:152px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FPR<br></b></nobr>");
write("</p>");
write("<p id=\"p6_56\" class=\"drag\" style=\"position:absolute;left:386px;top:267px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E26<br></b></nobr>");
write("</p>");
write("<p id=\"p6_57\" class=\"drag\" style=\"position:absolute;left:357px;top:251px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>NEP<br></b></nobr>");
write("</p>");
write("<p id=\"p6_58\" class=\"drag\" style=\"position:absolute;left:120px;top:57px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p6_59\" class=\"drag\" style=\"position:absolute;left:193px;top:50px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p6_60\" class=\"drag\" style=\"position:absolute;left:157px;top:50px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p6_61\" class=\"drag\" style=\"position:absolute;left:784px;top:84px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p6_62\" class=\"drag\" style=\"position:absolute;left:820px;top:85px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p6_63\" class=\"drag\" style=\"position:absolute;left:129px;top:678px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p6_64\" class=\"drag\" style=\"position:absolute;left:272px;top:267px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}