with(document) {
write("<v:group id=\"group13\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\" coordsize=\"950,863\">");
write("<v:rect id=\"rect13\"class=\"drag\"  style=\"width:950px;height:863px;\">");
write("<img id=\"img13\" src=\"../img/SAA3ECAA20300000000DBAD24.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p13_1\" class=\"drag\" style=\"position:absolute;left:746px;top:153px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C101<br>C201<br></b></nobr>");
write("</p>");
write("<p id=\"p13_2\" class=\"drag\" style=\"position:absolute;left:868px;top:181px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p13_3\" class=\"drag\" style=\"position:absolute;left:284px;top:733px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p13_4\" class=\"drag\" style=\"position:absolute;left:465px;top:796px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C202*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p13_5\" class=\"drag\" style=\"position:absolute;left:611px;top:813px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM/PCM E<br>(31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p13_6\" class=\"drag\" style=\"position:absolute;left:765px;top:718px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM/PCM B<br>(24P)<br></b></nobr>");
write("</p>");
write("<p id=\"p13_7\" class=\"drag\" style=\"position:absolute;left:819px;top:669px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM/PCM A<br>(31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p13_8\" class=\"drag\" style=\"position:absolute;left:848px;top:574px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p13_9\" class=\"drag\" style=\"position:absolute;left:255px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C203<br>C401<br></b></nobr>");
write("</p>");
write("<p id=\"p13_10\" class=\"drag\" style=\"position:absolute;left:612px;top:39px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C402<br></b></nobr>");
write("</p>");
write("<p id=\"p13_11\" class=\"drag\" style=\"position:absolute;left:689px;top:770px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PCM C<br>(22P)<br></b></nobr>");
write("</p>");
write("<p id=\"p13_12\" class=\"drag\" style=\"position:absolute;left:16px;top:827px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*2: KG, KR models<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}