with(document) {
write("<v:group id=\"group10\" class=\"drag\" style=\"position:relative; width:950px; height:1117px;\" coordsize=\"950,1117\">");
write("<v:rect id=\"rect10\"class=\"drag\"  style=\"width:950px;height:1117px;\">");
write("<img id=\"img10\" src=\"../img/SAA3ECPA20300000000DBAD22.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1117px;border-color:#ffffff\">");
write("<p id=\"p10_1\" class=\"drag\" style=\"position:absolute;left:356px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_2\" class=\"drag\" style=\"position:absolute;left:380px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_3\" class=\"drag\" style=\"position:absolute;left:356px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_4\" class=\"drag\" style=\"position:absolute;left:356px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_5\" class=\"drag\" style=\"position:absolute;left:380px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_6\" class=\"drag\" style=\"position:absolute;left:356px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_7\" class=\"drag\" style=\"position:absolute;left:380px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_8\" class=\"drag\" style=\"position:absolute;left:380px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_9\" class=\"drag\" style=\"position:absolute;left:345px;top:24px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C213*<br></b></nobr>");
write("</p>");
write("<p id=\"p10_10\" class=\"drag\" style=\"position:absolute;left:386px;top:57px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_11\" class=\"drag\" style=\"position:absolute;left:386px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_12\" class=\"drag\" style=\"position:absolute;left:404px;top:94px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_13\" class=\"drag\" style=\"position:absolute;left:367px;top:94px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_14\" class=\"drag\" style=\"position:absolute;left:680px;top:608px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_15\" class=\"drag\" style=\"position:absolute;left:680px;top:679px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_16\" class=\"drag\" style=\"position:absolute;left:645px;top:496px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C354<br></b></nobr>");
write("</p>");
write("<p id=\"p10_17\" class=\"drag\" style=\"position:absolute;left:656px;top:651px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_18\" class=\"drag\" style=\"position:absolute;left:680px;top:651px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_19\" class=\"drag\" style=\"position:absolute;left:656px;top:593px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_20\" class=\"drag\" style=\"position:absolute;left:680px;top:594px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_21\" class=\"drag\" style=\"position:absolute;left:656px;top:608px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_22\" class=\"drag\" style=\"position:absolute;left:656px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_23\" class=\"drag\" style=\"position:absolute;left:656px;top:636px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_24\" class=\"drag\" style=\"position:absolute;left:656px;top:679px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_25\" class=\"drag\" style=\"position:absolute;left:680px;top:665px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_26\" class=\"drag\" style=\"position:absolute;left:656px;top:665px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_27\" class=\"drag\" style=\"position:absolute;left:692px;top:547px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_28\" class=\"drag\" style=\"position:absolute;left:711px;top:547px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_29\" class=\"drag\" style=\"position:absolute;left:674px;top:528px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_30\" class=\"drag\" style=\"position:absolute;left:674px;top:547px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_31\" class=\"drag\" style=\"position:absolute;left:655px;top:528px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_32\" class=\"drag\" style=\"position:absolute;left:509px;top:496px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C353<br></b></nobr>");
write("</p>");
write("<p id=\"p10_33\" class=\"drag\" style=\"position:absolute;left:549px;top:547px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_34\" class=\"drag\" style=\"position:absolute;left:545px;top:594px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_35\" class=\"drag\" style=\"position:absolute;left:520px;top:593px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_36\" class=\"drag\" style=\"position:absolute;left:409px;top:636px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_37\" class=\"drag\" style=\"position:absolute;left:409px;top:608px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_38\" class=\"drag\" style=\"position:absolute;left:323px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_39\" class=\"drag\" style=\"position:absolute;left:396px;top:538px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_40\" class=\"drag\" style=\"position:absolute;left:414px;top:538px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_41\" class=\"drag\" style=\"position:absolute;left:340px;top:538px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_42\" class=\"drag\" style=\"position:absolute;left:323px;top:608px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_43\" class=\"drag\" style=\"position:absolute;left:323px;top:636px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_44\" class=\"drag\" style=\"position:absolute;left:409px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_45\" class=\"drag\" style=\"position:absolute;left:385px;top:636px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_46\" class=\"drag\" style=\"position:absolute;left:385px;top:593px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_47\" class=\"drag\" style=\"position:absolute;left:299px;top:593px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_48\" class=\"drag\" style=\"position:absolute;left:299px;top:608px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_49\" class=\"drag\" style=\"position:absolute;left:299px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_50\" class=\"drag\" style=\"position:absolute;left:299px;top:636px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_51\" class=\"drag\" style=\"position:absolute;left:385px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_52\" class=\"drag\" style=\"position:absolute;left:385px;top:608px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_53\" class=\"drag\" style=\"position:absolute;left:433px;top:538px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_54\" class=\"drag\" style=\"position:absolute;left:321px;top:538px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_55\" class=\"drag\" style=\"position:absolute;left:358px;top:538px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_56\" class=\"drag\" style=\"position:absolute;left:287px;top:496px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C352<br></b></nobr>");
write("</p>");
write("<p id=\"p10_57\" class=\"drag\" style=\"position:absolute;left:44px;top:496px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C351<br></b></nobr>");
write("</p>");
write("<p id=\"p10_58\" class=\"drag\" style=\"position:absolute;left:202px;top:538px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_59\" class=\"drag\" style=\"position:absolute;left:81px;top:538px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_60\" class=\"drag\" style=\"position:absolute;left:63px;top:538px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_61\" class=\"drag\" style=\"position:absolute;left:119px;top:538px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_62\" class=\"drag\" style=\"position:absolute;left:156px;top:608px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_63\" class=\"drag\" style=\"position:absolute;left:156px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_64\" class=\"drag\" style=\"position:absolute;left:70px;top:636px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_65\" class=\"drag\" style=\"position:absolute;left:94px;top:594px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_66\" class=\"drag\" style=\"position:absolute;left:70px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_67\" class=\"drag\" style=\"position:absolute;left:70px;top:608px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_68\" class=\"drag\" style=\"position:absolute;left:70px;top:593px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_69\" class=\"drag\" style=\"position:absolute;left:156px;top:593px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_70\" class=\"drag\" style=\"position:absolute;left:156px;top:636px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_71\" class=\"drag\" style=\"position:absolute;left:179px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_72\" class=\"drag\" style=\"position:absolute;left:94px;top:636px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_73\" class=\"drag\" style=\"position:absolute;left:94px;top:608px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_74\" class=\"drag\" style=\"position:absolute;left:680px;top:351px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_75\" class=\"drag\" style=\"position:absolute;left:630px;top:239px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C257<br></b></nobr>");
write("</p>");
write("<p id=\"p10_76\" class=\"drag\" style=\"position:absolute;left:656px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_77\" class=\"drag\" style=\"position:absolute;left:656px;top:379px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_78\" class=\"drag\" style=\"position:absolute;left:656px;top:393px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_79\" class=\"drag\" style=\"position:absolute;left:656px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_80\" class=\"drag\" style=\"position:absolute;left:656px;top:351px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_81\" class=\"drag\" style=\"position:absolute;left:680px;top:336px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_82\" class=\"drag\" style=\"position:absolute;left:656px;top:336px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_83\" class=\"drag\" style=\"position:absolute;left:656px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_84\" class=\"drag\" style=\"position:absolute;left:680px;top:394px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_85\" class=\"drag\" style=\"position:absolute;left:676px;top:297px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_86\" class=\"drag\" style=\"position:absolute;left:685px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_87\" class=\"drag\" style=\"position:absolute;left:660px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_88\" class=\"drag\" style=\"position:absolute;left:657px;top:297px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_89\" class=\"drag\" style=\"position:absolute;left:680px;top:379px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_90\" class=\"drag\" style=\"position:absolute;left:180px;top:379px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_91\" class=\"drag\" style=\"position:absolute;left:228px;top:287px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_92\" class=\"drag\" style=\"position:absolute;left:94px;top:379px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_93\" class=\"drag\" style=\"position:absolute;left:156px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_94\" class=\"drag\" style=\"position:absolute;left:70px;top:393px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_95\" class=\"drag\" style=\"position:absolute;left:94px;top:394px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_96\" class=\"drag\" style=\"position:absolute;left:70px;top:336px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_97\" class=\"drag\" style=\"position:absolute;left:70px;top:351px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_98\" class=\"drag\" style=\"position:absolute;left:70px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_99\" class=\"drag\" style=\"position:absolute;left:94px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_100\" class=\"drag\" style=\"position:absolute;left:70px;top:379px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_101\" class=\"drag\" style=\"position:absolute;left:180px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_102\" class=\"drag\" style=\"position:absolute;left:156px;top:351px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_103\" class=\"drag\" style=\"position:absolute;left:180px;top:336px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_104\" class=\"drag\" style=\"position:absolute;left:156px;top:336px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_105\" class=\"drag\" style=\"position:absolute;left:156px;top:379px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_106\" class=\"drag\" style=\"position:absolute;left:126px;top:287px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_107\" class=\"drag\" style=\"position:absolute;left:107px;top:287px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_108\" class=\"drag\" style=\"position:absolute;left:89px;top:287px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_109\" class=\"drag\" style=\"position:absolute;left:172px;top:287px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_110\" class=\"drag\" style=\"position:absolute;left:210px;top:287px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_111\" class=\"drag\" style=\"position:absolute;left:153px;top:394px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_112\" class=\"drag\" style=\"position:absolute;left:44px;top:239px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C254<br></b></nobr>");
write("</p>");
write("<p id=\"p10_113\" class=\"drag\" style=\"position:absolute;left:466px;top:336px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_114\" class=\"drag\" style=\"position:absolute;left:439px;top:436px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_115\" class=\"drag\" style=\"position:absolute;left:439px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p10_116\" class=\"drag\" style=\"position:absolute;left:439px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_117\" class=\"drag\" style=\"position:absolute;left:380px;top:379px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_118\" class=\"drag\" style=\"position:absolute;left:451px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_119\" class=\"drag\" style=\"position:absolute;left:511px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_120\" class=\"drag\" style=\"position:absolute;left:345px;top:239px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C255<br></b></nobr>");
write("</p>");
write("<p id=\"p10_121\" class=\"drag\" style=\"position:absolute;left:393px;top:297px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_122\" class=\"drag\" style=\"position:absolute;left:396px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_123\" class=\"drag\" style=\"position:absolute;left:355px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_124\" class=\"drag\" style=\"position:absolute;left:373px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_125\" class=\"drag\" style=\"position:absolute;left:373px;top:296px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_126\" class=\"drag\" style=\"position:absolute;left:412px;top:296px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_127\" class=\"drag\" style=\"position:absolute;left:430px;top:296px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_128\" class=\"drag\" style=\"position:absolute;left:492px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_129\" class=\"drag\" style=\"position:absolute;left:490px;top:296px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p10_130\" class=\"drag\" style=\"position:absolute;left:474px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_131\" class=\"drag\" style=\"position:absolute;left:471px;top:296px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_132\" class=\"drag\" style=\"position:absolute;left:466px;top:351px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_133\" class=\"drag\" style=\"position:absolute;left:356px;top:436px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_134\" class=\"drag\" style=\"position:absolute;left:442px;top:336px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_135\" class=\"drag\" style=\"position:absolute;left:466px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_136\" class=\"drag\" style=\"position:absolute;left:439px;top:379px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_137\" class=\"drag\" style=\"position:absolute;left:466px;top:379px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_138\" class=\"drag\" style=\"position:absolute;left:380px;top:394px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_139\" class=\"drag\" style=\"position:absolute;left:380px;top:351px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_140\" class=\"drag\" style=\"position:absolute;left:356px;top:379px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_141\" class=\"drag\" style=\"position:absolute;left:356px;top:393px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_142\" class=\"drag\" style=\"position:absolute;left:380px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_143\" class=\"drag\" style=\"position:absolute;left:356px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_144\" class=\"drag\" style=\"position:absolute;left:356px;top:351px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_145\" class=\"drag\" style=\"position:absolute;left:380px;top:336px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_146\" class=\"drag\" style=\"position:absolute;left:356px;top:336px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_147\" class=\"drag\" style=\"position:absolute;left:380px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_148\" class=\"drag\" style=\"position:absolute;left:356px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_149\" class=\"drag\" style=\"position:absolute;left:466px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_150\" class=\"drag\" style=\"position:absolute;left:466px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_151\" class=\"drag\" style=\"position:absolute;left:380px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_152\" class=\"drag\" style=\"position:absolute;left:356px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_153\" class=\"drag\" style=\"position:absolute;left:440px;top:352px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_154\" class=\"drag\" style=\"position:absolute;left:439px;top:393px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_155\" class=\"drag\" style=\"position:absolute;left:439px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_156\" class=\"drag\" style=\"position:absolute;left:630px;top:24px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C253<br></b></nobr>");
write("</p>");
write("<p id=\"p10_157\" class=\"drag\" style=\"position:absolute;left:739px;top:179px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_158\" class=\"drag\" style=\"position:absolute;left:830px;top:73px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_159\" class=\"drag\" style=\"position:absolute;left:795px;top:73px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_160\" class=\"drag\" style=\"position:absolute;left:758px;top:73px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_161\" class=\"drag\" style=\"position:absolute;left:777px;top:73px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_162\" class=\"drag\" style=\"position:absolute;left:638px;top:73px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_163\" class=\"drag\" style=\"position:absolute;left:656px;top:73px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_164\" class=\"drag\" style=\"position:absolute;left:675px;top:73px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_165\" class=\"drag\" style=\"position:absolute;left:693px;top:73px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_166\" class=\"drag\" style=\"position:absolute;left:712px;top:73px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_167\" class=\"drag\" style=\"position:absolute;left:546px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_168\" class=\"drag\" style=\"position:absolute;left:546px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_169\" class=\"drag\" style=\"position:absolute;left:528px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_170\" class=\"drag\" style=\"position:absolute;left:509px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_171\" class=\"drag\" style=\"position:absolute;left:488px;top:24px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C251<br></b></nobr>");
write("</p>");
write("<p id=\"p10_172\" class=\"drag\" style=\"position:absolute;left:499px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_173\" class=\"drag\" style=\"position:absolute;left:523px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_174\" class=\"drag\" style=\"position:absolute;left:499px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_175\" class=\"drag\" style=\"position:absolute;left:523px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_176\" class=\"drag\" style=\"position:absolute;left:499px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_177\" class=\"drag\" style=\"position:absolute;left:523px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_178\" class=\"drag\" style=\"position:absolute;left:499px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_179\" class=\"drag\" style=\"position:absolute;left:523px;top:179px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_180\" class=\"drag\" style=\"position:absolute;left:499px;top:179px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_181\" class=\"drag\" style=\"position:absolute;left:81px;top:94px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_182\" class=\"drag\" style=\"position:absolute;left:118px;top:94px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_183\" class=\"drag\" style=\"position:absolute;left:100px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_184\" class=\"drag\" style=\"position:absolute;left:100px;top:57px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_185\" class=\"drag\" style=\"position:absolute;left:242px;top:94px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_186\" class=\"drag\" style=\"position:absolute;left:242px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_187\" class=\"drag\" style=\"position:absolute;left:261px;top:57px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_188\" class=\"drag\" style=\"position:absolute;left:223px;top:57px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_189\" class=\"drag\" style=\"position:absolute;left:44px;top:24px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C211*<br></b></nobr>");
write("</p>");
write("<p id=\"p10_190\" class=\"drag\" style=\"position:absolute;left:202px;top:24px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C212*<br></b></nobr>");
write("</p>");
write("<p id=\"p10_191\" class=\"drag\" style=\"position:absolute;left:213px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_192\" class=\"drag\" style=\"position:absolute;left:237px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_193\" class=\"drag\" style=\"position:absolute;left:213px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_194\" class=\"drag\" style=\"position:absolute;left:213px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_195\" class=\"drag\" style=\"position:absolute;left:237px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_196\" class=\"drag\" style=\"position:absolute;left:213px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_197\" class=\"drag\" style=\"position:absolute;left:237px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_198\" class=\"drag\" style=\"position:absolute;left:237px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_199\" class=\"drag\" style=\"position:absolute;left:94px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_200\" class=\"drag\" style=\"position:absolute;left:94px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_201\" class=\"drag\" style=\"position:absolute;left:70px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_202\" class=\"drag\" style=\"position:absolute;left:94px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_203\" class=\"drag\" style=\"position:absolute;left:70px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_204\" class=\"drag\" style=\"position:absolute;left:70px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_205\" class=\"drag\" style=\"position:absolute;left:94px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_206\" class=\"drag\" style=\"position:absolute;left:70px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_207\" class=\"drag\" style=\"position:absolute;left:766px;top:179px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_208\" class=\"drag\" style=\"position:absolute;left:742px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_209\" class=\"drag\" style=\"position:absolute;left:742px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_210\" class=\"drag\" style=\"position:absolute;left:766px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_211\" class=\"drag\" style=\"position:absolute;left:742px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_212\" class=\"drag\" style=\"position:absolute;left:766px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_213\" class=\"drag\" style=\"position:absolute;left:656px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_214\" class=\"drag\" style=\"position:absolute;left:680px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_215\" class=\"drag\" style=\"position:absolute;left:656px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_216\" class=\"drag\" style=\"position:absolute;left:656px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_217\" class=\"drag\" style=\"position:absolute;left:680px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_218\" class=\"drag\" style=\"position:absolute;left:656px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_219\" class=\"drag\" style=\"position:absolute;left:680px;top:179px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_220\" class=\"drag\" style=\"position:absolute;left:656px;top:179px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_221\" class=\"drag\" style=\"position:absolute;left:742px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_222\" class=\"drag\" style=\"position:absolute;left:766px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_223\" class=\"drag\" style=\"position:absolute;left:680px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_224\" class=\"drag\" style=\"position:absolute;left:680px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_225\" class=\"drag\" style=\"position:absolute;left:103px;top:1079px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>* : Terminal side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p10_226\" class=\"drag\" style=\"position:absolute;left:87px;top:1035px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>· Connector with female terminals (single outline) : View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p10_227\" class=\"drag\" style=\"position:absolute;left:87px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>· Connector with male terminals (double outline) : View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p10_228\" class=\"drag\" style=\"position:absolute;left:32px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_229\" class=\"drag\" style=\"position:absolute;left:87px;top:1049px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p10_230\" class=\"drag\" style=\"position:absolute;left:123px;top:1049px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to ECM/PCM control.<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}