with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:511px;\" coordsize=\"950,511\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:511px;\">");
write("<img id=\"img2\" src=\"../img/SAA3EDLA20300000000CAAD29.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:511px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:260px;top:61px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:310px;top:44px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:358px;top:34px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:409px;top:26px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:461px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:512px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:668px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:767px;top:409px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:717px;top:441px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:678px;top:456px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:638px;top:468px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:589px;top:475px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:539px;top:480px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:488px;top:483px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:423px;top:482px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:374px;top:482px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:105px;top:396px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:820px;top:287px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}