with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1007px;\" coordsize=\"950,1007\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1007px;\">");
write("<img id=\"img1\" src=\"../img/SAA3E50A20326400000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1007px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:772px;top:225px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILL CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:475px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL TUBE/QUICK-CONNECT FITTINGS<br><a href=\"javascript:parent.Cts('000000000000543','i000')\"></b>Precautions,</a><br> in the '02 Jazz/Fit Shop Manual<br><a href=\"javascript:parent.Cts('000000000000545','i000')\">Removal,</a><br> in the '02 Jazz/Fit Shop Manual<br><a href=\"javascript:parent.Cts('000000000000546','i000')\">Installation,</a><br> in the '02 Jazz/Fit Shop Manual<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:676px;top:663px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL TANK<br><a href=\"javascript:parent.Cts('000000000000550','i000')\"></b>Replacement,</a><br> in the '02 Jazz/Fit Shop Manual<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:292px;top:762px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FEED PIPE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:18px;top:330px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL RAIL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:507px;top:712px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL VAPOR PIPE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:673px;top:133px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SUCTION LINE<br><a href=\"javascript:parent.Cts('000000000000544','i000')\"></b>Inspection,</a><br> in the '02 Jazz/Fit Shop Manual<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:676px;top:539px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BREATHER LINE<br><a href=\"javascript:parent.Cts('000000000000544','i000')\"></b>Inspection,<br></a><br> in the '02 Jazz/Fit Shop Manual<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:53px;top:789px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL PUMP<br><a href=\"javascript:parent.Cts('000000000001358','i000')\"></b>Circuit Troubleshooting,</a><br><a href=\"javascript:parent.Cts('000000000000549','i000')\">Replacement,</a> <br> in the '02 Jazz/Fit Shop Manual<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:53px;top:852px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILTER<br><a href=\"javascript:parent.Cts('000000000000542','i000')\"></b>Replacement,</a><br> in the '02 Jazz/Fit Shop Manual<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:53px;top:900px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL GAUGE SENDING UNIT<br><a href=\"javascript:parent.Cts('000000000000807','i000')\"></b>Test/</a><br> in the '02 Jazz/Fit Shop Manual<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:53px;top:947px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL PRESSURE REGULATOR<br><a href=\"javascript:parent.Cts('000000000000548','i000')\"></b>Replacement,</a><br> in the '02 Jazz/Fit Shop Manual<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}