with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:995px;\" coordsize=\"950,995\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:995px;\">");
write("<img id=\"img2\" src=\"../img/SAA3E5PJ54230100000EAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:995px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:378px;top:32px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:407px;top:32px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:651px;top:32px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front fog light relay<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:365px;top:946px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right front SRS sensor sub−harness<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:358px;top:945px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:340px;top:946px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:340px;top:925px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:358px;top:924px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:365px;top:925px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left front SRS sensor sub−harness<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:651px;top:804px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front ceiling/spotlights (with sunroof)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:651px;top:789px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof position sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:651px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:405px;top:732px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:378px;top:732px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:378px;top:675px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:407px;top:675px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:651px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left side turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:564px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:590px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:492px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:463px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:463px;top:596px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:490px;top:596px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:651px;top:546px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's door lock switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:651px;top:561px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's heated mirror<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:237px;top:488px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:658px;top:418px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power door unlock/Fuel fill door unlock relay<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:658px;top:303px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight adjuster switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:378px;top:318px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:407px;top:318px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:651px;top:61px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Combination light switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:378px;top:60px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:407px;top:60px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:658px;top:361px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power door lock/Fuel fill door lock relay<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:407px;top:596px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:378px;top:596px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:378px;top:532px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:404px;top:532px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:404px;top:461px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:378px;top:461px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:178px;top:532px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:149px;top:532px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:149px;top:461px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:178px;top:461px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:407px;top:432px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:378px;top:432px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:407px;top:403px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:378px;top:403px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:407px;top:375px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:378px;top:375px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:407px;top:346px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:378px;top:346px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:407px;top:289px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" class=\"drag\" style=\"position:absolute;left:378px;top:289px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" class=\"drag\" style=\"position:absolute;left:407px;top:261px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" class=\"drag\" style=\"position:absolute;left:378px;top:261px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" class=\"drag\" style=\"position:absolute;left:407px;top:232px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" class=\"drag\" style=\"position:absolute;left:378px;top:232px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" class=\"drag\" style=\"position:absolute;left:407px;top:203px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" class=\"drag\" style=\"position:absolute;left:378px;top:203px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" class=\"drag\" style=\"position:absolute;left:407px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" class=\"drag\" style=\"position:absolute;left:378px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" class=\"drag\" style=\"position:absolute;left:407px;top:146px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" class=\"drag\" style=\"position:absolute;left:378px;top:146px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" class=\"drag\" style=\"position:absolute;left:407px;top:118px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" class=\"drag\" style=\"position:absolute;left:378px;top:118px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" class=\"drag\" style=\"position:absolute;left:378px;top:89px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" class=\"drag\" style=\"position:absolute;left:407px;top:89px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" class=\"drag\" style=\"position:absolute;left:658px;top:682px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power mirror switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" class=\"drag\" style=\"position:absolute;left:435px;top:835px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" class=\"drag\" style=\"position:absolute;left:651px;top:846px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power window relay<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" class=\"drag\" style=\"position:absolute;left:651px;top:761px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof close relay<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" class=\"drag\" style=\"position:absolute;left:651px;top:746px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof open relay<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" class=\"drag\" style=\"position:absolute;left:651px;top:732px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" class=\"drag\" style=\"position:absolute;left:651px;top:596px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Hazard warning switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" class=\"drag\" style=\"position:absolute;left:651px;top:532px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's door lock knob switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" class=\"drag\" style=\"position:absolute;left:237px;top:499px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" class=\"drag\" style=\"position:absolute;left:658px;top:468px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power window master switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" class=\"drag\" style=\"position:absolute;left:651px;top:261px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Memory erase signal (MES) connector<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" class=\"drag\" style=\"position:absolute;left:651px;top:203px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge assembly (Entry light control circuit ground)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" class=\"drag\" style=\"position:absolute;left:651px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge assembly (S−GND)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" class=\"drag\" style=\"position:absolute;left:108px;top:946px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Roof wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" class=\"drag\" style=\"position:absolute;left:101px;top:945px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" class=\"drag\" style=\"position:absolute;left:84px;top:947px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" class=\"drag\" style=\"position:absolute;left:651px;top:146px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge assembly (P−GND)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" class=\"drag\" style=\"position:absolute;left:82px;top:968px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" class=\"drag\" style=\"position:absolute;left:101px;top:966px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" class=\"drag\" style=\"position:absolute;left:108px;top:968px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" class=\"drag\" style=\"position:absolute;left:651px;top:118px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear wiper/washer switch (without rear intermittent)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" class=\"drag\" style=\"position:absolute;left:651px;top:89px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Windshield wiper/washer switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" class=\"drag\" style=\"position:absolute;left:67px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" class=\"drag\" style=\"position:absolute;left:108px;top:925px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Dashboard wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" class=\"drag\" style=\"position:absolute;left:101px;top:924px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" class=\"drag\" style=\"position:absolute;left:85px;top:925px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" class=\"drag\" style=\"position:absolute;left:651px;top:232px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Ignition key switch<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}