with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1119px;\" coordsize=\"950,1119\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1119px;\">");
write("<img id=\"img1\" src=\"../img/SAA3ECPA20300000000EAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1119px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:726px;top:491px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C257<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:363px;top:652px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C214<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:417px;top:651px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C214<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:657px;top:86px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:657px;top:103px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:657px;top:135px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:669px;top:119px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:669px;top:218px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:668px;top:236px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:657px;top:167px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:659px;top:389px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:824px;top:59px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:860px;top:92px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:844px;top:190px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:844px;top:224px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:842px;top:296px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:769px;top:26px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:658px;top:184px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:657px;top:151px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:668px;top:270px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:670px;top:372px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:659px;top:411px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:669px;top:70px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:658px;top:202px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:657px;top:253px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:658px;top:290px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:668px;top:324px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:658px;top:308px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:659px;top:342px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:659px;top:429px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:723px;top:57px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C353<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:725px;top:399px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C251<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:725px;top:360px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C255<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:725px;top:279px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C254<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:725px;top:176px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C253<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:725px;top:159px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C351<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:725px;top:94px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C354<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:725px;top:78px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C352<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:872px;top:1023px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:841px;top:681px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGNITION<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:900px;top:636px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:840px;top:609px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:843px;top:631px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:839px;top:653px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:862px;top:786px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>STARTER<br>CUT<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:860px;top:856px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PGM-FI<br>MAIN<br>RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:860px;top:927px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PGM-FI<br>MAIN<br>RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:694px;top:816px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:693px;top:848px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:692px;top:861px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:692px;top:875px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:694px;top:888px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:694px;top:920px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:695px;top:979px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:694px;top:993px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:736px;top:1017px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:809px;top:1032px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:844px;top:1048px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FUEL PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:595px;top:1082px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:678px;top:1081px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:766px;top:1075px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:538px;top:1089px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:651px;top:1081px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:697px;top:725px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:698px;top:598px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:699px;top:621px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:712px;top:664px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:621px;top:1081px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:566px;top:1082px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:510px;top:1082px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:692px;top:803px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:695px;top:932px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:830px;top:1001px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C217<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:759px;top:905px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C212<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:760px;top:839px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C211<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:756px;top:772px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C213<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:761px;top:733px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C216<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:787px;top:692px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C210<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:644px;top:770px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:698px;top:642px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:697px;top:748px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:254px;top:223px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:184px;top:59px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:373px;top:240px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:267px;top:71px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:258px;top:179px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:252px;top:362px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:260px;top:377px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:201px;top:465px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:124px;top:471px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:141px;top:240px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A/C<br>CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:149px;top:313px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RADIATOR<br>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:121px;top:367px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:62px;top:444px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:227px;top:1080px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:251px;top:1080px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:277px;top:1080px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:352px;top:1087px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:22px;top:495px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TEST TACHOMETER<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:377px;top:1080px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:402px;top:1080px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:427px;top:1080px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:329px;top:1081px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:303px;top:1088px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:158px;top:501px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:260px;top:347px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:255px;top:296px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:35px;top:721px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUSES:<br>UNDER-HOOD<br>FUSE/RELAY BOX:<br>(1) No. 6 (40A)<br>(2) No. 3 (50A)<br>(3) No. 8 (15A)<br>(4) No. 16 (10A)<br>(5) No. 1 (80A)<br><br>UNDER-DASH<br>FUSE/RELAY BOX<br>(6) No. 20 (15A)<br>(7) No. 22 (7.5A)<br>(8) No. 7 (15A)<br>(9) No. 16 (7.5A)<br>(10) No. 11 (15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:21px;top:16px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:239px;top:58px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C372<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:239px;top:168px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C375<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:240px;top:326px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C304<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:135px;top:524px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C303<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:69px;top:993px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1: CVT<br>*2: M/T<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:183px;top:89px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:183px;top:142px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:84px;top:116px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:84px;top:143px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:257px;top:127px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:257px;top:154px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:267px;top:101px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:239px;top:90px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C373<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:238px;top:115px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C371<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:239px;top:143px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C374<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:289px;top:461px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C306<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:289px;top:489px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C214<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:259px;top:699px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:282px;top:715px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:17px;top:574px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE<br>PEDAL<br>POSITION<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:148px;top:584px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:148px;top:602px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:126px;top:566px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C209<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}