with(document) {
write("<v:group id=\"group12\" class=\"drag\" style=\"position:relative; width:950px; height:1090px;\" coordsize=\"950,1090\">");
write("<v:rect id=\"rect12\"class=\"drag\"  style=\"width:950px;height:1090px;\">");
write("<img id=\"img12\" src=\"../img/SAA3ECPA20300000000DBAD24.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1090px;border-color:#ffffff\">");
write("<p id=\"p12_1\" class=\"drag\" style=\"position:absolute;left:166px;top:865px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b> <br></b></nobr>");
write("</p>");
write("<p id=\"p12_2\" class=\"drag\" style=\"position:absolute;left:240px;top:823px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p12_3\" class=\"drag\" style=\"position:absolute;left:266px;top:822px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_4\" class=\"drag\" style=\"position:absolute;left:264px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p12_5\" class=\"drag\" style=\"position:absolute;left:482px;top:536px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p12_6\" class=\"drag\" style=\"position:absolute;left:509px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_7\" class=\"drag\" style=\"position:absolute;left:483px;top:437px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_8\" class=\"drag\" style=\"position:absolute;left:396px;top:536px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p12_9\" class=\"drag\" style=\"position:absolute;left:529px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_10\" class=\"drag\" style=\"position:absolute;left:153px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p12_11\" class=\"drag\" style=\"position:absolute;left:32px;top:936px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_12\" class=\"drag\" style=\"position:absolute;left:57px;top:936px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: CVT model<br></b></nobr>");
write("</p>");
write("<p id=\"p12_13\" class=\"drag\" style=\"position:absolute;left:485px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_14\" class=\"drag\" style=\"position:absolute;left:509px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_15\" class=\"drag\" style=\"position:absolute;left:509px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_16\" class=\"drag\" style=\"position:absolute;left:485px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_17\" class=\"drag\" style=\"position:absolute;left:523px;top:77px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_18\" class=\"drag\" style=\"position:absolute;left:504px;top:77px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_19\" class=\"drag\" style=\"position:absolute;left:473px;top:24px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C402<br></b></nobr>");
write("</p>");
write("<p id=\"p12_20\" class=\"drag\" style=\"position:absolute;left:168px;top:123px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p12_21\" class=\"drag\" style=\"position:absolute;left:194px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_22\" class=\"drag\" style=\"position:absolute;left:93px;top:179px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p12_23\" class=\"drag\" style=\"position:absolute;left:93px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_24\" class=\"drag\" style=\"position:absolute;left:93px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_25\" class=\"drag\" style=\"position:absolute;left:48px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p12_26\" class=\"drag\" style=\"position:absolute;left:87px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_27\" class=\"drag\" style=\"position:absolute;left:128px;top:59px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_28\" class=\"drag\" style=\"position:absolute;left:110px;top:59px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_29\" class=\"drag\" style=\"position:absolute;left:509px;top:508px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_30\" class=\"drag\" style=\"position:absolute;left:509px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p12_31\" class=\"drag\" style=\"position:absolute;left:483px;top:494px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p12_32\" class=\"drag\" style=\"position:absolute;left:483px;top:509px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p12_33\" class=\"drag\" style=\"position:absolute;left:397px;top:566px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p12_34\" class=\"drag\" style=\"position:absolute;left:423px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_35\" class=\"drag\" style=\"position:absolute;left:397px;top:552px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p12_36\" class=\"drag\" style=\"position:absolute;left:423px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_37\" class=\"drag\" style=\"position:absolute;left:436px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p12_38\" class=\"drag\" style=\"position:absolute;left:473px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p12_39\" class=\"drag\" style=\"position:absolute;left:473px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p12_40\" class=\"drag\" style=\"position:absolute;left:455px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p12_41\" class=\"drag\" style=\"position:absolute;left:740px;top:423px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p12_42\" class=\"drag\" style=\"position:absolute;left:766px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_43\" class=\"drag\" style=\"position:absolute;left:755px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p12_44\" class=\"drag\" style=\"position:absolute;left:154px;top:837px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p12_45\" class=\"drag\" style=\"position:absolute;left:180px;top:837px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_46\" class=\"drag\" style=\"position:absolute;left:154px;top:852px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p12_47\" class=\"drag\" style=\"position:absolute;left:180px;top:851px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_48\" class=\"drag\" style=\"position:absolute;left:94px;top:822px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_49\" class=\"drag\" style=\"position:absolute;left:264px;top:666px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p12_50\" class=\"drag\" style=\"position:absolute;left:283px;top:665px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p12_51\" class=\"drag\" style=\"position:absolute;left:261px;top:647px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p12_52\" class=\"drag\" style=\"position:absolute;left:423px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_53\" class=\"drag\" style=\"position:absolute;left:194px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_54\" class=\"drag\" style=\"position:absolute;left:66px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p12_55\" class=\"drag\" style=\"position:absolute;left:94px;top:251px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_56\" class=\"drag\" style=\"position:absolute;left:70px;top:236px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p12_57\" class=\"drag\" style=\"position:absolute;left:68px;top:252px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p12_58\" class=\"drag\" style=\"position:absolute;left:111px;top:80px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p12_59\" class=\"drag\" style=\"position:absolute;left:167px;top:251px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p12_60\" class=\"drag\" style=\"position:absolute;left:70px;top:208px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p12_61\" class=\"drag\" style=\"position:absolute;left:70px;top:193px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_62\" class=\"drag\" style=\"position:absolute;left:70px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_63\" class=\"drag\" style=\"position:absolute;left:70px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_64\" class=\"drag\" style=\"position:absolute;left:70px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_65\" class=\"drag\" style=\"position:absolute;left:70px;top:179px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_66\" class=\"drag\" style=\"position:absolute;left:70px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_67\" class=\"drag\" style=\"position:absolute;left:70px;top:222px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p12_68\" class=\"drag\" style=\"position:absolute;left:194px;top:222px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_69\" class=\"drag\" style=\"position:absolute;left:44px;top:24px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C101<br></b></nobr>");
write("</p>");
write("<p id=\"p12_70\" class=\"drag\" style=\"position:absolute;left:167px;top:80px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p12_71\" class=\"drag\" style=\"position:absolute;left:197px;top:80px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p12_72\" class=\"drag\" style=\"position:absolute;left:184px;top:59px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_73\" class=\"drag\" style=\"position:absolute;left:139px;top:80px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_74\" class=\"drag\" style=\"position:absolute;left:94px;top:236px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_75\" class=\"drag\" style=\"position:absolute;left:93px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_76\" class=\"drag\" style=\"position:absolute;left:194px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_77\" class=\"drag\" style=\"position:absolute;left:194px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_78\" class=\"drag\" style=\"position:absolute;left:194px;top:179px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_79\" class=\"drag\" style=\"position:absolute;left:194px;top:208px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_80\" class=\"drag\" style=\"position:absolute;left:69px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_81\" class=\"drag\" style=\"position:absolute;left:244px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p12_82\" class=\"drag\" style=\"position:absolute;left:260px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p12_83\" class=\"drag\" style=\"position:absolute;left:85px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p12_84\" class=\"drag\" style=\"position:absolute;left:260px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p12_85\" class=\"drag\" style=\"position:absolute;left:241px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p12_86\" class=\"drag\" style=\"position:absolute;left:223px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p12_87\" class=\"drag\" style=\"position:absolute;left:93px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_88\" class=\"drag\" style=\"position:absolute;left:194px;top:251px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p12_89\" class=\"drag\" style=\"position:absolute;left:194px;top:236px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_90\" class=\"drag\" style=\"position:absolute;left:194px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_91\" class=\"drag\" style=\"position:absolute;left:168px;top:137px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p12_92\" class=\"drag\" style=\"position:absolute;left:168px;top:151px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p12_93\" class=\"drag\" style=\"position:absolute;left:168px;top:166px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p12_94\" class=\"drag\" style=\"position:absolute;left:168px;top:180px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_95\" class=\"drag\" style=\"position:absolute;left:168px;top:194px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p12_96\" class=\"drag\" style=\"position:absolute;left:168px;top:209px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p12_97\" class=\"drag\" style=\"position:absolute;left:168px;top:223px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p12_98\" class=\"drag\" style=\"position:absolute;left:168px;top:237px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p12_99\" class=\"drag\" style=\"position:absolute;left:240px;top:752px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p12_100\" class=\"drag\" style=\"position:absolute;left:266px;top:751px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_101\" class=\"drag\" style=\"position:absolute;left:68px;top:866px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p12_102\" class=\"drag\" style=\"position:absolute;left:94px;top:865px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_103\" class=\"drag\" style=\"position:absolute;left:153px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p12_104\" class=\"drag\" style=\"position:absolute;left:97px;top:665px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p12_105\" class=\"drag\" style=\"position:absolute;left:549px;top:335px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p12_106\" class=\"drag\" style=\"position:absolute;left:529px;top:335px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_107\" class=\"drag\" style=\"position:absolute;left:483px;top:566px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p12_108\" class=\"drag\" style=\"position:absolute;left:509px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_109\" class=\"drag\" style=\"position:absolute;left:548px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p12_110\" class=\"drag\" style=\"position:absolute;left:483px;top:452px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p12_111\" class=\"drag\" style=\"position:absolute;left:509px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_112\" class=\"drag\" style=\"position:absolute;left:548px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p12_113\" class=\"drag\" style=\"position:absolute;left:766px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p12_114\" class=\"drag\" style=\"position:absolute;left:740px;top:552px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p12_115\" class=\"drag\" style=\"position:absolute;left:740px;top:466px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p12_116\" class=\"drag\" style=\"position:absolute;left:766px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_117\" class=\"drag\" style=\"position:absolute;left:739px;top:436px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p12_118\" class=\"drag\" style=\"position:absolute;left:662px;top:370px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p12_119\" class=\"drag\" style=\"position:absolute;left:792px;top:370px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p12_120\" class=\"drag\" style=\"position:absolute;left:718px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p12_121\" class=\"drag\" style=\"position:absolute;left:699px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p12_122\" class=\"drag\" style=\"position:absolute;left:683px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p12_123\" class=\"drag\" style=\"position:absolute;left:664px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p12_124\" class=\"drag\" style=\"position:absolute;left:664px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_125\" class=\"drag\" style=\"position:absolute;left:776px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_126\" class=\"drag\" style=\"position:absolute;left:794px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p12_127\" class=\"drag\" style=\"position:absolute;left:792px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_128\" class=\"drag\" style=\"position:absolute;left:736px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p12_129\" class=\"drag\" style=\"position:absolute;left:736px;top:370px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p12_130\" class=\"drag\" style=\"position:absolute;left:645px;top:296px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>ECM/PCM C (22P)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p12_131\" class=\"drag\" style=\"position:absolute;left:680px;top:536px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_132\" class=\"drag\" style=\"position:absolute;left:680px;top:522px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_133\" class=\"drag\" style=\"position:absolute;left:680px;top:508px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_134\" class=\"drag\" style=\"position:absolute;left:680px;top:479px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_135\" class=\"drag\" style=\"position:absolute;left:739px;top:479px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p12_136\" class=\"drag\" style=\"position:absolute;left:740px;top:452px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_137\" class=\"drag\" style=\"position:absolute;left:654px;top:537px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p12_138\" class=\"drag\" style=\"position:absolute;left:766px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_139\" class=\"drag\" style=\"position:absolute;left:739px;top:536px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p12_140\" class=\"drag\" style=\"position:absolute;left:739px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p12_141\" class=\"drag\" style=\"position:absolute;left:656px;top:522px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p12_142\" class=\"drag\" style=\"position:absolute;left:680px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_143\" class=\"drag\" style=\"position:absolute;left:656px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p12_144\" class=\"drag\" style=\"position:absolute;left:656px;top:479px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_145\" class=\"drag\" style=\"position:absolute;left:656px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_146\" class=\"drag\" style=\"position:absolute;left:656px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_147\" class=\"drag\" style=\"position:absolute;left:656px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_148\" class=\"drag\" style=\"position:absolute;left:656px;top:508px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p12_149\" class=\"drag\" style=\"position:absolute;left:654px;top:552px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p12_150\" class=\"drag\" style=\"position:absolute;left:740px;top:409px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p12_151\" class=\"drag\" style=\"position:absolute;left:739px;top:508px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p12_152\" class=\"drag\" style=\"position:absolute;left:740px;top:523px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p12_153\" class=\"drag\" style=\"position:absolute;left:680px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_154\" class=\"drag\" style=\"position:absolute;left:766px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_155\" class=\"drag\" style=\"position:absolute;left:680px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_156\" class=\"drag\" style=\"position:absolute;left:766px;top:522px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_157\" class=\"drag\" style=\"position:absolute;left:180px;top:865px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_158\" class=\"drag\" style=\"position:absolute;left:153px;top:822px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p12_159\" class=\"drag\" style=\"position:absolute;left:153px;top:779px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p12_160\" class=\"drag\" style=\"position:absolute;left:67px;top:851px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p12_161\" class=\"drag\" style=\"position:absolute;left:79px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p12_162\" class=\"drag\" style=\"position:absolute;left:180px;top:765px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p12_163\" class=\"drag\" style=\"position:absolute;left:180px;top:722px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_164\" class=\"drag\" style=\"position:absolute;left:153px;top:794px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p12_165\" class=\"drag\" style=\"position:absolute;left:154px;top:766px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_166\" class=\"drag\" style=\"position:absolute;left:154px;top:723px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p12_167\" class=\"drag\" style=\"position:absolute;left:153px;top:751px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p12_168\" class=\"drag\" style=\"position:absolute;left:240px;top:837px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p12_169\" class=\"drag\" style=\"position:absolute;left:154px;top:866px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p12_170\" class=\"drag\" style=\"position:absolute;left:94px;top:837px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_171\" class=\"drag\" style=\"position:absolute;left:70px;top:822px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p12_172\" class=\"drag\" style=\"position:absolute;left:70px;top:836px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p12_173\" class=\"drag\" style=\"position:absolute;left:266px;top:837px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_174\" class=\"drag\" style=\"position:absolute;left:266px;top:722px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_175\" class=\"drag\" style=\"position:absolute;left:94px;top:779px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_176\" class=\"drag\" style=\"position:absolute;left:94px;top:722px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_177\" class=\"drag\" style=\"position:absolute;left:266px;top:779px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_178\" class=\"drag\" style=\"position:absolute;left:70px;top:808px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p12_179\" class=\"drag\" style=\"position:absolute;left:70px;top:794px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_180\" class=\"drag\" style=\"position:absolute;left:70px;top:722px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_181\" class=\"drag\" style=\"position:absolute;left:70px;top:736px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_182\" class=\"drag\" style=\"position:absolute;left:70px;top:751px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_183\" class=\"drag\" style=\"position:absolute;left:70px;top:779px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_184\" class=\"drag\" style=\"position:absolute;left:70px;top:765px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_185\" class=\"drag\" style=\"position:absolute;left:266px;top:737px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_186\" class=\"drag\" style=\"position:absolute;left:94px;top:751px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_187\" class=\"drag\" style=\"position:absolute;left:94px;top:765px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_188\" class=\"drag\" style=\"position:absolute;left:94px;top:808px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_189\" class=\"drag\" style=\"position:absolute;left:154px;top:809px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p12_190\" class=\"drag\" style=\"position:absolute;left:240px;top:723px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p12_191\" class=\"drag\" style=\"position:absolute;left:240px;top:737px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p12_192\" class=\"drag\" style=\"position:absolute;left:240px;top:766px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p12_193\" class=\"drag\" style=\"position:absolute;left:240px;top:780px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p12_194\" class=\"drag\" style=\"position:absolute;left:240px;top:794px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p12_195\" class=\"drag\" style=\"position:absolute;left:240px;top:809px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p12_196\" class=\"drag\" style=\"position:absolute;left:180px;top:808px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p12_197\" class=\"drag\" style=\"position:absolute;left:266px;top:794px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_198\" class=\"drag\" style=\"position:absolute;left:266px;top:765px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_199\" class=\"drag\" style=\"position:absolute;left:266px;top:808px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_200\" class=\"drag\" style=\"position:absolute;left:44px;top:610px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>ECM/PCM E (31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_201\" class=\"drag\" style=\"position:absolute;left:284px;top:647px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p12_202\" class=\"drag\" style=\"position:absolute;left:217px;top:647px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p12_203\" class=\"drag\" style=\"position:absolute;left:172px;top:647px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_204\" class=\"drag\" style=\"position:absolute;left:150px;top:647px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_205\" class=\"drag\" style=\"position:absolute;left:128px;top:647px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_206\" class=\"drag\" style=\"position:absolute;left:83px;top:647px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_207\" class=\"drag\" style=\"position:absolute;left:283px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p12_208\" class=\"drag\" style=\"position:absolute;left:246px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p12_209\" class=\"drag\" style=\"position:absolute;left:209px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p12_210\" class=\"drag\" style=\"position:absolute;left:227px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p12_211\" class=\"drag\" style=\"position:absolute;left:172px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p12_212\" class=\"drag\" style=\"position:absolute;left:116px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p12_213\" class=\"drag\" style=\"position:absolute;left:97px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p12_214\" class=\"drag\" style=\"position:absolute;left:227px;top:665px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p12_215\" class=\"drag\" style=\"position:absolute;left:116px;top:665px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p12_216\" class=\"drag\" style=\"position:absolute;left:172px;top:665px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_217\" class=\"drag\" style=\"position:absolute;left:483px;top:480px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p12_218\" class=\"drag\" style=\"position:absolute;left:509px;top:479px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_219\" class=\"drag\" style=\"position:absolute;left:418px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p12_220\" class=\"drag\" style=\"position:absolute;left:492px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p12_221\" class=\"drag\" style=\"position:absolute;left:401px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p12_222\" class=\"drag\" style=\"position:absolute;left:492px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p12_223\" class=\"drag\" style=\"position:absolute;left:510px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p12_224\" class=\"drag\" style=\"position:absolute;left:399px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p12_225\" class=\"drag\" style=\"position:absolute;left:423px;top:335px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_226\" class=\"drag\" style=\"position:absolute;left:443px;top:335px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_227\" class=\"drag\" style=\"position:absolute;left:464px;top:335px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_228\" class=\"drag\" style=\"position:absolute;left:486px;top:335px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_229\" class=\"drag\" style=\"position:absolute;left:387px;top:296px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>ECM/PCM B (24P)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_230\" class=\"drag\" style=\"position:absolute;left:509px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_231\" class=\"drag\" style=\"position:absolute;left:509px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_232\" class=\"drag\" style=\"position:absolute;left:423px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_233\" class=\"drag\" style=\"position:absolute;left:399px;top:508px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p12_234\" class=\"drag\" style=\"position:absolute;left:399px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_235\" class=\"drag\" style=\"position:absolute;left:399px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_236\" class=\"drag\" style=\"position:absolute;left:399px;top:436px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_237\" class=\"drag\" style=\"position:absolute;left:399px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_238\" class=\"drag\" style=\"position:absolute;left:399px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_239\" class=\"drag\" style=\"position:absolute;left:399px;top:479px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_240\" class=\"drag\" style=\"position:absolute;left:399px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p12_241\" class=\"drag\" style=\"position:absolute;left:399px;top:522px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p12_242\" class=\"drag\" style=\"position:absolute;left:483px;top:523px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p12_243\" class=\"drag\" style=\"position:absolute;left:423px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_244\" class=\"drag\" style=\"position:absolute;left:423px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_245\" class=\"drag\" style=\"position:absolute;left:509px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p12_246\" class=\"drag\" style=\"position:absolute;left:509px;top:522px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_247\" class=\"drag\" style=\"position:absolute;left:483px;top:409px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p12_248\" class=\"drag\" style=\"position:absolute;left:483px;top:423px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p12_249\" class=\"drag\" style=\"position:absolute;left:483px;top:466px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p12_250\" class=\"drag\" style=\"position:absolute;left:482px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p12_251\" class=\"drag\" style=\"position:absolute;left:423px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p12_252\" class=\"drag\" style=\"position:absolute;left:423px;top:479px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_253\" class=\"drag\" style=\"position:absolute;left:423px;top:508px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_254\" class=\"drag\" style=\"position:absolute;left:283px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p12_255\" class=\"drag\" style=\"position:absolute;left:264px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p12_256\" class=\"drag\" style=\"position:absolute;left:246px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p12_257\" class=\"drag\" style=\"position:absolute;left:172px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_258\" class=\"drag\" style=\"position:absolute;left:134px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p12_259\" class=\"drag\" style=\"position:absolute;left:116px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p12_260\" class=\"drag\" style=\"position:absolute;left:97px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p12_261\" class=\"drag\" style=\"position:absolute;left:79px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p12_262\" class=\"drag\" style=\"position:absolute;left:227px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p12_263\" class=\"drag\" style=\"position:absolute;left:97px;top:370px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p12_264\" class=\"drag\" style=\"position:absolute;left:116px;top:370px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p12_265\" class=\"drag\" style=\"position:absolute;left:172px;top:370px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p12_266\" class=\"drag\" style=\"position:absolute;left:227px;top:370px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p12_267\" class=\"drag\" style=\"position:absolute;left:209px;top:370px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p12_268\" class=\"drag\" style=\"position:absolute;left:246px;top:370px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p12_269\" class=\"drag\" style=\"position:absolute;left:264px;top:370px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p12_270\" class=\"drag\" style=\"position:absolute;left:83px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_271\" class=\"drag\" style=\"position:absolute;left:105px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_272\" class=\"drag\" style=\"position:absolute;left:128px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_273\" class=\"drag\" style=\"position:absolute;left:150px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_274\" class=\"drag\" style=\"position:absolute;left:172px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_275\" class=\"drag\" style=\"position:absolute;left:194px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_276\" class=\"drag\" style=\"position:absolute;left:217px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p12_277\" class=\"drag\" style=\"position:absolute;left:284px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p12_278\" class=\"drag\" style=\"position:absolute;left:44px;top:296px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>ECM/PCM A (31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_279\" class=\"drag\" style=\"position:absolute;left:266px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_280\" class=\"drag\" style=\"position:absolute;left:266px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_281\" class=\"drag\" style=\"position:absolute;left:266px;top:479px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_282\" class=\"drag\" style=\"position:absolute;left:180px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_283\" class=\"drag\" style=\"position:absolute;left:240px;top:494px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p12_284\" class=\"drag\" style=\"position:absolute;left:240px;top:480px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p12_285\" class=\"drag\" style=\"position:absolute;left:240px;top:466px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p12_286\" class=\"drag\" style=\"position:absolute;left:240px;top:452px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p12_287\" class=\"drag\" style=\"position:absolute;left:240px;top:423px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p12_288\" class=\"drag\" style=\"position:absolute;left:240px;top:409px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p12_289\" class=\"drag\" style=\"position:absolute;left:154px;top:494px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p12_290\" class=\"drag\" style=\"position:absolute;left:94px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_291\" class=\"drag\" style=\"position:absolute;left:94px;top:479px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_292\" class=\"drag\" style=\"position:absolute;left:94px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_293\" class=\"drag\" style=\"position:absolute;left:94px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_294\" class=\"drag\" style=\"position:absolute;left:94px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_295\" class=\"drag\" style=\"position:absolute;left:266px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_296\" class=\"drag\" style=\"position:absolute;left:239px;top:436px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p12_297\" class=\"drag\" style=\"position:absolute;left:70px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_298\" class=\"drag\" style=\"position:absolute;left:70px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_299\" class=\"drag\" style=\"position:absolute;left:70px;top:436px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_300\" class=\"drag\" style=\"position:absolute;left:70px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_301\" class=\"drag\" style=\"position:absolute;left:70px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_302\" class=\"drag\" style=\"position:absolute;left:70px;top:479px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_303\" class=\"drag\" style=\"position:absolute;left:70px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p12_304\" class=\"drag\" style=\"position:absolute;left:266px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_305\" class=\"drag\" style=\"position:absolute;left:94px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_306\" class=\"drag\" style=\"position:absolute;left:94px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_307\" class=\"drag\" style=\"position:absolute;left:266px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_308\" class=\"drag\" style=\"position:absolute;left:180px;top:522px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_309\" class=\"drag\" style=\"position:absolute;left:266px;top:508px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_310\" class=\"drag\" style=\"position:absolute;left:70px;top:522px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p12_311\" class=\"drag\" style=\"position:absolute;left:70px;top:508px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p12_312\" class=\"drag\" style=\"position:absolute;left:94px;top:522px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_313\" class=\"drag\" style=\"position:absolute;left:94px;top:536px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_314\" class=\"drag\" style=\"position:absolute;left:154px;top:523px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p12_315\" class=\"drag\" style=\"position:absolute;left:154px;top:537px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p12_316\" class=\"drag\" style=\"position:absolute;left:240px;top:509px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p12_317\" class=\"drag\" style=\"position:absolute;left:180px;top:536px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p12_318\" class=\"drag\" style=\"position:absolute;left:153px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p12_319\" class=\"drag\" style=\"position:absolute;left:94px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_320\" class=\"drag\" style=\"position:absolute;left:68px;top:537px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p12_321\" class=\"drag\" style=\"position:absolute;left:68px;top:552px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p12_322\" class=\"drag\" style=\"position:absolute;left:153px;top:436px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p12_323\" class=\"drag\" style=\"position:absolute;left:154px;top:409px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p12_324\" class=\"drag\" style=\"position:absolute;left:154px;top:423px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p12_325\" class=\"drag\" style=\"position:absolute;left:154px;top:452px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_326\" class=\"drag\" style=\"position:absolute;left:153px;top:479px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p12_327\" class=\"drag\" style=\"position:absolute;left:154px;top:509px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p12_328\" class=\"drag\" style=\"position:absolute;left:239px;top:522px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p12_329\" class=\"drag\" style=\"position:absolute;left:180px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_330\" class=\"drag\" style=\"position:absolute;left:180px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_331\" class=\"drag\" style=\"position:absolute;left:180px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_332\" class=\"drag\" style=\"position:absolute;left:180px;top:508px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_333\" class=\"drag\" style=\"position:absolute;left:366px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_334\" class=\"drag\" style=\"position:absolute;left:396px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_335\" class=\"drag\" style=\"position:absolute;left:396px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_336\" class=\"drag\" style=\"position:absolute;left:378px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_337\" class=\"drag\" style=\"position:absolute;left:359px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_338\" class=\"drag\" style=\"position:absolute;left:341px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_339\" class=\"drag\" style=\"position:absolute;left:342px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_340\" class=\"drag\" style=\"position:absolute;left:366px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_341\" class=\"drag\" style=\"position:absolute;left:342px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_342\" class=\"drag\" style=\"position:absolute;left:342px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_343\" class=\"drag\" style=\"position:absolute;left:342px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_344\" class=\"drag\" style=\"position:absolute;left:366px;top:179px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_345\" class=\"drag\" style=\"position:absolute;left:342px;top:179px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_346\" class=\"drag\" style=\"position:absolute;left:330px;top:24px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C203<br></b></nobr>");
write("</p>");
write("<p id=\"p12_347\" class=\"drag\" style=\"position:absolute;left:366px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_348\" class=\"drag\" style=\"position:absolute;left:366px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_349\" class=\"drag\" style=\"position:absolute;left:342px;top:193px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_350\" class=\"drag\" style=\"position:absolute;left:87px;top:1035px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·Connector with female terminals (single outline) : View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p12_351\" class=\"drag\" style=\"position:absolute;left:87px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·Connector with male terminals (double outline) : View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p12_352\" class=\"drag\" style=\"position:absolute;left:32px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_353\" class=\"drag\" style=\"position:absolute;left:87px;top:1049px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p12_354\" class=\"drag\" style=\"position:absolute;left:123px;top:1049px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to ECM/PCM control.<br></b></nobr>");
write("</p>");
write("<p id=\"p12_355\" class=\"drag\" style=\"position:absolute;left:720px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_356\" class=\"drag\" style=\"position:absolute;left:757px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_357\" class=\"drag\" style=\"position:absolute;left:680px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_358\" class=\"drag\" style=\"position:absolute;left:680px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_359\" class=\"drag\" style=\"position:absolute;left:656px;top:436px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_360\" class=\"drag\" style=\"position:absolute;left:656px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_361\" class=\"drag\" style=\"position:absolute;left:155px;top:737px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p12_362\" class=\"drag\" style=\"position:absolute;left:180px;top:736px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p12_363\" class=\"drag\" style=\"position:absolute;left:135px;top:666px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}