with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1017px;\" coordsize=\"950,1017\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1017px;\">");
write("<img id=\"img1\" src=\"../img/SAA3ECPJ54260400000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1017px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:688px;top:915px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:688px;top:358px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:688px;top:273px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:657px;top:205px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:688px;top:193px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AUXILIARY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:688px;top:215px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(To page 22−7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:688px;top:204px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE HOLDER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:467px;top:954px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LIGHT SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:688px;top:904px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:688px;top:892px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:688px;top:335px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:688px;top:347px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:52px;top:307px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.22 (7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:57px;top:364px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>22−6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:52px;top:318px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:57px;top:353px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>From page<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:52px;top:330px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:52px;top:341px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:688px;top:261px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUSE/RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:688px;top:250px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:427px;top:461px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:427px;top:532px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:660px;top:875px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left headlight<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:583px;top:975px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:550px;top:918px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:467px;top:965px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Closed : switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:467px;top:942px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>COMBINATION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:304px;top:861px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.13 (20A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:660px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM/PCM (ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:310px;top:660px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>COMPRESSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:660px;top:158px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Via sunroof open/close relay)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:660px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power mirror defogger (Via defogger relay)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:660px;top:147px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof motor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:660px;top:318px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Taillight relay<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:235px;top:303px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.9 (10A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:657px;top:348px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:488px;top:318px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:202px;top:814px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:202px;top:802px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>HEADLIGHT <br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:660px;top:847px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right headlight<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:660px;top:547px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM/PCM (FANC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:489px;top:604px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:660px;top:604px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Condenser fan motor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:190px;top:588px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.11 (30A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:314px;top:495px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CONDENSER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:660px;top:532px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Radiator fan switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:314px;top:507px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:499px;top:532px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:660px;top:390px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Radiator fan motor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:317px;top:357px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:317px;top:345px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RADIATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:489px;top:390px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:660px;top:704px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/C compressor clutch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:310px;top:648px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:310px;top:671px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:499px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:488px;top:704px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:233px;top:374px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.10 (20A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:657px;top:905px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:424px;top:918px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:304px;top:831px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.12 (20A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:499px;top:847px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:488px;top:875px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:486px;top:261px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:657px;top:262px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:235px;top:246px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.8 (15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:188px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:488px;top:147px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:235px;top:131px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.7 (30A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:171px;top:98px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:61px;top:433px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:76px;top:383px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:555px;top:965px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}