with(document) {
write("<v:group id=\"group4\" class=\"drag\" style=\"position:relative; width:950px; height:1119px;\" coordsize=\"950,1119\">");
write("<v:rect id=\"rect4\"class=\"drag\"  style=\"width:950px;height:1119px;\">");
write("<img id=\"img4\" src=\"../img/SAA3ECPA20300000000EAAD10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1119px;border-color:#ffffff\">");
write("<p id=\"p4_1\" class=\"drag\" style=\"position:absolute;left:414px;top:186px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E31<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" class=\"drag\" style=\"position:absolute;left:217px;top:62px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" class=\"drag\" style=\"position:absolute;left:244px;top:70px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" class=\"drag\" style=\"position:absolute;left:391px;top:173px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MIL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" class=\"drag\" style=\"position:absolute;left:417px;top:246px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E5<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" class=\"drag\" style=\"position:absolute;left:389px;top:232px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FUP<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" class=\"drag\" style=\"position:absolute;left:413px;top:307px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E24<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" class=\"drag\" style=\"position:absolute;left:369px;top:293px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MTRTW<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" class=\"drag\" style=\"position:absolute;left:271px;top:63px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" class=\"drag\" style=\"position:absolute;left:158px;top:186px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" class=\"drag\" style=\"position:absolute;left:164px;top:135px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" class=\"drag\" style=\"position:absolute;left:76px;top:160px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MIL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" class=\"drag\" style=\"position:absolute;left:28px;top:346px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" class=\"drag\" style=\"position:absolute;left:321px;top:246px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" class=\"drag\" style=\"position:absolute;left:30px;top:517px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ABS CONTROL<br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" class=\"drag\" style=\"position:absolute;left:378px;top:511px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VABS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" class=\"drag\" style=\"position:absolute;left:413px;top:523px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" class=\"drag\" style=\"position:absolute;left:190px;top:1007px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" class=\"drag\" style=\"position:absolute;left:414px;top:939px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E23<br></b></nobr>");
write("</p>");
write("<p id=\"p4_20\" class=\"drag\" style=\"position:absolute;left:414px;top:864px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E29<br></b></nobr>");
write("</p>");
write("<p id=\"p4_21\" class=\"drag\" style=\"position:absolute;left:31px;top:858px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_22\" class=\"drag\" style=\"position:absolute;left:360px;top:864px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_23\" class=\"drag\" style=\"position:absolute;left:200px;top:703px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p4_24\" class=\"drag\" style=\"position:absolute;left:127px;top:837px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_25\" class=\"drag\" style=\"position:absolute;left:141px;top:905px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_26\" class=\"drag\" style=\"position:absolute;left:390px;top:852px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_27\" class=\"drag\" style=\"position:absolute;left:376px;top:927px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>K-LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_28\" class=\"drag\" style=\"position:absolute;left:340px;top:822px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p4_29\" class=\"drag\" style=\"position:absolute;left:302px;top:829px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p4_30\" class=\"drag\" style=\"position:absolute;left:417px;top:760px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_31\" class=\"drag\" style=\"position:absolute;left:390px;top:748px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LG3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_32\" class=\"drag\" style=\"position:absolute;left:275px;top:939px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_33\" class=\"drag\" style=\"position:absolute;left:275px;top:760px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_34\" class=\"drag\" style=\"position:absolute;left:151px;top:524px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_35\" class=\"drag\" style=\"position:absolute;left:332px;top:307px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_36\" class=\"drag\" style=\"position:absolute;left:136px;top:117px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C207<br></b></nobr>");
write("</p>");
write("<p id=\"p4_37\" class=\"drag\" style=\"position:absolute;left:137px;top:168px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C206<br></b></nobr>");
write("</p>");
write("<p id=\"p4_38\" class=\"drag\" style=\"position:absolute;left:137px;top:477px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C301<br></b></nobr>");
write("</p>");
write("<p id=\"p4_39\" class=\"drag\" style=\"position:absolute;left:192px;top:503px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C306<br></b></nobr>");
write("</p>");
write("<p id=\"p4_40\" class=\"drag\" style=\"position:absolute;left:237px;top:503px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C214<br></b></nobr>");
write("</p>");
write("<p id=\"p4_41\" class=\"drag\" style=\"position:absolute;left:270px;top:546px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C201<br></b></nobr>");
write("</p>");
write("<p id=\"p4_42\" class=\"drag\" style=\"position:absolute;left:315px;top:546px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C101<br></b></nobr>");
write("</p>");
write("<p id=\"p4_43\" class=\"drag\" style=\"position:absolute;left:104px;top:801px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C204<br></b></nobr>");
write("</p>");
write("<p id=\"p4_44\" class=\"drag\" style=\"position:absolute;left:23px;top:450px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_45\" class=\"drag\" style=\"position:absolute;left:272px;top:864px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_46\" class=\"drag\" style=\"position:absolute;left:235px;top:523px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_47\" class=\"drag\" style=\"position:absolute;left:320px;top:523px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_48\" class=\"drag\" style=\"position:absolute;left:321px;top:186px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_49\" class=\"drag\" style=\"position:absolute;left:128px;top:891px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_50\" class=\"drag\" style=\"position:absolute;left:414px;top:993px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E30<br></b></nobr>");
write("</p>");
write("<p id=\"p4_51\" class=\"drag\" style=\"position:absolute;left:387px;top:981px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WEN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_52\" class=\"drag\" style=\"position:absolute;left:606px;top:43px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_53\" class=\"drag\" style=\"position:absolute;left:759px;top:91px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_54\" class=\"drag\" style=\"position:absolute;left:836px;top:435px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EVAP CANISTER<br>PURGE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_55\" class=\"drag\" style=\"position:absolute;left:848px;top:620px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ALT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_56\" class=\"drag\" style=\"position:absolute;left:569px;top:535px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p4_57\" class=\"drag\" style=\"position:absolute;left:570px;top:581px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B18<br></b></nobr>");
write("</p>");
write("<p id=\"p4_58\" class=\"drag\" style=\"position:absolute;left:610px;top:534px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_59\" class=\"drag\" style=\"position:absolute;left:588px;top:520px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ALTF<br></b></nobr>");
write("</p>");
write("<p id=\"p4_60\" class=\"drag\" style=\"position:absolute;left:611px;top:582px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_61\" class=\"drag\" style=\"position:absolute;left:589px;top:567px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ALTC<br></b></nobr>");
write("</p>");
write("<p id=\"p4_62\" class=\"drag\" style=\"position:absolute;left:610px;top:416px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_63\" class=\"drag\" style=\"position:absolute;left:570px;top:416px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B21<br></b></nobr>");
write("</p>");
write("<p id=\"p4_64\" class=\"drag\" style=\"position:absolute;left:588px;top:401px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PCS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_65\" class=\"drag\" style=\"position:absolute;left:572px;top:908px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_66\" class=\"drag\" style=\"position:absolute;left:572px;top:872px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p4_67\" class=\"drag\" style=\"position:absolute;left:589px;top:860px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PG1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_68\" class=\"drag\" style=\"position:absolute;left:589px;top:895px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PG2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_69\" class=\"drag\" style=\"position:absolute;left:715px;top:54px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p4_70\" class=\"drag\" style=\"position:absolute;left:600px;top:80px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_71\" class=\"drag\" style=\"position:absolute;left:855px;top:729px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EVAPORATOR<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_72\" class=\"drag\" style=\"position:absolute;left:573px;top:749px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_73\" class=\"drag\" style=\"position:absolute;left:569px;top:694px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E12<br></b></nobr>");
write("</p>");
write("<p id=\"p4_74\" class=\"drag\" style=\"position:absolute;left:589px;top:681px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TAC<br></b></nobr>");
write("</p>");
write("<p id=\"p4_75\" class=\"drag\" style=\"position:absolute;left:589px;top:737px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SG3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_76\" class=\"drag\" style=\"position:absolute;left:640px;top:694px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_77\" class=\"drag\" style=\"position:absolute;left:640px;top:750px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_78\" class=\"drag\" style=\"position:absolute;left:820px;top:810px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To CLIMATE <br>CONTROL UNIT<br>(With CLIMATE<br>CONTROL)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_79\" class=\"drag\" style=\"position:absolute;left:569px;top:252px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p4_80\" class=\"drag\" style=\"position:absolute;left:588px;top:238px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VSS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_81\" class=\"drag\" style=\"position:absolute;left:820px;top:322px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VSS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_82\" class=\"drag\" style=\"position:absolute;left:636px;top:80px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C201<br></b></nobr>");
write("</p>");
write("<p id=\"p4_83\" class=\"drag\" style=\"position:absolute;left:652px;top:138px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C101<br></b></nobr>");
write("</p>");
write("<p id=\"p4_84\" class=\"drag\" style=\"position:absolute;left:799px;top:71px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C116<br></b></nobr>");
write("</p>");
write("<p id=\"p4_85\" class=\"drag\" style=\"position:absolute;left:875px;top:126px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>J/C<br></b></nobr>");
write("</p>");
write("<p id=\"p4_86\" class=\"drag\" style=\"position:absolute;left:780px;top:203px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C103<br></b></nobr>");
write("</p>");
write("<p id=\"p4_87\" class=\"drag\" style=\"position:absolute;left:814px;top:377px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C119<br></b></nobr>");
write("</p>");
write("<p id=\"p4_88\" class=\"drag\" style=\"position:absolute;left:723px;top:348px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p4_89\" class=\"drag\" style=\"position:absolute;left:803px;top:478px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C122<br></b></nobr>");
write("</p>");
write("<p id=\"p4_90\" class=\"drag\" style=\"position:absolute;left:712px;top:665px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C203<br></b></nobr>");
write("</p>");
write("<p id=\"p4_91\" class=\"drag\" style=\"position:absolute;left:749px;top:665px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C401<br></b></nobr>");
write("</p>");
write("<p id=\"p4_92\" class=\"drag\" style=\"position:absolute;left:830px;top:674px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C402<br></b></nobr>");
write("</p>");
write("<p id=\"p4_93\" class=\"drag\" style=\"position:absolute;left:759px;top:109px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_94\" class=\"drag\" style=\"position:absolute;left:740px;top:400px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_95\" class=\"drag\" style=\"position:absolute;left:740px;top:223px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_96\" class=\"drag\" style=\"position:absolute;left:740px;top:506px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_97\" class=\"drag\" style=\"position:absolute;left:755px;top:301px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_98\" class=\"drag\" style=\"position:absolute;left:899px;top:182px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_99\" class=\"drag\" style=\"position:absolute;left:612px;top:252px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_100\" class=\"drag\" style=\"position:absolute;left:778px;top:694px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_101\" class=\"drag\" style=\"position:absolute;left:778px;top:750px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_102\" class=\"drag\" style=\"position:absolute;left:745px;top:823px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_103\" class=\"drag\" style=\"position:absolute;left:570px;top:1023px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A23<br></b></nobr>");
write("</p>");
write("<p id=\"p4_104\" class=\"drag\" style=\"position:absolute;left:569px;top:989px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A24<br></b></nobr>");
write("</p>");
write("<p id=\"p4_105\" class=\"drag\" style=\"position:absolute;left:589px;top:976px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LG1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_106\" class=\"drag\" style=\"position:absolute;left:628px;top:988px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_107\" class=\"drag\" style=\"position:absolute;left:589px;top:1010px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LG2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_108\" class=\"drag\" style=\"position:absolute;left:776px;top:951px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p4_109\" class=\"drag\" style=\"position:absolute;left:640px;top:872px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_110\" class=\"drag\" style=\"position:absolute;left:870px;top:1069px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p4_111\" class=\"drag\" style=\"position:absolute;left:776px;top:1073px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p4_112\" class=\"drag\" style=\"position:absolute;left:870px;top:952px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p4_113\" class=\"drag\" style=\"position:absolute;left:640px;top:908px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_114\" class=\"drag\" style=\"position:absolute;left:628px;top:1023px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}