with(document) {
write("<v:group id=\"group25\" class=\"drag\" style=\"position:relative; width:950px; height:799px;\" coordsize=\"950,799\">");
write("<v:rect id=\"rect25\"class=\"drag\"  style=\"width:950px;height:799px;\">");
write("<img id=\"img25\" src=\"../img/SAA4EF0A20300000000DBAD72.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:799px;border-color:#ffffff\">");
write("<p id=\"p25_1\" class=\"drag\" style=\"position:absolute;left:359px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C120<br></b></nobr>");
write("</p>");
write("<p id=\"p25_2\" class=\"drag\" style=\"position:absolute;left:418px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C102<br></b></nobr>");
write("</p>");
write("<p id=\"p25_3\" class=\"drag\" style=\"position:absolute;left:482px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C105<br></b></nobr>");
write("</p>");
write("<p id=\"p25_4\" class=\"drag\" style=\"position:absolute;left:541px;top:32px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C119<br></b></nobr>");
write("</p>");
write("<p id=\"p25_5\" class=\"drag\" style=\"position:absolute;left:607px;top:48px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C106*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p25_6\" class=\"drag\" style=\"position:absolute;left:666px;top:70px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C118<br></b></nobr>");
write("</p>");
write("<p id=\"p25_7\" class=\"drag\" style=\"position:absolute;left:729px;top:104px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C103*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p25_8\" class=\"drag\" style=\"position:absolute;left:792px;top:151px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C107*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p25_9\" class=\"drag\" style=\"position:absolute;left:794px;top:655px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C108*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p25_10\" class=\"drag\" style=\"position:absolute;left:665px;top:714px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C110*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p25_11\" class=\"drag\" style=\"position:absolute;left:590px;top:727px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C111*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p25_12\" class=\"drag\" style=\"position:absolute;left:505px;top:731px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C112*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p25_13\" class=\"drag\" style=\"position:absolute;left:733px;top:688px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C109*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p25_14\" class=\"drag\" style=\"position:absolute;left:306px;top:696px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C113*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p25_15\" class=\"drag\" style=\"position:absolute;left:126px;top:630px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p25_16\" class=\"drag\" style=\"position:absolute;left:83px;top:546px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C116<br></b></nobr>");
write("</p>");
write("<p id=\"p25_17\" class=\"drag\" style=\"position:absolute;left:46px;top:483px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C151<br></b></nobr>");
write("</p>");
write("<p id=\"p25_18\" class=\"drag\" style=\"position:absolute;left:52px;top:183px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p25_19\" class=\"drag\" style=\"position:absolute;left:94px;top:136px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C115<br></b></nobr>");
write("</p>");
write("<p id=\"p25_20\" class=\"drag\" style=\"position:absolute;left:133px;top:103px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C117<br></b></nobr>");
write("</p>");
write("<p id=\"p25_21\" class=\"drag\" style=\"position:absolute;left:180px;top:75px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C104<br></b></nobr>");
write("</p>");
write("<p id=\"p25_22\" class=\"drag\" style=\"position:absolute;left:3px;top:747px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1: M/T<br>*2: CVT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}