with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\" coordsize=\"950,863\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:950px;height:863px;\">");
write("<img id=\"img3\" src=\"../img/SAA4EFAA20300000000DBAD34.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:76px;top:29px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24P JUNCTION<br>CONNECTOR (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:273px;top:29px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PRIMARY HO2S<br>(SENSOR 1) (2)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:424px;top:29px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>APP SENSOR<br>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:554px;top:29px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IAT/MAP SENSOR <br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:846px;top:29px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CMP SENSOR<br>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:710px;top:18px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EVAP CANISTER<br>PURGE VALVE<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:61px;top:176px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECT SENSOR<br>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:183px;top:187px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VSS (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:288px;top:177px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2P CONNECTOR<br>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:438px;top:187px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ELD (10)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:839px;top:165px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (13)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:700px;top:177px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TEST TACHOMETER<br>CONNECTOR (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:571px;top:166px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (11)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:53px;top:316px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (14)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:174px;top:316px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (15)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:320px;top:316px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (16)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:461px;top:327px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>THROTTLE<br>BODY (17)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:585px;top:316px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 REAR<br>IGNITION COIL<br>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:719px;top:316px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 REAR<br>IGNITION COIL<br>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:839px;top:316px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 3 FRONT<br>IGNITION COIL<br>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:38px;top:476px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 3 REAR<br>IGNITION COIL<br>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:162px;top:476px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 4 REAR<br>IGNITION COIL<br>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:286px;top:476px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 4 FRONT<br>IGNITION COIL<br>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:420px;top:487px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 4 INJECTOR<br>(24)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:560px;top:487px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 3 INJECTOR<br>(25)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:690px;top:487px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>KNOCK SENSOR<br>(26)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:818px;top:487px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 INJECTOR<br>(27)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:54px;top:625px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 FRONT<br>IGNITION COIL<br>(28)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:193px;top:636px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ALTERNATOR<br>(29)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:312px;top:636px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 INJECTOR<br>(30)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:447px;top:625px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 FRONT<br>IGNITION COIL<br>(31)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:586px;top:636px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR VALVE<br>(32)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:710px;top:636px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CKP SENSOR<br>(33)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:0px;top:779px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>**: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}