with(document) {
write("<v:group id=\"group28\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect28\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img28\" src=\"../img/SAA4EF0A20300000000DBAD75.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p28_1\" class=\"drag\" style=\"position:absolute;left:231px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p28_2\" class=\"drag\" style=\"position:absolute;left:255px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p28_3\" class=\"drag\" style=\"position:absolute;left:255px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p28_4\" class=\"drag\" style=\"position:absolute;left:231px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_5\" class=\"drag\" style=\"position:absolute;left:269px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_6\" class=\"drag\" style=\"position:absolute;left:269px;top:93px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p28_7\" class=\"drag\" style=\"position:absolute;left:250px;top:93px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p28_8\" class=\"drag\" style=\"position:absolute;left:250px;top:74px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_9\" class=\"drag\" style=\"position:absolute;left:255px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p28_10\" class=\"drag\" style=\"position:absolute;left:231px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_11\" class=\"drag\" style=\"position:absolute;left:231px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p28_12\" class=\"drag\" style=\"position:absolute;left:255px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p28_13\" class=\"drag\" style=\"position:absolute;left:64px;top:1020px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p28_14\" class=\"drag\" style=\"position:absolute;left:119px;top:1020px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p28_15\" class=\"drag\" style=\"position:absolute;left:119px;top:1034px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p28_16\" class=\"drag\" style=\"position:absolute;left:119px;top:1048px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p28_17\" class=\"drag\" style=\"position:absolute;left:135px;top:1034px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with female terminals (single outline): View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p28_18\" class=\"drag\" style=\"position:absolute;left:135px;top:1020px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with male terminals (double outline): View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p28_19\" class=\"drag\" style=\"position:absolute;left:155px;top:1048px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to ECM/PCM control.<br></b></nobr>");
write("</p>");
write("<p id=\"p28_20\" class=\"drag\" style=\"position:absolute;left:219px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C122<br></b></nobr>");
write("</p>");
write("<p id=\"p28_21\" class=\"drag\" style=\"position:absolute;left:641px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C125<br></b></nobr>");
write("</p>");
write("<p id=\"p28_22\" class=\"drag\" style=\"position:absolute;left:691px;top:69px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_23\" class=\"drag\" style=\"position:absolute;left:672px;top:69px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_24\" class=\"drag\" style=\"position:absolute;left:653px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_25\" class=\"drag\" style=\"position:absolute;left:677px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p28_26\" class=\"drag\" style=\"position:absolute;left:677px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_27\" class=\"drag\" style=\"position:absolute;left:653px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_28\" class=\"drag\" style=\"position:absolute;left:784px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C126<br></b></nobr>");
write("</p>");
write("<p id=\"p28_29\" class=\"drag\" style=\"position:absolute;left:795px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_30\" class=\"drag\" style=\"position:absolute;left:820px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_31\" class=\"drag\" style=\"position:absolute;left:820px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_32\" class=\"drag\" style=\"position:absolute;left:840px;top:76px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p28_33\" class=\"drag\" style=\"position:absolute;left:821px;top:76px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_34\" class=\"drag\" style=\"position:absolute;left:802px;top:76px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_35\" class=\"drag\" style=\"position:absolute;left:795px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_36\" class=\"drag\" style=\"position:absolute;left:795px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p28_37\" class=\"drag\" style=\"position:absolute;left:820px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p28_38\" class=\"drag\" style=\"position:absolute;left:541px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p28_39\" class=\"drag\" style=\"position:absolute;left:517px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p28_40\" class=\"drag\" style=\"position:absolute;left:517px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_41\" class=\"drag\" style=\"position:absolute;left:524px;top:76px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_42\" class=\"drag\" style=\"position:absolute;left:543px;top:76px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_43\" class=\"drag\" style=\"position:absolute;left:561px;top:76px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p28_44\" class=\"drag\" style=\"position:absolute;left:541px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_45\" class=\"drag\" style=\"position:absolute;left:541px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p28_46\" class=\"drag\" style=\"position:absolute;left:517px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_47\" class=\"drag\" style=\"position:absolute;left:505px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C124<br></b></nobr>");
write("</p>");
write("<p id=\"p28_48\" class=\"drag\" style=\"position:absolute;left:88px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_49\" class=\"drag\" style=\"position:absolute;left:112px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p28_50\" class=\"drag\" style=\"position:absolute;left:117px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_51\" class=\"drag\" style=\"position:absolute;left:76px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C121<br></b></nobr>");
write("</p>");
write("<p id=\"p28_52\" class=\"drag\" style=\"position:absolute;left:374px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_53\" class=\"drag\" style=\"position:absolute;left:398px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_54\" class=\"drag\" style=\"position:absolute;left:398px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p28_55\" class=\"drag\" style=\"position:absolute;left:374px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_56\" class=\"drag\" style=\"position:absolute;left:393px;top:69px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_57\" class=\"drag\" style=\"position:absolute;left:412px;top:69px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_58\" class=\"drag\" style=\"position:absolute;left:362px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C123<br></b></nobr>");
write("</p>");
write("<p id=\"p28_59\" class=\"drag\" style=\"position:absolute;left:684px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_60\" class=\"drag\" style=\"position:absolute;left:745px;top:343px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p28_61\" class=\"drag\" style=\"position:absolute;left:770px;top:343px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_62\" class=\"drag\" style=\"position:absolute;left:684px;top:343px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p28_63\" class=\"drag\" style=\"position:absolute;left:770px;top:314px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_64\" class=\"drag\" style=\"position:absolute;left:745px;top:314px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p28_65\" class=\"drag\" style=\"position:absolute;left:745px;top:328px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p28_66\" class=\"drag\" style=\"position:absolute;left:660px;top:343px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p28_67\" class=\"drag\" style=\"position:absolute;left:660px;top:328px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_68\" class=\"drag\" style=\"position:absolute;left:684px;top:314px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_69\" class=\"drag\" style=\"position:absolute;left:660px;top:314px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_70\" class=\"drag\" style=\"position:absolute;left:712px;top:260px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_71\" class=\"drag\" style=\"position:absolute;left:731px;top:260px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_72\" class=\"drag\" style=\"position:absolute;left:750px;top:260px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p28_73\" class=\"drag\" style=\"position:absolute;left:713px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p28_74\" class=\"drag\" style=\"position:absolute;left:750px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p28_75\" class=\"drag\" style=\"position:absolute;left:648px;top:216px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C131<br></b></nobr>");
write("</p>");
write("<p id=\"p28_76\" class=\"drag\" style=\"position:absolute;left:362px;top:216px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C129<br></b></nobr>");
write("</p>");
write("<p id=\"p28_77\" class=\"drag\" style=\"position:absolute;left:412px;top:262px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_78\" class=\"drag\" style=\"position:absolute;left:393px;top:262px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_79\" class=\"drag\" style=\"position:absolute;left:374px;top:328px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_80\" class=\"drag\" style=\"position:absolute;left:398px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p28_81\" class=\"drag\" style=\"position:absolute;left:398px;top:314px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_82\" class=\"drag\" style=\"position:absolute;left:374px;top:314px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_83\" class=\"drag\" style=\"position:absolute;left:505px;top:216px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C130<br></b></nobr>");
write("</p>");
write("<p id=\"p28_84\" class=\"drag\" style=\"position:absolute;left:517px;top:314px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_85\" class=\"drag\" style=\"position:absolute;left:541px;top:314px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p28_86\" class=\"drag\" style=\"position:absolute;left:541px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_87\" class=\"drag\" style=\"position:absolute;left:561px;top:269px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p28_88\" class=\"drag\" style=\"position:absolute;left:543px;top:269px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_89\" class=\"drag\" style=\"position:absolute;left:524px;top:269px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_90\" class=\"drag\" style=\"position:absolute;left:517px;top:328px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_91\" class=\"drag\" style=\"position:absolute;left:517px;top:343px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p28_92\" class=\"drag\" style=\"position:absolute;left:541px;top:343px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p28_93\" class=\"drag\" style=\"position:absolute;left:255px;top:343px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p28_94\" class=\"drag\" style=\"position:absolute;left:231px;top:343px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p28_95\" class=\"drag\" style=\"position:absolute;left:231px;top:328px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_96\" class=\"drag\" style=\"position:absolute;left:238px;top:269px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_97\" class=\"drag\" style=\"position:absolute;left:257px;top:269px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_98\" class=\"drag\" style=\"position:absolute;left:275px;top:269px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p28_99\" class=\"drag\" style=\"position:absolute;left:255px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_100\" class=\"drag\" style=\"position:absolute;left:255px;top:314px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p28_101\" class=\"drag\" style=\"position:absolute;left:231px;top:314px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_102\" class=\"drag\" style=\"position:absolute;left:219px;top:216px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C128<br></b></nobr>");
write("</p>");
write("<p id=\"p28_103\" class=\"drag\" style=\"position:absolute;left:88px;top:314px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_104\" class=\"drag\" style=\"position:absolute;left:112px;top:314px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_105\" class=\"drag\" style=\"position:absolute;left:112px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p28_106\" class=\"drag\" style=\"position:absolute;left:88px;top:328px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_107\" class=\"drag\" style=\"position:absolute;left:107px;top:262px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_108\" class=\"drag\" style=\"position:absolute;left:126px;top:262px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_109\" class=\"drag\" style=\"position:absolute;left:76px;top:216px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C127<br></b></nobr>");
write("</p>");
write("<p id=\"p28_110\" class=\"drag\" style=\"position:absolute;left:76px;top:452px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C136<br></b></nobr>");
write("</p>");
write("<p id=\"p28_111\" class=\"drag\" style=\"position:absolute;left:112px;top:550px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_112\" class=\"drag\" style=\"position:absolute;left:112px;top:564px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p28_113\" class=\"drag\" style=\"position:absolute;left:133px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p28_114\" class=\"drag\" style=\"position:absolute;left:114px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_115\" class=\"drag\" style=\"position:absolute;left:112px;top:579px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p28_116\" class=\"drag\" style=\"position:absolute;left:88px;top:550px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_117\" class=\"drag\" style=\"position:absolute;left:95px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p28_118\" class=\"drag\" style=\"position:absolute;left:88px;top:564px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p28_119\" class=\"drag\" style=\"position:absolute;left:88px;top:578px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}