with(document) {
write("<v:group id=\"group26\" class=\"drag\" style=\"position:relative; width:950px; height:1085px;\" coordsize=\"950,1085\">");
write("<v:rect id=\"rect26\"class=\"drag\"  style=\"width:950px;height:1085px;\">");
write("<img id=\"img26\" src=\"../img/SAA4EF0A20300000000DBAD73.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1085px;border-color:#ffffff\">");
write("<p id=\"p26_1\" class=\"drag\" style=\"position:absolute;left:553px;top:651px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_2\" class=\"drag\" style=\"position:absolute;left:553px;top:637px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_3\" class=\"drag\" style=\"position:absolute;left:553px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_4\" class=\"drag\" style=\"position:absolute;left:553px;top:608px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_5\" class=\"drag\" style=\"position:absolute;left:526px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p26_6\" class=\"drag\" style=\"position:absolute;left:467px;top:608px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p26_7\" class=\"drag\" style=\"position:absolute;left:467px;top:594px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p26_8\" class=\"drag\" style=\"position:absolute;left:467px;top:580px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p26_9\" class=\"drag\" style=\"position:absolute;left:467px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p26_10\" class=\"drag\" style=\"position:absolute;left:467px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p26_11\" class=\"drag\" style=\"position:absolute;left:441px;top:609px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p26_12\" class=\"drag\" style=\"position:absolute;left:370px;top:513px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p26_13\" class=\"drag\" style=\"position:absolute;left:360px;top:682px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C151<br></b></nobr>");
write("</p>");
write("<p id=\"p26_14\" class=\"drag\" style=\"position:absolute;left:390px;top:733px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_15\" class=\"drag\" style=\"position:absolute;left:410px;top:733px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_16\" class=\"drag\" style=\"position:absolute;left:371px;top:794px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_17\" class=\"drag\" style=\"position:absolute;left:396px;top:794px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_18\" class=\"drag\" style=\"position:absolute;left:396px;top:780px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p26_19\" class=\"drag\" style=\"position:absolute;left:371px;top:779px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_20\" class=\"drag\" style=\"position:absolute;left:800px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_21\" class=\"drag\" style=\"position:absolute;left:824px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p26_22\" class=\"drag\" style=\"position:absolute;left:824px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_23\" class=\"drag\" style=\"position:absolute;left:800px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_24\" class=\"drag\" style=\"position:absolute;left:838px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_25\" class=\"drag\" style=\"position:absolute;left:819px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_26\" class=\"drag\" style=\"position:absolute;left:789px;top:453px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C118<br></b></nobr>");
write("</p>");
write("<p id=\"p26_27\" class=\"drag\" style=\"position:absolute;left:85px;top:779px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_28\" class=\"drag\" style=\"position:absolute;left:110px;top:780px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p26_29\" class=\"drag\" style=\"position:absolute;left:110px;top:794px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p26_30\" class=\"drag\" style=\"position:absolute;left:85px;top:794px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_31\" class=\"drag\" style=\"position:absolute;left:124px;top:733px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_32\" class=\"drag\" style=\"position:absolute;left:105px;top:733px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_33\" class=\"drag\" style=\"position:absolute;left:74px;top:682px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C119<br></b></nobr>");
write("</p>");
write("<p id=\"p26_34\" class=\"drag\" style=\"position:absolute;left:228px;top:808px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_35\" class=\"drag\" style=\"position:absolute;left:228px;top:794px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_36\" class=\"drag\" style=\"position:absolute;left:235px;top:734px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_37\" class=\"drag\" style=\"position:absolute;left:228px;top:779px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_38\" class=\"drag\" style=\"position:absolute;left:253px;top:808px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_39\" class=\"drag\" style=\"position:absolute;left:254px;top:734px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_40\" class=\"drag\" style=\"position:absolute;left:273px;top:734px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_41\" class=\"drag\" style=\"position:absolute;left:253px;top:794px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p26_42\" class=\"drag\" style=\"position:absolute;left:253px;top:780px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p26_43\" class=\"drag\" style=\"position:absolute;left:217px;top:682px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C120<br></b></nobr>");
write("</p>");
write("<p id=\"p26_44\" class=\"drag\" style=\"position:absolute;left:681px;top:580px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p26_45\" class=\"drag\" style=\"position:absolute;left:657px;top:579px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_46\" class=\"drag\" style=\"position:absolute;left:657px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_47\" class=\"drag\" style=\"position:absolute;left:664px;top:506px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_48\" class=\"drag\" style=\"position:absolute;left:683px;top:506px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_49\" class=\"drag\" style=\"position:absolute;left:702px;top:506px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_50\" class=\"drag\" style=\"position:absolute;left:681px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_51\" class=\"drag\" style=\"position:absolute;left:681px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_52\" class=\"drag\" style=\"position:absolute;left:657px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_53\" class=\"drag\" style=\"position:absolute;left:646px;top:453px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C117<br></b></nobr>");
write("</p>");
write("<p id=\"p26_54\" class=\"drag\" style=\"position:absolute;left:553px;top:594px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_55\" class=\"drag\" style=\"position:absolute;left:553px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p26_56\" class=\"drag\" style=\"position:absolute;left:467px;top:651px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p26_57\" class=\"drag\" style=\"position:absolute;left:467px;top:637px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p26_58\" class=\"drag\" style=\"position:absolute;left:467px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p26_59\" class=\"drag\" style=\"position:absolute;left:381px;top:651px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_60\" class=\"drag\" style=\"position:absolute;left:381px;top:637px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_61\" class=\"drag\" style=\"position:absolute;left:381px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_62\" class=\"drag\" style=\"position:absolute;left:381px;top:608px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_63\" class=\"drag\" style=\"position:absolute;left:381px;top:594px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_64\" class=\"drag\" style=\"position:absolute;left:381px;top:580px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_65\" class=\"drag\" style=\"position:absolute;left:381px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_66\" class=\"drag\" style=\"position:absolute;left:527px;top:652px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p26_67\" class=\"drag\" style=\"position:absolute;left:527px;top:638px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p26_68\" class=\"drag\" style=\"position:absolute;left:527px;top:623px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p26_69\" class=\"drag\" style=\"position:absolute;left:527px;top:609px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p26_70\" class=\"drag\" style=\"position:absolute;left:526px;top:579px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p26_71\" class=\"drag\" style=\"position:absolute;left:357px;top:651px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p26_72\" class=\"drag\" style=\"position:absolute;left:556px;top:513px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p26_73\" class=\"drag\" style=\"position:absolute;left:556px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p26_74\" class=\"drag\" style=\"position:absolute;left:574px;top:513px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p26_75\" class=\"drag\" style=\"position:absolute;left:574px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p26_76\" class=\"drag\" style=\"position:absolute;left:537px;top:513px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p26_77\" class=\"drag\" style=\"position:absolute;left:527px;top:595px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p26_78\" class=\"drag\" style=\"position:absolute;left:527px;top:552px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p26_79\" class=\"drag\" style=\"position:absolute;left:441px;top:638px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p26_80\" class=\"drag\" style=\"position:absolute;left:441px;top:652px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p26_81\" class=\"drag\" style=\"position:absolute;left:441px;top:566px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p26_82\" class=\"drag\" style=\"position:absolute;left:441px;top:580px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p26_83\" class=\"drag\" style=\"position:absolute;left:441px;top:595px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p26_84\" class=\"drag\" style=\"position:absolute;left:443px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p26_85\" class=\"drag\" style=\"position:absolute;left:357px;top:594px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p26_86\" class=\"drag\" style=\"position:absolute;left:357px;top:608px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p26_87\" class=\"drag\" style=\"position:absolute;left:357px;top:579px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_88\" class=\"drag\" style=\"position:absolute;left:357px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_89\" class=\"drag\" style=\"position:absolute;left:381px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_90\" class=\"drag\" style=\"position:absolute;left:357px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_91\" class=\"drag\" style=\"position:absolute;left:357px;top:637px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p26_92\" class=\"drag\" style=\"position:absolute;left:441px;top:623px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p26_93\" class=\"drag\" style=\"position:absolute;left:357px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p26_94\" class=\"drag\" style=\"position:absolute;left:346px;top:453px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C116<br></b></nobr>");
write("</p>");
write("<p id=\"p26_95\" class=\"drag\" style=\"position:absolute;left:502px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p26_96\" class=\"drag\" style=\"position:absolute;left:484px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p26_97\" class=\"drag\" style=\"position:absolute;left:500px;top:513px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p26_98\" class=\"drag\" style=\"position:absolute;left:537px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p26_99\" class=\"drag\" style=\"position:absolute;left:465px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p26_100\" class=\"drag\" style=\"position:absolute;left:444px;top:513px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p26_101\" class=\"drag\" style=\"position:absolute;left:447px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p26_102\" class=\"drag\" style=\"position:absolute;left:428px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p26_103\" class=\"drag\" style=\"position:absolute;left:407px;top:513px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p26_104\" class=\"drag\" style=\"position:absolute;left:410px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_105\" class=\"drag\" style=\"position:absolute;left:372px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_106\" class=\"drag\" style=\"position:absolute;left:391px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_107\" class=\"drag\" style=\"position:absolute;left:388px;top:513px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p26_108\" class=\"drag\" style=\"position:absolute;left:521px;top:494px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p26_109\" class=\"drag\" style=\"position:absolute;left:518px;top:513px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p26_110\" class=\"drag\" style=\"position:absolute;left:426px;top:513px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p26_111\" class=\"drag\" style=\"position:absolute;left:74px;top:453px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C113<br></b></nobr>");
write("</p>");
write("<p id=\"p26_112\" class=\"drag\" style=\"position:absolute;left:105px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_113\" class=\"drag\" style=\"position:absolute;left:124px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_114\" class=\"drag\" style=\"position:absolute;left:85px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_115\" class=\"drag\" style=\"position:absolute;left:110px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_116\" class=\"drag\" style=\"position:absolute;left:110px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_117\" class=\"drag\" style=\"position:absolute;left:85px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_118\" class=\"drag\" style=\"position:absolute;left:105px;top:452px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_119\" class=\"drag\" style=\"position:absolute;left:253px;top:580px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p26_120\" class=\"drag\" style=\"position:absolute;left:228px;top:579px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_121\" class=\"drag\" style=\"position:absolute;left:228px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_122\" class=\"drag\" style=\"position:absolute;left:235px;top:506px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_123\" class=\"drag\" style=\"position:absolute;left:254px;top:506px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_124\" class=\"drag\" style=\"position:absolute;left:273px;top:506px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_125\" class=\"drag\" style=\"position:absolute;left:253px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_126\" class=\"drag\" style=\"position:absolute;left:253px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_127\" class=\"drag\" style=\"position:absolute;left:228px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_128\" class=\"drag\" style=\"position:absolute;left:217px;top:453px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C115<br></b></nobr>");
write("</p>");
write("<p id=\"p26_129\" class=\"drag\" style=\"position:absolute;left:61px;top:979px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>*2 : CVT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_130\" class=\"drag\" style=\"position:absolute;left:61px;top:965px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>*1 : M/T<br></b></nobr>");
write("</p>");
write("<p id=\"p26_131\" class=\"drag\" style=\"position:absolute;left:62px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p26_132\" class=\"drag\" style=\"position:absolute;left:117px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p26_133\" class=\"drag\" style=\"position:absolute;left:117px;top:1035px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p26_134\" class=\"drag\" style=\"position:absolute;left:117px;top:1049px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p26_135\" class=\"drag\" style=\"position:absolute;left:133px;top:1035px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with female terminals (single outline): View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p26_136\" class=\"drag\" style=\"position:absolute;left:133px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with male terminals (double outline): View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p26_137\" class=\"drag\" style=\"position:absolute;left:153px;top:1049px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to ECM/PCM control.<br></b></nobr>");
write("</p>");
write("<p id=\"p26_138\" class=\"drag\" style=\"position:absolute;left:731px;top:225px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C112<br></b></nobr>");
write("</p>");
write("<p id=\"p26_139\" class=\"drag\" style=\"position:absolute;left:743px;top:322px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_140\" class=\"drag\" style=\"position:absolute;left:767px;top:323px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p26_141\" class=\"drag\" style=\"position:absolute;left:767px;top:337px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p26_142\" class=\"drag\" style=\"position:absolute;left:788px;top:277px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_143\" class=\"drag\" style=\"position:absolute;left:769px;top:277px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_144\" class=\"drag\" style=\"position:absolute;left:750px;top:277px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_145\" class=\"drag\" style=\"position:absolute;left:743px;top:337px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_146\" class=\"drag\" style=\"position:absolute;left:743px;top:351px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_147\" class=\"drag\" style=\"position:absolute;left:767px;top:351px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_148\" class=\"drag\" style=\"position:absolute;left:762px;top:223px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_149\" class=\"drag\" style=\"position:absolute;left:619px;top:223px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_150\" class=\"drag\" style=\"position:absolute;left:600px;top:322px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_151\" class=\"drag\" style=\"position:absolute;left:624px;top:323px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p26_152\" class=\"drag\" style=\"position:absolute;left:624px;top:337px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p26_153\" class=\"drag\" style=\"position:absolute;left:600px;top:337px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_154\" class=\"drag\" style=\"position:absolute;left:638px;top:276px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_155\" class=\"drag\" style=\"position:absolute;left:619px;top:276px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_156\" class=\"drag\" style=\"position:absolute;left:589px;top:225px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C111<br></b></nobr>");
write("</p>");
write("<p id=\"p26_157\" class=\"drag\" style=\"position:absolute;left:446px;top:225px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C110<br></b></nobr>");
write("</p>");
write("<p id=\"p26_158\" class=\"drag\" style=\"position:absolute;left:476px;top:276px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_159\" class=\"drag\" style=\"position:absolute;left:495px;top:276px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_160\" class=\"drag\" style=\"position:absolute;left:457px;top:337px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_161\" class=\"drag\" style=\"position:absolute;left:481px;top:337px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_162\" class=\"drag\" style=\"position:absolute;left:481px;top:323px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_163\" class=\"drag\" style=\"position:absolute;left:457px;top:322px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_164\" class=\"drag\" style=\"position:absolute;left:477px;top:223px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_165\" class=\"drag\" style=\"position:absolute;left:334px;top:223px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_166\" class=\"drag\" style=\"position:absolute;left:314px;top:322px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_167\" class=\"drag\" style=\"position:absolute;left:338px;top:323px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_168\" class=\"drag\" style=\"position:absolute;left:338px;top:337px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p26_169\" class=\"drag\" style=\"position:absolute;left:314px;top:337px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_170\" class=\"drag\" style=\"position:absolute;left:352px;top:276px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_171\" class=\"drag\" style=\"position:absolute;left:333px;top:276px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_172\" class=\"drag\" style=\"position:absolute;left:303px;top:225px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C109<br></b></nobr>");
write("</p>");
write("<p id=\"p26_173\" class=\"drag\" style=\"position:absolute;left:105px;top:223px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_174\" class=\"drag\" style=\"position:absolute;left:195px;top:380px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_175\" class=\"drag\" style=\"position:absolute;left:195px;top:323px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p26_176\" class=\"drag\" style=\"position:absolute;left:195px;top:337px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_177\" class=\"drag\" style=\"position:absolute;left:195px;top:351px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_178\" class=\"drag\" style=\"position:absolute;left:195px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p26_179\" class=\"drag\" style=\"position:absolute;left:169px;top:380px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p26_180\" class=\"drag\" style=\"position:absolute;left:171px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p26_181\" class=\"drag\" style=\"position:absolute;left:171px;top:351px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p26_182\" class=\"drag\" style=\"position:absolute;left:171px;top:337px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p26_183\" class=\"drag\" style=\"position:absolute;left:171px;top:322px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p26_184\" class=\"drag\" style=\"position:absolute;left:85px;top:379px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p26_185\" class=\"drag\" style=\"position:absolute;left:192px;top:284px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p26_186\" class=\"drag\" style=\"position:absolute;left:157px;top:284px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p26_187\" class=\"drag\" style=\"position:absolute;left:176px;top:284px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p26_188\" class=\"drag\" style=\"position:absolute;left:157px;top:266px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_189\" class=\"drag\" style=\"position:absolute;left:176px;top:266px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p26_190\" class=\"drag\" style=\"position:absolute;left:85px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p26_191\" class=\"drag\" style=\"position:absolute;left:110px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p26_192\" class=\"drag\" style=\"position:absolute;left:110px;top:351px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_193\" class=\"drag\" style=\"position:absolute;left:85px;top:351px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_194\" class=\"drag\" style=\"position:absolute;left:85px;top:337px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_195\" class=\"drag\" style=\"position:absolute;left:110px;top:337px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_196\" class=\"drag\" style=\"position:absolute;left:85px;top:322px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_197\" class=\"drag\" style=\"position:absolute;left:119px;top:284px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p26_198\" class=\"drag\" style=\"position:absolute;left:138px;top:284px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p26_199\" class=\"drag\" style=\"position:absolute;left:138px;top:266px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_200\" class=\"drag\" style=\"position:absolute;left:74px;top:225px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C108<br></b></nobr>");
write("</p>");
write("<p id=\"p26_201\" class=\"drag\" style=\"position:absolute;left:789px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C107<br></b></nobr>");
write("</p>");
write("<p id=\"p26_202\" class=\"drag\" style=\"position:absolute;left:800px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_203\" class=\"drag\" style=\"position:absolute;left:824px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p26_204\" class=\"drag\" style=\"position:absolute;left:824px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_205\" class=\"drag\" style=\"position:absolute;left:845px;top:77px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_206\" class=\"drag\" style=\"position:absolute;left:826px;top:77px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_207\" class=\"drag\" style=\"position:absolute;left:807px;top:77px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_208\" class=\"drag\" style=\"position:absolute;left:800px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_209\" class=\"drag\" style=\"position:absolute;left:800px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_210\" class=\"drag\" style=\"position:absolute;left:824px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_211\" class=\"drag\" style=\"position:absolute;left:820px;top:23px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_212\" class=\"drag\" style=\"position:absolute;left:677px;top:23px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_213\" class=\"drag\" style=\"position:absolute;left:681px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_214\" class=\"drag\" style=\"position:absolute;left:657px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_215\" class=\"drag\" style=\"position:absolute;left:657px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_216\" class=\"drag\" style=\"position:absolute;left:664px;top:77px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_217\" class=\"drag\" style=\"position:absolute;left:683px;top:77px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_218\" class=\"drag\" style=\"position:absolute;left:702px;top:77px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_219\" class=\"drag\" style=\"position:absolute;left:681px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p26_220\" class=\"drag\" style=\"position:absolute;left:681px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p26_221\" class=\"drag\" style=\"position:absolute;left:657px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_222\" class=\"drag\" style=\"position:absolute;left:646px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C106<br></b></nobr>");
write("</p>");
write("<p id=\"p26_223\" class=\"drag\" style=\"position:absolute;left:503px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C105<br></b></nobr>");
write("</p>");
write("<p id=\"p26_224\" class=\"drag\" style=\"position:absolute;left:514px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_225\" class=\"drag\" style=\"position:absolute;left:539px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p26_226\" class=\"drag\" style=\"position:absolute;left:539px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_227\" class=\"drag\" style=\"position:absolute;left:559px;top:77px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_228\" class=\"drag\" style=\"position:absolute;left:540px;top:77px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_229\" class=\"drag\" style=\"position:absolute;left:521px;top:77px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_230\" class=\"drag\" style=\"position:absolute;left:514px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_231\" class=\"drag\" style=\"position:absolute;left:514px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_232\" class=\"drag\" style=\"position:absolute;left:539px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_233\" class=\"drag\" style=\"position:absolute;left:360px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C104<br></b></nobr>");
write("</p>");
write("<p id=\"p26_234\" class=\"drag\" style=\"position:absolute;left:390px;top:76px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_235\" class=\"drag\" style=\"position:absolute;left:410px;top:76px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_236\" class=\"drag\" style=\"position:absolute;left:371px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_237\" class=\"drag\" style=\"position:absolute;left:396px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_238\" class=\"drag\" style=\"position:absolute;left:396px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_239\" class=\"drag\" style=\"position:absolute;left:371px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_240\" class=\"drag\" style=\"position:absolute;left:248px;top:23px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_241\" class=\"drag\" style=\"position:absolute;left:74px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C102<br></b></nobr>");
write("</p>");
write("<p id=\"p26_242\" class=\"drag\" style=\"position:absolute;left:105px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_243\" class=\"drag\" style=\"position:absolute;left:124px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_244\" class=\"drag\" style=\"position:absolute;left:124px;top:84px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p26_245\" class=\"drag\" style=\"position:absolute;left:105px;top:84px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_246\" class=\"drag\" style=\"position:absolute;left:85px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_247\" class=\"drag\" style=\"position:absolute;left:110px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_248\" class=\"drag\" style=\"position:absolute;left:110px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_249\" class=\"drag\" style=\"position:absolute;left:85px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_250\" class=\"drag\" style=\"position:absolute;left:85px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_251\" class=\"drag\" style=\"position:absolute;left:110px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p26_252\" class=\"drag\" style=\"position:absolute;left:110px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_253\" class=\"drag\" style=\"position:absolute;left:85px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p26_254\" class=\"drag\" style=\"position:absolute;left:228px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_255\" class=\"drag\" style=\"position:absolute;left:253px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p26_256\" class=\"drag\" style=\"position:absolute;left:253px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p26_257\" class=\"drag\" style=\"position:absolute;left:228px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_258\" class=\"drag\" style=\"position:absolute;left:228px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_259\" class=\"drag\" style=\"position:absolute;left:253px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p26_260\" class=\"drag\" style=\"position:absolute;left:276px;top:76px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p26_261\" class=\"drag\" style=\"position:absolute;left:257px;top:76px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p26_262\" class=\"drag\" style=\"position:absolute;left:238px;top:76px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p26_263\" class=\"drag\" style=\"position:absolute;left:217px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C103<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}