with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:687px;\" coordsize=\"950,687\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:687px;\">");
write("<img id=\"img1\" src=\"../img/SAA4E60D00060845111KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:687px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:582px;top:50px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DISC BRAKE MODEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:759px;top:165px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:579px;top:349px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:785px;top:414px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DISC BRAKE MODEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:590px;top:473px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PARKING BRAKE CABLE<br></b>Check for stiffness, and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:551px;top:528px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EQUALIZER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:515px;top:577px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ADJUSTING NUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:187px;top:588px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PARKING BRAKE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:54px;top:650px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>(Sliding surface)<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:19px;top:269px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PARKING BRAKE LEVER<br></b>Check for smooth<br>operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:234px;top:164px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}