with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img3\" src=\"../img/SAA4EF0A20300000000EAAD38.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:540px;top:146px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:540px;top:177px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:861px;top:126px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:601px;top:146px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:601px;top:177px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:754px;top:209px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:839px;top:237px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>KNOCK SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:544px;top:271px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:601px;top:270px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:563px;top:256px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>KS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:563px;top:164px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TPS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:563px;top:133px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VCC2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:846px;top:648px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IAT SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:847px;top:710px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECT SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:540px;top:631px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:540px;top:685px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B17<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:543px;top:749px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:563px;top:735px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:601px;top:685px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:563px;top:672px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IAT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:562px;top:619px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SG2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:772px;top:668px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:601px;top:748px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:850px;top:347px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR VALVE<br>POSITION<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:540px;top:403px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:563px;top:387px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGRP<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:601px;top:402px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:541px;top:473px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:563px;top:459px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:776px;top:420px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:776px;top:387px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:808px;top:451px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:780px;top:511px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:610px;top:472px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:773px;top:731px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:601px;top:632px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:855px;top:471px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:384px;top:194px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A30<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:343px;top:179px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS1I<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:222px;top:175px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:235px;top:215px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:384px;top:271px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A29<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:342px;top:257px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS2I<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:222px;top:272px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:222px;top:252px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:234px;top:292px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:383px;top:348px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A28<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:342px;top:334px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS3I<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:222px;top:350px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" class=\"drag\" style=\"position:absolute;left:222px;top:330px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" class=\"drag\" style=\"position:absolute;left:234px;top:370px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" class=\"drag\" style=\"position:absolute;left:384px;top:426px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A27<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" class=\"drag\" style=\"position:absolute;left:342px;top:412px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS4I<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" class=\"drag\" style=\"position:absolute;left:222px;top:408px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" class=\"drag\" style=\"position:absolute;left:235px;top:448px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" class=\"drag\" style=\"position:absolute;left:235px;top:193px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" class=\"drag\" style=\"position:absolute;left:388px;top:726px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" class=\"drag\" style=\"position:absolute;left:339px;top:711px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS1E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" class=\"drag\" style=\"position:absolute;left:384px;top:803px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" class=\"drag\" style=\"position:absolute;left:339px;top:789px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS2E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" class=\"drag\" style=\"position:absolute;left:384px;top:881px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" class=\"drag\" style=\"position:absolute;left:339px;top:867px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS3E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" class=\"drag\" style=\"position:absolute;left:384px;top:958px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B22<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" class=\"drag\" style=\"position:absolute;left:339px;top:944px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS4E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" class=\"drag\" style=\"position:absolute;left:222px;top:428px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" class=\"drag\" style=\"position:absolute;left:237px;top:707px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" class=\"drag\" style=\"position:absolute;left:237px;top:747px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" class=\"drag\" style=\"position:absolute;left:223px;top:804px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" class=\"drag\" style=\"position:absolute;left:237px;top:785px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" class=\"drag\" style=\"position:absolute;left:236px;top:824px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" class=\"drag\" style=\"position:absolute;left:223px;top:882px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" class=\"drag\" style=\"position:absolute;left:237px;top:863px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" class=\"drag\" style=\"position:absolute;left:236px;top:903px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" class=\"drag\" style=\"position:absolute;left:237px;top:941px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" class=\"drag\" style=\"position:absolute;left:237px;top:726px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" class=\"drag\" style=\"position:absolute;left:223px;top:960px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" class=\"drag\" style=\"position:absolute;left:236px;top:981px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" class=\"drag\" style=\"position:absolute;left:20px;top:183px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" class=\"drag\" style=\"position:absolute;left:146px;top:204px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" class=\"drag\" style=\"position:absolute;left:22px;top:234px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 FRONT IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" class=\"drag\" style=\"position:absolute;left:21px;top:715px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" class=\"drag\" style=\"position:absolute;left:146px;top:736px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" class=\"drag\" style=\"position:absolute;left:21px;top:766px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 REAR IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" class=\"drag\" style=\"position:absolute;left:20px;top:792px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" class=\"drag\" style=\"position:absolute;left:146px;top:814px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" class=\"drag\" style=\"position:absolute;left:21px;top:844px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 REAR IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" class=\"drag\" style=\"position:absolute;left:20px;top:870px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" class=\"drag\" style=\"position:absolute;left:146px;top:891px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" class=\"drag\" style=\"position:absolute;left:21px;top:921px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 3 REAR IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" class=\"drag\" style=\"position:absolute;left:20px;top:948px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" class=\"drag\" style=\"position:absolute;left:146px;top:969px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" class=\"drag\" style=\"position:absolute;left:21px;top:999px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 4 REAR IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" class=\"drag\" style=\"position:absolute;left:20px;top:260px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" class=\"drag\" style=\"position:absolute;left:146px;top:282px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" class=\"drag\" style=\"position:absolute;left:22px;top:312px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 FRONT IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" class=\"drag\" style=\"position:absolute;left:19px;top:338px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" class=\"drag\" style=\"position:absolute;left:146px;top:360px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_98\" class=\"drag\" style=\"position:absolute;left:21px;top:389px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 3 FRONT IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_99\" class=\"drag\" style=\"position:absolute;left:19px;top:416px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_100\" class=\"drag\" style=\"position:absolute;left:146px;top:437px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_101\" class=\"drag\" style=\"position:absolute;left:21px;top:467px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 4 FRONT IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_102\" class=\"drag\" style=\"position:absolute;left:322px;top:520px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p3_103\" class=\"drag\" style=\"position:absolute;left:322px;top:1052px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p3_104\" class=\"drag\" style=\"position:absolute;left:107px;top:36px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_105\" class=\"drag\" style=\"position:absolute;left:87px;top:77px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_106\" class=\"drag\" style=\"position:absolute;left:63px;top:96px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C302<br></b></nobr>");
write("</p>");
write("<p id=\"p3_107\" class=\"drag\" style=\"position:absolute;left:63px;top:121px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C114<br></b></nobr>");
write("</p>");
write("<p id=\"p3_108\" class=\"drag\" style=\"position:absolute;left:337px;top:117px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>J/C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_109\" class=\"drag\" style=\"position:absolute;left:337px;top:132px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C116<br></b></nobr>");
write("</p>");
write("<p id=\"p3_110\" class=\"drag\" style=\"position:absolute;left:138px;top:156px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_111\" class=\"drag\" style=\"position:absolute;left:108px;top:569px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_112\" class=\"drag\" style=\"position:absolute;left:87px;top:610px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_113\" class=\"drag\" style=\"position:absolute;left:64px;top:628px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C302<br></b></nobr>");
write("</p>");
write("<p id=\"p3_114\" class=\"drag\" style=\"position:absolute;left:64px;top:653px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C114<br></b></nobr>");
write("</p>");
write("<p id=\"p3_115\" class=\"drag\" style=\"position:absolute;left:335px;top:649px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>J/C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_116\" class=\"drag\" style=\"position:absolute;left:335px;top:664px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C116<br></b></nobr>");
write("</p>");
write("<p id=\"p3_117\" class=\"drag\" style=\"position:absolute;left:151px;top:687px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_118\" class=\"drag\" style=\"position:absolute;left:804px;top:133px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C117<br></b></nobr>");
write("</p>");
write("<p id=\"p3_119\" class=\"drag\" style=\"position:absolute;left:803px;top:249px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C121<br></b></nobr>");
write("</p>");
write("<p id=\"p3_120\" class=\"drag\" style=\"position:absolute;left:814px;top:372px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C131<br></b></nobr>");
write("</p>");
write("<p id=\"p3_121\" class=\"drag\" style=\"position:absolute;left:811px;top:652px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C118<br></b></nobr>");
write("</p>");
write("<p id=\"p3_122\" class=\"drag\" style=\"position:absolute;left:813px;top:716px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C104<br></b></nobr>");
write("</p>");
write("<p id=\"p3_123\" class=\"drag\" style=\"position:absolute;left:216px;top:163px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C130<br></b></nobr>");
write("</p>");
write("<p id=\"p3_124\" class=\"drag\" style=\"position:absolute;left:216px;top:240px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C128<br></b></nobr>");
write("</p>");
write("<p id=\"p3_125\" class=\"drag\" style=\"position:absolute;left:217px;top:317px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C126<br></b></nobr>");
write("</p>");
write("<p id=\"p3_126\" class=\"drag\" style=\"position:absolute;left:217px;top:394px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C124<br></b></nobr>");
write("</p>");
write("<p id=\"p3_127\" class=\"drag\" style=\"position:absolute;left:217px;top:695px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C135<br></b></nobr>");
write("</p>");
write("<p id=\"p3_128\" class=\"drag\" style=\"position:absolute;left:217px;top:772px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C134<br></b></nobr>");
write("</p>");
write("<p id=\"p3_129\" class=\"drag\" style=\"position:absolute;left:218px;top:849px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C133<br></b></nobr>");
write("</p>");
write("<p id=\"p3_130\" class=\"drag\" style=\"position:absolute;left:218px;top:926px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C132<br></b></nobr>");
write("</p>");
write("<p id=\"p3_131\" class=\"drag\" style=\"position:absolute;left:544px;top:821px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_132\" class=\"drag\" style=\"position:absolute;left:563px;top:808px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PHO2S<br></b></nobr>");
write("</p>");
write("<p id=\"p3_133\" class=\"drag\" style=\"position:absolute;left:544px;top:851px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_134\" class=\"drag\" style=\"position:absolute;left:601px;top:850px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_135\" class=\"drag\" style=\"position:absolute;left:563px;top:837px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PHO2SHTC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_136\" class=\"drag\" style=\"position:absolute;left:853px;top:884px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PRIMARY<br>HO2S<br>(SENSOR 1)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_137\" class=\"drag\" style=\"position:absolute;left:776px;top:864px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_138\" class=\"drag\" style=\"position:absolute;left:775px;top:836px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_139\" class=\"drag\" style=\"position:absolute;left:744px;top:907px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p3_140\" class=\"drag\" style=\"position:absolute;left:611px;top:822px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_141\" class=\"drag\" style=\"position:absolute;left:628px;top:589px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p3_142\" class=\"drag\" style=\"position:absolute;left:608px;top:553px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_143\" class=\"drag\" style=\"position:absolute;left:816px;top:809px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C102<br></b></nobr>");
write("</p>");
write("<p id=\"p3_144\" class=\"drag\" style=\"position:absolute;left:544px;top:960px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_145\" class=\"drag\" style=\"position:absolute;left:564px;top:947px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHO2S<br></b></nobr>");
write("</p>");
write("<p id=\"p3_146\" class=\"drag\" style=\"position:absolute;left:544px;top:990px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_147\" class=\"drag\" style=\"position:absolute;left:601px;top:989px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_148\" class=\"drag\" style=\"position:absolute;left:563px;top:977px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHO2SHTC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_149\" class=\"drag\" style=\"position:absolute;left:823px;top:1025px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SECONDARY HO2S<br>(SENSOR 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_150\" class=\"drag\" style=\"position:absolute;left:800px;top:1004px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_151\" class=\"drag\" style=\"position:absolute;left:800px;top:975px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_152\" class=\"drag\" style=\"position:absolute;left:684px;top:1021px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p3_153\" class=\"drag\" style=\"position:absolute;left:810px;top:946px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C218<br></b></nobr>");
write("</p>");
write("<p id=\"p3_154\" class=\"drag\" style=\"position:absolute;left:726px;top:1021px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p3_155\" class=\"drag\" style=\"position:absolute;left:744px;top:936px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p3_156\" class=\"drag\" style=\"position:absolute;left:601px;top:961px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_157\" class=\"drag\" style=\"position:absolute;left:908px;top:785px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_158\" class=\"drag\" style=\"position:absolute;left:760px;top:588px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p3_159\" class=\"drag\" style=\"position:absolute;left:801px;top:597px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p3_160\" class=\"drag\" style=\"position:absolute;left:761px;top:325px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}