with(document) {
write("<v:group id=\"group36\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect36\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img36\" src=\"../img/SAA4EF0A20300000000DBAD83.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p36_1\" class=\"drag\" style=\"position:absolute;left:253px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p36_2\" class=\"drag\" style=\"position:absolute;left:300px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_3\" class=\"drag\" style=\"position:absolute;left:300px;top:492px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_4\" class=\"drag\" style=\"position:absolute;left:214px;top:492px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_5\" class=\"drag\" style=\"position:absolute;left:214px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p36_6\" class=\"drag\" style=\"position:absolute;left:273px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p36_7\" class=\"drag\" style=\"position:absolute;left:187px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p36_8\" class=\"drag\" style=\"position:absolute;left:300px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_9\" class=\"drag\" style=\"position:absolute;left:273px;top:449px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p36_10\" class=\"drag\" style=\"position:absolute;left:273px;top:492px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p36_11\" class=\"drag\" style=\"position:absolute;left:273px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p36_12\" class=\"drag\" style=\"position:absolute;left:273px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p36_13\" class=\"drag\" style=\"position:absolute;left:300px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_14\" class=\"drag\" style=\"position:absolute;left:273px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p36_15\" class=\"drag\" style=\"position:absolute;left:273px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p36_16\" class=\"drag\" style=\"position:absolute;left:300px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_17\" class=\"drag\" style=\"position:absolute;left:300px;top:450px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_18\" class=\"drag\" style=\"position:absolute;left:214px;top:450px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_19\" class=\"drag\" style=\"position:absolute;left:128px;top:450px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_20\" class=\"drag\" style=\"position:absolute;left:128px;top:492px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_21\" class=\"drag\" style=\"position:absolute;left:104px;top:492px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p36_22\" class=\"drag\" style=\"position:absolute;left:190px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p36_23\" class=\"drag\" style=\"position:absolute;left:104px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p36_24\" class=\"drag\" style=\"position:absolute;left:104px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_25\" class=\"drag\" style=\"position:absolute;left:104px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_26\" class=\"drag\" style=\"position:absolute;left:104px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_27\" class=\"drag\" style=\"position:absolute;left:104px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_28\" class=\"drag\" style=\"position:absolute;left:104px;top:449px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_29\" class=\"drag\" style=\"position:absolute;left:128px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p36_30\" class=\"drag\" style=\"position:absolute;left:190px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p36_31\" class=\"drag\" style=\"position:absolute;left:214px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p36_32\" class=\"drag\" style=\"position:absolute;left:187px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p36_33\" class=\"drag\" style=\"position:absolute;left:187px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p36_34\" class=\"drag\" style=\"position:absolute;left:187px;top:492px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p36_35\" class=\"drag\" style=\"position:absolute;left:187px;top:449px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p36_36\" class=\"drag\" style=\"position:absolute;left:128px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_37\" class=\"drag\" style=\"position:absolute;left:128px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_38\" class=\"drag\" style=\"position:absolute;left:128px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_39\" class=\"drag\" style=\"position:absolute;left:214px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_40\" class=\"drag\" style=\"position:absolute;left:214px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_41\" class=\"drag\" style=\"position:absolute;left:301px;top:367px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p36_42\" class=\"drag\" style=\"position:absolute;left:304px;top:349px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p36_43\" class=\"drag\" style=\"position:absolute;left:282px;top:367px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p36_44\" class=\"drag\" style=\"position:absolute;left:97px;top:367px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p36_45\" class=\"drag\" style=\"position:absolute;left:115px;top:367px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p36_46\" class=\"drag\" style=\"position:absolute;left:118px;top:349px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_47\" class=\"drag\" style=\"position:absolute;left:245px;top:367px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p36_48\" class=\"drag\" style=\"position:absolute;left:266px;top:349px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p36_49\" class=\"drag\" style=\"position:absolute;left:248px;top:349px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p36_50\" class=\"drag\" style=\"position:absolute;left:171px;top:367px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p36_51\" class=\"drag\" style=\"position:absolute;left:173px;top:349px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_52\" class=\"drag\" style=\"position:absolute;left:152px;top:367px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p36_53\" class=\"drag\" style=\"position:absolute;left:134px;top:367px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p36_54\" class=\"drag\" style=\"position:absolute;left:136px;top:349px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_55\" class=\"drag\" style=\"position:absolute;left:227px;top:367px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p36_56\" class=\"drag\" style=\"position:absolute;left:264px;top:367px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p36_57\" class=\"drag\" style=\"position:absolute;left:190px;top:367px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p36_58\" class=\"drag\" style=\"position:absolute;left:155px;top:349px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_59\" class=\"drag\" style=\"position:absolute;left:736px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_60\" class=\"drag\" style=\"position:absolute;left:650px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_61\" class=\"drag\" style=\"position:absolute;left:709px;top:165px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p36_62\" class=\"drag\" style=\"position:absolute;left:709px;top:208px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p36_63\" class=\"drag\" style=\"position:absolute;left:734px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p36_64\" class=\"drag\" style=\"position:absolute;left:753px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p36_65\" class=\"drag\" style=\"position:absolute;left:697px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p36_66\" class=\"drag\" style=\"position:absolute;left:678px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p36_67\" class=\"drag\" style=\"position:absolute;left:644px;top:62px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_68\" class=\"drag\" style=\"position:absolute;left:625px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p36_69\" class=\"drag\" style=\"position:absolute;left:662px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p36_70\" class=\"drag\" style=\"position:absolute;left:718px;top:62px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_71\" class=\"drag\" style=\"position:absolute;left:716px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p36_72\" class=\"drag\" style=\"position:absolute;left:407px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p36_73\" class=\"drag\" style=\"position:absolute;left:383px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_74\" class=\"drag\" style=\"position:absolute;left:407px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_75\" class=\"drag\" style=\"position:absolute;left:383px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_76\" class=\"drag\" style=\"position:absolute;left:383px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_77\" class=\"drag\" style=\"position:absolute;left:383px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_78\" class=\"drag\" style=\"position:absolute;left:383px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_79\" class=\"drag\" style=\"position:absolute;left:407px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_80\" class=\"drag\" style=\"position:absolute;left:383px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p36_81\" class=\"drag\" style=\"position:absolute;left:407px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_82\" class=\"drag\" style=\"position:absolute;left:378px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_83\" class=\"drag\" style=\"position:absolute;left:396px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_84\" class=\"drag\" style=\"position:absolute;left:434px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_85\" class=\"drag\" style=\"position:absolute;left:378px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_86\" class=\"drag\" style=\"position:absolute;left:214px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_87\" class=\"drag\" style=\"position:absolute;left:214px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_88\" class=\"drag\" style=\"position:absolute;left:214px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_89\" class=\"drag\" style=\"position:absolute;left:128px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_90\" class=\"drag\" style=\"position:absolute;left:128px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_91\" class=\"drag\" style=\"position:absolute;left:128px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_92\" class=\"drag\" style=\"position:absolute;left:128px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_93\" class=\"drag\" style=\"position:absolute;left:128px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_94\" class=\"drag\" style=\"position:absolute;left:187px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p36_95\" class=\"drag\" style=\"position:absolute;left:187px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p36_96\" class=\"drag\" style=\"position:absolute;left:187px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p36_97\" class=\"drag\" style=\"position:absolute;left:187px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p36_98\" class=\"drag\" style=\"position:absolute;left:187px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p36_99\" class=\"drag\" style=\"position:absolute;left:188px;top:193px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p36_100\" class=\"drag\" style=\"position:absolute;left:214px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_101\" class=\"drag\" style=\"position:absolute;left:104px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p36_102\" class=\"drag\" style=\"position:absolute;left:190px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p36_103\" class=\"drag\" style=\"position:absolute;left:104px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_104\" class=\"drag\" style=\"position:absolute;left:104px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_105\" class=\"drag\" style=\"position:absolute;left:104px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_106\" class=\"drag\" style=\"position:absolute;left:104px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_107\" class=\"drag\" style=\"position:absolute;left:104px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_108\" class=\"drag\" style=\"position:absolute;left:104px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p36_109\" class=\"drag\" style=\"position:absolute;left:187px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p36_110\" class=\"drag\" style=\"position:absolute;left:104px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p36_111\" class=\"drag\" style=\"position:absolute;left:128px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_112\" class=\"drag\" style=\"position:absolute;left:128px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_113\" class=\"drag\" style=\"position:absolute;left:214px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p36_114\" class=\"drag\" style=\"position:absolute;left:214px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_115\" class=\"drag\" style=\"position:absolute;left:196px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_116\" class=\"drag\" style=\"position:absolute;left:255px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p36_117\" class=\"drag\" style=\"position:absolute;left:137px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p36_118\" class=\"drag\" style=\"position:absolute;left:140px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_119\" class=\"drag\" style=\"position:absolute;left:99px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_120\" class=\"drag\" style=\"position:absolute;left:118px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_121\" class=\"drag\" style=\"position:absolute;left:118px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p36_122\" class=\"drag\" style=\"position:absolute;left:156px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p36_123\" class=\"drag\" style=\"position:absolute;left:175px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p36_124\" class=\"drag\" style=\"position:absolute;left:237px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p36_125\" class=\"drag\" style=\"position:absolute;left:216px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p36_126\" class=\"drag\" style=\"position:absolute;left:99px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p36_127\" class=\"drag\" style=\"position:absolute;left:92px;top:309px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C263<br></b></nobr>");
write("</p>");
write("<p id=\"p36_128\" class=\"drag\" style=\"position:absolute;left:736px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_129\" class=\"drag\" style=\"position:absolute;left:736px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_130\" class=\"drag\" style=\"position:absolute;left:736px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p36_131\" class=\"drag\" style=\"position:absolute;left:736px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p36_132\" class=\"drag\" style=\"position:absolute;left:708px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p36_133\" class=\"drag\" style=\"position:absolute;left:708px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p36_134\" class=\"drag\" style=\"position:absolute;left:708px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p36_135\" class=\"drag\" style=\"position:absolute;left:607px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C262<br></b></nobr>");
write("</p>");
write("<p id=\"p36_136\" class=\"drag\" style=\"position:absolute;left:736px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p36_137\" class=\"drag\" style=\"position:absolute;left:711px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p36_138\" class=\"drag\" style=\"position:absolute;left:625px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p36_139\" class=\"drag\" style=\"position:absolute;left:625px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p36_140\" class=\"drag\" style=\"position:absolute;left:625px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_141\" class=\"drag\" style=\"position:absolute;left:625px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_142\" class=\"drag\" style=\"position:absolute;left:625px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_143\" class=\"drag\" style=\"position:absolute;left:625px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_144\" class=\"drag\" style=\"position:absolute;left:625px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_145\" class=\"drag\" style=\"position:absolute;left:650px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_146\" class=\"drag\" style=\"position:absolute;left:650px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_147\" class=\"drag\" style=\"position:absolute;left:711px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p36_148\" class=\"drag\" style=\"position:absolute;left:328px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C261<br></b></nobr>");
write("</p>");
write("<p id=\"p36_149\" class=\"drag\" style=\"position:absolute;left:92px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C260<br></b></nobr>");
write("</p>");
write("<p id=\"p36_150\" class=\"drag\" style=\"position:absolute;left:150px;top:1069px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>* : Terminal side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p36_151\" class=\"drag\" style=\"position:absolute;left:80px;top:1019px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p36_152\" class=\"drag\" style=\"position:absolute;left:135px;top:1019px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p36_153\" class=\"drag\" style=\"position:absolute;left:135px;top:1034px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p36_154\" class=\"drag\" style=\"position:absolute;left:135px;top:1048px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p36_155\" class=\"drag\" style=\"position:absolute;left:151px;top:1034px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with female terminals (single outline): View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p36_156\" class=\"drag\" style=\"position:absolute;left:151px;top:1019px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with male terminals (double outline): View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p36_157\" class=\"drag\" style=\"position:absolute;left:171px;top:1048px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to ECM/PCM control.<br></b></nobr>");
write("</p>");
write("<p id=\"p36_158\" class=\"drag\" style=\"position:absolute;left:423px;top:735px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p36_159\" class=\"drag\" style=\"position:absolute;left:444px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p36_160\" class=\"drag\" style=\"position:absolute;left:465px;top:620px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_161\" class=\"drag\" style=\"position:absolute;left:446px;top:620px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_162\" class=\"drag\" style=\"position:absolute;left:407px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p36_163\" class=\"drag\" style=\"position:absolute;left:372px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p36_164\" class=\"drag\" style=\"position:absolute;left:372px;top:620px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_165\" class=\"drag\" style=\"position:absolute;left:353px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p36_166\" class=\"drag\" style=\"position:absolute;left:335px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p36_167\" class=\"drag\" style=\"position:absolute;left:335px;top:620px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_168\" class=\"drag\" style=\"position:absolute;left:425px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p36_169\" class=\"drag\" style=\"position:absolute;left:463px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p36_170\" class=\"drag\" style=\"position:absolute;left:391px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p36_171\" class=\"drag\" style=\"position:absolute;left:353px;top:620px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_172\" class=\"drag\" style=\"position:absolute;left:128px;top:735px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_173\" class=\"drag\" style=\"position:absolute;left:128px;top:750px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_174\" class=\"drag\" style=\"position:absolute;left:155px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p36_175\" class=\"drag\" style=\"position:absolute;left:136px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_176\" class=\"drag\" style=\"position:absolute;left:128px;top:721px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_177\" class=\"drag\" style=\"position:absolute;left:104px;top:750px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p36_178\" class=\"drag\" style=\"position:absolute;left:104px;top:721px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_179\" class=\"drag\" style=\"position:absolute;left:104px;top:735px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_180\" class=\"drag\" style=\"position:absolute;left:104px;top:707px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_181\" class=\"drag\" style=\"position:absolute;left:104px;top:692px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_182\" class=\"drag\" style=\"position:absolute;left:128px;top:678px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p36_183\" class=\"drag\" style=\"position:absolute;left:104px;top:678px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_184\" class=\"drag\" style=\"position:absolute;left:128px;top:693px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p36_185\" class=\"drag\" style=\"position:absolute;left:99px;top:620px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_186\" class=\"drag\" style=\"position:absolute;left:155px;top:620px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_187\" class=\"drag\" style=\"position:absolute;left:118px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_188\" class=\"drag\" style=\"position:absolute;left:700px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_189\" class=\"drag\" style=\"position:absolute;left:676px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_190\" class=\"drag\" style=\"position:absolute;left:676px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_191\" class=\"drag\" style=\"position:absolute;left:676px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_192\" class=\"drag\" style=\"position:absolute;left:700px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p36_193\" class=\"drag\" style=\"position:absolute;left:676px;top:449px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_194\" class=\"drag\" style=\"position:absolute;left:664px;top:309px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C265<br></b></nobr>");
write("</p>");
write("<p id=\"p36_195\" class=\"drag\" style=\"position:absolute;left:694px;top:307px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p36_196\" class=\"drag\" style=\"position:absolute;left:704px;top:337px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_197\" class=\"drag\" style=\"position:absolute;left:704px;top:356px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_198\" class=\"drag\" style=\"position:absolute;left:722px;top:374px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_199\" class=\"drag\" style=\"position:absolute;left:685px;top:374px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_200\" class=\"drag\" style=\"position:absolute;left:700px;top:450px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_201\" class=\"drag\" style=\"position:absolute;left:700px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_202\" class=\"drag\" style=\"position:absolute;left:492px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_203\" class=\"drag\" style=\"position:absolute;left:492px;top:450px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_204\" class=\"drag\" style=\"position:absolute;left:478px;top:374px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_205\" class=\"drag\" style=\"position:absolute;left:515px;top:374px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_206\" class=\"drag\" style=\"position:absolute;left:496px;top:356px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_207\" class=\"drag\" style=\"position:absolute;left:496px;top:337px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_208\" class=\"drag\" style=\"position:absolute;left:487px;top:307px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p36_209\" class=\"drag\" style=\"position:absolute;left:364px;top:721px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_210\" class=\"drag\" style=\"position:absolute;left:450px;top:735px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_211\" class=\"drag\" style=\"position:absolute;left:340px;top:735px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_212\" class=\"drag\" style=\"position:absolute;left:423px;top:721px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p36_213\" class=\"drag\" style=\"position:absolute;left:425px;top:678px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p36_214\" class=\"drag\" style=\"position:absolute;left:328px;top:580px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C381<br></b></nobr>");
write("</p>");
write("<p id=\"p36_215\" class=\"drag\" style=\"position:absolute;left:450px;top:693px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_216\" class=\"drag\" style=\"position:absolute;left:450px;top:678px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p36_217\" class=\"drag\" style=\"position:absolute;left:450px;top:707px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_218\" class=\"drag\" style=\"position:absolute;left:450px;top:721px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_219\" class=\"drag\" style=\"position:absolute;left:364px;top:735px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_220\" class=\"drag\" style=\"position:absolute;left:364px;top:693px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_221\" class=\"drag\" style=\"position:absolute;left:340px;top:721px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_222\" class=\"drag\" style=\"position:absolute;left:425px;top:692px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p36_223\" class=\"drag\" style=\"position:absolute;left:364px;top:707px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_224\" class=\"drag\" style=\"position:absolute;left:340px;top:707px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_225\" class=\"drag\" style=\"position:absolute;left:340px;top:692px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_226\" class=\"drag\" style=\"position:absolute;left:364px;top:678px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p36_227\" class=\"drag\" style=\"position:absolute;left:340px;top:678px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_228\" class=\"drag\" style=\"position:absolute;left:364px;top:764px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_229\" class=\"drag\" style=\"position:absolute;left:340px;top:764px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p36_230\" class=\"drag\" style=\"position:absolute;left:450px;top:750px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_231\" class=\"drag\" style=\"position:absolute;left:364px;top:750px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p36_232\" class=\"drag\" style=\"position:absolute;left:340px;top:750px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p36_233\" class=\"drag\" style=\"position:absolute;left:424px;top:708px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p36_234\" class=\"drag\" style=\"position:absolute;left:423px;top:750px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p36_235\" class=\"drag\" style=\"position:absolute;left:457px;top:309px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C264<br></b></nobr>");
write("</p>");
write("<p id=\"p36_236\" class=\"drag\" style=\"position:absolute;left:468px;top:449px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_237\" class=\"drag\" style=\"position:absolute;left:492px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_238\" class=\"drag\" style=\"position:absolute;left:468px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_239\" class=\"drag\" style=\"position:absolute;left:468px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_240\" class=\"drag\" style=\"position:absolute;left:492px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_241\" class=\"drag\" style=\"position:absolute;left:468px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_242\" class=\"drag\" style=\"position:absolute;left:92px;top:580px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C380<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}