with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:560px;\" coordsize=\"950,560\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:560px;\">");
write("<img id=\"img1\" src=\"../img/SAA4EF0J22100000000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:560px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:863px;top:425px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:580px;top:327px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RELAY DRIVING CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:609px;top:371px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:595px;top:384px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:544px;top:328px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:834px;top:536px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: RHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:821px;top:536px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:821px;top:530px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:834px;top:530px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: LHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:652px;top:384px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:667px;top:371px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:870px;top:299px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:897px;top:228px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:880px;top:426px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:823px;top:384px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:737px;top:302px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:737px;top:296px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ABS INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:689px;top:422px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:830px;top:490px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:837px;top:473px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:837px;top:445px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:823px;top:426px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:838px;top:371px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:795px;top:384px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:809px;top:371px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:897px;top:355px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:731px;top:384px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:745px;top:371px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:507px;top:272px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BEEPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:709px;top:371px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:695px;top:384px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:565px;top:299px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:897px;top:191px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:695px;top:175px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:538px;top:236px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>COOLANT HIGH <br>TEMPERATURE <br>WARNING <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:584px;top:236px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>COOLANT LOW <br>TEMPERATURE <br>INDICATOR <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:631px;top:236px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LOW FUEL <br>INDICATOR <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:667px;top:236px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IMMOBILIZER <br>INDICATOR <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:709px;top:236px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CHARGING <br>SYSTEM <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:774px;top:236px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ABS <br>INDICATOR <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:809px;top:236px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRAKE <br>SYSTEM <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:890px;top:212px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>POWER <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:855px;top:227px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:499px;top:322px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.8 (15A) FUSE <br>(In the under−hood <br>fuse/relay box)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:591px;top:422px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ACTIVATION <br>INDICATOR <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:645px;top:422px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IMMOBILIZER <br>CONTROL <br>UNIT−RECEIVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:689px;top:428px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:738px;top:426px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ABS MODULATOR−CONTROL <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:845px;top:454px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRAKE FLUID <br>LEVEL <br>SWITCH <br>(Closed : <br>Float down)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:902px;top:454px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PARKING <br>BRAKE <br>SWITCH <br>(Closed : <br>Lever up)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:694px;top:422px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ALTERNATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:694px;top:428px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>NAVIGATION <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:181px;top:203px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:155px;top:543px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:324px;top:292px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:56px;top:471px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:22px;top:434px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:51px;top:434px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:310px;top:153px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:301px;top:138px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:270px;top:109px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:156px;top:137px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:156px;top:109px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:150px;top:75px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:128px;top:137px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:233px;top:249px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>POWER CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:287px;top:395px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:300px;top:425px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:300px;top:478px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:291px;top:530px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:293px;top:491px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:85px;top:434px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:100px;top:446px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:143px;top:446px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:114px;top:491px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:112px;top:530px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:122px;top:478px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:129px;top:434px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:138px;top:410px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:343px;top:142px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:357px;top:175px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:422px;top:371px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:414px;top:394px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:412px;top:530px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:409px;top:299px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:227px;top:394px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:236px;top:371px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:186px;top:371px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:171px;top:395px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:221px;top:138px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:195px;top:436px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:154px;top:299px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:102px;top:23px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.3 (50A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:164px;top:175px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:51px;top:395px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:300px;top:371px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:25px;top:175px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:236px;top:175px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:279px;top:175px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:64px;top:371px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:78px;top:281px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:123px;top:239px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FUEL GAUGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:79px;top:239px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TACHOMETER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:270px;top:138px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:149px;top:53px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:197px;top:37px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:187px;top:25px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:229px;top:31px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:155px;top:31px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:101px;top:45px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.8 (15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:54px;top:11px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:23px;top:18px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:178px;top:11px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:59px;top:23px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.1 (80A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:281px;top:66px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:281px;top:60px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:35px;top:239px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SPEEDOMETER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:307px;top:58px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY <br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:334px;top:95px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.9 (10A) FUSE <br>(In the under−hood <br>fuse/relay box)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:118px;top:161px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TEST <br>TACHOMETER <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:296px;top:168px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>VEHICLE SPEED <br>SENSOR (VSS)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:172px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RELAY <br>DRIVING<br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:171px;top:246px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ODO/TRIP <br>DISPLAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:173px;top:277px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVE <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:307px;top:243px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ODO/TRIP/LDC BACK <br>LIGHT STABLIZING <br>POWER CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:397px;top:210px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LIGHTS−ON <br>REMINDER CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:390px;top:247px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LCD <br>BACK <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:429px;top:251px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BACK <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:390px;top:321px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TRIP/<br>RESET <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:307px;top:308px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:121px;top:388px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.3 (7.5A) FUSE <br>(In the under−dash <br>fuse/relay box)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:18px;top:471px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>NAVIGATION <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:100px;top:460px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>VEHICLE SPEED <br>SENSOR (VSS)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:307px;top:447px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FUEL <br>GAUGE <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:332px;top:443px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FUEL <br>GAUGE <br>SENDING <br>UNIT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}