with(document) {
write("<v:group id=\"group6\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect6\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img6\" src=\"../img/SAA4EFAA20300000000DBAD37.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p6_1\" class=\"drag\" style=\"position:absolute;left:22px;top:64px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3P CONNECTOR (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" class=\"drag\" style=\"position:absolute;left:175px;top:54px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P CONNECTOR<br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" class=\"drag\" style=\"position:absolute;left:410px;top:63px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GAUGE B (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" class=\"drag\" style=\"position:absolute;left:714px;top:63px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GAUGE A (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" class=\"drag\" style=\"position:absolute;left:58px;top:185px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGNITION SWITCH<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" class=\"drag\" style=\"position:absolute;left:215px;top:185px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SERVICE CHECK<br>CONNECTOR (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" class=\"drag\" style=\"position:absolute;left:384px;top:185px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR (7)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" class=\"drag\" style=\"position:absolute;left:610px;top:185px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SECONDARY HO2S<br>(SENSOR 2) (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" class=\"drag\" style=\"position:absolute;left:778px;top:196px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FUEL PUMP (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" class=\"drag\" style=\"position:absolute;left:225px;top:319px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION SWITCH<br>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" class=\"drag\" style=\"position:absolute;left:715px;top:330px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" class=\"drag\" style=\"position:absolute;left:110px;top:476px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (15)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" class=\"drag\" style=\"position:absolute;left:317px;top:476px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (16)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" class=\"drag\" style=\"position:absolute;left:525px;top:476px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (17)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" class=\"drag\" style=\"position:absolute;left:380px;top:322px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PGM-FI MAIN<br>RELAY 1 (12)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" class=\"drag\" style=\"position:absolute;left:519px;top:322px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PGM-FI MAIN<br>RELAY 2 (13)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" class=\"drag\" style=\"position:absolute;left:115px;top:605px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX (19)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" class=\"drag\" style=\"position:absolute;left:309px;top:605px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX (20)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" class=\"drag\" style=\"position:absolute;left:543px;top:627px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P CONNECTOR (21)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_20\" class=\"drag\" style=\"position:absolute;left:765px;top:601px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECM CONNECTOR<br>No. 1 (9P) (22)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_21\" class=\"drag\" style=\"position:absolute;left:52px;top:331px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12P JUNCTION<br>CONNECTOR (10)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_22\" class=\"drag\" style=\"position:absolute;left:105px;top:734px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECM CONNECTOR<br>No. 3 (52P) (23)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_23\" class=\"drag\" style=\"position:absolute;left:614px;top:734px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECM CONNECTOR<br>No. 5 (9P) (25)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_24\" class=\"drag\" style=\"position:absolute;left:772px;top:734px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INERTIA SWITCH<br>(26)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_25\" class=\"drag\" style=\"position:absolute;left:393px;top:733px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECM CONNECTOR<br>No. 4 (40P) (24)<sup>**</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_26\" class=\"drag\" style=\"position:absolute;left:771px;top:465px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX (18)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_27\" class=\"drag\" style=\"position:absolute;left:0px;top:928px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>**: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}