with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:783px;\" coordsize=\"950,783\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:783px;\">");
write("<img id=\"img1\" src=\"../img/SAA4E60F00000057111LAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:783px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:16px;top:95px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MOUNTING CUSHION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:203px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEAT GUARD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:401px;top:213px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:207px;top:198px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>9.8 N·m<br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:623px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PINION SHAFT GROMMET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:537px;top:259px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RACK GUIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:590px;top:199px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:621px;top:129px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DISC WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:684px;top:155px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:741px;top:180px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RACK GUIDE SCREW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:856px;top:294px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCKNUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:885px;top:453px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:692px;top:453px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:759px;top:512px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20 N·m<br>(2.0 kgf·m, 14 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:199px;top:371px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MOUNTING CUSHION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:63px;top:589px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCK WASHER<br></b>Replace<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:197px;top:631px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RACK END<br>83 N·m (8.5 kgf·m, 61 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:362px;top:715px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BOOT BAND<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:464px;top:752px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BOOT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:588px;top:752px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TIE-ROD CLIP<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}