with(document) {
write("<v:group id=\"group34\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect34\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img34\" src=\"../img/SAA4EF0A20300000000DBAD81.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p34_1\" class=\"drag\" style=\"position:absolute;left:177px;top:1069px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>* : Terminal side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p34_2\" class=\"drag\" style=\"position:absolute;left:107px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p34_3\" class=\"drag\" style=\"position:absolute;left:162px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p34_4\" class=\"drag\" style=\"position:absolute;left:162px;top:1036px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p34_5\" class=\"drag\" style=\"position:absolute;left:162px;top:1050px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p34_6\" class=\"drag\" style=\"position:absolute;left:178px;top:1036px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with female terminals (single outline): View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p34_7\" class=\"drag\" style=\"position:absolute;left:178px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with male terminals (double outline): View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p34_8\" class=\"drag\" style=\"position:absolute;left:198px;top:1050px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to ECM/PCM control.<br></b></nobr>");
write("</p>");
write("<p id=\"p34_9\" class=\"drag\" style=\"position:absolute;left:655px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p34_10\" class=\"drag\" style=\"position:absolute;left:731px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p34_11\" class=\"drag\" style=\"position:absolute;left:714px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p34_12\" class=\"drag\" style=\"position:absolute;left:715px;top:495px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p34_13\" class=\"drag\" style=\"position:absolute;left:715px;top:481px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p34_14\" class=\"drag\" style=\"position:absolute;left:631px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p34_15\" class=\"drag\" style=\"position:absolute;left:655px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p34_16\" class=\"drag\" style=\"position:absolute;left:741px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p34_17\" class=\"drag\" style=\"position:absolute;left:741px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p34_18\" class=\"drag\" style=\"position:absolute;left:631px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p34_19\" class=\"drag\" style=\"position:absolute;left:655px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p34_20\" class=\"drag\" style=\"position:absolute;left:631px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p34_21\" class=\"drag\" style=\"position:absolute;left:655px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p34_22\" class=\"drag\" style=\"position:absolute;left:631px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p34_23\" class=\"drag\" style=\"position:absolute;left:631px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p34_24\" class=\"drag\" style=\"position:absolute;left:655px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p34_25\" class=\"drag\" style=\"position:absolute;left:717px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p34_26\" class=\"drag\" style=\"position:absolute;left:631px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p34_27\" class=\"drag\" style=\"position:absolute;left:655px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p34_28\" class=\"drag\" style=\"position:absolute;left:741px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p34_29\" class=\"drag\" style=\"position:absolute;left:741px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p34_30\" class=\"drag\" style=\"position:absolute;left:741px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p34_31\" class=\"drag\" style=\"position:absolute;left:751px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p34_32\" class=\"drag\" style=\"position:absolute;left:769px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p34_33\" class=\"drag\" style=\"position:absolute;left:753px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p34_34\" class=\"drag\" style=\"position:absolute;left:710px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p34_35\" class=\"drag\" style=\"position:absolute;left:691px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p34_36\" class=\"drag\" style=\"position:absolute;left:653px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p34_37\" class=\"drag\" style=\"position:absolute;left:634px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p34_38\" class=\"drag\" style=\"position:absolute;left:634px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p34_39\" class=\"drag\" style=\"position:absolute;left:675px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p34_40\" class=\"drag\" style=\"position:absolute;left:675px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p34_41\" class=\"drag\" style=\"position:absolute;left:620px;top:311px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C306<br></b></nobr>");
write("</p>");
write("<p id=\"p34_42\" class=\"drag\" style=\"position:absolute;left:728px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p34_43\" class=\"drag\" style=\"position:absolute;left:717px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p34_44\" class=\"drag\" style=\"position:absolute;left:714px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p34_45\" class=\"drag\" style=\"position:absolute;left:714px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p34_46\" class=\"drag\" style=\"position:absolute;left:631px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p34_47\" class=\"drag\" style=\"position:absolute;left:741px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p34_48\" class=\"drag\" style=\"position:absolute;left:119px;top:311px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C218<br></b></nobr>");
write("</p>");
write("<p id=\"p34_49\" class=\"drag\" style=\"position:absolute;left:150px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p34_50\" class=\"drag\" style=\"position:absolute;left:169px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p34_51\" class=\"drag\" style=\"position:absolute;left:169px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p34_52\" class=\"drag\" style=\"position:absolute;left:150px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p34_53\" class=\"drag\" style=\"position:absolute;left:131px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p34_54\" class=\"drag\" style=\"position:absolute;left:155px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p34_55\" class=\"drag\" style=\"position:absolute;left:155px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p34_56\" class=\"drag\" style=\"position:absolute;left:131px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p34_57\" class=\"drag\" style=\"position:absolute;left:131px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p34_58\" class=\"drag\" style=\"position:absolute;left:155px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p34_59\" class=\"drag\" style=\"position:absolute;left:155px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p34_60\" class=\"drag\" style=\"position:absolute;left:131px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p34_61\" class=\"drag\" style=\"position:absolute;left:374px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p34_62\" class=\"drag\" style=\"position:absolute;left:398px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p34_63\" class=\"drag\" style=\"position:absolute;left:398px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p34_64\" class=\"drag\" style=\"position:absolute;left:374px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p34_65\" class=\"drag\" style=\"position:absolute;left:374px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p34_66\" class=\"drag\" style=\"position:absolute;left:398px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p34_67\" class=\"drag\" style=\"position:absolute;left:421px;top:363px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p34_68\" class=\"drag\" style=\"position:absolute;left:403px;top:363px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p34_69\" class=\"drag\" style=\"position:absolute;left:384px;top:362px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p34_70\" class=\"drag\" style=\"position:absolute;left:362px;top:311px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C305<br></b></nobr>");
write("</p>");
write("<p id=\"p34_71\" class=\"drag\" style=\"position:absolute;left:150px;top:23px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p34_72\" class=\"drag\" style=\"position:absolute;left:215px;top:166px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p34_73\" class=\"drag\" style=\"position:absolute;left:241px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p34_74\" class=\"drag\" style=\"position:absolute;left:191px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p34_75\" class=\"drag\" style=\"position:absolute;left:241px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p34_76\" class=\"drag\" style=\"position:absolute;left:138px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p34_77\" class=\"drag\" style=\"position:absolute;left:691px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C217<br></b></nobr>");
write("</p>");
write("<p id=\"p34_78\" class=\"drag\" style=\"position:absolute;left:712px;top:61px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p34_79\" class=\"drag\" style=\"position:absolute;left:730px;top:61px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p34_80\" class=\"drag\" style=\"position:absolute;left:722px;top:80px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p34_81\" class=\"drag\" style=\"position:absolute;left:740px;top:80px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p34_82\" class=\"drag\" style=\"position:absolute;left:703px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p34_83\" class=\"drag\" style=\"position:absolute;left:703px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p34_84\" class=\"drag\" style=\"position:absolute;left:703px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p34_85\" class=\"drag\" style=\"position:absolute;left:703px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p34_86\" class=\"drag\" style=\"position:absolute;left:703px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p34_87\" class=\"drag\" style=\"position:absolute;left:727px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p34_88\" class=\"drag\" style=\"position:absolute;left:727px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p34_89\" class=\"drag\" style=\"position:absolute;left:727px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p34_90\" class=\"drag\" style=\"position:absolute;left:727px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p34_91\" class=\"drag\" style=\"position:absolute;left:452px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p34_92\" class=\"drag\" style=\"position:absolute;left:482px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p34_93\" class=\"drag\" style=\"position:absolute;left:427px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C209<br></b></nobr>");
write("</p>");
write("<p id=\"p34_94\" class=\"drag\" style=\"position:absolute;left:438px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p34_95\" class=\"drag\" style=\"position:absolute;left:462px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p34_96\" class=\"drag\" style=\"position:absolute;left:438px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p34_97\" class=\"drag\" style=\"position:absolute;left:438px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p34_98\" class=\"drag\" style=\"position:absolute;left:462px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p34_99\" class=\"drag\" style=\"position:absolute;left:438px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p34_100\" class=\"drag\" style=\"position:absolute;left:119px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C204<br></b></nobr>");
write("</p>");
write("<p id=\"p34_101\" class=\"drag\" style=\"position:absolute;left:155px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p34_102\" class=\"drag\" style=\"position:absolute;left:155px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p34_103\" class=\"drag\" style=\"position:absolute;left:131px;top:208px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p34_104\" class=\"drag\" style=\"position:absolute;left:214px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p34_105\" class=\"drag\" style=\"position:absolute;left:131px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p34_106\" class=\"drag\" style=\"position:absolute;left:131px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p34_107\" class=\"drag\" style=\"position:absolute;left:131px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p34_108\" class=\"drag\" style=\"position:absolute;left:131px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p34_109\" class=\"drag\" style=\"position:absolute;left:131px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p34_110\" class=\"drag\" style=\"position:absolute;left:131px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p34_111\" class=\"drag\" style=\"position:absolute;left:155px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p34_112\" class=\"drag\" style=\"position:absolute;left:217px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p34_113\" class=\"drag\" style=\"position:absolute;left:131px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p34_114\" class=\"drag\" style=\"position:absolute;left:241px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p34_115\" class=\"drag\" style=\"position:absolute;left:215px;top:224px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p34_116\" class=\"drag\" style=\"position:absolute;left:241px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p34_117\" class=\"drag\" style=\"position:absolute;left:214px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p34_118\" class=\"drag\" style=\"position:absolute;left:214px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p34_119\" class=\"drag\" style=\"position:absolute;left:214px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p34_120\" class=\"drag\" style=\"position:absolute;left:214px;top:208px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p34_121\" class=\"drag\" style=\"position:absolute;left:249px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p34_122\" class=\"drag\" style=\"position:absolute;left:212px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p34_123\" class=\"drag\" style=\"position:absolute;left:194px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p34_124\" class=\"drag\" style=\"position:absolute;left:228px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p34_125\" class=\"drag\" style=\"position:absolute;left:265px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}