with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:959px;\" coordsize=\"950,959\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:959px;\">");
write("<img id=\"img1\" src=\"../img/SAA4E64J46643400000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:959px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:222px;top:165px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT REAR DOOR SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:471px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PASSENGER'S SUPER LOCKING*<sup>1</sup><br>ACTUATOR/KNOB SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:471px;top:47px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PASSENGER'S DOOR LOCK ACTUATOR*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:548px;top:87px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PASSENGER'S KEY CYLINDER SWITCH*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:627px;top:135px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PASSENGER'S DOOR SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:704px;top:182px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVER'S KEY <br>CYLINDER SWITCH*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:3px;top:213px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILL DOOR LOCK ACTUATOR <br>(KU, KQ model)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:748px;top:531px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER WINDOW <br>MASTER SWITCH<br>(Has built-in driver's <br>door lock switch)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:655px;top:605px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVER'S SUPER LOCKING<br>ACTUATOR/KNOB SWITCH*<sup>1</sup><br>DRIVER'S DOOR LOCK<br>ACTUATOR/KNOB SWITCH*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:576px;top:682px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVER'S DOOR SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:517px;top:716px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT REAR SUPER LOCKING ACTUATOR/<br>KNOB SWITCH*<sup>1</sup><br>RIGHT REAR DOOR LOCK ACTUATOR*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:437px;top:779px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT REAR DOOR SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:263px;top:858px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT REAR SUPER LOCKING ACTUATOR/KNOB SWITCH*<sup>1</sup><br>LEFT REAR DOOR LOCKING ACTUATOR*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:16px;top:897px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILGATE LATCH SWITCH<br>TAILGATE LOCK ACTUATOR<br>TAILGATE LOCK KNOB SWITCH*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:138px;top:795px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILGATE KEY <br>CYLINDER SWITCH*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:16px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1: KE model<br>*2: Except KE model<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}