with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:475px; height:385px;\" coordsize=\"475,385\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:475px;height:385px;\">");
write("<img id=\"img2\" src=\"../img/SAA4EP0K72200081160FAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:385px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:119px;top:13px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>TORQUE SENSOR 7P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:136px;top:355px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:318px;top:104px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of<br>female terminals<br></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:253px;top:210px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>EPS CONTROL UNIT<br>CONNECTOR B (14P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:41px;top:326px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>T/S GND (WHT)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:209px;top:306px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>VT3 (BLU)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:65px;top:301px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>VT6 (YEL)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:160px;top:145px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Vcc2 (RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:267px;top:145px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Vcc1 (BRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:57px;top:65px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>VT6 (YEL)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:16px;top:40px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>T/S GND (WHT)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:234px;top:65px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>VT3 (BLU)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:164px;top:208px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Vcc2<br>(RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:69px;top:210px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Vcc1<br>(BRN)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}