with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:319px;\" coordsize=\"950,319\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:319px;\">");
write("<img id=\"img1\" src=\"../img/SAA5ET0J22100000000BBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:319px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:292px;top:286px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2 sec.~5 sec.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:454px;top:286px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5 sec.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:609px;top:252px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Move to self-diagnosis mode.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:163px;top:53px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:163px;top:140px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:163px;top:226px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:29px;top:37px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Ignition<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:29px;top:75px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:29px;top:121px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Lighting<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:29px;top:159px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:29px;top:203px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Trip/Reset<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:29px;top:243px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:163px;top:13px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON (II)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:163px;top:100px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:163px;top:185px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}