with(document) {
write("<v:group id=\"group5\" class=\"drag\" style=\"position:relative; width:950px; height:751px;\" coordsize=\"950,751\">");
write("<v:rect id=\"rect5\"class=\"drag\"  style=\"width:950px;height:751px;\">");
write("<img id=\"img5\" src=\"../img/SAA5EGAA20300000000DBAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:751px;border-color:#ffffff\">");
write("<p id=\"p5_1\" class=\"drag\" style=\"position:absolute;left:64px;top:183px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE <br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" class=\"drag\" style=\"position:absolute;left:149px;top:136px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C135<br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" class=\"drag\" style=\"position:absolute;left:212px;top:96px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C134<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" class=\"drag\" style=\"position:absolute;left:284px;top:63px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C126<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" class=\"drag\" style=\"position:absolute;left:371px;top:34px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C133<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" class=\"drag\" style=\"position:absolute;left:448px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C132<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" class=\"drag\" style=\"position:absolute;left:521px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C124<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" class=\"drag\" style=\"position:absolute;left:819px;top:538px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C123<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" class=\"drag\" style=\"position:absolute;left:788px;top:586px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C125<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" class=\"drag\" style=\"position:absolute;left:737px;top:623px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C121<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" class=\"drag\" style=\"position:absolute;left:687px;top:652px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C127<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" class=\"drag\" style=\"position:absolute;left:623px;top:673px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C122<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" class=\"drag\" style=\"position:absolute;left:556px;top:709px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C128<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" class=\"drag\" style=\"position:absolute;left:483px;top:715px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C129<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" class=\"drag\" style=\"position:absolute;left:417px;top:715px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C130<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" class=\"drag\" style=\"position:absolute;left:357px;top:715px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C131<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" class=\"drag\" style=\"position:absolute;left:276px;top:710px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C136<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}