with(document) {
write("<v:group id=\"group8\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect8\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img8\" src=\"../img/SAA5EGAA20300000000DBAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p8_1\" class=\"drag\" style=\"position:absolute;left:65px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p8_2\" class=\"drag\" style=\"position:absolute;left:120px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p8_3\" class=\"drag\" style=\"position:absolute;left:120px;top:1036px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p8_4\" class=\"drag\" style=\"position:absolute;left:120px;top:1050px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p8_5\" class=\"drag\" style=\"position:absolute;left:135px;top:1036px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with female terminals (single outline): View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p8_6\" class=\"drag\" style=\"position:absolute;left:135px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with male terminals (double outline): View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p8_7\" class=\"drag\" style=\"position:absolute;left:152px;top:1050px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to PCM control.<br></b></nobr>");
write("</p>");
write("<p id=\"p8_8\" class=\"drag\" style=\"position:absolute;left:813px;top:537px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_9\" class=\"drag\" style=\"position:absolute;left:813px;top:523px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_10\" class=\"drag\" style=\"position:absolute;left:813px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_11\" class=\"drag\" style=\"position:absolute;left:813px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_12\" class=\"drag\" style=\"position:absolute;left:813px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_13\" class=\"drag\" style=\"position:absolute;left:813px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_14\" class=\"drag\" style=\"position:absolute;left:813px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_15\" class=\"drag\" style=\"position:absolute;left:701px;top:538px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p8_16\" class=\"drag\" style=\"position:absolute;left:691px;top:311px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C266<br></b></nobr>");
write("</p>");
write("<p id=\"p8_17\" class=\"drag\" style=\"position:absolute;left:703px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_18\" class=\"drag\" style=\"position:absolute;left:703px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_19\" class=\"drag\" style=\"position:absolute;left:703px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_20\" class=\"drag\" style=\"position:absolute;left:703px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_21\" class=\"drag\" style=\"position:absolute;left:703px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_22\" class=\"drag\" style=\"position:absolute;left:703px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_23\" class=\"drag\" style=\"position:absolute;left:703px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_24\" class=\"drag\" style=\"position:absolute;left:786px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_25\" class=\"drag\" style=\"position:absolute;left:786px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_26\" class=\"drag\" style=\"position:absolute;left:813px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_27\" class=\"drag\" style=\"position:absolute;left:786px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p8_28\" class=\"drag\" style=\"position:absolute;left:786px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p8_29\" class=\"drag\" style=\"position:absolute;left:727px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_30\" class=\"drag\" style=\"position:absolute;left:727px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_31\" class=\"drag\" style=\"position:absolute;left:727px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_32\" class=\"drag\" style=\"position:absolute;left:786px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p8_33\" class=\"drag\" style=\"position:absolute;left:727px;top:509px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_34\" class=\"drag\" style=\"position:absolute;left:703px;top:509px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_35\" class=\"drag\" style=\"position:absolute;left:786px;top:509px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p8_36\" class=\"drag\" style=\"position:absolute;left:813px;top:509px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_37\" class=\"drag\" style=\"position:absolute;left:727px;top:523px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_38\" class=\"drag\" style=\"position:absolute;left:703px;top:523px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_39\" class=\"drag\" style=\"position:absolute;left:786px;top:523px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p8_40\" class=\"drag\" style=\"position:absolute;left:727px;top:537px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_41\" class=\"drag\" style=\"position:absolute;left:786px;top:537px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p8_42\" class=\"drag\" style=\"position:absolute;left:786px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p8_43\" class=\"drag\" style=\"position:absolute;left:786px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p8_44\" class=\"drag\" style=\"position:absolute;left:727px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_45\" class=\"drag\" style=\"position:absolute;left:727px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_46\" class=\"drag\" style=\"position:absolute;left:715px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_47\" class=\"drag\" style=\"position:absolute;left:696px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_48\" class=\"drag\" style=\"position:absolute;left:789px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p8_49\" class=\"drag\" style=\"position:absolute;left:733px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p8_50\" class=\"drag\" style=\"position:absolute;left:770px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p8_51\" class=\"drag\" style=\"position:absolute;left:773px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_52\" class=\"drag\" style=\"position:absolute;left:754px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_53\" class=\"drag\" style=\"position:absolute;left:751px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p8_54\" class=\"drag\" style=\"position:absolute;left:736px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_55\" class=\"drag\" style=\"position:absolute;left:829px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_56\" class=\"drag\" style=\"position:absolute;left:826px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p8_57\" class=\"drag\" style=\"position:absolute;left:847px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_58\" class=\"drag\" style=\"position:absolute;left:845px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p8_59\" class=\"drag\" style=\"position:absolute;left:863px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p8_60\" class=\"drag\" style=\"position:absolute;left:863px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p8_61\" class=\"drag\" style=\"position:absolute;left:699px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_62\" class=\"drag\" style=\"position:absolute;left:717px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_63\" class=\"drag\" style=\"position:absolute;left:557px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_64\" class=\"drag\" style=\"position:absolute;left:557px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_65\" class=\"drag\" style=\"position:absolute;left:584px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_66\" class=\"drag\" style=\"position:absolute;left:484px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_67\" class=\"drag\" style=\"position:absolute;left:484px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_68\" class=\"drag\" style=\"position:absolute;left:557px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p8_69\" class=\"drag\" style=\"position:absolute;left:557px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p8_70\" class=\"drag\" style=\"position:absolute;left:584px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_71\" class=\"drag\" style=\"position:absolute;left:584px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_72\" class=\"drag\" style=\"position:absolute;left:584px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_73\" class=\"drag\" style=\"position:absolute;left:560px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_74\" class=\"drag\" style=\"position:absolute;left:560px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_75\" class=\"drag\" style=\"position:absolute;left:460px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_76\" class=\"drag\" style=\"position:absolute;left:460px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_77\" class=\"drag\" style=\"position:absolute;left:460px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_78\" class=\"drag\" style=\"position:absolute;left:460px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_79\" class=\"drag\" style=\"position:absolute;left:484px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_80\" class=\"drag\" style=\"position:absolute;left:484px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_81\" class=\"drag\" style=\"position:absolute;left:460px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_82\" class=\"drag\" style=\"position:absolute;left:460px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_83\" class=\"drag\" style=\"position:absolute;left:460px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_84\" class=\"drag\" style=\"position:absolute;left:484px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_85\" class=\"drag\" style=\"position:absolute;left:571px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_86\" class=\"drag\" style=\"position:absolute;left:574px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_87\" class=\"drag\" style=\"position:absolute;left:499px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_88\" class=\"drag\" style=\"position:absolute;left:499px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_89\" class=\"drag\" style=\"position:absolute;left:481px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_90\" class=\"drag\" style=\"position:absolute;left:462px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_91\" class=\"drag\" style=\"position:absolute;left:462px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_92\" class=\"drag\" style=\"position:absolute;left:553px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_93\" class=\"drag\" style=\"position:absolute;left:518px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_94\" class=\"drag\" style=\"position:absolute;left:448px;top:311px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C251<br></b></nobr>");
write("</p>");
write("<p id=\"p8_95\" class=\"drag\" style=\"position:absolute;left:127px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_96\" class=\"drag\" style=\"position:absolute;left:127px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_97\" class=\"drag\" style=\"position:absolute;left:134px;top:352px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_98\" class=\"drag\" style=\"position:absolute;left:115px;top:352px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_99\" class=\"drag\" style=\"position:absolute;left:598px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_100\" class=\"drag\" style=\"position:absolute;left:598px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_101\" class=\"drag\" style=\"position:absolute;left:657px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p8_102\" class=\"drag\" style=\"position:absolute;left:657px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p8_103\" class=\"drag\" style=\"position:absolute;left:684px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_104\" class=\"drag\" style=\"position:absolute;left:657px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p8_105\" class=\"drag\" style=\"position:absolute;left:571px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p8_106\" class=\"drag\" style=\"position:absolute;left:598px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_107\" class=\"drag\" style=\"position:absolute;left:684px;top:237px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_108\" class=\"drag\" style=\"position:absolute;left:657px;top:237px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p8_109\" class=\"drag\" style=\"position:absolute;left:574px;top:237px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_110\" class=\"drag\" style=\"position:absolute;left:598px;top:237px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_111\" class=\"drag\" style=\"position:absolute;left:684px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_112\" class=\"drag\" style=\"position:absolute;left:657px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p8_113\" class=\"drag\" style=\"position:absolute;left:574px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_114\" class=\"drag\" style=\"position:absolute;left:598px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_115\" class=\"drag\" style=\"position:absolute;left:657px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p8_116\" class=\"drag\" style=\"position:absolute;left:584px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_117\" class=\"drag\" style=\"position:absolute;left:566px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_118\" class=\"drag\" style=\"position:absolute;left:730px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p8_119\" class=\"drag\" style=\"position:absolute;left:730px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p8_120\" class=\"drag\" style=\"position:absolute;left:712px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p8_121\" class=\"drag\" style=\"position:absolute;left:714px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_122\" class=\"drag\" style=\"position:absolute;left:693px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p8_123\" class=\"drag\" style=\"position:absolute;left:696px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_124\" class=\"drag\" style=\"position:absolute;left:77px;top:311px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C208<br></b></nobr>");
write("</p>");
write("<p id=\"p8_125\" class=\"drag\" style=\"position:absolute;left:134px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_126\" class=\"drag\" style=\"position:absolute;left:115px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_127\" class=\"drag\" style=\"position:absolute;left:103px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_128\" class=\"drag\" style=\"position:absolute;left:103px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_129\" class=\"drag\" style=\"position:absolute;left:103px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_130\" class=\"drag\" style=\"position:absolute;left:127px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_131\" class=\"drag\" style=\"position:absolute;left:127px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_132\" class=\"drag\" style=\"position:absolute;left:103px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_133\" class=\"drag\" style=\"position:absolute;left:208px;top:352px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_134\" class=\"drag\" style=\"position:absolute;left:206px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p8_135\" class=\"drag\" style=\"position:absolute;left:224px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p8_136\" class=\"drag\" style=\"position:absolute;left:103px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_137\" class=\"drag\" style=\"position:absolute;left:103px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_138\" class=\"drag\" style=\"position:absolute;left:103px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_139\" class=\"drag\" style=\"position:absolute;left:188px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_140\" class=\"drag\" style=\"position:absolute;left:188px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_141\" class=\"drag\" style=\"position:absolute;left:186px;top:467px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_142\" class=\"drag\" style=\"position:absolute;left:212px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_143\" class=\"drag\" style=\"position:absolute;left:212px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_144\" class=\"drag\" style=\"position:absolute;left:212px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_145\" class=\"drag\" style=\"position:absolute;left:212px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_146\" class=\"drag\" style=\"position:absolute;left:150px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p8_147\" class=\"drag\" style=\"position:absolute;left:187px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_148\" class=\"drag\" style=\"position:absolute;left:227px;top:352px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_149\" class=\"drag\" style=\"position:absolute;left:185px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p8_150\" class=\"drag\" style=\"position:absolute;left:186px;top:495px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p8_151\" class=\"drag\" style=\"position:absolute;left:212px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_152\" class=\"drag\" style=\"position:absolute;left:185px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p8_153\" class=\"drag\" style=\"position:absolute;left:212px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_154\" class=\"drag\" style=\"position:absolute;left:190px;top:352px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_155\" class=\"drag\" style=\"position:absolute;left:171px;top:352px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_156\" class=\"drag\" style=\"position:absolute;left:168px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_157\" class=\"drag\" style=\"position:absolute;left:153px;top:352px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_158\" class=\"drag\" style=\"position:absolute;left:127px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_159\" class=\"drag\" style=\"position:absolute;left:127px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_160\" class=\"drag\" style=\"position:absolute;left:127px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_161\" class=\"drag\" style=\"position:absolute;left:186px;top:452px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_162\" class=\"drag\" style=\"position:absolute;left:212px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_163\" class=\"drag\" style=\"position:absolute;left:398px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_164\" class=\"drag\" style=\"position:absolute;left:198px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_165\" class=\"drag\" style=\"position:absolute;left:198px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_166\" class=\"drag\" style=\"position:absolute;left:112px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_167\" class=\"drag\" style=\"position:absolute;left:272px;top:167px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p8_168\" class=\"drag\" style=\"position:absolute;left:172px;top:224px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p8_169\" class=\"drag\" style=\"position:absolute;left:172px;top:195px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p8_170\" class=\"drag\" style=\"position:absolute;left:109px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p8_171\" class=\"drag\" style=\"position:absolute;left:90px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p8_172\" class=\"drag\" style=\"position:absolute;left:128px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p8_173\" class=\"drag\" style=\"position:absolute;left:84px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_174\" class=\"drag\" style=\"position:absolute;left:102px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_175\" class=\"drag\" style=\"position:absolute;left:415px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p8_176\" class=\"drag\" style=\"position:absolute;left:434px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p8_177\" class=\"drag\" style=\"position:absolute;left:378px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p8_178\" class=\"drag\" style=\"position:absolute;left:397px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p8_179\" class=\"drag\" style=\"position:absolute;left:443px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p8_180\" class=\"drag\" style=\"position:absolute;left:425px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p8_181\" class=\"drag\" style=\"position:absolute;left:350px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p8_182\" class=\"drag\" style=\"position:absolute;left:369px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p8_183\" class=\"drag\" style=\"position:absolute;left:332px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p8_184\" class=\"drag\" style=\"position:absolute;left:323px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p8_185\" class=\"drag\" style=\"position:absolute;left:360px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p8_186\" class=\"drag\" style=\"position:absolute;left:341px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p8_187\" class=\"drag\" style=\"position:absolute;left:267px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_188\" class=\"drag\" style=\"position:absolute;left:232px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_189\" class=\"drag\" style=\"position:absolute;left:248px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p8_190\" class=\"drag\" style=\"position:absolute;left:258px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p8_191\" class=\"drag\" style=\"position:absolute;left:276px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p8_192\" class=\"drag\" style=\"position:absolute;left:202px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p8_193\" class=\"drag\" style=\"position:absolute;left:183px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p8_194\" class=\"drag\" style=\"position:absolute;left:176px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_195\" class=\"drag\" style=\"position:absolute;left:158px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_196\" class=\"drag\" style=\"position:absolute;left:214px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_197\" class=\"drag\" style=\"position:absolute;left:195px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_198\" class=\"drag\" style=\"position:absolute;left:139px;top:65px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_199\" class=\"drag\" style=\"position:absolute;left:146px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p8_200\" class=\"drag\" style=\"position:absolute;left:398px;top:237px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_201\" class=\"drag\" style=\"position:absolute;left:398px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_202\" class=\"drag\" style=\"position:absolute;left:398px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_203\" class=\"drag\" style=\"position:absolute;left:398px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_204\" class=\"drag\" style=\"position:absolute;left:371px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p8_205\" class=\"drag\" style=\"position:absolute;left:371px;top:237px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p8_206\" class=\"drag\" style=\"position:absolute;left:371px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p8_207\" class=\"drag\" style=\"position:absolute;left:371px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p8_208\" class=\"drag\" style=\"position:absolute;left:371px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p8_209\" class=\"drag\" style=\"position:absolute;left:371px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>38<br></b></nobr>");
write("</p>");
write("<p id=\"p8_210\" class=\"drag\" style=\"position:absolute;left:371px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p8_211\" class=\"drag\" style=\"position:absolute;left:371px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p8_212\" class=\"drag\" style=\"position:absolute;left:398px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_213\" class=\"drag\" style=\"position:absolute;left:371px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p8_214\" class=\"drag\" style=\"position:absolute;left:371px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p8_215\" class=\"drag\" style=\"position:absolute;left:271px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p8_216\" class=\"drag\" style=\"position:absolute;left:271px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p8_217\" class=\"drag\" style=\"position:absolute;left:298px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_218\" class=\"drag\" style=\"position:absolute;left:271px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p8_219\" class=\"drag\" style=\"position:absolute;left:271px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p8_220\" class=\"drag\" style=\"position:absolute;left:271px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p8_221\" class=\"drag\" style=\"position:absolute;left:271px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p8_222\" class=\"drag\" style=\"position:absolute;left:271px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p8_223\" class=\"drag\" style=\"position:absolute;left:271px;top:237px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p8_224\" class=\"drag\" style=\"position:absolute;left:271px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p8_225\" class=\"drag\" style=\"position:absolute;left:298px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_226\" class=\"drag\" style=\"position:absolute;left:298px;top:152px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_227\" class=\"drag\" style=\"position:absolute;left:298px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_228\" class=\"drag\" style=\"position:absolute;left:298px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_229\" class=\"drag\" style=\"position:absolute;left:298px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_230\" class=\"drag\" style=\"position:absolute;left:298px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_231\" class=\"drag\" style=\"position:absolute;left:684px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_232\" class=\"drag\" style=\"position:absolute;left:598px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_233\" class=\"drag\" style=\"position:absolute;left:598px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_234\" class=\"drag\" style=\"position:absolute;left:598px;top:152px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_235\" class=\"drag\" style=\"position:absolute;left:603px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_236\" class=\"drag\" style=\"position:absolute;left:618px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p8_237\" class=\"drag\" style=\"position:absolute;left:621px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_238\" class=\"drag\" style=\"position:absolute;left:640px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_239\" class=\"drag\" style=\"position:absolute;left:684px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_240\" class=\"drag\" style=\"position:absolute;left:657px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p8_241\" class=\"drag\" style=\"position:absolute;left:684px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_242\" class=\"drag\" style=\"position:absolute;left:657px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p8_243\" class=\"drag\" style=\"position:absolute;left:677px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_244\" class=\"drag\" style=\"position:absolute;left:637px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p8_245\" class=\"drag\" style=\"position:absolute;left:600px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p8_246\" class=\"drag\" style=\"position:absolute;left:684px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_247\" class=\"drag\" style=\"position:absolute;left:684px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_248\" class=\"drag\" style=\"position:absolute;left:684px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_249\" class=\"drag\" style=\"position:absolute;left:684px;top:152px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_250\" class=\"drag\" style=\"position:absolute;left:657px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_251\" class=\"drag\" style=\"position:absolute;left:657px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_252\" class=\"drag\" style=\"position:absolute;left:574px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_253\" class=\"drag\" style=\"position:absolute;left:574px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_254\" class=\"drag\" style=\"position:absolute;left:574px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_255\" class=\"drag\" style=\"position:absolute;left:675px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p8_256\" class=\"drag\" style=\"position:absolute;left:656px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p8_257\" class=\"drag\" style=\"position:absolute;left:659px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_258\" class=\"drag\" style=\"position:absolute;left:574px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_259\" class=\"drag\" style=\"position:absolute;left:598px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_260\" class=\"drag\" style=\"position:absolute;left:598px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_261\" class=\"drag\" style=\"position:absolute;left:574px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_262\" class=\"drag\" style=\"position:absolute;left:574px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_263\" class=\"drag\" style=\"position:absolute;left:574px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_264\" class=\"drag\" style=\"position:absolute;left:563px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_265\" class=\"drag\" style=\"position:absolute;left:582px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_266\" class=\"drag\" style=\"position:absolute;left:555px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C207<br></b></nobr>");
write("</p>");
write("<p id=\"p8_267\" class=\"drag\" style=\"position:absolute;left:355px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_268\" class=\"drag\" style=\"position:absolute;left:320px;top:311px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C210<br></b></nobr>");
write("</p>");
write("<p id=\"p8_269\" class=\"drag\" style=\"position:absolute;left:331px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_270\" class=\"drag\" style=\"position:absolute;left:355px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_271\" class=\"drag\" style=\"position:absolute;left:355px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_272\" class=\"drag\" style=\"position:absolute;left:331px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_273\" class=\"drag\" style=\"position:absolute;left:331px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_274\" class=\"drag\" style=\"position:absolute;left:331px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_275\" class=\"drag\" style=\"position:absolute;left:331px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_276\" class=\"drag\" style=\"position:absolute;left:355px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_277\" class=\"drag\" style=\"position:absolute;left:331px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_278\" class=\"drag\" style=\"position:absolute;left:331px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_279\" class=\"drag\" style=\"position:absolute;left:355px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_280\" class=\"drag\" style=\"position:absolute;left:369px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_281\" class=\"drag\" style=\"position:absolute;left:332px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_282\" class=\"drag\" style=\"position:absolute;left:351px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_283\" class=\"drag\" style=\"position:absolute;left:383px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_284\" class=\"drag\" style=\"position:absolute;left:336px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_285\" class=\"drag\" style=\"position:absolute;left:198px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_286\" class=\"drag\" style=\"position:absolute;left:198px;top:237px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_287\" class=\"drag\" style=\"position:absolute;left:198px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_288\" class=\"drag\" style=\"position:absolute;left:198px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_289\" class=\"drag\" style=\"position:absolute;left:198px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_290\" class=\"drag\" style=\"position:absolute;left:171px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p8_291\" class=\"drag\" style=\"position:absolute;left:171px;top:237px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p8_292\" class=\"drag\" style=\"position:absolute;left:171px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p8_293\" class=\"drag\" style=\"position:absolute;left:171px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p8_294\" class=\"drag\" style=\"position:absolute;left:171px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p8_295\" class=\"drag\" style=\"position:absolute;left:171px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p8_296\" class=\"drag\" style=\"position:absolute;left:112px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_297\" class=\"drag\" style=\"position:absolute;left:112px;top:237px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_298\" class=\"drag\" style=\"position:absolute;left:112px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_299\" class=\"drag\" style=\"position:absolute;left:105px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C206<br></b></nobr>");
write("</p>");
write("<p id=\"p8_300\" class=\"drag\" style=\"position:absolute;left:198px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_301\" class=\"drag\" style=\"position:absolute;left:112px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_302\" class=\"drag\" style=\"position:absolute;left:112px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_303\" class=\"drag\" style=\"position:absolute;left:171px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_304\" class=\"drag\" style=\"position:absolute;left:85px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p8_305\" class=\"drag\" style=\"position:absolute;left:88px;top:237px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_306\" class=\"drag\" style=\"position:absolute;left:88px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_307\" class=\"drag\" style=\"position:absolute;left:88px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_308\" class=\"drag\" style=\"position:absolute;left:88px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_309\" class=\"drag\" style=\"position:absolute;left:88px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_310\" class=\"drag\" style=\"position:absolute;left:88px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_311\" class=\"drag\" style=\"position:absolute;left:88px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_312\" class=\"drag\" style=\"position:absolute;left:88px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_313\" class=\"drag\" style=\"position:absolute;left:88px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_314\" class=\"drag\" style=\"position:absolute;left:112px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_315\" class=\"drag\" style=\"position:absolute;left:112px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_316\" class=\"drag\" style=\"position:absolute;left:112px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_317\" class=\"drag\" style=\"position:absolute;left:171px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}