with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img3\" src=\"../img/SAA5ET0A14600000000DAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:436px;top:742px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CYLINDER HEAD<br>L13A3 engine:<br><a href=\"javascript:parent.Cts('000000000000515','i000')\"></b>Removal,</a><br> in the Shop Manual, P/N 62SAA00<br><a href=\"javascript:parent.Cts('000000000000027','i000')\">Inspection,</a><br> in the Shop Manual, P/N 62SAA00<br><a href=\"javascript:parent.Cts('000000000000516','i000')\">Installation,</a><br> in the Shop Manual, P/N 62SAA00<br></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:436px;top:993px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST VALVE<br><a href=\"javascript:parent.Cts('000000000000031','i000')\"></b>Removal,</a><br> in the Shop Manual, P/N 62SAA00<br><a href=\"javascript:parent.Cts('000000000000032','i000')\">Installation,</a><br> in the Shop Manual, P/N 62SAA00<br></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:16px;top:182px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST <br>VALVE SEAL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:251px;top:68px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPRING RETAINER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:250px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VALVE KEEPERS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:16px;top:341px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VALVE SPRING <br>SEAT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:53px;top:423px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST VALVE <br>GUIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:16px;top:524px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAMSHAFT POSITION (CMP) <br>(TOP DEAD CENTER(TDC) ) <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:759px;top:200px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAMSHAFT<br>THRUST COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:795px;top:294px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE VALVE<br>SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:16px;top:57px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST VALVE<br>SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:780px;top:369px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE VALVE SEAL<br><a href=\"javascript:parent.Cts('000000000000505','i000')\"></b>Replacement,<br></a><br> in the Shop Manual,<br> P/N 62SAA00<br></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:597px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROCKER ARM ASSEMBLY<br>L13A3 engine:<br><a href=\"javascript:parent.Cts('000000000000500','i000')\"></b>Overhaul,</a><br> in the Shop Manual, P/N 62SAA00<br><a href=\"javascript:parent.Cts('000000000000501','i000')\">Inspection,</a><br> in the Shop Manual, P/N 62SAA00<br></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:579px;top:396px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RINGS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:295px;top:281px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAMSHAFT<br><a href=\"javascript:parent.Cts('000000000002016','i000')\"></b>Inspection,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:496px;top:665px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VTEC SOLENOID <br>VALVE FILTER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:662px;top:681px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VTEC SOLENOID VALVE ASSEMBLY<br>L15A5 engine:<br><a href=\"javascript:parent.Cts('000000000003135','i000')\"></b>Replacement,</a><br> in the Shop Manual<br> Supplement, P/N 62SAA21<br></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:597px;top:108px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>L15A5 engine:<br><a href=\"javascript:parent.Cts('000000000000862','i000')\"></b>Overhaul,</a><br> in the Shop Manual Supplement, P/N 62SAA21<br><a href=\"javascript:parent.Cts('000000000000864','i000')\">Inspection,</a><br> in the Shop Manual Supplement, P/N 62SAA21<br></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:731px;top:460px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE VALVE GUIDE<br>L13A3 engine:<br><a href=\"javascript:parent.Cts('000000000000505','i000')\"></b>Replacement,</a><br> in the Shop Manual,<br> P/N 62SAA00<br></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:731px;top:537px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>L15A5 engine:<br><a href=\"javascript:parent.Cts('000000000000868','i000')\"></b>Replacement,</a><br> in the Shop Manual<br> Supplement, P/N 62SAA21<br></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:436px;top:865px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>L15A5 engine:<br><a href=\"javascript:parent.Cts('000000000000852','i000')\"></b>Removal,</a><br> in the Shop Manual Supplement, P/N 62SAA21<br><a href=\"javascript:parent.Cts('000000000000027','i000')\">Inspection,</a><br> in the Shop Manual, P/N 62SAA00<br><a href=\"javascript:parent.Cts('000000000000853','i000')\">Installation,</a><br> in the Shop Manual Supplement, P/N 62SAA21<br></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:28px;top:952px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE VALVE<br><a href=\"javascript:parent.Cts('000000000000031','i000')\"></b>Removal,</a><br> in the Shop Manual, P/N 62SAA00<br><a href=\"javascript:parent.Cts('000000000000032','i000')\">Installation,</a><br> in the Shop Manual, P/N 62SAA00<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}