with(document) {
write("<v:group id=\"group5\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect5\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img5\" src=\"../img/SAA5EGAA20300000000EAAD11.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p5_1\" class=\"drag\" style=\"position:absolute;left:805px;top:139px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SECONDARY<br>HO2S (SENSOR 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" class=\"drag\" style=\"position:absolute;left:190px;top:76px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHO2S<br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" class=\"drag\" style=\"position:absolute;left:190px;top:130px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHO2SHTC<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" class=\"drag\" style=\"position:absolute;left:815px;top:60px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" class=\"drag\" style=\"position:absolute;left:743px;top:67px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" class=\"drag\" style=\"position:absolute;left:815px;top:77px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" class=\"drag\" style=\"position:absolute;left:743px;top:84px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" class=\"drag\" style=\"position:absolute;left:815px;top:95px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" class=\"drag\" style=\"position:absolute;left:743px;top:101px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" class=\"drag\" style=\"position:absolute;left:815px;top:112px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" class=\"drag\" style=\"position:absolute;left:743px;top:119px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" class=\"drag\" style=\"position:absolute;left:192px;top:186px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHO2SG<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" class=\"drag\" style=\"position:absolute;left:264px;top:124px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" class=\"drag\" style=\"position:absolute;left:264px;top:179px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" class=\"drag\" style=\"position:absolute;left:264px;top:67px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" class=\"drag\" style=\"position:absolute;left:462px;top:94px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" class=\"drag\" style=\"position:absolute;left:437px;top:126px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_18\" class=\"drag\" style=\"position:absolute;left:702px;top:158px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_19\" class=\"drag\" style=\"position:absolute;left:687px;top:460px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p5_20\" class=\"drag\" style=\"position:absolute;left:190px;top:486px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p5_21\" class=\"drag\" style=\"position:absolute;left:190px;top:501px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BKSW<br></b></nobr>");
write("</p>");
write("<p id=\"p5_22\" class=\"drag\" style=\"position:absolute;left:680px;top:486px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_23\" class=\"drag\" style=\"position:absolute;left:608px;top:493px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_24\" class=\"drag\" style=\"position:absolute;left:264px;top:494px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_25\" class=\"drag\" style=\"position:absolute;left:775px;top:497px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Brake pedal pressed: closed<br>Brake pedal released: open<br></b></nobr>");
write("</p>");
write("<p id=\"p5_26\" class=\"drag\" style=\"position:absolute;left:775px;top:535px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Brake pedal pressed: open<br>Brake pedal released: closed<br></b></nobr>");
write("</p>");
write("<p id=\"p5_27\" class=\"drag\" style=\"position:absolute;left:680px;top:506px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_28\" class=\"drag\" style=\"position:absolute;left:608px;top:513px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_29\" class=\"drag\" style=\"position:absolute;left:680px;top:525px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p5_30\" class=\"drag\" style=\"position:absolute;left:680px;top:544px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p5_31\" class=\"drag\" style=\"position:absolute;left:190px;top:544px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p5_32\" class=\"drag\" style=\"position:absolute;left:190px;top:559px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BKPD<br></b></nobr>");
write("</p>");
write("<p id=\"p5_33\" class=\"drag\" style=\"position:absolute;left:608px;top:551px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_34\" class=\"drag\" style=\"position:absolute;left:565px;top:638px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p5_35\" class=\"drag\" style=\"position:absolute;left:587px;top:571px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14P <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_36\" class=\"drag\" style=\"position:absolute;left:573px;top:589px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_37\" class=\"drag\" style=\"position:absolute;left:518px;top:638px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p5_38\" class=\"drag\" style=\"position:absolute;left:408px;top:455px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p5_39\" class=\"drag\" style=\"position:absolute;left:353px;top:389px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_40\" class=\"drag\" style=\"position:absolute;left:372px;top:455px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p5_41\" class=\"drag\" style=\"position:absolute;left:823px;top:281px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MIL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_42\" class=\"drag\" style=\"position:absolute;left:764px;top:205px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p5_43\" class=\"drag\" style=\"position:absolute;left:190px;top:309px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_44\" class=\"drag\" style=\"position:absolute;left:190px;top:324px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FUP<br></b></nobr>");
write("</p>");
write("<p id=\"p5_45\" class=\"drag\" style=\"position:absolute;left:727px;top:309px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p5_46\" class=\"drag\" style=\"position:absolute;left:653px;top:316px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_47\" class=\"drag\" style=\"position:absolute;left:190px;top:360px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_48\" class=\"drag\" style=\"position:absolute;left:190px;top:374px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MTRTW<br></b></nobr>");
write("</p>");
write("<p id=\"p5_49\" class=\"drag\" style=\"position:absolute;left:727px;top:360px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p5_50\" class=\"drag\" style=\"position:absolute;left:653px;top:367px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_51\" class=\"drag\" style=\"position:absolute;left:727px;top:250px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p5_52\" class=\"drag\" style=\"position:absolute;left:654px;top:257px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_53\" class=\"drag\" style=\"position:absolute;left:727px;top:227px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_54\" class=\"drag\" style=\"position:absolute;left:654px;top:234px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_55\" class=\"drag\" style=\"position:absolute;left:589px;top:296px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p5_56\" class=\"drag\" style=\"position:absolute;left:190px;top:249px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p5_57\" class=\"drag\" style=\"position:absolute;left:190px;top:264px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MIL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_58\" class=\"drag\" style=\"position:absolute;left:264px;top:257px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_59\" class=\"drag\" style=\"position:absolute;left:769px;top:1009px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To IMMOBILIZER UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_60\" class=\"drag\" style=\"position:absolute;left:818px;top:748px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SERVICE<br>CHECK<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_61\" class=\"drag\" style=\"position:absolute;left:818px;top:831px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_62\" class=\"drag\" style=\"position:absolute;left:775px;top:741px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_63\" class=\"drag\" style=\"position:absolute;left:703px;top:748px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_64\" class=\"drag\" style=\"position:absolute;left:775px;top:760px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_65\" class=\"drag\" style=\"position:absolute;left:703px;top:767px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_66\" class=\"drag\" style=\"position:absolute;left:775px;top:801px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p5_67\" class=\"drag\" style=\"position:absolute;left:703px;top:808px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_68\" class=\"drag\" style=\"position:absolute;left:775px;top:820px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p5_69\" class=\"drag\" style=\"position:absolute;left:775px;top:839px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p5_70\" class=\"drag\" style=\"position:absolute;left:775px;top:858px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p5_71\" class=\"drag\" style=\"position:absolute;left:703px;top:846px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_72\" class=\"drag\" style=\"position:absolute;left:191px;top:760px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p5_73\" class=\"drag\" style=\"position:absolute;left:191px;top:774px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p5_74\" class=\"drag\" style=\"position:absolute;left:190px;top:820px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p5_75\" class=\"drag\" style=\"position:absolute;left:190px;top:834px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>K-LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p5_76\" class=\"drag\" style=\"position:absolute;left:264px;top:827px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_77\" class=\"drag\" style=\"position:absolute;left:634px;top:956px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p5_78\" class=\"drag\" style=\"position:absolute;left:703px;top:865px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_79\" class=\"drag\" style=\"position:absolute;left:264px;top:767px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_80\" class=\"drag\" style=\"position:absolute;left:576px;top:911px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p5_81\" class=\"drag\" style=\"position:absolute;left:518px;top:709px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p5_82\" class=\"drag\" style=\"position:absolute;left:190px;top:1002px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p5_83\" class=\"drag\" style=\"position:absolute;left:190px;top:1016px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IMOCD<br></b></nobr>");
write("</p>");
write("<p id=\"p5_84\" class=\"drag\" style=\"position:absolute;left:264px;top:1010px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_85\" class=\"drag\" style=\"position:absolute;left:406px;top:729px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p5_86\" class=\"drag\" style=\"position:absolute;left:351px;top:663px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_87\" class=\"drag\" style=\"position:absolute;left:371px;top:729px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p5_88\" class=\"drag\" style=\"position:absolute;left:702px;top:27px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p5_89\" class=\"drag\" style=\"position:absolute;left:608px;top:532px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_90\" class=\"drag\" style=\"position:absolute;left:190px;top:60px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p5_91\" class=\"drag\" style=\"position:absolute;left:190px;top:116px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p5_92\" class=\"drag\" style=\"position:absolute;left:192px;top:172px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p5_93\" class=\"drag\" style=\"position:absolute;left:182px;top:44px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 4 (40P)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_94\" class=\"drag\" style=\"position:absolute;left:182px;top:101px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 5 (9P)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_95\" class=\"drag\" style=\"position:absolute;left:182px;top:157px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 4 (40P)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_96\" class=\"drag\" style=\"position:absolute;left:703px;top:827px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}