with(document) {
write("<v:group id=\"group36\" class=\"drag\" style=\"position:relative; width:950px; height:1112px;\" coordsize=\"950,1112\">");
write("<v:rect id=\"rect36\"class=\"drag\"  style=\"width:950px;height:1112px;\">");
write("<img id=\"img36\" src=\"../img/SAA5ES0A20300000000DBAD83.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1112px;border-color:#ffffff\">");
write("<p id=\"p36_1\" class=\"drag\" style=\"position:absolute;left:149px;top:23px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p36_2\" class=\"drag\" style=\"position:absolute;left:130px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_3\" class=\"drag\" style=\"position:absolute;left:154px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p36_4\" class=\"drag\" style=\"position:absolute;left:130px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_5\" class=\"drag\" style=\"position:absolute;left:130px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_6\" class=\"drag\" style=\"position:absolute;left:154px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_7\" class=\"drag\" style=\"position:absolute;left:154px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p36_8\" class=\"drag\" style=\"position:absolute;left:755px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_9\" class=\"drag\" style=\"position:absolute;left:583px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_10\" class=\"drag\" style=\"position:absolute;left:583px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p36_11\" class=\"drag\" style=\"position:absolute;left:559px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_12\" class=\"drag\" style=\"position:absolute;left:559px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_13\" class=\"drag\" style=\"position:absolute;left:559px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_14\" class=\"drag\" style=\"position:absolute;left:559px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_15\" class=\"drag\" style=\"position:absolute;left:583px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_16\" class=\"drag\" style=\"position:absolute;left:559px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_17\" class=\"drag\" style=\"position:absolute;left:583px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_18\" class=\"drag\" style=\"position:absolute;left:547px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C217<br></b></nobr>");
write("</p>");
write("<p id=\"p36_19\" class=\"drag\" style=\"position:absolute;left:597px;top:80px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_20\" class=\"drag\" style=\"position:absolute;left:578px;top:80px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_21\" class=\"drag\" style=\"position:absolute;left:587px;top:61px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_22\" class=\"drag\" style=\"position:absolute;left:569px;top:61px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_23\" class=\"drag\" style=\"position:absolute;left:412px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_24\" class=\"drag\" style=\"position:absolute;left:387px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_25\" class=\"drag\" style=\"position:absolute;left:412px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p36_26\" class=\"drag\" style=\"position:absolute;left:387px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_27\" class=\"drag\" style=\"position:absolute;left:387px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_28\" class=\"drag\" style=\"position:absolute;left:387px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_29\" class=\"drag\" style=\"position:absolute;left:376px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C209<br></b></nobr>");
write("</p>");
write("<p id=\"p36_30\" class=\"drag\" style=\"position:absolute;left:216px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p36_31\" class=\"drag\" style=\"position:absolute;left:213px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p36_32\" class=\"drag\" style=\"position:absolute;left:240px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p36_33\" class=\"drag\" style=\"position:absolute;left:154px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_34\" class=\"drag\" style=\"position:absolute;left:130px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_35\" class=\"drag\" style=\"position:absolute;left:154px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_36\" class=\"drag\" style=\"position:absolute;left:130px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_37\" class=\"drag\" style=\"position:absolute;left:130px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_38\" class=\"drag\" style=\"position:absolute;left:130px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_39\" class=\"drag\" style=\"position:absolute;left:130px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_40\" class=\"drag\" style=\"position:absolute;left:240px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p36_41\" class=\"drag\" style=\"position:absolute;left:154px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p36_42\" class=\"drag\" style=\"position:absolute;left:130px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p36_43\" class=\"drag\" style=\"position:absolute;left:130px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p36_44\" class=\"drag\" style=\"position:absolute;left:130px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p36_45\" class=\"drag\" style=\"position:absolute;left:240px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p36_46\" class=\"drag\" style=\"position:absolute;left:213px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p36_47\" class=\"drag\" style=\"position:absolute;left:214px;top:167px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p36_48\" class=\"drag\" style=\"position:absolute;left:213px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p36_49\" class=\"drag\" style=\"position:absolute;left:213px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p36_50\" class=\"drag\" style=\"position:absolute;left:213px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p36_51\" class=\"drag\" style=\"position:absolute;left:214px;top:224px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p36_52\" class=\"drag\" style=\"position:absolute;left:240px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_53\" class=\"drag\" style=\"position:absolute;left:421px;top:373px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p36_54\" class=\"drag\" style=\"position:absolute;left:423px;top:355px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_55\" class=\"drag\" style=\"position:absolute;left:440px;top:373px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p36_56\" class=\"drag\" style=\"position:absolute;left:399px;top:373px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p36_57\" class=\"drag\" style=\"position:absolute;left:380px;top:373px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p36_58\" class=\"drag\" style=\"position:absolute;left:361px;top:373px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p36_59\" class=\"drag\" style=\"position:absolute;left:323px;top:355px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_60\" class=\"drag\" style=\"position:absolute;left:305px;top:373px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p36_61\" class=\"drag\" style=\"position:absolute;left:305px;top:355px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_62\" class=\"drag\" style=\"position:absolute;left:345px;top:355px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_63\" class=\"drag\" style=\"position:absolute;left:345px;top:373px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p36_64\" class=\"drag\" style=\"position:absolute;left:140px;top:355px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_65\" class=\"drag\" style=\"position:absolute;left:159px;top:355px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_66\" class=\"drag\" style=\"position:absolute;left:178px;top:355px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_67\" class=\"drag\" style=\"position:absolute;left:749px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_68\" class=\"drag\" style=\"position:absolute;left:768px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_69\" class=\"drag\" style=\"position:absolute;left:768px;top:84px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_70\" class=\"drag\" style=\"position:absolute;left:750px;top:84px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_71\" class=\"drag\" style=\"position:absolute;left:435px;top:62px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_72\" class=\"drag\" style=\"position:absolute;left:397px;top:62px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_73\" class=\"drag\" style=\"position:absolute;left:137px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p36_74\" class=\"drag\" style=\"position:absolute;left:190px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p36_75\" class=\"drag\" style=\"position:absolute;left:264px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p36_76\" class=\"drag\" style=\"position:absolute;left:227px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p36_77\" class=\"drag\" style=\"position:absolute;left:192px;top:62px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_78\" class=\"drag\" style=\"position:absolute;left:211px;top:62px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_79\" class=\"drag\" style=\"position:absolute;left:248px;top:62px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p36_80\" class=\"drag\" style=\"position:absolute;left:755px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_81\" class=\"drag\" style=\"position:absolute;left:730px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_82\" class=\"drag\" style=\"position:absolute;left:755px;top:152px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p36_83\" class=\"drag\" style=\"position:absolute;left:730px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_84\" class=\"drag\" style=\"position:absolute;left:412px;top:452px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_85\" class=\"drag\" style=\"position:absolute;left:326px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p36_86\" class=\"drag\" style=\"position:absolute;left:326px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_87\" class=\"drag\" style=\"position:absolute;left:326px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p36_88\" class=\"drag\" style=\"position:absolute;left:301px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p36_89\" class=\"drag\" style=\"position:absolute;left:326px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_90\" class=\"drag\" style=\"position:absolute;left:301px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p36_91\" class=\"drag\" style=\"position:absolute;left:301px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_92\" class=\"drag\" style=\"position:absolute;left:301px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_93\" class=\"drag\" style=\"position:absolute;left:301px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p36_94\" class=\"drag\" style=\"position:absolute;left:326px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p36_95\" class=\"drag\" style=\"position:absolute;left:384px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p36_96\" class=\"drag\" style=\"position:absolute;left:301px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p36_97\" class=\"drag\" style=\"position:absolute;left:301px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p36_98\" class=\"drag\" style=\"position:absolute;left:387px;top:409px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p36_99\" class=\"drag\" style=\"position:absolute;left:387px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p36_100\" class=\"drag\" style=\"position:absolute;left:412px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_101\" class=\"drag\" style=\"position:absolute;left:412px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p36_102\" class=\"drag\" style=\"position:absolute;left:412px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_103\" class=\"drag\" style=\"position:absolute;left:412px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p36_104\" class=\"drag\" style=\"position:absolute;left:384px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p36_105\" class=\"drag\" style=\"position:absolute;left:384px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p36_106\" class=\"drag\" style=\"position:absolute;left:385px;top:481px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p36_107\" class=\"drag\" style=\"position:absolute;left:385px;top:495px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p36_108\" class=\"drag\" style=\"position:absolute;left:412px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p36_109\" class=\"drag\" style=\"position:absolute;left:290px;top:311px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C306<br></b></nobr>");
write("</p>");
write("<p id=\"p36_110\" class=\"drag\" style=\"position:absolute;left:177px;top:1073px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>* : Terminal side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p36_111\" class=\"drag\" style=\"position:absolute;left:118px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C204<br></b></nobr>");
write("</p>");
write("<p id=\"p36_112\" class=\"drag\" style=\"position:absolute;left:730px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p36_113\" class=\"drag\" style=\"position:absolute;left:755px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p36_114\" class=\"drag\" style=\"position:absolute;left:730px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p36_115\" class=\"drag\" style=\"position:absolute;left:719px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C218<br></b></nobr>");
write("</p>");
write("<p id=\"p36_116\" class=\"drag\" style=\"position:absolute;left:161px;top:1050px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p36_117\" class=\"drag\" style=\"position:absolute;left:118px;top:311px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C305<br></b></nobr>");
write("</p>");
write("<p id=\"p36_118\" class=\"drag\" style=\"position:absolute;left:161px;top:1035px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>· Connector with female terminals (single outline) : View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p36_119\" class=\"drag\" style=\"position:absolute;left:161px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>· Connector with male terminals (double outline) : View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p36_120\" class=\"drag\" style=\"position:absolute;left:106px;top:1021px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p36_121\" class=\"drag\" style=\"position:absolute;left:199px;top:1050px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to ECM/PCM control.<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}