with(document) {
write("<v:group id=\"group9\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect9\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img9\" src=\"../img/SAA5ES0A20300000000EAAD43.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p9_1\" class=\"drag\" style=\"position:absolute;left:540px;top:167px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p9_2\" class=\"drag\" style=\"position:absolute;left:861px;top:116px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_3\" class=\"drag\" style=\"position:absolute;left:604px;top:167px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_4\" class=\"drag\" style=\"position:absolute;left:757px;top:198px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_5\" class=\"drag\" style=\"position:absolute;left:840px;top:230px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>KNOCK SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_6\" class=\"drag\" style=\"position:absolute;left:544px;top:260px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p9_7\" class=\"drag\" style=\"position:absolute;left:604px;top:260px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_8\" class=\"drag\" style=\"position:absolute;left:560px;top:248px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>KS<br></b></nobr>");
write("</p>");
write("<p id=\"p9_9\" class=\"drag\" style=\"position:absolute;left:560px;top:155px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TPS<br></b></nobr>");
write("</p>");
write("<p id=\"p9_10\" class=\"drag\" style=\"position:absolute;left:846px;top:638px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IAT SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_11\" class=\"drag\" style=\"position:absolute;left:847px;top:700px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECT SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_12\" class=\"drag\" style=\"position:absolute;left:540px;top:675px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B17<br></b></nobr>");
write("</p>");
write("<p id=\"p9_13\" class=\"drag\" style=\"position:absolute;left:543px;top:738px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p9_14\" class=\"drag\" style=\"position:absolute;left:560px;top:726px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_15\" class=\"drag\" style=\"position:absolute;left:604px;top:674px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_16\" class=\"drag\" style=\"position:absolute;left:560px;top:662px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IAT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_17\" class=\"drag\" style=\"position:absolute;left:772px;top:657px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_18\" class=\"drag\" style=\"position:absolute;left:604px;top:738px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_19\" class=\"drag\" style=\"position:absolute;left:850px;top:337px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR VALVE<br>POSITION<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_20\" class=\"drag\" style=\"position:absolute;left:540px;top:393px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p9_21\" class=\"drag\" style=\"position:absolute;left:560px;top:380px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGRP<br></b></nobr>");
write("</p>");
write("<p id=\"p9_22\" class=\"drag\" style=\"position:absolute;left:604px;top:392px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_23\" class=\"drag\" style=\"position:absolute;left:541px;top:463px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p9_24\" class=\"drag\" style=\"position:absolute;left:560px;top:450px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_25\" class=\"drag\" style=\"position:absolute;left:779px;top:409px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_26\" class=\"drag\" style=\"position:absolute;left:779px;top:376px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_27\" class=\"drag\" style=\"position:absolute;left:611px;top:462px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_28\" class=\"drag\" style=\"position:absolute;left:772px;top:721px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_29\" class=\"drag\" style=\"position:absolute;left:855px;top:461px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_30\" class=\"drag\" style=\"position:absolute;left:384px;top:183px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A30<br></b></nobr>");
write("</p>");
write("<p id=\"p9_31\" class=\"drag\" style=\"position:absolute;left:343px;top:169px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_32\" class=\"drag\" style=\"position:absolute;left:226px;top:165px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_33\" class=\"drag\" style=\"position:absolute;left:235px;top:205px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_34\" class=\"drag\" style=\"position:absolute;left:384px;top:261px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A29<br></b></nobr>");
write("</p>");
write("<p id=\"p9_35\" class=\"drag\" style=\"position:absolute;left:342px;top:246px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_36\" class=\"drag\" style=\"position:absolute;left:226px;top:261px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_37\" class=\"drag\" style=\"position:absolute;left:226px;top:242px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_38\" class=\"drag\" style=\"position:absolute;left:235px;top:283px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_39\" class=\"drag\" style=\"position:absolute;left:384px;top:338px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A28<br></b></nobr>");
write("</p>");
write("<p id=\"p9_40\" class=\"drag\" style=\"position:absolute;left:342px;top:324px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS3<br></b></nobr>");
write("</p>");
write("<p id=\"p9_41\" class=\"drag\" style=\"position:absolute;left:226px;top:339px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_42\" class=\"drag\" style=\"position:absolute;left:226px;top:320px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_43\" class=\"drag\" style=\"position:absolute;left:235px;top:360px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_44\" class=\"drag\" style=\"position:absolute;left:384px;top:416px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A27<br></b></nobr>");
write("</p>");
write("<p id=\"p9_45\" class=\"drag\" style=\"position:absolute;left:342px;top:402px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS4<br></b></nobr>");
write("</p>");
write("<p id=\"p9_46\" class=\"drag\" style=\"position:absolute;left:226px;top:398px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_47\" class=\"drag\" style=\"position:absolute;left:235px;top:438px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_48\" class=\"drag\" style=\"position:absolute;left:234px;top:184px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_49\" class=\"drag\" style=\"position:absolute;left:226px;top:417px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_50\" class=\"drag\" style=\"position:absolute;left:20px;top:172px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p9_51\" class=\"drag\" style=\"position:absolute;left:146px;top:194px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p9_52\" class=\"drag\" style=\"position:absolute;left:22px;top:224px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_53\" class=\"drag\" style=\"position:absolute;left:20px;top:250px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p9_54\" class=\"drag\" style=\"position:absolute;left:146px;top:272px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p9_55\" class=\"drag\" style=\"position:absolute;left:22px;top:301px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_56\" class=\"drag\" style=\"position:absolute;left:19px;top:328px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p9_57\" class=\"drag\" style=\"position:absolute;left:146px;top:349px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p9_58\" class=\"drag\" style=\"position:absolute;left:21px;top:379px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 3 IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_59\" class=\"drag\" style=\"position:absolute;left:19px;top:405px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p9_60\" class=\"drag\" style=\"position:absolute;left:146px;top:427px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p9_61\" class=\"drag\" style=\"position:absolute;left:21px;top:457px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 4 IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_62\" class=\"drag\" style=\"position:absolute;left:322px;top:510px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p9_63\" class=\"drag\" style=\"position:absolute;left:107px;top:26px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p9_64\" class=\"drag\" style=\"position:absolute;left:86px;top:67px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_65\" class=\"drag\" style=\"position:absolute;left:66px;top:86px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C302<br></b></nobr>");
write("</p>");
write("<p id=\"p9_66\" class=\"drag\" style=\"position:absolute;left:66px;top:111px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C114<br></b></nobr>");
write("</p>");
write("<p id=\"p9_67\" class=\"drag\" style=\"position:absolute;left:337px;top:107px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>J/C<br></b></nobr>");
write("</p>");
write("<p id=\"p9_68\" class=\"drag\" style=\"position:absolute;left:337px;top:122px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C116<br></b></nobr>");
write("</p>");
write("<p id=\"p9_69\" class=\"drag\" style=\"position:absolute;left:142px;top:145px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_70\" class=\"drag\" style=\"position:absolute;left:810px;top:124px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C117<br></b></nobr>");
write("</p>");
write("<p id=\"p9_71\" class=\"drag\" style=\"position:absolute;left:810px;top:239px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C121<br></b></nobr>");
write("</p>");
write("<p id=\"p9_72\" class=\"drag\" style=\"position:absolute;left:818px;top:363px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C131<br></b></nobr>");
write("</p>");
write("<p id=\"p9_73\" class=\"drag\" style=\"position:absolute;left:816px;top:645px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C118<br></b></nobr>");
write("</p>");
write("<p id=\"p9_74\" class=\"drag\" style=\"position:absolute;left:817px;top:708px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C104<br></b></nobr>");
write("</p>");
write("<p id=\"p9_75\" class=\"drag\" style=\"position:absolute;left:216px;top:153px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C130<br></b></nobr>");
write("</p>");
write("<p id=\"p9_76\" class=\"drag\" style=\"position:absolute;left:216px;top:230px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C128<br></b></nobr>");
write("</p>");
write("<p id=\"p9_77\" class=\"drag\" style=\"position:absolute;left:217px;top:307px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C126<br></b></nobr>");
write("</p>");
write("<p id=\"p9_78\" class=\"drag\" style=\"position:absolute;left:217px;top:384px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C124<br></b></nobr>");
write("</p>");
write("<p id=\"p9_79\" class=\"drag\" style=\"position:absolute;left:544px;top:811px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p9_80\" class=\"drag\" style=\"position:absolute;left:562px;top:798px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PHO2S<br></b></nobr>");
write("</p>");
write("<p id=\"p9_81\" class=\"drag\" style=\"position:absolute;left:544px;top:840px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_82\" class=\"drag\" style=\"position:absolute;left:604px;top:840px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_83\" class=\"drag\" style=\"position:absolute;left:561px;top:827px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PHO2SHTC<br></b></nobr>");
write("</p>");
write("<p id=\"p9_84\" class=\"drag\" style=\"position:absolute;left:779px;top:854px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_85\" class=\"drag\" style=\"position:absolute;left:683px;top:888px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p9_86\" class=\"drag\" style=\"position:absolute;left:610px;top:811px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_87\" class=\"drag\" style=\"position:absolute;left:388px;top:694px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_88\" class=\"drag\" style=\"position:absolute;left:345px;top:680px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHO2S<br></b></nobr>");
write("</p>");
write("<p id=\"p9_89\" class=\"drag\" style=\"position:absolute;left:388px;top:723px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E6<br></b></nobr>");
write("</p>");
write("<p id=\"p9_90\" class=\"drag\" style=\"position:absolute;left:290px;top:723px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_91\" class=\"drag\" style=\"position:absolute;left:324px;top:710px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHO2SHTC<br></b></nobr>");
write("</p>");
write("<p id=\"p9_92\" class=\"drag\" style=\"position:absolute;left:25px;top:758px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SECONDARY<br>HO2S<br>(SENSOR 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_93\" class=\"drag\" style=\"position:absolute;left:120px;top:737px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_94\" class=\"drag\" style=\"position:absolute;left:121px;top:709px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_95\" class=\"drag\" style=\"position:absolute;left:254px;top:770px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p9_96\" class=\"drag\" style=\"position:absolute;left:101px;top:677px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C218<br></b></nobr>");
write("</p>");
write("<p id=\"p9_97\" class=\"drag\" style=\"position:absolute;left:213px;top:771px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p9_98\" class=\"drag\" style=\"position:absolute;left:193px;top:669px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p9_99\" class=\"drag\" style=\"position:absolute;left:289px;top:694px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p9_100\" class=\"drag\" style=\"position:absolute;left:212px;top:989px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p9_101\" class=\"drag\" style=\"position:absolute;left:388px;top:908px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p9_102\" class=\"drag\" style=\"position:absolute;left:344px;top:895px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VTPSW<br></b></nobr>");
write("</p>");
write("<p id=\"p9_103\" class=\"drag\" style=\"position:absolute;left:25px;top:946px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VTEC OIL<br>PRESSURE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p9_104\" class=\"drag\" style=\"position:absolute;left:88px;top:886px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C152<br></b></nobr>");
write("</p>");
write("<p id=\"p9_105\" class=\"drag\" style=\"position:absolute;left:290px;top:909px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_106\" class=\"drag\" style=\"position:absolute;left:118px;top:927px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_107\" class=\"drag\" style=\"position:absolute;left:540px;top:622px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p9_108\" class=\"drag\" style=\"position:absolute;left:560px;top:609px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SG2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_109\" class=\"drag\" style=\"position:absolute;left:604px;top:622px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_110\" class=\"drag\" style=\"position:absolute;left:541px;top:562px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p9_111\" class=\"drag\" style=\"position:absolute;left:561px;top:549px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VCC2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_112\" class=\"drag\" style=\"position:absolute;left:604px;top:561px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_113\" class=\"drag\" style=\"position:absolute;left:756px;top:136px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_114\" class=\"drag\" style=\"position:absolute;left:809px;top:441px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_115\" class=\"drag\" style=\"position:absolute;left:780px;top:501px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p9_116\" class=\"drag\" style=\"position:absolute;left:855px;top:873px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PRIMARY<br>HO2S<br>(SENSOR 1)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_117\" class=\"drag\" style=\"position:absolute;left:778px;top:826px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_118\" class=\"drag\" style=\"position:absolute;left:820px;top:800px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C102<br></b></nobr>");
write("</p>");
write("<p id=\"p9_119\" class=\"drag\" style=\"position:absolute;left:540px;top:981px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p9_120\" class=\"drag\" style=\"position:absolute;left:560px;top:968px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VTS<br></b></nobr>");
write("</p>");
write("<p id=\"p9_121\" class=\"drag\" style=\"position:absolute;left:603px;top:981px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_122\" class=\"drag\" style=\"position:absolute;left:820px;top:965px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C151<br></b></nobr>");
write("</p>");
write("<p id=\"p9_123\" class=\"drag\" style=\"position:absolute;left:858px;top:1015px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VTEC<br>SOLENOID<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_124\" class=\"drag\" style=\"position:absolute;left:776px;top:997px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_125\" class=\"drag\" style=\"position:absolute;left:733px;top:1056px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p9_126\" class=\"drag\" style=\"position:absolute;left:792px;top:630px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p9_127\" class=\"drag\" style=\"position:absolute;left:817px;top:578px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_128\" class=\"drag\" style=\"position:absolute;left:765px;top:318px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p9_129\" class=\"drag\" style=\"position:absolute;left:884px;top:594px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C116<br></b></nobr>");
write("</p>");
write("<p id=\"p9_130\" class=\"drag\" style=\"position:absolute;left:748px;top:631px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p9_131\" class=\"drag\" style=\"position:absolute;left:744px;top:896px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p9_132\" class=\"drag\" style=\"position:absolute;left:725px;top:955px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p9_133\" class=\"drag\" style=\"position:absolute;left:884px;top:510px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>J/C<br></b></nobr>");
write("</p>");
write("<p id=\"p9_134\" class=\"drag\" style=\"position:absolute;left:18px;top:852px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p9_135\" class=\"drag\" style=\"position:absolute;left:19px;top:648px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}