with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:950px; height:671px;\" coordsize=\"950,671\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:950px;height:671px;\">");
write("<img id=\"img3\" src=\"../img/SAA5ESPA20300000000DBAD35.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:671px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:665px;top:61px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C303*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:1px;top:627px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*2: CVT<br>*3: LHD<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:718px;top:81px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C371*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:614px;top:36px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C114*<sup>3</sup><br>C302*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:449px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:768px;top:334px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>COMPARTMENT<br>WIRE HARNESS*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:777px;top:442px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C372*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:761px;top:481px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C373*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:739px;top:515px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C374*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:523px;top:582px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:429px;top:580px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C301*<sup>2,</sup>*<sup>3</sup><br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}