with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:991px;\" coordsize=\"950,991\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:991px;\">");
write("<img id=\"img1\" src=\"../img/SAA5EGAA20300062951CAAD38.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:991px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:282px;top:467px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ENGINE<br>COOLANT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:610px;top:483px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:622px;top:503px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:623px;top:536px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:710px;top:543px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:768px;top:556px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:366px;top:384px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:456px;top:492px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:529px;top:365px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:118px;top:203px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:196px;top:168px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:253px;top:202px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:250px;top:248px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:183px;top:279px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:278px;top:361px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:302px;top:417px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:649px;top:351px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:765px;top:374px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:233px;top:66px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:188px;top:21px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:457px;top:373px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:372px;top:207px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:727px;top:405px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:422px;top:165px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:853px;top:566px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:625px;top:397px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:813px;top:638px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:16px;top:711px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:16px;top:743px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:16px;top:774px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:16px;top:790px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:16px;top:806px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:16px;top:822px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:16px;top:838px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:16px;top:854px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:16px;top:870px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:16px;top:886px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:16px;top:902px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:16px;top:918px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:16px;top:934px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:16px;top:950px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:486px;top:711px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:486px;top:727px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:486px;top:743px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:486px;top:758px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:486px;top:774px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:486px;top:790px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:486px;top:822px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:486px;top:838px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:486px;top:854px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:486px;top:886px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(24)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:486px;top:918px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(25)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:486px;top:934px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(26)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:38px;top:711px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PRIMARY HEATED OXYGEN SENSOR<br>(PRIMARY HO2S) (SENSOR 1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:38px;top:774px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MANIFOLD ABSOLUTE PRESSURE (MAP) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:38px;top:743px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY HEATED OXYGEN SENSOR<br>(PRIMARY HO2S) (SENSOR 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:38px;top:790px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE COOLANT TEMPERATURE (ECT) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:38px;top:806px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>KNOCK SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:38px;top:822px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT POSITION (CKP) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:38px;top:838px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE AIR TEMPERATURE (IAT) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:38px;top:854px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAMSHAFT SPEED (CMP) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:38px;top:870px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SIDE IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:38px;top:886px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR SIDE IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:38px;top:902px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IDLE AIR CONTROL (IAC) VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:38px;top:918px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>THROTTLE BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:38px;top:934px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INJECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:38px;top:950px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FULE PULSATION DAMPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:508px;top:854px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EVAPORATIVE EMISSION (EVAP) CANISTER PURGE<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:508px;top:886px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EVAPORATIVE EMISSION (EVAP) CONTROL<br>CANISTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:508px;top:823px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POSITIVE CRANKCASE VENTILATION (PCV) VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:508px;top:838px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>THREE WAY CATALYTIC CONVERTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:508px;top:918px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL TANK VAPOR/LIQUID SEPARATION VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:508px;top:934px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EVAPORATIVE EMISSION (EVAP) TWO WAY VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:508px;top:711px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:508px;top:727px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL PRESSURE REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:508px;top:743px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:508px;top:758px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL TANK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:508px;top:774px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>AIR CLEANER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:508px;top:790px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST GAS RECIRCULATION (EGR) VALVE and<br>POSITION SENSOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}