with(document) {
write("<v:group id=\"group22\" class=\"drag\" style=\"position:relative; width:950px; height:1063px;\" coordsize=\"950,1063\">");
write("<v:rect id=\"rect22\"class=\"drag\"  style=\"width:950px;height:1063px;\">");
write("<img id=\"img22\" src=\"../img/SAA5ES0A20300000000DBAD69.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1063px;border-color:#ffffff\">");
write("<p id=\"p22_1\" class=\"drag\" style=\"position:absolute;left:267px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p22_2\" class=\"drag\" style=\"position:absolute;left:92px;top:942px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>*7 : Without inertia switch<br></b></nobr>");
write("</p>");
write("<p id=\"p22_3\" class=\"drag\" style=\"position:absolute;left:647px;top:680px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_4\" class=\"drag\" style=\"position:absolute;left:671px;top:680px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_5\" class=\"drag\" style=\"position:absolute;left:647px;top:694px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_6\" class=\"drag\" style=\"position:absolute;left:647px;top:708px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_7\" class=\"drag\" style=\"position:absolute;left:671px;top:694px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_8\" class=\"drag\" style=\"position:absolute;left:647px;top:723px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_9\" class=\"drag\" style=\"position:absolute;left:671px;top:723px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_10\" class=\"drag\" style=\"position:absolute;left:671px;top:709px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p22_11\" class=\"drag\" style=\"position:absolute;left:661px;top:633px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_12\" class=\"drag\" style=\"position:absolute;left:698px;top:633px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_13\" class=\"drag\" style=\"position:absolute;left:680px;top:633px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_14\" class=\"drag\" style=\"position:absolute;left:642px;top:633px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_15\" class=\"drag\" style=\"position:absolute;left:621px;top:582px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C382<br></b></nobr>");
write("</p>");
write("<p id=\"p22_16\" class=\"drag\" style=\"position:absolute;left:437px;top:737px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p22_17\" class=\"drag\" style=\"position:absolute;left:458px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p22_18\" class=\"drag\" style=\"position:absolute;left:479px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p22_19\" class=\"drag\" style=\"position:absolute;left:461px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_20\" class=\"drag\" style=\"position:absolute;left:421px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p22_21\" class=\"drag\" style=\"position:absolute;left:387px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p22_22\" class=\"drag\" style=\"position:absolute;left:387px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_23\" class=\"drag\" style=\"position:absolute;left:368px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p22_24\" class=\"drag\" style=\"position:absolute;left:349px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p22_25\" class=\"drag\" style=\"position:absolute;left:349px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_26\" class=\"drag\" style=\"position:absolute;left:440px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p22_27\" class=\"drag\" style=\"position:absolute;left:477px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p22_28\" class=\"drag\" style=\"position:absolute;left:405px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p22_29\" class=\"drag\" style=\"position:absolute;left:368px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_30\" class=\"drag\" style=\"position:absolute;left:143px;top:737px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_31\" class=\"drag\" style=\"position:absolute;left:143px;top:751px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_32\" class=\"drag\" style=\"position:absolute;left:169px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p22_33\" class=\"drag\" style=\"position:absolute;left:151px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p22_34\" class=\"drag\" style=\"position:absolute;left:143px;top:723px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_35\" class=\"drag\" style=\"position:absolute;left:118px;top:751px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p22_36\" class=\"drag\" style=\"position:absolute;left:118px;top:722px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_37\" class=\"drag\" style=\"position:absolute;left:118px;top:736px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p22_38\" class=\"drag\" style=\"position:absolute;left:118px;top:708px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_39\" class=\"drag\" style=\"position:absolute;left:118px;top:694px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_40\" class=\"drag\" style=\"position:absolute;left:143px;top:680px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p22_41\" class=\"drag\" style=\"position:absolute;left:118px;top:679px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_42\" class=\"drag\" style=\"position:absolute;left:143px;top:694px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p22_43\" class=\"drag\" style=\"position:absolute;left:114px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_44\" class=\"drag\" style=\"position:absolute;left:169px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_45\" class=\"drag\" style=\"position:absolute;left:132px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_46\" class=\"drag\" style=\"position:absolute;left:714px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL*<sup>7</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p22_47\" class=\"drag\" style=\"position:absolute;left:690px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_48\" class=\"drag\" style=\"position:absolute;left:714px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK*<sup>6</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p22_49\" class=\"drag\" style=\"position:absolute;left:690px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_50\" class=\"drag\" style=\"position:absolute;left:690px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_51\" class=\"drag\" style=\"position:absolute;left:714px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p22_52\" class=\"drag\" style=\"position:absolute;left:690px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_53\" class=\"drag\" style=\"position:absolute;left:679px;top:311px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C265<br></b></nobr>");
write("</p>");
write("<p id=\"p22_54\" class=\"drag\" style=\"position:absolute;left:709px;top:309px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p22_55\" class=\"drag\" style=\"position:absolute;left:718px;top:339px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_56\" class=\"drag\" style=\"position:absolute;left:718px;top:357px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_57\" class=\"drag\" style=\"position:absolute;left:737px;top:376px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_58\" class=\"drag\" style=\"position:absolute;left:700px;top:376px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_59\" class=\"drag\" style=\"position:absolute;left:714px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_60\" class=\"drag\" style=\"position:absolute;left:714px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_61\" class=\"drag\" style=\"position:absolute;left:507px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_62\" class=\"drag\" style=\"position:absolute;left:507px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_63\" class=\"drag\" style=\"position:absolute;left:492px;top:376px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_64\" class=\"drag\" style=\"position:absolute;left:530px;top:376px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_65\" class=\"drag\" style=\"position:absolute;left:511px;top:357px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_66\" class=\"drag\" style=\"position:absolute;left:511px;top:339px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_67\" class=\"drag\" style=\"position:absolute;left:314px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_68\" class=\"drag\" style=\"position:absolute;left:314px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_69\" class=\"drag\" style=\"position:absolute;left:228px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_70\" class=\"drag\" style=\"position:absolute;left:228px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p22_71\" class=\"drag\" style=\"position:absolute;left:287px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p22_72\" class=\"drag\" style=\"position:absolute;left:201px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p22_73\" class=\"drag\" style=\"position:absolute;left:314px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_74\" class=\"drag\" style=\"position:absolute;left:287px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p22_75\" class=\"drag\" style=\"position:absolute;left:287px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p22_76\" class=\"drag\" style=\"position:absolute;left:287px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p22_77\" class=\"drag\" style=\"position:absolute;left:287px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p22_78\" class=\"drag\" style=\"position:absolute;left:314px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_79\" class=\"drag\" style=\"position:absolute;left:287px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p22_80\" class=\"drag\" style=\"position:absolute;left:287px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p22_81\" class=\"drag\" style=\"position:absolute;left:314px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_82\" class=\"drag\" style=\"position:absolute;left:314px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_83\" class=\"drag\" style=\"position:absolute;left:228px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_84\" class=\"drag\" style=\"position:absolute;left:143px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_85\" class=\"drag\" style=\"position:absolute;left:143px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_86\" class=\"drag\" style=\"position:absolute;left:118px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p22_87\" class=\"drag\" style=\"position:absolute;left:204px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p22_88\" class=\"drag\" style=\"position:absolute;left:118px;top:479px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p22_89\" class=\"drag\" style=\"position:absolute;left:118px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_90\" class=\"drag\" style=\"position:absolute;left:118px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_91\" class=\"drag\" style=\"position:absolute;left:118px;top:436px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_92\" class=\"drag\" style=\"position:absolute;left:118px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p22_93\" class=\"drag\" style=\"position:absolute;left:118px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_94\" class=\"drag\" style=\"position:absolute;left:143px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p22_95\" class=\"drag\" style=\"position:absolute;left:204px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p22_96\" class=\"drag\" style=\"position:absolute;left:228px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p22_97\" class=\"drag\" style=\"position:absolute;left:201px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p22_98\" class=\"drag\" style=\"position:absolute;left:201px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p22_99\" class=\"drag\" style=\"position:absolute;left:201px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p22_100\" class=\"drag\" style=\"position:absolute;left:201px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p22_101\" class=\"drag\" style=\"position:absolute;left:143px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_102\" class=\"drag\" style=\"position:absolute;left:143px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_103\" class=\"drag\" style=\"position:absolute;left:143px;top:480px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_104\" class=\"drag\" style=\"position:absolute;left:228px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_105\" class=\"drag\" style=\"position:absolute;left:228px;top:437px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_106\" class=\"drag\" style=\"position:absolute;left:315px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p22_107\" class=\"drag\" style=\"position:absolute;left:318px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p22_108\" class=\"drag\" style=\"position:absolute;left:297px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p22_109\" class=\"drag\" style=\"position:absolute;left:111px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p22_110\" class=\"drag\" style=\"position:absolute;left:130px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p22_111\" class=\"drag\" style=\"position:absolute;left:132px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_112\" class=\"drag\" style=\"position:absolute;left:260px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p22_113\" class=\"drag\" style=\"position:absolute;left:281px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p22_114\" class=\"drag\" style=\"position:absolute;left:262px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p22_115\" class=\"drag\" style=\"position:absolute;left:185px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p22_116\" class=\"drag\" style=\"position:absolute;left:188px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p22_117\" class=\"drag\" style=\"position:absolute;left:167px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p22_118\" class=\"drag\" style=\"position:absolute;left:148px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p22_119\" class=\"drag\" style=\"position:absolute;left:151px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_120\" class=\"drag\" style=\"position:absolute;left:241px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p22_121\" class=\"drag\" style=\"position:absolute;left:278px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p22_122\" class=\"drag\" style=\"position:absolute;left:204px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p22_123\" class=\"drag\" style=\"position:absolute;left:169px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_124\" class=\"drag\" style=\"position:absolute;left:750px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_125\" class=\"drag\" style=\"position:absolute;left:664px;top:208px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_126\" class=\"drag\" style=\"position:absolute;left:724px;top:166px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p22_127\" class=\"drag\" style=\"position:absolute;left:724px;top:209px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p22_128\" class=\"drag\" style=\"position:absolute;left:749px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p22_129\" class=\"drag\" style=\"position:absolute;left:767px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p22_130\" class=\"drag\" style=\"position:absolute;left:711px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p22_131\" class=\"drag\" style=\"position:absolute;left:693px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p22_132\" class=\"drag\" style=\"position:absolute;left:658px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_133\" class=\"drag\" style=\"position:absolute;left:640px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p22_134\" class=\"drag\" style=\"position:absolute;left:677px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p22_135\" class=\"drag\" style=\"position:absolute;left:732px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_136\" class=\"drag\" style=\"position:absolute;left:730px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p22_137\" class=\"drag\" style=\"position:absolute;left:421px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p22_138\" class=\"drag\" style=\"position:absolute;left:397px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_139\" class=\"drag\" style=\"position:absolute;left:421px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_140\" class=\"drag\" style=\"position:absolute;left:397px;top:136px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_141\" class=\"drag\" style=\"position:absolute;left:397px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_142\" class=\"drag\" style=\"position:absolute;left:397px;top:179px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p22_143\" class=\"drag\" style=\"position:absolute;left:397px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_144\" class=\"drag\" style=\"position:absolute;left:421px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_145\" class=\"drag\" style=\"position:absolute;left:397px;top:193px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p22_146\" class=\"drag\" style=\"position:absolute;left:421px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_147\" class=\"drag\" style=\"position:absolute;left:392px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_148\" class=\"drag\" style=\"position:absolute;left:411px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_149\" class=\"drag\" style=\"position:absolute;left:448px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_150\" class=\"drag\" style=\"position:absolute;left:392px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_151\" class=\"drag\" style=\"position:absolute;left:228px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_152\" class=\"drag\" style=\"position:absolute;left:228px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_153\" class=\"drag\" style=\"position:absolute;left:228px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_154\" class=\"drag\" style=\"position:absolute;left:143px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_155\" class=\"drag\" style=\"position:absolute;left:143px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_156\" class=\"drag\" style=\"position:absolute;left:143px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_157\" class=\"drag\" style=\"position:absolute;left:143px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_158\" class=\"drag\" style=\"position:absolute;left:143px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_159\" class=\"drag\" style=\"position:absolute;left:201px;top:223px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p22_160\" class=\"drag\" style=\"position:absolute;left:201px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p22_161\" class=\"drag\" style=\"position:absolute;left:201px;top:208px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p22_162\" class=\"drag\" style=\"position:absolute;left:201px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p22_163\" class=\"drag\" style=\"position:absolute;left:201px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p22_164\" class=\"drag\" style=\"position:absolute;left:202px;top:195px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p22_165\" class=\"drag\" style=\"position:absolute;left:228px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_166\" class=\"drag\" style=\"position:absolute;left:118px;top:222px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p22_167\" class=\"drag\" style=\"position:absolute;left:204px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p22_168\" class=\"drag\" style=\"position:absolute;left:143px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p22_169\" class=\"drag\" style=\"position:absolute;left:118px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_170\" class=\"drag\" style=\"position:absolute;left:118px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p22_171\" class=\"drag\" style=\"position:absolute;left:118px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_172\" class=\"drag\" style=\"position:absolute;left:118px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_173\" class=\"drag\" style=\"position:absolute;left:118px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_174\" class=\"drag\" style=\"position:absolute;left:118px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p22_175\" class=\"drag\" style=\"position:absolute;left:201px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p22_176\" class=\"drag\" style=\"position:absolute;left:118px;top:208px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p22_177\" class=\"drag\" style=\"position:absolute;left:143px;top:208px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p22_178\" class=\"drag\" style=\"position:absolute;left:143px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_179\" class=\"drag\" style=\"position:absolute;left:228px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_180\" class=\"drag\" style=\"position:absolute;left:228px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_181\" class=\"drag\" style=\"position:absolute;left:210px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_182\" class=\"drag\" style=\"position:absolute;left:270px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p22_183\" class=\"drag\" style=\"position:absolute;left:152px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p22_184\" class=\"drag\" style=\"position:absolute;left:154px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_185\" class=\"drag\" style=\"position:absolute;left:114px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_186\" class=\"drag\" style=\"position:absolute;left:132px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_187\" class=\"drag\" style=\"position:absolute;left:132px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p22_188\" class=\"drag\" style=\"position:absolute;left:171px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p22_189\" class=\"drag\" style=\"position:absolute;left:189px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p22_190\" class=\"drag\" style=\"position:absolute;left:251px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p22_191\" class=\"drag\" style=\"position:absolute;left:232px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p22_192\" class=\"drag\" style=\"position:absolute;left:230px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p22_193\" class=\"drag\" style=\"position:absolute;left:114px;top:83px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p22_194\" class=\"drag\" style=\"position:absolute;left:502px;top:309px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p22_195\" class=\"drag\" style=\"position:absolute;left:92px;top:928px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>*6 : With inertia switch<br></b></nobr>");
write("</p>");
write("<p id=\"p22_196\" class=\"drag\" style=\"position:absolute;left:378px;top:723px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_197\" class=\"drag\" style=\"position:absolute;left:464px;top:737px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_198\" class=\"drag\" style=\"position:absolute;left:354px;top:737px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p22_199\" class=\"drag\" style=\"position:absolute;left:437px;top:723px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p22_200\" class=\"drag\" style=\"position:absolute;left:440px;top:680px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p22_201\" class=\"drag\" style=\"position:absolute;left:343px;top:582px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C381<br></b></nobr>");
write("</p>");
write("<p id=\"p22_202\" class=\"drag\" style=\"position:absolute;left:464px;top:694px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_203\" class=\"drag\" style=\"position:absolute;left:464px;top:680px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p22_204\" class=\"drag\" style=\"position:absolute;left:464px;top:709px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_205\" class=\"drag\" style=\"position:absolute;left:464px;top:723px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_206\" class=\"drag\" style=\"position:absolute;left:378px;top:737px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_207\" class=\"drag\" style=\"position:absolute;left:378px;top:694px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_208\" class=\"drag\" style=\"position:absolute;left:354px;top:722px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_209\" class=\"drag\" style=\"position:absolute;left:440px;top:694px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p22_210\" class=\"drag\" style=\"position:absolute;left:378px;top:709px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_211\" class=\"drag\" style=\"position:absolute;left:354px;top:708px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_212\" class=\"drag\" style=\"position:absolute;left:354px;top:694px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_213\" class=\"drag\" style=\"position:absolute;left:378px;top:680px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p22_214\" class=\"drag\" style=\"position:absolute;left:354px;top:680px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_215\" class=\"drag\" style=\"position:absolute;left:378px;top:766px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_216\" class=\"drag\" style=\"position:absolute;left:354px;top:765px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p22_217\" class=\"drag\" style=\"position:absolute;left:464px;top:751px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_218\" class=\"drag\" style=\"position:absolute;left:378px;top:751px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p22_219\" class=\"drag\" style=\"position:absolute;left:354px;top:751px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p22_220\" class=\"drag\" style=\"position:absolute;left:438px;top:709px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p22_221\" class=\"drag\" style=\"position:absolute;left:437px;top:751px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p22_222\" class=\"drag\" style=\"position:absolute;left:107px;top:311px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C263<br></b></nobr>");
write("</p>");
write("<p id=\"p22_223\" class=\"drag\" style=\"position:absolute;left:471px;top:311px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C264<br></b></nobr>");
write("</p>");
write("<p id=\"p22_224\" class=\"drag\" style=\"position:absolute;left:483px;top:451px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_225\" class=\"drag\" style=\"position:absolute;left:507px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_226\" class=\"drag\" style=\"position:absolute;left:483px;top:436px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_227\" class=\"drag\" style=\"position:absolute;left:483px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_228\" class=\"drag\" style=\"position:absolute;left:507px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_229\" class=\"drag\" style=\"position:absolute;left:483px;top:408px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_230\" class=\"drag\" style=\"position:absolute;left:750px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_231\" class=\"drag\" style=\"position:absolute;left:750px;top:208px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p22_232\" class=\"drag\" style=\"position:absolute;left:750px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p22_233\" class=\"drag\" style=\"position:absolute;left:750px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p22_234\" class=\"drag\" style=\"position:absolute;left:723px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p22_235\" class=\"drag\" style=\"position:absolute;left:723px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p22_236\" class=\"drag\" style=\"position:absolute;left:723px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p22_237\" class=\"drag\" style=\"position:absolute;left:621px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C262<br></b></nobr>");
write("</p>");
write("<p id=\"p22_238\" class=\"drag\" style=\"position:absolute;left:750px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p22_239\" class=\"drag\" style=\"position:absolute;left:726px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p22_240\" class=\"drag\" style=\"position:absolute;left:640px;top:208px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p22_241\" class=\"drag\" style=\"position:absolute;left:640px;top:194px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p22_242\" class=\"drag\" style=\"position:absolute;left:640px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p22_243\" class=\"drag\" style=\"position:absolute;left:640px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p22_244\" class=\"drag\" style=\"position:absolute;left:640px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p22_245\" class=\"drag\" style=\"position:absolute;left:640px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p22_246\" class=\"drag\" style=\"position:absolute;left:640px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p22_247\" class=\"drag\" style=\"position:absolute;left:664px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p22_248\" class=\"drag\" style=\"position:absolute;left:664px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p22_249\" class=\"drag\" style=\"position:absolute;left:726px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p22_250\" class=\"drag\" style=\"position:absolute;left:343px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C261<br></b></nobr>");
write("</p>");
write("<p id=\"p22_251\" class=\"drag\" style=\"position:absolute;left:107px;top:25px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C260<br></b></nobr>");
write("</p>");
write("<p id=\"p22_252\" class=\"drag\" style=\"position:absolute;left:107px;top:582px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C380<br></b></nobr>");
write("</p>");
write("<p id=\"p22_253\" class=\"drag\" style=\"position:absolute;left:169px;top:1035px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>* <br></b></nobr>");
write("</p>");
write("<p id=\"p22_254\" class=\"drag\" style=\"position:absolute;left:145px;top:1012px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p22_255\" class=\"drag\" style=\"position:absolute;left:145px;top:998px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p22_256\" class=\"drag\" style=\"position:absolute;left:145px;top:984px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p22_257\" class=\"drag\" style=\"position:absolute;left:90px;top:984px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p22_258\" class=\"drag\" style=\"position:absolute;left:185px;top:1012px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to ECM/PCM control.<br></b></nobr>");
write("</p>");
write("<p id=\"p22_259\" class=\"drag\" style=\"position:absolute;left:159px;top:998px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with female terminals (single outline) : View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p22_260\" class=\"drag\" style=\"position:absolute;left:159px;top:984px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with male terminals (double outline) : View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p22_261\" class=\"drag\" style=\"position:absolute;left:185px;top:1035px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Terminal side of female terminals<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}