with(document) {
write("<v:group id=\"group20\" class=\"drag\" style=\"position:relative; width:950px; height:1063px;\" coordsize=\"950,1063\">");
write("<v:rect id=\"rect20\"class=\"drag\"  style=\"width:950px;height:1063px;\">");
write("<img id=\"img20\" src=\"../img/SAA5ES0A20300000000DBAD67.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1063px;border-color:#ffffff\">");
write("<p id=\"p20_1\" class=\"drag\" style=\"position:absolute;left:81px;top:906px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>*6 : Except IN model<br></b></nobr>");
write("</p>");
write("<p id=\"p20_2\" class=\"drag\" style=\"position:absolute;left:616px;top:453px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p20_3\" class=\"drag\" style=\"position:absolute;left:691px;top:352px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p20_4\" class=\"drag\" style=\"position:absolute;left:131px;top:309px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p20_5\" class=\"drag\" style=\"position:absolute;left:675px;top:467px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p20_6\" class=\"drag\" style=\"position:absolute;left:675px;top:497px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p20_7\" class=\"drag\" style=\"position:absolute;left:675px;top:483px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p20_8\" class=\"drag\" style=\"position:absolute;left:592px;top:481px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p20_9\" class=\"drag\" style=\"position:absolute;left:616px;top:468px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p20_10\" class=\"drag\" style=\"position:absolute;left:702px;top:482px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p20_11\" class=\"drag\" style=\"position:absolute;left:702px;top:496px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p20_12\" class=\"drag\" style=\"position:absolute;left:592px;top:496px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p20_13\" class=\"drag\" style=\"position:absolute;left:616px;top:496px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p20_14\" class=\"drag\" style=\"position:absolute;left:592px;top:410px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p20_15\" class=\"drag\" style=\"position:absolute;left:616px;top:410px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p20_16\" class=\"drag\" style=\"position:absolute;left:592px;top:424px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p20_17\" class=\"drag\" style=\"position:absolute;left:592px;top:438px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p20_18\" class=\"drag\" style=\"position:absolute;left:616px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p20_19\" class=\"drag\" style=\"position:absolute;left:677px;top:424px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p20_20\" class=\"drag\" style=\"position:absolute;left:592px;top:453px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p20_21\" class=\"drag\" style=\"position:absolute;left:616px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p20_22\" class=\"drag\" style=\"position:absolute;left:702px;top:453px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p20_23\" class=\"drag\" style=\"position:absolute;left:702px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p20_24\" class=\"drag\" style=\"position:absolute;left:702px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p20_25\" class=\"drag\" style=\"position:absolute;left:711px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p20_26\" class=\"drag\" style=\"position:absolute;left:730px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p20_27\" class=\"drag\" style=\"position:absolute;left:713px;top:352px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p20_28\" class=\"drag\" style=\"position:absolute;left:670px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p20_29\" class=\"drag\" style=\"position:absolute;left:652px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p20_30\" class=\"drag\" style=\"position:absolute;left:613px;top:352px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p20_31\" class=\"drag\" style=\"position:absolute;left:595px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p20_32\" class=\"drag\" style=\"position:absolute;left:595px;top:352px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p20_33\" class=\"drag\" style=\"position:absolute;left:635px;top:352px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p20_34\" class=\"drag\" style=\"position:absolute;left:635px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p20_35\" class=\"drag\" style=\"position:absolute;left:580px;top:313px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C306<br></b></nobr>");
write("</p>");
write("<p id=\"p20_36\" class=\"drag\" style=\"position:absolute;left:689px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p20_37\" class=\"drag\" style=\"position:absolute;left:677px;top:410px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p20_38\" class=\"drag\" style=\"position:absolute;left:675px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p20_39\" class=\"drag\" style=\"position:absolute;left:675px;top:453px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p20_40\" class=\"drag\" style=\"position:absolute;left:592px;top:467px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p20_41\" class=\"drag\" style=\"position:absolute;left:702px;top:468px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p20_42\" class=\"drag\" style=\"position:absolute;left:81px;top:935px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>*10 : Except KE, KN models<br></b></nobr>");
write("</p>");
write("<p id=\"p20_43\" class=\"drag\" style=\"position:absolute;left:197px;top:168px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p20_44\" class=\"drag\" style=\"position:absolute;left:223px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p20_45\" class=\"drag\" style=\"position:absolute;left:173px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p20_46\" class=\"drag\" style=\"position:absolute;left:81px;top:920px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>*9 : KE, KN models<br></b></nobr>");
write("</p>");
write("<p id=\"p20_47\" class=\"drag\" style=\"position:absolute;left:222px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN*<sup>10</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p20_48\" class=\"drag\" style=\"position:absolute;left:120px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p20_49\" class=\"drag\" style=\"position:absolute;left:389px;top:23px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p20_50\" class=\"drag\" style=\"position:absolute;left:101px;top:313px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C218<br></b></nobr>");
write("</p>");
write("<p id=\"p20_51\" class=\"drag\" style=\"position:absolute;left:132px;top:355px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p20_52\" class=\"drag\" style=\"position:absolute;left:151px;top:355px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p20_53\" class=\"drag\" style=\"position:absolute;left:151px;top:374px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p20_54\" class=\"drag\" style=\"position:absolute;left:132px;top:374px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p20_55\" class=\"drag\" style=\"position:absolute;left:113px;top:410px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p20_56\" class=\"drag\" style=\"position:absolute;left:137px;top:410px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p20_57\" class=\"drag\" style=\"position:absolute;left:137px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p20_58\" class=\"drag\" style=\"position:absolute;left:113px;top:424px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p20_59\" class=\"drag\" style=\"position:absolute;left:113px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p20_60\" class=\"drag\" style=\"position:absolute;left:137px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p20_61\" class=\"drag\" style=\"position:absolute;left:137px;top:453px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p20_62\" class=\"drag\" style=\"position:absolute;left:113px;top:453px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p20_63\" class=\"drag\" style=\"position:absolute;left:730px;top:27px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C217<br></b></nobr>");
write("</p>");
write("<p id=\"p20_64\" class=\"drag\" style=\"position:absolute;left:751px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p20_65\" class=\"drag\" style=\"position:absolute;left:769px;top:63px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p20_66\" class=\"drag\" style=\"position:absolute;left:761px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p20_67\" class=\"drag\" style=\"position:absolute;left:779px;top:81px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p20_68\" class=\"drag\" style=\"position:absolute;left:742px;top:124px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p20_69\" class=\"drag\" style=\"position:absolute;left:742px;top:138px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p20_70\" class=\"drag\" style=\"position:absolute;left:742px;top:153px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p20_71\" class=\"drag\" style=\"position:absolute;left:742px;top:167px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p20_72\" class=\"drag\" style=\"position:absolute;left:742px;top:181px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p20_73\" class=\"drag\" style=\"position:absolute;left:766px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p20_74\" class=\"drag\" style=\"position:absolute;left:766px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p20_75\" class=\"drag\" style=\"position:absolute;left:766px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p20_76\" class=\"drag\" style=\"position:absolute;left:766px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p20_77\" class=\"drag\" style=\"position:absolute;left:570px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p20_78\" class=\"drag\" style=\"position:absolute;left:600px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p20_79\" class=\"drag\" style=\"position:absolute;left:544px;top:27px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C209<br></b></nobr>");
write("</p>");
write("<p id=\"p20_80\" class=\"drag\" style=\"position:absolute;left:556px;top:167px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p20_81\" class=\"drag\" style=\"position:absolute;left:580px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p20_82\" class=\"drag\" style=\"position:absolute;left:556px;top:153px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p20_83\" class=\"drag\" style=\"position:absolute;left:556px;top:138px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p20_84\" class=\"drag\" style=\"position:absolute;left:580px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p20_85\" class=\"drag\" style=\"position:absolute;left:556px;top:124px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p20_86\" class=\"drag\" style=\"position:absolute;left:101px;top:27px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C204<br></b></nobr>");
write("</p>");
write("<p id=\"p20_87\" class=\"drag\" style=\"position:absolute;left:137px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p20_88\" class=\"drag\" style=\"position:absolute;left:137px;top:210px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p20_89\" class=\"drag\" style=\"position:absolute;left:113px;top:210px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p20_90\" class=\"drag\" style=\"position:absolute;left:196px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p20_91\" class=\"drag\" style=\"position:absolute;left:113px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p20_92\" class=\"drag\" style=\"position:absolute;left:113px;top:124px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p20_93\" class=\"drag\" style=\"position:absolute;left:113px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p20_94\" class=\"drag\" style=\"position:absolute;left:113px;top:153px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p20_95\" class=\"drag\" style=\"position:absolute;left:113px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p20_96\" class=\"drag\" style=\"position:absolute;left:113px;top:167px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p20_97\" class=\"drag\" style=\"position:absolute;left:137px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p20_98\" class=\"drag\" style=\"position:absolute;left:199px;top:124px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p20_99\" class=\"drag\" style=\"position:absolute;left:113px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p20_100\" class=\"drag\" style=\"position:absolute;left:223px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p20_101\" class=\"drag\" style=\"position:absolute;left:197px;top:225px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p20_102\" class=\"drag\" style=\"position:absolute;left:223px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p20_103\" class=\"drag\" style=\"position:absolute;left:196px;top:153px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p20_104\" class=\"drag\" style=\"position:absolute;left:196px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p20_105\" class=\"drag\" style=\"position:absolute;left:196px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p20_106\" class=\"drag\" style=\"position:absolute;left:196px;top:210px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p20_107\" class=\"drag\" style=\"position:absolute;left:231px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p20_108\" class=\"drag\" style=\"position:absolute;left:194px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p20_109\" class=\"drag\" style=\"position:absolute;left:175px;top:66px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p20_110\" class=\"drag\" style=\"position:absolute;left:210px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p20_111\" class=\"drag\" style=\"position:absolute;left:247px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p20_112\" class=\"drag\" style=\"position:absolute;left:133px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p20_113\" class=\"drag\" style=\"position:absolute;left:370px;top:138px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p20_114\" class=\"drag\" style=\"position:absolute;left:394px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p20_115\" class=\"drag\" style=\"position:absolute;left:394px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p20_116\" class=\"drag\" style=\"position:absolute;left:370px;top:124px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p20_117\" class=\"drag\" style=\"position:absolute;left:408px;top:79px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p20_118\" class=\"drag\" style=\"position:absolute;left:389px;top:79px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p20_119\" class=\"drag\" style=\"position:absolute;left:359px;top:27px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C205<br></b></nobr>");
write("</p>");
write("<p id=\"p20_120\" class=\"drag\" style=\"position:absolute;left:356px;top:410px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p20_121\" class=\"drag\" style=\"position:absolute;left:380px;top:410px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p20_122\" class=\"drag\" style=\"position:absolute;left:380px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p20_123\" class=\"drag\" style=\"position:absolute;left:356px;top:424px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p20_124\" class=\"drag\" style=\"position:absolute;left:356px;top:438px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p20_125\" class=\"drag\" style=\"position:absolute;left:380px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p20_126\" class=\"drag\" style=\"position:absolute;left:403px;top:364px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p20_127\" class=\"drag\" style=\"position:absolute;left:385px;top:364px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p20_128\" class=\"drag\" style=\"position:absolute;left:366px;top:364px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p20_129\" class=\"drag\" style=\"position:absolute;left:344px;top:313px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C305<br></b></nobr>");
write("</p>");
write("<p id=\"p20_130\" class=\"drag\" style=\"position:absolute;left:161px;top:1029px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>* <br></b></nobr>");
write("</p>");
write("<p id=\"p20_131\" class=\"drag\" style=\"position:absolute;left:137px;top:1007px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p20_132\" class=\"drag\" style=\"position:absolute;left:137px;top:992px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p20_133\" class=\"drag\" style=\"position:absolute;left:137px;top:978px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p20_134\" class=\"drag\" style=\"position:absolute;left:83px;top:978px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p20_135\" class=\"drag\" style=\"position:absolute;left:177px;top:1007px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to ECM/PCM control.<br></b></nobr>");
write("</p>");
write("<p id=\"p20_136\" class=\"drag\" style=\"position:absolute;left:152px;top:992px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with female terminals (single outline) : View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p20_137\" class=\"drag\" style=\"position:absolute;left:152px;top:978px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with male terminals (double outline) : View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p20_138\" class=\"drag\" style=\"position:absolute;left:178px;top:1030px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Terminal side of female terminals<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}