with(document) {
write("<v:group id=\"group8\" class=\"drag\" style=\"position:relative; width:950px; height:1063px;\" coordsize=\"950,1063\">");
write("<v:rect id=\"rect8\"class=\"drag\"  style=\"width:950px;height:1063px;\">");
write("<img id=\"img8\" src=\"../img/SAA5ES0A20300000000DBADB5.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1063px;border-color:#ffffff\">");
write("<p id=\"p8_1\" class=\"drag\" style=\"position:absolute;left:287px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_2\" class=\"drag\" style=\"position:absolute;left:287px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_3\" class=\"drag\" style=\"position:absolute;left:287px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_4\" class=\"drag\" style=\"position:absolute;left:287px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_5\" class=\"drag\" style=\"position:absolute;left:287px;top:211px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_6\" class=\"drag\" style=\"position:absolute;left:260px;top:211px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p8_7\" class=\"drag\" style=\"position:absolute;left:260px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p8_8\" class=\"drag\" style=\"position:absolute;left:260px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p8_9\" class=\"drag\" style=\"position:absolute;left:260px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p8_10\" class=\"drag\" style=\"position:absolute;left:260px;top:153px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p8_11\" class=\"drag\" style=\"position:absolute;left:174px;top:239px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p8_12\" class=\"drag\" style=\"position:absolute;left:201px;top:211px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_13\" class=\"drag\" style=\"position:absolute;left:201px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_14\" class=\"drag\" style=\"position:absolute;left:201px;top:239px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_15\" class=\"drag\" style=\"position:absolute;left:287px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_16\" class=\"drag\" style=\"position:absolute;left:287px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_17\" class=\"drag\" style=\"position:absolute;left:174px;top:211px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p8_18\" class=\"drag\" style=\"position:absolute;left:175px;top:226px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p8_19\" class=\"drag\" style=\"position:absolute;left:260px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p8_20\" class=\"drag\" style=\"position:absolute;left:260px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p8_21\" class=\"drag\" style=\"position:absolute;left:174px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p8_22\" class=\"drag\" style=\"position:absolute;left:174px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p8_23\" class=\"drag\" style=\"position:absolute;left:174px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p8_24\" class=\"drag\" style=\"position:absolute;left:174px;top:153px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_25\" class=\"drag\" style=\"position:absolute;left:174px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_26\" class=\"drag\" style=\"position:absolute;left:201px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_27\" class=\"drag\" style=\"position:absolute;left:201px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_28\" class=\"drag\" style=\"position:absolute;left:201px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_29\" class=\"drag\" style=\"position:absolute;left:201px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p8_30\" class=\"drag\" style=\"position:absolute;left:110px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2, *4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_31\" class=\"drag\" style=\"position:absolute;left:91px;top:239px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_32\" class=\"drag\" style=\"position:absolute;left:91px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_33\" class=\"drag\" style=\"position:absolute;left:91px;top:211px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_34\" class=\"drag\" style=\"position:absolute;left:91px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_35\" class=\"drag\" style=\"position:absolute;left:174px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p8_36\" class=\"drag\" style=\"position:absolute;left:115px;top:211px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_37\" class=\"drag\" style=\"position:absolute;left:115px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_38\" class=\"drag\" style=\"position:absolute;left:201px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_39\" class=\"drag\" style=\"position:absolute;left:91px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_40\" class=\"drag\" style=\"position:absolute;left:122px;top:61px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p8_41\" class=\"drag\" style=\"position:absolute;left:122px;top:89px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p8_42\" class=\"drag\" style=\"position:absolute;left:140px;top:61px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p8_43\" class=\"drag\" style=\"position:absolute;left:140px;top:89px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p8_44\" class=\"drag\" style=\"position:absolute;left:159px;top:57px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p8_45\" class=\"drag\" style=\"position:absolute;left:159px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p8_46\" class=\"drag\" style=\"position:absolute;left:159px;top:94px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p8_47\" class=\"drag\" style=\"position:absolute;left:177px;top:57px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p8_48\" class=\"drag\" style=\"position:absolute;left:177px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p8_49\" class=\"drag\" style=\"position:absolute;left:177px;top:94px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p8_50\" class=\"drag\" style=\"position:absolute;left:196px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p8_51\" class=\"drag\" style=\"position:absolute;left:196px;top:94px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p8_52\" class=\"drag\" style=\"position:absolute;left:215px;top:57px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p8_53\" class=\"drag\" style=\"position:absolute;left:215px;top:75px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_54\" class=\"drag\" style=\"position:absolute;left:215px;top:94px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_55\" class=\"drag\" style=\"position:absolute;left:236px;top:57px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_56\" class=\"drag\" style=\"position:absolute;left:254px;top:57px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_57\" class=\"drag\" style=\"position:absolute;left:273px;top:57px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_58\" class=\"drag\" style=\"position:absolute;left:273px;top:94px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_59\" class=\"drag\" style=\"position:absolute;left:254px;top:94px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_60\" class=\"drag\" style=\"position:absolute;left:253px;top:282px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2, * <br></b></nobr>");
write("</p>");
write("<p id=\"p8_61\" class=\"drag\" style=\"position:absolute;left:396px;top:282px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2, * <br></b></nobr>");
write("</p>");
write("<p id=\"p8_62\" class=\"drag\" style=\"position:absolute;left:377px;top:382px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_63\" class=\"drag\" style=\"position:absolute;left:401px;top:382px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_64\" class=\"drag\" style=\"position:absolute;left:406px;top:329px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_65\" class=\"drag\" style=\"position:absolute;left:365px;top:284px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C373<br></b></nobr>");
write("</p>");
write("<p id=\"p8_66\" class=\"drag\" style=\"position:absolute;left:748px;top:418px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_67\" class=\"drag\" style=\"position:absolute;left:748px;top:375px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_68\" class=\"drag\" style=\"position:absolute;left:773px;top:375px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_69\" class=\"drag\" style=\"position:absolute;left:748px;top:389px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_70\" class=\"drag\" style=\"position:absolute;left:748px;top:403px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_71\" class=\"drag\" style=\"position:absolute;left:751px;top:322px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_72\" class=\"drag\" style=\"position:absolute;left:737px;top:277px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C375<br></b></nobr>");
write("</p>");
write("<p id=\"p8_73\" class=\"drag\" style=\"position:absolute;left:768px;top:275px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2, * <br></b></nobr>");
write("</p>");
write("<p id=\"p8_74\" class=\"drag\" style=\"position:absolute;left:603px;top:432px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p8_75\" class=\"drag\" style=\"position:absolute;left:234px;top:382px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_76\" class=\"drag\" style=\"position:absolute;left:258px;top:382px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_77\" class=\"drag\" style=\"position:absolute;left:234px;top:396px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_78\" class=\"drag\" style=\"position:absolute;left:263px;top:324px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_79\" class=\"drag\" style=\"position:absolute;left:222px;top:284px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C372<br></b></nobr>");
write("</p>");
write("<p id=\"p8_80\" class=\"drag\" style=\"position:absolute;left:110px;top:282px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2, * <br></b></nobr>");
write("</p>");
write("<p id=\"p8_81\" class=\"drag\" style=\"position:absolute;left:79px;top:284px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C371<br></b></nobr>");
write("</p>");
write("<p id=\"p8_82\" class=\"drag\" style=\"position:absolute;left:94px;top:329px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_83\" class=\"drag\" style=\"position:absolute;left:91px;top:410px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_84\" class=\"drag\" style=\"position:absolute;left:91px;top:396px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_85\" class=\"drag\" style=\"position:absolute;left:115px;top:382px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_86\" class=\"drag\" style=\"position:absolute;left:91px;top:382px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_87\" class=\"drag\" style=\"position:absolute;left:91px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_88\" class=\"drag\" style=\"position:absolute;left:768px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_89\" class=\"drag\" style=\"position:absolute;left:611px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_90\" class=\"drag\" style=\"position:absolute;left:434px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_91\" class=\"drag\" style=\"position:absolute;left:458px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_92\" class=\"drag\" style=\"position:absolute;left:458px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_93\" class=\"drag\" style=\"position:absolute;left:434px;top:124px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_94\" class=\"drag\" style=\"position:absolute;left:472px;top:80px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_95\" class=\"drag\" style=\"position:absolute;left:453px;top:80px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_96\" class=\"drag\" style=\"position:absolute;left:422px;top:27px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C302<br></b></nobr>");
write("</p>");
write("<p id=\"p8_97\" class=\"drag\" style=\"position:absolute;left:580px;top:27px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C303<br></b></nobr>");
write("</p>");
write("<p id=\"p8_98\" class=\"drag\" style=\"position:absolute;left:629px;top:80px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_99\" class=\"drag\" style=\"position:absolute;left:591px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_100\" class=\"drag\" style=\"position:absolute;left:615px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_101\" class=\"drag\" style=\"position:absolute;left:591px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_102\" class=\"drag\" style=\"position:absolute;left:539px;top:275px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2, * <br></b></nobr>");
write("</p>");
write("<p id=\"p8_103\" class=\"drag\" style=\"position:absolute;left:605px;top:418px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p8_104\" class=\"drag\" style=\"position:absolute;left:605px;top:403px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_105\" class=\"drag\" style=\"position:absolute;left:605px;top:389px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_106\" class=\"drag\" style=\"position:absolute;left:605px;top:375px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_107\" class=\"drag\" style=\"position:absolute;left:520px;top:431px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_108\" class=\"drag\" style=\"position:absolute;left:591px;top:318px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_109\" class=\"drag\" style=\"position:absolute;left:628px;top:318px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_110\" class=\"drag\" style=\"position:absolute;left:520px;top:417px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_111\" class=\"drag\" style=\"position:absolute;left:544px;top:432px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_112\" class=\"drag\" style=\"position:absolute;left:544px;top:404px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_113\" class=\"drag\" style=\"position:absolute;left:520px;top:403px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_114\" class=\"drag\" style=\"position:absolute;left:520px;top:389px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_115\" class=\"drag\" style=\"position:absolute;left:544px;top:389px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_116\" class=\"drag\" style=\"position:absolute;left:520px;top:374px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_117\" class=\"drag\" style=\"position:absolute;left:573px;top:318px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_118\" class=\"drag\" style=\"position:absolute;left:508px;top:277px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C374<br></b></nobr>");
write("</p>");
write("<p id=\"p8_119\" class=\"drag\" style=\"position:absolute;left:453px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_120\" class=\"drag\" style=\"position:absolute;left:749px;top:124px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_121\" class=\"drag\" style=\"position:absolute;left:773px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_122\" class=\"drag\" style=\"position:absolute;left:773px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_123\" class=\"drag\" style=\"position:absolute;left:749px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_124\" class=\"drag\" style=\"position:absolute;left:749px;top:153px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_125\" class=\"drag\" style=\"position:absolute;left:773px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_126\" class=\"drag\" style=\"position:absolute;left:796px;top:79px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_127\" class=\"drag\" style=\"position:absolute;left:777px;top:79px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_128\" class=\"drag\" style=\"position:absolute;left:758px;top:79px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_129\" class=\"drag\" style=\"position:absolute;left:737px;top:27px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C304<br></b></nobr>");
write("</p>");
write("<p id=\"p8_130\" class=\"drag\" style=\"position:absolute;left:79px;top:27px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C301<br></b></nobr>");
write("</p>");
write("<p id=\"p8_131\" class=\"drag\" style=\"position:absolute;left:91px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_132\" class=\"drag\" style=\"position:absolute;left:115px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_133\" class=\"drag\" style=\"position:absolute;left:91px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_134\" class=\"drag\" style=\"position:absolute;left:91px;top:153px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_135\" class=\"drag\" style=\"position:absolute;left:115px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_136\" class=\"drag\" style=\"position:absolute;left:115px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_137\" class=\"drag\" style=\"position:absolute;left:91px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_138\" class=\"drag\" style=\"position:absolute;left:144px;top:1024px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>* <br></b></nobr>");
write("</p>");
write("<p id=\"p8_139\" class=\"drag\" style=\"position:absolute;left:120px;top:1001px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p8_140\" class=\"drag\" style=\"position:absolute;left:120px;top:987px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p8_141\" class=\"drag\" style=\"position:absolute;left:120px;top:973px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p8_142\" class=\"drag\" style=\"position:absolute;left:66px;top:973px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p8_143\" class=\"drag\" style=\"position:absolute;left:160px;top:1001px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to ECM/PCM control.<br></b></nobr>");
write("</p>");
write("<p id=\"p8_144\" class=\"drag\" style=\"position:absolute;left:135px;top:987px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with female terminals (single outline) : View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p8_145\" class=\"drag\" style=\"position:absolute;left:135px;top:973px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with male terminals (double outline) : View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p8_146\" class=\"drag\" style=\"position:absolute;left:161px;top:1025px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Terminal side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p8_147\" class=\"drag\" style=\"position:absolute;left:66px;top:923px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>*2 : RHD<br></b></nobr>");
write("</p>");
write("<p id=\"p8_148\" class=\"drag\" style=\"position:absolute;left:66px;top:937px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>*4 : CVT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}