with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" src=\"../img/SAA5ET0K80100081110FAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:88px;top:14px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>VSA CONTROL UNIT 46P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:36px;top:63px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RR-GND (BLU/YEL)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:24px;top:36px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RL-GND (GRY/RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:84px;top:147px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FR-GND<br>(BLU)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:107px;top:183px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FR +B<br>(GRN/<br>BLK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:225px;top:150px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FL +B (BLU/ORN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:228px;top:63px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FL-GND (BRN/WHT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:205px;top:37px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RL +B (YEL/RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:181px;top:173px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RR +B (GRN/YEL)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:127px;top:290px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}