with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:995px;\" coordsize=\"950,995\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:995px;\">");
write("<img id=\"img1\" src=\"../img/SAA5ET2E15110700000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:995px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:495px;top:405px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>To 5V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:183px;top:59px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.3 (50A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:483px;top:394px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:483px;top:377px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>E9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:115px;top:59px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.1 (80A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:375px;top:459px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>POWERTRAIN CONTROL MODULE (PCM)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:44px;top:51px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:711px;top:516px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ATP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:711px;top:525px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:711px;top:542px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:699px;top:574px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:456px;top:666px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:230px;top:732px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:317px;top:62px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:463px;top:643px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:457px;top:620px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:185px;top:577px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:258px;top:39px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:168px;top:866px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:654px;top:542px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:641px;top:562px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:654px;top:525px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:654px;top:516px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ATP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:370px;top:59px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.11 (15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:139px;top:900px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:136px;top:957px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:769px;top:525px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:859px;top:831px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:856px;top:889px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:435px;top:660px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>B12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:435px;top:637px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:756px;top:574px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:718px;top:563px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:740px;top:525px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:769px;top:516px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ATP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:769px;top:542px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:740px;top:542px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:740px;top:516px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ATP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:248px;top:62px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:836px;top:136px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:790px;top:136px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:349px;top:716px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:349px;top:665px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:349px;top:642px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:349px;top:619px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:349px;top:690px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:465px;top:740px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:435px;top:712px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:455px;top:717px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:435px;top:735px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:435px;top:695px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:578px;top:643px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:517px;top:525px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>D IND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:504px;top:562px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:517px;top:542px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>E11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:568px;top:377px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:568px;top:394px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>M−SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:757px;top:377px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:757px;top:394px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>S−DN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:849px;top:377px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:849px;top:394px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>S−UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:435px;top:757px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>B11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:454px;top:763px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:603px;top:694px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:660px;top:694px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:557px;top:542px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:557px;top:525px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>M IND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:534px;top:563px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:168px;top:603px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:168px;top:626px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:168px;top:649px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>B5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:139px;top:563px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:162px;top:525px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LED C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:162px;top:542px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>E20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:128px;top:542px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>E21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:105px;top:574px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:128px;top:525px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LED B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:94px;top:525px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LED A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:72px;top:563px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:94px;top:542px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>E8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:168px;top:735px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:349px;top:739px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:348px;top:762px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:88px;top:39px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:810px;top:68px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>S−UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:837px;top:168px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:791px;top:168px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:837px;top:294px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:836px;top:267px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:836px;top:214px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:744px;top:214px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:744px;top:267px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:727px;top:294px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:727px;top:357px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:837px;top:357px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:719px;top:68px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>S−DN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:698px;top:136px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:744px;top:136px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:699px;top:168px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:727px;top:169px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:557px;top:62px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>7SPEED MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:546px;top:39px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>7SPEED MODE MAIN SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:545px;top:168px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:602px;top:168px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:556px;top:136px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:601px;top:136px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:624px;top:136px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:647px;top:136px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:556px;top:214px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:601px;top:214px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:556px;top:267px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:601px;top:267px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:599px;top:323px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:602px;top:277px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:545px;top:294px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:556px;top:357px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:461px;top:300px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:404px;top:300px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:409px;top:182px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>KQ model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:826px;top:794px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:797px;top:794px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:711px;top:800px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:603px;top:897px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>TRANSMISSION RANGE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:683px;top:800px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:654px;top:811px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:626px;top:828px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:809px;top:775px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:784px;top:775px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:727px;top:775px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:698px;top:775px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:670px;top:775px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:641px;top:775px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:613px;top:775px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:740px;top:811px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:769px;top:828px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:756px;top:775px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:777px;top:563px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:797px;top:542px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:797px;top:516px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ATP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:797px;top:525px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>NP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:435px;top:615px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:569px;top:717px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:579px;top:740px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:369px;top:88px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.16 (7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:242px;top:151px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:550px;top:454px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>To 12V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:110px;top:740px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:340px;top:30px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:789px;top:41px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>STEERING SHIFT <br>+(PLUS) SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:698px;top:41px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>STEERING SHIFT <br>−(MINUS) SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:494px;top:234px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>FUEL <br>CUTOFF <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:493px;top:173px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>KB, KE, <br>KG models<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:225px;top:628px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INPUT <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:290px;top:685px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DIMMING <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:220px;top:857px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SHIFT <br>INDICATOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}