with(document) {
write("<v:group id=\"group4\" class=\"drag\" style=\"position:relative; width:950px; height:1119px;\" coordsize=\"950,1119\">");
write("<v:rect id=\"rect4\"class=\"drag\"  style=\"width:950px;height:1119px;\">");
write("<img id=\"img4\" src=\"../img/SAA5EGAA20300000000EAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1119px;border-color:#ffffff\">");
write("<p id=\"p4_1\" class=\"drag\" style=\"position:absolute;left:414px;top:192px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E31<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" class=\"drag\" style=\"position:absolute;left:217px;top:69px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" class=\"drag\" style=\"position:absolute;left:391px;top:180px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MIL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" class=\"drag\" style=\"position:absolute;left:417px;top:253px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E5<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" class=\"drag\" style=\"position:absolute;left:389px;top:239px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FUP<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" class=\"drag\" style=\"position:absolute;left:413px;top:313px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E24<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" class=\"drag\" style=\"position:absolute;left:368px;top:300px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MTRTW<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" class=\"drag\" style=\"position:absolute;left:834px;top:278px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EVAP CANISTER<br>PURGE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" class=\"drag\" style=\"position:absolute;left:844px;top:474px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ALTERNATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" class=\"drag\" style=\"position:absolute;left:569px;top:377px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" class=\"drag\" style=\"position:absolute;left:570px;top:423px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B18<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" class=\"drag\" style=\"position:absolute;left:612px;top:377px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" class=\"drag\" style=\"position:absolute;left:589px;top:362px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ALTF<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" class=\"drag\" style=\"position:absolute;left:614px;top:423px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" class=\"drag\" style=\"position:absolute;left:589px;top:409px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ALTC<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" class=\"drag\" style=\"position:absolute;left:613px;top:258px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" class=\"drag\" style=\"position:absolute;left:570px;top:258px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B21<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" class=\"drag\" style=\"position:absolute;left:588px;top:243px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PCS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" class=\"drag\" style=\"position:absolute;left:572px;top:761px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_20\" class=\"drag\" style=\"position:absolute;left:572px;top:726px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p4_21\" class=\"drag\" style=\"position:absolute;left:592px;top:714px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PG1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_22\" class=\"drag\" style=\"position:absolute;left:592px;top:749px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PG2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_23\" class=\"drag\" style=\"position:absolute;left:853px;top:583px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EVAPORATOR<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_24\" class=\"drag\" style=\"position:absolute;left:573px;top:602px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_25\" class=\"drag\" style=\"position:absolute;left:569px;top:547px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E12<br></b></nobr>");
write("</p>");
write("<p id=\"p4_26\" class=\"drag\" style=\"position:absolute;left:589px;top:534px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TAC<br></b></nobr>");
write("</p>");
write("<p id=\"p4_27\" class=\"drag\" style=\"position:absolute;left:589px;top:590px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SG3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_28\" class=\"drag\" style=\"position:absolute;left:641px;top:547px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_29\" class=\"drag\" style=\"position:absolute;left:641px;top:603px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_30\" class=\"drag\" style=\"position:absolute;left:819px;top:664px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To CLIMATE <br>CONTROL UNIT<br>(With CLIMATE<br>CONTROL)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_31\" class=\"drag\" style=\"position:absolute;left:815px;top:219px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C119<br></b></nobr>");
write("</p>");
write("<p id=\"p4_32\" class=\"drag\" style=\"position:absolute;left:803px;top:320px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C122<br></b></nobr>");
write("</p>");
write("<p id=\"p4_33\" class=\"drag\" style=\"position:absolute;left:711px;top:519px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C203<br></b></nobr>");
write("</p>");
write("<p id=\"p4_34\" class=\"drag\" style=\"position:absolute;left:749px;top:519px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C401<br></b></nobr>");
write("</p>");
write("<p id=\"p4_35\" class=\"drag\" style=\"position:absolute;left:830px;top:528px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C402<br></b></nobr>");
write("</p>");
write("<p id=\"p4_36\" class=\"drag\" style=\"position:absolute;left:684px;top:491px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p4_37\" class=\"drag\" style=\"position:absolute;left:744px;top:242px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_38\" class=\"drag\" style=\"position:absolute;left:743px;top:348px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_39\" class=\"drag\" style=\"position:absolute;left:778px;top:547px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_40\" class=\"drag\" style=\"position:absolute;left:779px;top:603px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_41\" class=\"drag\" style=\"position:absolute;left:677px;top:530px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_42\" class=\"drag\" style=\"position:absolute;left:745px;top:676px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_43\" class=\"drag\" style=\"position:absolute;left:569px;top:876px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A23<br></b></nobr>");
write("</p>");
write("<p id=\"p4_44\" class=\"drag\" style=\"position:absolute;left:569px;top:842px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A24<br></b></nobr>");
write("</p>");
write("<p id=\"p4_45\" class=\"drag\" style=\"position:absolute;left:592px;top:830px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LG1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_46\" class=\"drag\" style=\"position:absolute;left:631px;top:842px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_47\" class=\"drag\" style=\"position:absolute;left:592px;top:865px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LG2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_48\" class=\"drag\" style=\"position:absolute;left:776px;top:804px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p4_49\" class=\"drag\" style=\"position:absolute;left:640px;top:725px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_50\" class=\"drag\" style=\"position:absolute;left:870px;top:922px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p4_51\" class=\"drag\" style=\"position:absolute;left:776px;top:927px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p4_52\" class=\"drag\" style=\"position:absolute;left:870px;top:805px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p4_53\" class=\"drag\" style=\"position:absolute;left:640px;top:761px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_54\" class=\"drag\" style=\"position:absolute;left:631px;top:876px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_55\" class=\"drag\" style=\"position:absolute;left:164px;top:142px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_56\" class=\"drag\" style=\"position:absolute;left:76px;top:167px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MIL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_57\" class=\"drag\" style=\"position:absolute;left:27px;top:353px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p4_58\" class=\"drag\" style=\"position:absolute;left:326px;top:253px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_59\" class=\"drag\" style=\"position:absolute;left:332px;top:314px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_60\" class=\"drag\" style=\"position:absolute;left:136px;top:124px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C207<br></b></nobr>");
write("</p>");
write("<p id=\"p4_61\" class=\"drag\" style=\"position:absolute;left:137px;top:175px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C206<br></b></nobr>");
write("</p>");
write("<p id=\"p4_62\" class=\"drag\" style=\"position:absolute;left:324px;top:193px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_63\" class=\"drag\" style=\"position:absolute;left:607px;top:50px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_64\" class=\"drag\" style=\"position:absolute;left:715px;top:61px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p4_65\" class=\"drag\" style=\"position:absolute;left:762px;top:112px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_66\" class=\"drag\" style=\"position:absolute;left:600px;top:81px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_67\" class=\"drag\" style=\"position:absolute;left:636px;top:101px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C201<br></b></nobr>");
write("</p>");
write("<p id=\"p4_68\" class=\"drag\" style=\"position:absolute;left:651px;top:159px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C101<br></b></nobr>");
write("</p>");
write("<p id=\"p4_69\" class=\"drag\" style=\"position:absolute;left:816px;top:82px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C116<br></b></nobr>");
write("</p>");
write("<p id=\"p4_70\" class=\"drag\" style=\"position:absolute;left:875px;top:138px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>J/C<br></b></nobr>");
write("</p>");
write("<p id=\"p4_71\" class=\"drag\" style=\"position:absolute;left:762px;top:130px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_72\" class=\"drag\" style=\"position:absolute;left:36px;top:876px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_73\" class=\"drag\" style=\"position:absolute;left:43px;top:474px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ABS CONTROL<br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_74\" class=\"drag\" style=\"position:absolute;left:378px;top:468px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VABS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_75\" class=\"drag\" style=\"position:absolute;left:413px;top:481px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p4_76\" class=\"drag\" style=\"position:absolute;left:155px;top:481px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_77\" class=\"drag\" style=\"position:absolute;left:137px;top:434px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C301<br></b></nobr>");
write("</p>");
write("<p id=\"p4_78\" class=\"drag\" style=\"position:absolute;left:191px;top:460px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C306<br></b></nobr>");
write("</p>");
write("<p id=\"p4_79\" class=\"drag\" style=\"position:absolute;left:237px;top:460px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C214<br></b></nobr>");
write("</p>");
write("<p id=\"p4_80\" class=\"drag\" style=\"position:absolute;left:270px;top:504px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C201<br></b></nobr>");
write("</p>");
write("<p id=\"p4_81\" class=\"drag\" style=\"position:absolute;left:315px;top:504px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C101<br></b></nobr>");
write("</p>");
write("<p id=\"p4_82\" class=\"drag\" style=\"position:absolute;left:189px;top:682px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p4_83\" class=\"drag\" style=\"position:absolute;left:37px;top:604px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SERVICE<br>CHECK<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_84\" class=\"drag\" style=\"position:absolute;left:104px;top:572px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C205<br></b></nobr>");
write("</p>");
write("<p id=\"p4_85\" class=\"drag\" style=\"position:absolute;left:239px;top:481px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_86\" class=\"drag\" style=\"position:absolute;left:324px;top:480px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_87\" class=\"drag\" style=\"position:absolute;left:200px;top:745px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p4_88\" class=\"drag\" style=\"position:absolute;left:133px;top:829px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_89\" class=\"drag\" style=\"position:absolute;left:417px;top:779px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_90\" class=\"drag\" style=\"position:absolute;left:389px;top:768px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LG3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_91\" class=\"drag\" style=\"position:absolute;left:278px;top:780px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_92\" class=\"drag\" style=\"position:absolute;left:107px;top:799px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C204<br></b></nobr>");
write("</p>");
write("<p id=\"p4_93\" class=\"drag\" style=\"position:absolute;left:353px;top:687px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p4_94\" class=\"drag\" style=\"position:absolute;left:330px;top:726px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_95\" class=\"drag\" style=\"position:absolute;left:414px;top:606px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E29<br></b></nobr>");
write("</p>");
write("<p id=\"p4_96\" class=\"drag\" style=\"position:absolute;left:371px;top:606px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_97\" class=\"drag\" style=\"position:absolute;left:389px;top:593px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_98\" class=\"drag\" style=\"position:absolute;left:142px;top:625px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_99\" class=\"drag\" style=\"position:absolute;left:200px;top:1054px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p4_100\" class=\"drag\" style=\"position:absolute;left:414px;top:874px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E23<br></b></nobr>");
write("</p>");
write("<p id=\"p4_101\" class=\"drag\" style=\"position:absolute;left:147px;top:921px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_102\" class=\"drag\" style=\"position:absolute;left:374px;top:863px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>K-LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_103\" class=\"drag\" style=\"position:absolute;left:299px;top:875px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_104\" class=\"drag\" style=\"position:absolute;left:413px;top:940px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E30<br></b></nobr>");
write("</p>");
write("<p id=\"p4_105\" class=\"drag\" style=\"position:absolute;left:382px;top:926px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WEN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_106\" class=\"drag\" style=\"position:absolute;left:300px;top:940px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}