with(document) {
write("<v:group id=\"group10\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect10\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img10\" src=\"../img/SAA5ESPA20300000000DBAD42.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p10_1\" class=\"drag\" style=\"position:absolute;left:746px;top:450px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_2\" class=\"drag\" style=\"position:absolute;left:746px;top:535px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_3\" class=\"drag\" style=\"position:absolute;left:660px;top:535px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_4\" class=\"drag\" style=\"position:absolute;left:660px;top:521px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_5\" class=\"drag\" style=\"position:absolute;left:660px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_6\" class=\"drag\" style=\"position:absolute;left:660px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_7\" class=\"drag\" style=\"position:absolute;left:660px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_8\" class=\"drag\" style=\"position:absolute;left:719px;top:535px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p10_9\" class=\"drag\" style=\"position:absolute;left:719px;top:521px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p10_10\" class=\"drag\" style=\"position:absolute;left:636px;top:449px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_11\" class=\"drag\" style=\"position:absolute;left:660px;top:450px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_12\" class=\"drag\" style=\"position:absolute;left:660px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_13\" class=\"drag\" style=\"position:absolute;left:636px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_14\" class=\"drag\" style=\"position:absolute;left:636px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_15\" class=\"drag\" style=\"position:absolute;left:636px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_16\" class=\"drag\" style=\"position:absolute;left:636px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_17\" class=\"drag\" style=\"position:absolute;left:746px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_18\" class=\"drag\" style=\"position:absolute;left:634px;top:536px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_19\" class=\"drag\" style=\"position:absolute;left:636px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_20\" class=\"drag\" style=\"position:absolute;left:636px;top:492px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_21\" class=\"drag\" style=\"position:absolute;left:636px;top:507px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_22\" class=\"drag\" style=\"position:absolute;left:636px;top:521px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_23\" class=\"drag\" style=\"position:absolute;left:746px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_24\" class=\"drag\" style=\"position:absolute;left:746px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_25\" class=\"drag\" style=\"position:absolute;left:746px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_26\" class=\"drag\" style=\"position:absolute;left:746px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_27\" class=\"drag\" style=\"position:absolute;left:719px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_28\" class=\"drag\" style=\"position:absolute;left:719px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_29\" class=\"drag\" style=\"position:absolute;left:719px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_30\" class=\"drag\" style=\"position:absolute;left:719px;top:449px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_31\" class=\"drag\" style=\"position:absolute;left:719px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p10_32\" class=\"drag\" style=\"position:absolute;left:719px;top:492px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p10_33\" class=\"drag\" style=\"position:absolute;left:719px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_34\" class=\"drag\" style=\"position:absolute;left:746px;top:521px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_35\" class=\"drag\" style=\"position:absolute;left:746px;top:507px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_36\" class=\"drag\" style=\"position:absolute;left:719px;top:507px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p10_37\" class=\"drag\" style=\"position:absolute;left:660px;top:507px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_38\" class=\"drag\" style=\"position:absolute;left:457px;top:492px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_39\" class=\"drag\" style=\"position:absolute;left:482px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_40\" class=\"drag\" style=\"position:absolute;left:457px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_41\" class=\"drag\" style=\"position:absolute;left:482px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_42\" class=\"drag\" style=\"position:absolute;left:457px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_43\" class=\"drag\" style=\"position:absolute;left:482px;top:450px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_44\" class=\"drag\" style=\"position:absolute;left:457px;top:449px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_45\" class=\"drag\" style=\"position:absolute;left:482px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_46\" class=\"drag\" style=\"position:absolute;left:457px;top:435px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_47\" class=\"drag\" style=\"position:absolute;left:191px;top:299px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_48\" class=\"drag\" style=\"position:absolute;left:196px;top:414px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_49\" class=\"drag\" style=\"position:absolute;left:196px;top:400px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_50\" class=\"drag\" style=\"position:absolute;left:171px;top:442px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_51\" class=\"drag\" style=\"position:absolute;left:171px;top:428px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_52\" class=\"drag\" style=\"position:absolute;left:171px;top:414px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_53\" class=\"drag\" style=\"position:absolute;left:171px;top:399px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_54\" class=\"drag\" style=\"position:absolute;left:171px;top:457px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_55\" class=\"drag\" style=\"position:absolute;left:296px;top:400px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_56\" class=\"drag\" style=\"position:absolute;left:196px;top:471px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_57\" class=\"drag\" style=\"position:absolute;left:196px;top:485px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_58\" class=\"drag\" style=\"position:absolute;left:269px;top:428px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_59\" class=\"drag\" style=\"position:absolute;left:171px;top:471px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_60\" class=\"drag\" style=\"position:absolute;left:171px;top:485px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_61\" class=\"drag\" style=\"position:absolute;left:271px;top:399px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_62\" class=\"drag\" style=\"position:absolute;left:271px;top:414px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_63\" class=\"drag\" style=\"position:absolute;left:296px;top:414px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_64\" class=\"drag\" style=\"position:absolute;left:296px;top:428px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_65\" class=\"drag\" style=\"position:absolute;left:296px;top:457px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_66\" class=\"drag\" style=\"position:absolute;left:296px;top:471px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_67\" class=\"drag\" style=\"position:absolute;left:270px;top:458px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_68\" class=\"drag\" style=\"position:absolute;left:269px;top:471px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_69\" class=\"drag\" style=\"position:absolute;left:270px;top:486px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_70\" class=\"drag\" style=\"position:absolute;left:296px;top:485px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_71\" class=\"drag\" style=\"position:absolute;left:160px;top:302px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C208<br></b></nobr>");
write("</p>");
write("<p id=\"p10_72\" class=\"drag\" style=\"position:absolute;left:624px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_73\" class=\"drag\" style=\"position:absolute;left:683px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p10_74\" class=\"drag\" style=\"position:absolute;left:710px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_75\" class=\"drag\" style=\"position:absolute;left:710px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_76\" class=\"drag\" style=\"position:absolute;left:710px;top:235px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_77\" class=\"drag\" style=\"position:absolute;left:683px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_78\" class=\"drag\" style=\"position:absolute;left:683px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p10_79\" class=\"drag\" style=\"position:absolute;left:683px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p10_80\" class=\"drag\" style=\"position:absolute;left:683px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_81\" class=\"drag\" style=\"position:absolute;left:683px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_82\" class=\"drag\" style=\"position:absolute;left:683px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_83\" class=\"drag\" style=\"position:absolute;left:683px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_84\" class=\"drag\" style=\"position:absolute;left:710px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_85\" class=\"drag\" style=\"position:absolute;left:710px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_86\" class=\"drag\" style=\"position:absolute;left:710px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_87\" class=\"drag\" style=\"position:absolute;left:600px;top:235px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_88\" class=\"drag\" style=\"position:absolute;left:600px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_89\" class=\"drag\" style=\"position:absolute;left:600px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_90\" class=\"drag\" style=\"position:absolute;left:600px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_91\" class=\"drag\" style=\"position:absolute;left:597px;top:249px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_92\" class=\"drag\" style=\"position:absolute;left:624px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_93\" class=\"drag\" style=\"position:absolute;left:600px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_94\" class=\"drag\" style=\"position:absolute;left:600px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_95\" class=\"drag\" style=\"position:absolute;left:600px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_96\" class=\"drag\" style=\"position:absolute;left:600px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_97\" class=\"drag\" style=\"position:absolute;left:624px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_98\" class=\"drag\" style=\"position:absolute;left:624px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_99\" class=\"drag\" style=\"position:absolute;left:600px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_100\" class=\"drag\" style=\"position:absolute;left:683px;top:235px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p10_101\" class=\"drag\" style=\"position:absolute;left:683px;top:249px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p10_102\" class=\"drag\" style=\"position:absolute;left:624px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_103\" class=\"drag\" style=\"position:absolute;left:624px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_104\" class=\"drag\" style=\"position:absolute;left:624px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_105\" class=\"drag\" style=\"position:absolute;left:624px;top:235px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_106\" class=\"drag\" style=\"position:absolute;left:624px;top:250px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_107\" class=\"drag\" style=\"position:absolute;left:710px;top:250px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_108\" class=\"drag\" style=\"position:absolute;left:710px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_109\" class=\"drag\" style=\"position:absolute;left:303px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_110\" class=\"drag\" style=\"position:absolute;left:303px;top:250px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_111\" class=\"drag\" style=\"position:absolute;left:217px;top:250px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_112\" class=\"drag\" style=\"position:absolute;left:217px;top:235px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_113\" class=\"drag\" style=\"position:absolute;left:217px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_114\" class=\"drag\" style=\"position:absolute;left:217px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_115\" class=\"drag\" style=\"position:absolute;left:217px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_116\" class=\"drag\" style=\"position:absolute;left:389px;top:250px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_117\" class=\"drag\" style=\"position:absolute;left:389px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_118\" class=\"drag\" style=\"position:absolute;left:362px;top:249px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p10_119\" class=\"drag\" style=\"position:absolute;left:362px;top:235px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p10_120\" class=\"drag\" style=\"position:absolute;left:362px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p10_121\" class=\"drag\" style=\"position:absolute;left:362px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p10_122\" class=\"drag\" style=\"position:absolute;left:362px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p10_123\" class=\"drag\" style=\"position:absolute;left:276px;top:249px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p10_124\" class=\"drag\" style=\"position:absolute;left:277px;top:236px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p10_125\" class=\"drag\" style=\"position:absolute;left:624px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_126\" class=\"drag\" style=\"position:absolute;left:622px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_127\" class=\"drag\" style=\"position:absolute;left:643px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_128\" class=\"drag\" style=\"position:absolute;left:640px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_129\" class=\"drag\" style=\"position:absolute;left:661px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_130\" class=\"drag\" style=\"position:absolute;left:659px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_131\" class=\"drag\" style=\"position:absolute;left:680px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_132\" class=\"drag\" style=\"position:absolute;left:677px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_133\" class=\"drag\" style=\"position:absolute;left:698px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_134\" class=\"drag\" style=\"position:absolute;left:696px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p10_135\" class=\"drag\" style=\"position:absolute;left:715px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_136\" class=\"drag\" style=\"position:absolute;left:754px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_137\" class=\"drag\" style=\"position:absolute;left:752px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p10_138\" class=\"drag\" style=\"position:absolute;left:773px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_139\" class=\"drag\" style=\"position:absolute;left:770px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p10_140\" class=\"drag\" style=\"position:absolute;left:789px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_141\" class=\"drag\" style=\"position:absolute;left:789px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p10_142\" class=\"drag\" style=\"position:absolute;left:463px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_143\" class=\"drag\" style=\"position:absolute;left:509px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_144\" class=\"drag\" style=\"position:absolute;left:458px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_145\" class=\"drag\" style=\"position:absolute;left:477px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_146\" class=\"drag\" style=\"position:absolute;left:496px;top:372px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_147\" class=\"drag\" style=\"position:absolute;left:295px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_148\" class=\"drag\" style=\"position:absolute;left:313px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_149\" class=\"drag\" style=\"position:absolute;left:202px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_150\" class=\"drag\" style=\"position:absolute;left:220px;top:346px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_151\" class=\"drag\" style=\"position:absolute;left:311px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_152\" class=\"drag\" style=\"position:absolute;left:292px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_153\" class=\"drag\" style=\"position:absolute;left:274px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_154\" class=\"drag\" style=\"position:absolute;left:236px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_155\" class=\"drag\" style=\"position:absolute;left:220px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_156\" class=\"drag\" style=\"position:absolute;left:202px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_157\" class=\"drag\" style=\"position:absolute;left:760px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p10_158\" class=\"drag\" style=\"position:absolute;left:760px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_159\" class=\"drag\" style=\"position:absolute;left:742px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p10_160\" class=\"drag\" style=\"position:absolute;left:744px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_161\" class=\"drag\" style=\"position:absolute;left:723px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p10_162\" class=\"drag\" style=\"position:absolute;left:726px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_163\" class=\"drag\" style=\"position:absolute;left:705px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p10_164\" class=\"drag\" style=\"position:absolute;left:686px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_165\" class=\"drag\" style=\"position:absolute;left:688px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_166\" class=\"drag\" style=\"position:absolute;left:670px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_167\" class=\"drag\" style=\"position:absolute;left:649px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_168\" class=\"drag\" style=\"position:absolute;left:651px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_169\" class=\"drag\" style=\"position:absolute;left:630px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_170\" class=\"drag\" style=\"position:absolute;left:633px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_171\" class=\"drag\" style=\"position:absolute;left:612px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_172\" class=\"drag\" style=\"position:absolute;left:614px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_173\" class=\"drag\" style=\"position:absolute;left:596px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_174\" class=\"drag\" style=\"position:absolute;left:461px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p10_175\" class=\"drag\" style=\"position:absolute;left:461px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_176\" class=\"drag\" style=\"position:absolute;left:442px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_177\" class=\"drag\" style=\"position:absolute;left:185px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_178\" class=\"drag\" style=\"position:absolute;left:182px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_179\" class=\"drag\" style=\"position:absolute;left:203px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_180\" class=\"drag\" style=\"position:absolute;left:201px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p10_181\" class=\"drag\" style=\"position:absolute;left:370px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_182\" class=\"drag\" style=\"position:absolute;left:166px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_183\" class=\"drag\" style=\"position:absolute;left:240px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_184\" class=\"drag\" style=\"position:absolute;left:259px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_185\" class=\"drag\" style=\"position:absolute;left:424px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p10_186\" class=\"drag\" style=\"position:absolute;left:275px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p10_187\" class=\"drag\" style=\"position:absolute;left:238px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p10_188\" class=\"drag\" style=\"position:absolute;left:256px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p10_189\" class=\"drag\" style=\"position:absolute;left:277px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_190\" class=\"drag\" style=\"position:absolute;left:219px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p10_191\" class=\"drag\" style=\"position:absolute;left:222px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_192\" class=\"drag\" style=\"position:absolute;left:387px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p10_193\" class=\"drag\" style=\"position:absolute;left:387px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_194\" class=\"drag\" style=\"position:absolute;left:405px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p10_195\" class=\"drag\" style=\"position:absolute;left:405px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_196\" class=\"drag\" style=\"position:absolute;left:219px;top:1071px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>* : Terminal side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p10_197\" class=\"drag\" style=\"position:absolute;left:193px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_198\" class=\"drag\" style=\"position:absolute;left:217px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_199\" class=\"drag\" style=\"position:absolute;left:217px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_200\" class=\"drag\" style=\"position:absolute;left:193px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_201\" class=\"drag\" style=\"position:absolute;left:193px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_202\" class=\"drag\" style=\"position:absolute;left:193px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_203\" class=\"drag\" style=\"position:absolute;left:160px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C206<br></b></nobr>");
write("</p>");
write("<p id=\"p10_204\" class=\"drag\" style=\"position:absolute;left:193px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_205\" class=\"drag\" style=\"position:absolute;left:303px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_206\" class=\"drag\" style=\"position:absolute;left:217px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_207\" class=\"drag\" style=\"position:absolute;left:217px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_208\" class=\"drag\" style=\"position:absolute;left:190px;top:249px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_209\" class=\"drag\" style=\"position:absolute;left:193px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_210\" class=\"drag\" style=\"position:absolute;left:193px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_211\" class=\"drag\" style=\"position:absolute;left:193px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_212\" class=\"drag\" style=\"position:absolute;left:193px;top:235px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_213\" class=\"drag\" style=\"position:absolute;left:303px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_214\" class=\"drag\" style=\"position:absolute;left:303px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_215\" class=\"drag\" style=\"position:absolute;left:277px;top:122px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_216\" class=\"drag\" style=\"position:absolute;left:276px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_217\" class=\"drag\" style=\"position:absolute;left:277px;top:150px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_218\" class=\"drag\" style=\"position:absolute;left:276px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_219\" class=\"drag\" style=\"position:absolute;left:276px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p10_220\" class=\"drag\" style=\"position:absolute;left:276px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p10_221\" class=\"drag\" style=\"position:absolute;left:276px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_222\" class=\"drag\" style=\"position:absolute;left:389px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_223\" class=\"drag\" style=\"position:absolute;left:303px;top:235px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_224\" class=\"drag\" style=\"position:absolute;left:303px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_225\" class=\"drag\" style=\"position:absolute;left:303px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_226\" class=\"drag\" style=\"position:absolute;left:276px;top:221px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p10_227\" class=\"drag\" style=\"position:absolute;left:362px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p10_228\" class=\"drag\" style=\"position:absolute;left:362px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p10_229\" class=\"drag\" style=\"position:absolute;left:362px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p10_230\" class=\"drag\" style=\"position:absolute;left:362px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p10_231\" class=\"drag\" style=\"position:absolute;left:362px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p10_232\" class=\"drag\" style=\"position:absolute;left:389px;top:207px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_233\" class=\"drag\" style=\"position:absolute;left:389px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_234\" class=\"drag\" style=\"position:absolute;left:147px;top:961px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>*2 : CVT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_235\" class=\"drag\" style=\"position:absolute;left:457px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_236\" class=\"drag\" style=\"position:absolute;left:482px;top:407px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_237\" class=\"drag\" style=\"position:absolute;left:457px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_238\" class=\"drag\" style=\"position:absolute;left:446px;top:309px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C210<br></b></nobr>");
write("</p>");
write("<p id=\"p10_239\" class=\"drag\" style=\"position:absolute;left:589px;top:23px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C207<br></b></nobr>");
write("</p>");
write("<p id=\"p10_240\" class=\"drag\" style=\"position:absolute;left:203px;top:1048px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p10_241\" class=\"drag\" style=\"position:absolute;left:617px;top:309px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C266<br></b></nobr>");
write("</p>");
write("<p id=\"p10_242\" class=\"drag\" style=\"position:absolute;left:217px;top:1034px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with female terminals (single outline): View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p10_243\" class=\"drag\" style=\"position:absolute;left:217px;top:1019px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with male terminals (double outline): View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p10_244\" class=\"drag\" style=\"position:absolute;left:148px;top:1019px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_245\" class=\"drag\" style=\"position:absolute;left:242px;top:1048px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to ECM/PCM control.<br></b></nobr>");
write("</p>");
write("<p id=\"p10_246\" class=\"drag\" style=\"position:absolute;left:269px;top:442px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_247\" class=\"drag\" style=\"position:absolute;left:203px;top:1019px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p10_248\" class=\"drag\" style=\"position:absolute;left:203px;top:1034px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}