with(document) {
write("<v:group id=\"group13\" class=\"drag\" style=\"position:relative; width:950px; height:767px;\" coordsize=\"950,767\">");
write("<v:rect id=\"rect13\"class=\"drag\"  style=\"width:950px;height:767px;\">");
write("<img id=\"img13\" src=\"../img/SAA5ES0A20300000000DBAD59.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:767px;border-color:#ffffff\">");
write("<p id=\"p13_1\" class=\"drag\" style=\"position:absolute;left:59px;top:151px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p13_2\" class=\"drag\" style=\"position:absolute;left:656px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p13_3\" class=\"drag\" style=\"position:absolute;left:37px;top:507px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p13_4\" class=\"drag\" style=\"position:absolute;left:408px;top:554px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C265<br></b></nobr>");
write("</p>");
write("<p id=\"p13_5\" class=\"drag\" style=\"position:absolute;left:318px;top:554px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C264<br></b></nobr>");
write("</p>");
write("<p id=\"p13_6\" class=\"drag\" style=\"position:absolute;left:540px;top:554px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C262<br></b></nobr>");
write("</p>");
write("<p id=\"p13_7\" class=\"drag\" style=\"position:absolute;left:622px;top:712px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C260<br></b></nobr>");
write("</p>");
write("<p id=\"p13_8\" class=\"drag\" style=\"position:absolute;left:645px;top:673px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C261<br></b></nobr>");
write("</p>");
write("<p id=\"p13_9\" class=\"drag\" style=\"position:absolute;left:506px;top:702px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BACK SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p13_10\" class=\"drag\" style=\"position:absolute;left:414px;top:667px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C263<br></b></nobr>");
write("</p>");
write("<p id=\"p13_11\" class=\"drag\" style=\"position:absolute;left:414px;top:706px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C382<br></b></nobr>");
write("</p>");
write("<p id=\"p13_12\" class=\"drag\" style=\"position:absolute;left:390px;top:736px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C380<br></b></nobr>");
write("</p>");
write("<p id=\"p13_13\" class=\"drag\" style=\"position:absolute;left:177px;top:720px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C381<br></b></nobr>");
write("</p>");
write("<p id=\"p13_14\" class=\"drag\" style=\"position:absolute;left:270px;top:702px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SIDE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}