with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\" coordsize=\"950,1071\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1071px;\">");
write("<img id=\"img1\" src=\"../img/SAA5ET3J54200000000DEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:370px;top:477px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER <br>MIRROR<br>DEFOGGER <br>RELAY or<br>FRONT FOG <br>LIGHT RELAY<br>(Without rear fog light)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:520px;top:598px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT ACTIVATION<br>INDICATOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:625px;top:638px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT ACTIVATION<br>INDICATOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:678px;top:686px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PGM-FI MAIN<br>RELAY1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:725px;top:731px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PGM-FI MAIN<br>RELAY2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:362px;top:1029px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILLIGHT<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:221px;top:606px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FOG<br>LIGHT RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:33px;top:769px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FOG LIGHT RELAY<br>(With front fog lights)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:92px;top:955px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER DOOR<br>UNLOCK RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:72px;top:863px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER DOOR<br>LOCK RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:179px;top:1029px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STARTER CUT<br>RELAY (CVT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:507px;top:1029px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER WINDOW<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:661px;top:937px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLOWER MOTOR<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:709px;top:893px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/T REVERSE RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:583px;top:982px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WINDOW<br>DEFOGGER RELAY<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}