with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img1\" src=\"../img/SAA5ET0J16166200000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:702px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GLASS RUN CHANNEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:349px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GLASS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:189px;top:55px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR LOWER CHANNEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:33px;top:448px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER HANDLE<br>PROTECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:818px;top:693px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCK KNOB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:130px;top:922px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER DOOR<br>LOCK ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:21px;top:617px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STRIKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:52px;top:812px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LATCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:534px;top:860px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCK ROD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:675px;top:372px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:692px;top:666px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INNER HANDLE ROD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:735px;top:1049px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INNER HANDLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:181px;top:158px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COLLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:127px;top:396px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER HANDLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:651px;top:561px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROD PROTECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:831px;top:881px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCK CRANK<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}