with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:542px;\" coordsize=\"950,542\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:542px;\">");
write("<img id=\"img1\" src=\"../img/SAA5ET3H46400000000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:542px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:817px;top:23px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:817px;top:13px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:824px;top:13px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: With daytime lighting gauge assembly<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:824px;top:24px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: Without daytime lighting gauge assembly<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:851px;top:389px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(With outer lap tensioner)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:883px;top:257px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:855px;top:257px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:791px;top:257px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:823px;top:257px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:836px;top:326px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TBL1o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:837px;top:311px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TBL1i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:776px;top:311px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TBR1i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:774px;top:326px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TBR1o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:883px;top:311px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:855px;top:311px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:794px;top:311px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:823px;top:311px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:880px;top:284px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:857px;top:284px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:824px;top:284px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:789px;top:284px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:514px;top:209px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:543px;top:209px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:579px;top:209px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:608px;top:209px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:547px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:519px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:583px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:612px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:505px;top:168px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TL1o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:507px;top:182px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TL1i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:570px;top:182px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TR1i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:569px;top:168px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TR1o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:547px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:583px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:612px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:519px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:682px;top:448px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:695px;top:376px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:695px;top:348px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:680px;top:527px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:545px;top:257px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:585px;top:284px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:549px;top:284px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:580px;top:257px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:677px;top:257px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:672px;top:284px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:855px;top:179px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:883px;top:179px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:851px;top:206px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:879px;top:206px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRY/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:818px;top:206px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:790px;top:206px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:760px;top:206px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:732px;top:206px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:823px;top:179px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:794px;top:179px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:621px;top:238px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SRS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:765px;top:179px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:737px;top:179px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:680px;top:179px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:708px;top:179px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:675px;top:206px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:704px;top:206px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:677px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:705px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:734px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:763px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:791px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:820px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:852px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:881px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:666px;top:164px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SDo<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:667px;top:179px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SDi<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:784px;top:175px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IDi<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:505px;top:220px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>U2o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:725px;top:179px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SPi<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:723px;top:164px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SPo<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:845px;top:175px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IPi<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:866px;top:79px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(With side airbags)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:528px;top:126px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT SIDE<br>SEAT BELT<br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:592px;top:126px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT SIDE<br>SEAT BELT<br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:561px;top:190px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FLOOR<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:657px;top:186px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FLOOR<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:687px;top:121px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVER'S<br>SIDE AIRBAG<br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:744px;top:115px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FRONT<br>PASSENGER'S<br>SIDE AIRBAG<br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:804px;top:147px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVER'S<br>SIDE IMPACT<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:860px;top:144px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FRONT<br>PASSENGER'S<br>SIDE IMPACT<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:765px;top:261px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FLOOR<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:863px;top:358px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT SIDE<br>SEAT BELT<br>OUTER LAP<br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:803px;top:358px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT SIDE<br>SEAT BELT<br>OUTER LAP<br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:707px;top:354px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MEMORY<br>ERASE<br>SIGNAL (MES)<br>CONNECTOR<br>(2P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:559px;top:344px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR<br>(16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:328px;top:141px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:382px;top:102px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:156px;top:387px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:150px;top:401px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:153px;top:407px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:110px;top:330px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:347px;top:72px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FSR1i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:295px;top:72px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FSL1i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:297px;top:132px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FS3i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:296px;top:118px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FS3o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:398px;top:220px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G404<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:326px;top:119px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:308px;top:119px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:362px;top:76px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:380px;top:76px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:326px;top:76px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:308px;top:76px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:359px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:377px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:364px;top:102px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:382px;top:141px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:382px;top:206px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:363px;top:206px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:310px;top:206px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:328px;top:206px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:328px;top:102px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:310px;top:102px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:324px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:306px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:349px;top:132px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FS2o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:351px;top:118px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FS2i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:362px;top:132px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:380px;top:132px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:98px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:66px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:183px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:155px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:255px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:223px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:107px;top:350px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:217px;top:182px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>P1i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:215px;top:168px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>P1o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:349px;top:254px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>U1o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:104px;top:344px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:55px;top:220px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>U1o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:63px;top:197px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:143px;top:104px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>D1o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:145px;top:89px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>D1i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:145px;top:168px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>D2i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:143px;top:182px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>D2o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:29px;top:197px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:26px;top:418px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:26px;top:320px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:189px;top:355px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:257px;top:209px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:222px;top:209px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:183px;top:104px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:179px;top:209px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:150px;top:209px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:103px;top:209px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:65px;top:209px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:155px;top:182px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:183px;top:182px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:155px;top:104px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:156px;top:156px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:185px;top:156px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:39px;top:209px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:101px;top:200px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:69px;top:200px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:37px;top:200px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:81px;top:174px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:81px;top:180px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:113px;top:180px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(10A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:113px;top:174px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:49px;top:180px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(7.5A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:49px;top:174px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:48px;top:131px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:33px;top:124px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" class=\"drag\" style=\"position:absolute;left:104px;top:232px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>VB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" class=\"drag\" style=\"position:absolute;left:72px;top:232px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>VA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" class=\"drag\" style=\"position:absolute;left:255px;top:168px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" class=\"drag\" style=\"position:absolute;left:226px;top:168px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" class=\"drag\" style=\"position:absolute;left:34px;top:27px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" class=\"drag\" style=\"position:absolute;left:37px;top:318px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" class=\"drag\" style=\"position:absolute;left:54px;top:418px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" class=\"drag\" style=\"position:absolute;left:34px;top:421px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" class=\"drag\" style=\"position:absolute;left:228px;top:238px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SRS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" class=\"drag\" style=\"position:absolute;left:359px;top:257px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" class=\"drag\" style=\"position:absolute;left:37px;top:527px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" class=\"drag\" style=\"position:absolute;left:39px;top:448px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" class=\"drag\" style=\"position:absolute;left:363px;top:284px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" class=\"drag\" style=\"position:absolute;left:58px;top:72px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER−HOOD<br>FUSE/RELAY<br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" class=\"drag\" style=\"position:absolute;left:61px;top:126px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IGNITION<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" class=\"drag\" style=\"position:absolute;left:92px;top:144px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER−DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" class=\"drag\" style=\"position:absolute;left:118px;top:204px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" class=\"drag\" style=\"position:absolute;left:165px;top:40px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DRIVER'S<br>AIRBAG<br>FIRST<br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" class=\"drag\" style=\"position:absolute;left:204px;top:124px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CABLE<br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" class=\"drag\" style=\"position:absolute;left:236px;top:111px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FRONT<br>PASSENGER'S<br>AIRBAG<br>FIRST<br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" class=\"drag\" style=\"position:absolute;left:275px;top:83px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ENGINE<br>COMPARTMENT<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" class=\"drag\" style=\"position:absolute;left:282px;top:183px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" class=\"drag\" style=\"position:absolute;left:393px;top:80px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FRONT<br>SENSOR<br>SUB<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" class=\"drag\" style=\"position:absolute;left:314px;top:44px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT <br>FRONT<br>IMPACT<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" class=\"drag\" style=\"position:absolute;left:368px;top:44px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT<br>FRONT<br>IMPACT<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" class=\"drag\" style=\"position:absolute;left:333px;top:308px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" class=\"drag\" style=\"position:absolute;left:47px;top:308px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE HARNESS <br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" class=\"drag\" style=\"position:absolute;left:40px;top:350px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SRS<br>INDICATOR<br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" class=\"drag\" style=\"position:absolute;left:54px;top:386px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SRS<br>INDICATOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}