with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SAA5ET0G10500000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:761px;top:42px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLOWER MOTOR RELAY<br><a href=\"javascript:parent.Cts('000000000003007','i000')\"></b>Test,</a><br> in the Shop Manual,<br> P/N 62SAA00<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:711px;top:222px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:737px;top:517px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RADIATOR FAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:671px;top:578px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTSIDE AIR TEMPERATURE SENSOR<br><a href=\"javascript:parent.Cts('000000000003200','i000')\"></b>Test,</a><br><a href=\"javascript:parent.Cts('000000000003201','i000')\">Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:628px;top:669px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CONDENSER FAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:361px;top:669px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C PRESSURE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:419px;top:699px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:386px;top:818px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RADIATOR FAN RELAY<br><a href=\"javascript:parent.Cts('000000000003007','i000')\"></b>Test,</a><br> in the Shop Manual, P/N 62SAA00<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:340px;top:878px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CONDENSER FAN RELAY<br><a href=\"javascript:parent.Cts('000000000003007','i000')\"></b>Test,</a><br> in the Shop Manual, P/N 62SAA00<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:255px;top:942px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COMPRESSOR CLUTCH RELAY<br><a href=\"javascript:parent.Cts('000000000003007','i000')\"></b>Test,</a><br> in the Shop Manual, P/N 62SAA00<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:38px;top:1072px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>LHD type is shown, RHD type is similar.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}