with(document) {
write("<v:group id=\"group5\" class=\"drag\" style=\"position:relative; width:950px; height:687px;\" coordsize=\"950,687\">");
write("<v:rect id=\"rect5\"class=\"drag\"  style=\"width:950px;height:687px;\">");
write("<img id=\"img5\" src=\"../img/SAA5ES0A20300000000DBADB2.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:687px;border-color:#ffffff\">");
write("<p id=\"p5_1\" class=\"drag\" style=\"position:absolute;left:211px;top:120px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C135<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" class=\"drag\" style=\"position:absolute;left:126px;top:513px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>COMPARTMENT<br>WIRE<br>HARNESS*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" class=\"drag\" style=\"position:absolute;left:112px;top:116px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" class=\"drag\" style=\"position:absolute;left:17px;top:639px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*2: RHD<br>*16: Except IN, KH models<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" class=\"drag\" style=\"position:absolute;left:291px;top:108px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C134<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" class=\"drag\" style=\"position:absolute;left:364px;top:109px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C126<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" class=\"drag\" style=\"position:absolute;left:509px;top:85px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C133<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" class=\"drag\" style=\"position:absolute;left:597px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C132<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" class=\"drag\" style=\"position:absolute;left:708px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C124<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" class=\"drag\" style=\"position:absolute;left:782px;top:442px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C123<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" class=\"drag\" style=\"position:absolute;left:759px;top:473px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C125<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" class=\"drag\" style=\"position:absolute;left:692px;top:501px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C121<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" class=\"drag\" style=\"position:absolute;left:665px;top:531px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C127<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" class=\"drag\" style=\"position:absolute;left:641px;top:561px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C122<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" class=\"drag\" style=\"position:absolute;left:548px;top:531px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C128<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" class=\"drag\" style=\"position:absolute;left:530px;top:562px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C129<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" class=\"drag\" style=\"position:absolute;left:514px;top:594px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C130<br></b></nobr>");
write("</p>");
write("<p id=\"p5_18\" class=\"drag\" style=\"position:absolute;left:487px;top:622px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C131*<sup>16</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p5_19\" class=\"drag\" style=\"position:absolute;left:340px;top:575px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C136<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}