with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:565px;\" coordsize=\"950,565\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:565px;\">");
write("<img id=\"img1\" src=\"../img/SAA5ET0J54230100000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:565px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:114px;top:519px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:130px;top:518px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:138px;top:519px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Engine compartment wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:96px;top:469px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G202<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:688px;top:127px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right front parking light<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:688px;top:77px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Windshield washer motor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:688px;top:27px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right headlight adjuster unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:96px;top:298px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:688px;top:91px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear washer motor<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:688px;top:141px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right front turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:688px;top:177px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Noise condenser<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:350px;top:27px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:377px;top:27px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:377px;top:77px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:350px;top:77px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:377px;top:127px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:350px;top:127px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:377px;top:177px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:350px;top:177px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:377px;top:341px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:350px;top:341px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:377px;top:391px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:350px;top:391px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:350px;top:227px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:377px;top:227px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:688px;top:227px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right front fog light<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:688px;top:391px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>VSA modulator−control unit<br>(or ABS modulator−control unit)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:688px;top:341px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>VSA modulator−control unit<br>(or ABS modulator−control unit)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}