with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:1017px;\" coordsize=\"950,1017\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:1017px;\">");
write("<img id=\"img2\" src=\"../img/SAA5ET2E15117700000CAAD10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1017px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:721px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:200px;top:449px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>To 12V<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:173px;top:392px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>To 5V<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:809px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:771px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:709px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:750px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:537px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:433px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:450px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:478px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:435px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:403px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:350px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:324px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:404px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:403px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:377px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:221px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:196px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:147px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:337px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:246px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:160px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:493px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:493px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:298px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:300px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:233px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:135px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:138px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:672px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:377px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:696px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:685px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:510px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:233px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:172px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:796px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:757px;top:948px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>(27)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:796px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:808px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:733px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:794px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:311px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:209px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:735px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:690px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:508px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:125px;top:980px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A (31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:293px;top:980px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B (24P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:430px;top:980px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C (22P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:670px;top:980px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>E (31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" class=\"drag\" style=\"position:absolute;left:734px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" class=\"drag\" style=\"position:absolute;left:672px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" class=\"drag\" style=\"position:absolute;left:809px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" class=\"drag\" style=\"position:absolute;left:765px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" class=\"drag\" style=\"position:absolute;left:720px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" class=\"drag\" style=\"position:absolute;left:705px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" class=\"drag\" style=\"position:absolute;left:770px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" class=\"drag\" style=\"position:absolute;left:783px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" class=\"drag\" style=\"position:absolute;left:697px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" class=\"drag\" style=\"position:absolute;left:463px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" class=\"drag\" style=\"position:absolute;left:537px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" class=\"drag\" style=\"position:absolute;left:435px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" class=\"drag\" style=\"position:absolute;left:525px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" class=\"drag\" style=\"position:absolute;left:539px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" class=\"drag\" style=\"position:absolute;left:363px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" class=\"drag\" style=\"position:absolute;left:363px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" class=\"drag\" style=\"position:absolute;left:324px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" class=\"drag\" style=\"position:absolute;left:390px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" class=\"drag\" style=\"position:absolute;left:360px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" class=\"drag\" style=\"position:absolute;left:345px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" class=\"drag\" style=\"position:absolute;left:330px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" class=\"drag\" style=\"position:absolute;left:315px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" class=\"drag\" style=\"position:absolute;left:300px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" class=\"drag\" style=\"position:absolute;left:147px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" class=\"drag\" style=\"position:absolute;left:160px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" class=\"drag\" style=\"position:absolute;left:258px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" class=\"drag\" style=\"position:absolute;left:271px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" class=\"drag\" style=\"position:absolute;left:258px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" class=\"drag\" style=\"position:absolute;left:246px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" class=\"drag\" style=\"position:absolute;left:197px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" class=\"drag\" style=\"position:absolute;left:153px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" class=\"drag\" style=\"position:absolute;left:168px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" class=\"drag\" style=\"position:absolute;left:183px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" class=\"drag\" style=\"position:absolute;left:198px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" class=\"drag\" style=\"position:absolute;left:212px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" class=\"drag\" style=\"position:absolute;left:227px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" class=\"drag\" style=\"position:absolute;left:272px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" class=\"drag\" style=\"position:absolute;left:480px;top:917px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" class=\"drag\" style=\"position:absolute;left:722px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" class=\"drag\" style=\"position:absolute;left:685px;top:947px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" class=\"drag\" style=\"position:absolute;left:412px;top:877px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PCM Connector Terminal Locations<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" class=\"drag\" style=\"position:absolute;left:670px;top:933px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" class=\"drag\" style=\"position:absolute;left:782px;top:933px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" class=\"drag\" style=\"position:absolute;left:499px;top:746px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INHIBITOR SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" class=\"drag\" style=\"position:absolute;left:735px;top:43px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CVT SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" class=\"drag\" style=\"position:absolute;left:792px;top:349px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" class=\"drag\" style=\"position:absolute;left:770px;top:375px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>VEL1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" class=\"drag\" style=\"position:absolute;left:770px;top:358px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C22<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" class=\"drag\" style=\"position:absolute;left:750px;top:309px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" class=\"drag\" style=\"position:absolute;left:786px;top:161px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" class=\"drag\" style=\"position:absolute;left:717px;top:161px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_105\" class=\"drag\" style=\"position:absolute;left:760px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_106\" class=\"drag\" style=\"position:absolute;left:726px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_107\" class=\"drag\" style=\"position:absolute;left:794px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_108\" class=\"drag\" style=\"position:absolute;left:640px;top:309px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_109\" class=\"drag\" style=\"position:absolute;left:650px;top:358px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_110\" class=\"drag\" style=\"position:absolute;left:650px;top:375px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>NDN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_111\" class=\"drag\" style=\"position:absolute;left:674px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_112\" class=\"drag\" style=\"position:absolute;left:606px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_113\" class=\"drag\" style=\"position:absolute;left:640px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_114\" class=\"drag\" style=\"position:absolute;left:597px;top:161px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_115\" class=\"drag\" style=\"position:absolute;left:664px;top:161px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_116\" class=\"drag\" style=\"position:absolute;left:510px;top:320px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_117\" class=\"drag\" style=\"position:absolute;left:477px;top:309px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_118\" class=\"drag\" style=\"position:absolute;left:530px;top:384px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>(PB)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_119\" class=\"drag\" style=\"position:absolute;left:496px;top:375px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>VCC1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_120\" class=\"drag\" style=\"position:absolute;left:496px;top:358px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_121\" class=\"drag\" style=\"position:absolute;left:530px;top:375px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>MAP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_122\" class=\"drag\" style=\"position:absolute;left:530px;top:358px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A19<br></b></nobr>");
write("</p>");
write("<p id=\"p2_123\" class=\"drag\" style=\"position:absolute;left:564px;top:375px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SG1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_124\" class=\"drag\" style=\"position:absolute;left:564px;top:358px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_125\" class=\"drag\" style=\"position:absolute;left:554px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_126\" class=\"drag\" style=\"position:absolute;left:486px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_127\" class=\"drag\" style=\"position:absolute;left:520px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_128\" class=\"drag\" style=\"position:absolute;left:477px;top:161px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_129\" class=\"drag\" style=\"position:absolute;left:543px;top:309px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_130\" class=\"drag\" style=\"position:absolute;left:424px;top:161px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_131\" class=\"drag\" style=\"position:absolute;left:356px;top:161px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_132\" class=\"drag\" style=\"position:absolute;left:400px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_133\" class=\"drag\" style=\"position:absolute;left:549px;top:663px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_134\" class=\"drag\" style=\"position:absolute;left:549px;top:681px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_135\" class=\"drag\" style=\"position:absolute;left:503px;top:681px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_136\" class=\"drag\" style=\"position:absolute;left:378px;top:584px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_137\" class=\"drag\" style=\"position:absolute;left:425px;top:583px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_138\" class=\"drag\" style=\"position:absolute;left:444px;top:523px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B24<br></b></nobr>");
write("</p>");
write("<p id=\"p2_139\" class=\"drag\" style=\"position:absolute;left:399px;top:523px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_140\" class=\"drag\" style=\"position:absolute;left:388px;top:681px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_141\" class=\"drag\" style=\"position:absolute;left:434px;top:681px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_142\" class=\"drag\" style=\"position:absolute;left:444px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DR LS+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_143\" class=\"drag\" style=\"position:absolute;left:399px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DR LS−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_144\" class=\"drag\" style=\"position:absolute;left:284px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SC LS−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_145\" class=\"drag\" style=\"position:absolute;left:330px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SC LS+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_146\" class=\"drag\" style=\"position:absolute;left:216px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DN LS+<br></b></nobr>");
write("</p>");
write("<p id=\"p2_147\" class=\"drag\" style=\"position:absolute;left:314px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_148\" class=\"drag\" style=\"position:absolute;left:280px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_149\" class=\"drag\" style=\"position:absolute;left:410px;top:375px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>NDR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_150\" class=\"drag\" style=\"position:absolute;left:410px;top:358px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_151\" class=\"drag\" style=\"position:absolute;left:390px;top:309px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_152\" class=\"drag\" style=\"position:absolute;left:366px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_153\" class=\"drag\" style=\"position:absolute;left:434px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_154\" class=\"drag\" style=\"position:absolute;left:324px;top:375px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ECT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_155\" class=\"drag\" style=\"position:absolute;left:324px;top:358px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_156\" class=\"drag\" style=\"position:absolute;left:304px;top:309px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_157\" class=\"drag\" style=\"position:absolute;left:320px;top:681px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_158\" class=\"drag\" style=\"position:absolute;left:274px;top:681px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_159\" class=\"drag\" style=\"position:absolute;left:170px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DN LS−<br></b></nobr>");
write("</p>");
write("<p id=\"p2_160\" class=\"drag\" style=\"position:absolute;left:513px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SOL INH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_161\" class=\"drag\" style=\"position:absolute;left:170px;top:523px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_162\" class=\"drag\" style=\"position:absolute;left:216px;top:523px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_163\" class=\"drag\" style=\"position:absolute;left:284px;top:523px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_164\" class=\"drag\" style=\"position:absolute;left:330px;top:523px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>B16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_165\" class=\"drag\" style=\"position:absolute;left:513px;top:523px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_166\" class=\"drag\" style=\"position:absolute;left:374px;top:440px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>POWERTRAIN CONTROL MODULE (PCM)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_167\" class=\"drag\" style=\"position:absolute;left:160px;top:681px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_168\" class=\"drag\" style=\"position:absolute;left:206px;top:681px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_169\" class=\"drag\" style=\"position:absolute;left:150px;top:584px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PNK/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_170\" class=\"drag\" style=\"position:absolute;left:195px;top:583px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_171\" class=\"drag\" style=\"position:absolute;left:321px;top:583px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_172\" class=\"drag\" style=\"position:absolute;left:264px;top:584px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PNK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_173\" class=\"drag\" style=\"position:absolute;left:492px;top:584px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_174\" class=\"drag\" style=\"position:absolute;left:219px;top:309px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_175\" class=\"drag\" style=\"position:absolute;left:238px;top:358px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_176\" class=\"drag\" style=\"position:absolute;left:238px;top:375px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SG2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_177\" class=\"drag\" style=\"position:absolute;left:228px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_178\" class=\"drag\" style=\"position:absolute;left:194px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_179\" class=\"drag\" style=\"position:absolute;left:160px;top:122px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_180\" class=\"drag\" style=\"position:absolute;left:184px;top:321px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_181\" class=\"drag\" style=\"position:absolute;left:150px;top:309px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_182\" class=\"drag\" style=\"position:absolute;left:204px;top:358px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_183\" class=\"drag\" style=\"position:absolute;left:204px;top:375px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>TPS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_184\" class=\"drag\" style=\"position:absolute;left:170px;top:358px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_185\" class=\"drag\" style=\"position:absolute;left:170px;top:375px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>VCC2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_186\" class=\"drag\" style=\"position:absolute;left:172px;top:34px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>THROTTLE <br>POSITION SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_187\" class=\"drag\" style=\"position:absolute;left:274px;top:25px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ENGINE COOLANT <br>TEMPERATURE <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_188\" class=\"drag\" style=\"position:absolute;left:376px;top:34px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CVT DRIVE PULLEY <br>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_189\" class=\"drag\" style=\"position:absolute;left:491px;top:34px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>MANIFOLD ABSOLUTE <br>PRESSURE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_190\" class=\"drag\" style=\"position:absolute;left:612px;top:34px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CVT DRIVEN PULLEY <br>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_191\" class=\"drag\" style=\"position:absolute;left:153px;top:746px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CVT DRIVEN PULLEY <br>PRESSURE CONTROL <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_192\" class=\"drag\" style=\"position:absolute;left:267px;top:746px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CVT START CLUTCH <br>PRESSURE CONTROL <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_193\" class=\"drag\" style=\"position:absolute;left:382px;top:746px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CVT DRIVE PULLEY <br>PRESSURE CONTROL <br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_194\" class=\"drag\" style=\"position:absolute;left:816px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LG2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_195\" class=\"drag\" style=\"position:absolute;left:816px;top:523px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A23<br></b></nobr>");
write("</p>");
write("<p id=\"p2_196\" class=\"drag\" style=\"position:absolute;left:771px;top:523px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A24<br></b></nobr>");
write("</p>");
write("<p id=\"p2_197\" class=\"drag\" style=\"position:absolute;left:771px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LG1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_198\" class=\"drag\" style=\"position:absolute;left:804px;top:847px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p2_199\" class=\"drag\" style=\"position:absolute;left:751px;top:578px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_200\" class=\"drag\" style=\"position:absolute;left:796px;top:578px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_201\" class=\"drag\" style=\"position:absolute;left:796px;top:664px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_202\" class=\"drag\" style=\"position:absolute;left:633px;top:523px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_203\" class=\"drag\" style=\"position:absolute;left:633px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PG2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_204\" class=\"drag\" style=\"position:absolute;left:596px;top:560px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK (L15A1 engine)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_205\" class=\"drag\" style=\"position:absolute;left:588px;top:523px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_206\" class=\"drag\" style=\"position:absolute;left:588px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PG1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_207\" class=\"drag\" style=\"position:absolute;left:577px;top:578px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_208\" class=\"drag\" style=\"position:absolute;left:621px;top:847px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p2_209\" class=\"drag\" style=\"position:absolute;left:623px;top:664px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_210\" class=\"drag\" style=\"position:absolute;left:669px;top:578px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_211\" class=\"drag\" style=\"position:absolute;left:679px;top:523px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_212\" class=\"drag\" style=\"position:absolute;left:725px;top:523px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>C3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_213\" class=\"drag\" style=\"position:absolute;left:596px;top:551px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN (L13A1 engine)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_214\" class=\"drag\" style=\"position:absolute;left:312px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_215\" class=\"drag\" style=\"position:absolute;left:389px;top:932px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_216\" class=\"drag\" style=\"position:absolute;left:679px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CVT PG1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_217\" class=\"drag\" style=\"position:absolute;left:725px;top:506px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CVT PG2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_218\" class=\"drag\" style=\"position:absolute;left:687px;top:560px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK (L15A1 engine)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_219\" class=\"drag\" style=\"position:absolute;left:687px;top:551px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN (L13A1 engine)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}