with(document) {
write("<v:group id=\"group4\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect4\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img4\" src=\"../img/SAA6EHPA20300000000DBAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p4_1\" class=\"drag\" style=\"position:absolute;left:75px;top:594px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" class=\"drag\" style=\"position:absolute;left:75px;top:580px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" class=\"drag\" style=\"position:absolute;left:75px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" class=\"drag\" style=\"position:absolute;left:193px;top:179px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" class=\"drag\" style=\"position:absolute;left:217px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" class=\"drag\" style=\"position:absolute;left:217px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" class=\"drag\" style=\"position:absolute;left:193px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" class=\"drag\" style=\"position:absolute;left:193px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" class=\"drag\" style=\"position:absolute;left:217px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" class=\"drag\" style=\"position:absolute;left:217px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" class=\"drag\" style=\"position:absolute;left:193px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" class=\"drag\" style=\"position:absolute;left:213px;top:98px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" class=\"drag\" style=\"position:absolute;left:232px;top:98px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" class=\"drag\" style=\"position:absolute;left:232px;top:80px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" class=\"drag\" style=\"position:absolute;left:213px;top:80px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" class=\"drag\" style=\"position:absolute;left:27px;top:1035px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" class=\"drag\" style=\"position:absolute;left:82px;top:1035px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" class=\"drag\" style=\"position:absolute;left:82px;top:1049px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" class=\"drag\" style=\"position:absolute;left:82px;top:1064px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p4_20\" class=\"drag\" style=\"position:absolute;left:97px;top:1049px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with female terminals (single outline): View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p4_21\" class=\"drag\" style=\"position:absolute;left:97px;top:1035px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with male terminals (double outline): View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p4_22\" class=\"drag\" style=\"position:absolute;left:115px;top:1064px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to ECM/PCM control.<br></b></nobr>");
write("</p>");
write("<p id=\"p4_23\" class=\"drag\" style=\"position:absolute;left:182px;top:39px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C122<br></b></nobr>");
write("</p>");
write("<p id=\"p4_24\" class=\"drag\" style=\"position:absolute;left:39px;top:468px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C136<br></b></nobr>");
write("</p>");
write("<p id=\"p4_25\" class=\"drag\" style=\"position:absolute;left:50px;top:565px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_26\" class=\"drag\" style=\"position:absolute;left:95px;top:520px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_27\" class=\"drag\" style=\"position:absolute;left:76px;top:520px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_28\" class=\"drag\" style=\"position:absolute;left:57px;top:520px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_29\" class=\"drag\" style=\"position:absolute;left:50px;top:580px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_30\" class=\"drag\" style=\"position:absolute;left:50px;top:594px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_31\" class=\"drag\" style=\"position:absolute;left:646px;top:344px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_32\" class=\"drag\" style=\"position:absolute;left:708px;top:358px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p4_33\" class=\"drag\" style=\"position:absolute;left:732px;top:358px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_34\" class=\"drag\" style=\"position:absolute;left:646px;top:358px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_35\" class=\"drag\" style=\"position:absolute;left:732px;top:330px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_36\" class=\"drag\" style=\"position:absolute;left:708px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_37\" class=\"drag\" style=\"position:absolute;left:708px;top:344px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p4_38\" class=\"drag\" style=\"position:absolute;left:622px;top:358px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_39\" class=\"drag\" style=\"position:absolute;left:622px;top:344px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_40\" class=\"drag\" style=\"position:absolute;left:646px;top:330px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_41\" class=\"drag\" style=\"position:absolute;left:622px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_42\" class=\"drag\" style=\"position:absolute;left:675px;top:275px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_43\" class=\"drag\" style=\"position:absolute;left:694px;top:275px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_44\" class=\"drag\" style=\"position:absolute;left:712px;top:275px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_45\" class=\"drag\" style=\"position:absolute;left:675px;top:294px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_46\" class=\"drag\" style=\"position:absolute;left:712px;top:294px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p4_47\" class=\"drag\" style=\"position:absolute;left:611px;top:232px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C131<br></b></nobr>");
write("</p>");
write("<p id=\"p4_48\" class=\"drag\" style=\"position:absolute;left:325px;top:232px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C129<br></b></nobr>");
write("</p>");
write("<p id=\"p4_49\" class=\"drag\" style=\"position:absolute;left:374px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_50\" class=\"drag\" style=\"position:absolute;left:355px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_51\" class=\"drag\" style=\"position:absolute;left:336px;top:344px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_52\" class=\"drag\" style=\"position:absolute;left:360px;top:344px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_53\" class=\"drag\" style=\"position:absolute;left:360px;top:330px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_54\" class=\"drag\" style=\"position:absolute;left:336px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_55\" class=\"drag\" style=\"position:absolute;left:468px;top:232px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C130<br></b></nobr>");
write("</p>");
write("<p id=\"p4_56\" class=\"drag\" style=\"position:absolute;left:479px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_57\" class=\"drag\" style=\"position:absolute;left:503px;top:330px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_58\" class=\"drag\" style=\"position:absolute;left:503px;top:344px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_59\" class=\"drag\" style=\"position:absolute;left:524px;top:284px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_60\" class=\"drag\" style=\"position:absolute;left:505px;top:284px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_61\" class=\"drag\" style=\"position:absolute;left:486px;top:284px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_62\" class=\"drag\" style=\"position:absolute;left:479px;top:344px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_63\" class=\"drag\" style=\"position:absolute;left:479px;top:358px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_64\" class=\"drag\" style=\"position:absolute;left:503px;top:358px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_65\" class=\"drag\" style=\"position:absolute;left:217px;top:358px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_66\" class=\"drag\" style=\"position:absolute;left:193px;top:358px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_67\" class=\"drag\" style=\"position:absolute;left:193px;top:344px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_68\" class=\"drag\" style=\"position:absolute;left:200px;top:284px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_69\" class=\"drag\" style=\"position:absolute;left:219px;top:284px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_70\" class=\"drag\" style=\"position:absolute;left:238px;top:284px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_71\" class=\"drag\" style=\"position:absolute;left:217px;top:344px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_72\" class=\"drag\" style=\"position:absolute;left:217px;top:330px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_73\" class=\"drag\" style=\"position:absolute;left:193px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_74\" class=\"drag\" style=\"position:absolute;left:182px;top:232px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C128<br></b></nobr>");
write("</p>");
write("<p id=\"p4_75\" class=\"drag\" style=\"position:absolute;left:50px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_76\" class=\"drag\" style=\"position:absolute;left:75px;top:330px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_77\" class=\"drag\" style=\"position:absolute;left:75px;top:344px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_78\" class=\"drag\" style=\"position:absolute;left:50px;top:344px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_79\" class=\"drag\" style=\"position:absolute;left:70px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_80\" class=\"drag\" style=\"position:absolute;left:89px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_81\" class=\"drag\" style=\"position:absolute;left:39px;top:232px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C127<br></b></nobr>");
write("</p>");
write("<p id=\"p4_82\" class=\"drag\" style=\"position:absolute;left:603px;top:39px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C125<br></b></nobr>");
write("</p>");
write("<p id=\"p4_83\" class=\"drag\" style=\"position:absolute;left:653px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_84\" class=\"drag\" style=\"position:absolute;left:634px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_85\" class=\"drag\" style=\"position:absolute;left:615px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_86\" class=\"drag\" style=\"position:absolute;left:639px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_87\" class=\"drag\" style=\"position:absolute;left:639px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_88\" class=\"drag\" style=\"position:absolute;left:615px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_89\" class=\"drag\" style=\"position:absolute;left:746px;top:39px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C126<br></b></nobr>");
write("</p>");
write("<p id=\"p4_90\" class=\"drag\" style=\"position:absolute;left:758px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_91\" class=\"drag\" style=\"position:absolute;left:782px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_92\" class=\"drag\" style=\"position:absolute;left:782px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_93\" class=\"drag\" style=\"position:absolute;left:802px;top:91px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_94\" class=\"drag\" style=\"position:absolute;left:784px;top:91px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_95\" class=\"drag\" style=\"position:absolute;left:765px;top:91px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_96\" class=\"drag\" style=\"position:absolute;left:758px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_97\" class=\"drag\" style=\"position:absolute;left:758px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_98\" class=\"drag\" style=\"position:absolute;left:782px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_99\" class=\"drag\" style=\"position:absolute;left:503px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_100\" class=\"drag\" style=\"position:absolute;left:479px;top:165px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_101\" class=\"drag\" style=\"position:absolute;left:479px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_102\" class=\"drag\" style=\"position:absolute;left:486px;top:91px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_103\" class=\"drag\" style=\"position:absolute;left:505px;top:91px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_104\" class=\"drag\" style=\"position:absolute;left:524px;top:91px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_105\" class=\"drag\" style=\"position:absolute;left:503px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_106\" class=\"drag\" style=\"position:absolute;left:503px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_107\" class=\"drag\" style=\"position:absolute;left:479px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_108\" class=\"drag\" style=\"position:absolute;left:468px;top:39px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C124<br></b></nobr>");
write("</p>");
write("<p id=\"p4_109\" class=\"drag\" style=\"position:absolute;left:50px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_110\" class=\"drag\" style=\"position:absolute;left:75px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_111\" class=\"drag\" style=\"position:absolute;left:79px;top:91px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_112\" class=\"drag\" style=\"position:absolute;left:39px;top:39px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C121<br></b></nobr>");
write("</p>");
write("<p id=\"p4_113\" class=\"drag\" style=\"position:absolute;left:336px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_114\" class=\"drag\" style=\"position:absolute;left:360px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_115\" class=\"drag\" style=\"position:absolute;left:360px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_116\" class=\"drag\" style=\"position:absolute;left:336px;top:151px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_117\" class=\"drag\" style=\"position:absolute;left:355px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_118\" class=\"drag\" style=\"position:absolute;left:374px;top:85px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_119\" class=\"drag\" style=\"position:absolute;left:325px;top:39px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C123<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}