with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\" coordsize=\"950,863\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:863px;\">");
write("<img id=\"img1\" src=\"../img/SAA6EU0A18400025501KDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:741px;top:492px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST MANIFOLD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:220px;top:114px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:608px;top:772px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m<br>(2.2 kgf·m, 16 lbf·ft)<br></b>Tighten the bolts in steps,<br>alternating side-to-side.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:339px;top:690px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>44 N·m<br>(4.5 kgf·m, 33 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:60px;top:629px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>24 N·m <br>(2.4 kgf·m, 17 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:585px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:203px;top:690px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:826px;top:447px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:16px;top:552px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST MANIFOLD<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:17px;top:438px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PRIMARY HEATED<br>OXYGEN SENSOR<br>(PRIMARY HO2S)<br>44 N·m <br>(4.5 kgf·m, 33 lbf·ft)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}