with(document) {
write("<v:group id=\"group14\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\" coordsize=\"950,863\">");
write("<v:rect id=\"rect14\"class=\"drag\"  style=\"width:950px;height:863px;\">");
write("<img id=\"img14\" src=\"../img/SAA6EHPA20300000000DBAD28.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p14_1\" class=\"drag\" style=\"position:absolute;left:54px;top:414px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EGR VALVE (11)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_2\" class=\"drag\" style=\"position:absolute;left:221px;top:218px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>KNOCK SENSOR (7)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_3\" class=\"drag\" style=\"position:absolute;left:61px;top:33px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 1 IGNITION<br>COIL (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_4\" class=\"drag\" style=\"position:absolute;left:412px;top:34px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 4 IGNITION<br>COIL (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_5\" class=\"drag\" style=\"position:absolute;left:582px;top:219px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ALTERNATOR (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_6\" class=\"drag\" style=\"position:absolute;left:238px;top:32px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 2 IGNITION<br>COIL (2)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_7\" class=\"drag\" style=\"position:absolute;left:589px;top:33px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 4 IGNITION<br>COIL (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_8\" class=\"drag\" style=\"position:absolute;left:396px;top:220px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 2 INJECTOR (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_9\" class=\"drag\" style=\"position:absolute;left:752px;top:220px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 1 INJECTOR (10)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_10\" class=\"drag\" style=\"position:absolute;left:44px;top:220px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 3 INJECTOR (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_11\" class=\"drag\" style=\"position:absolute;left:227px;top:412px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CKP SENSOR (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_12\" class=\"drag\" style=\"position:absolute;left:400px;top:413px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2P CONNECTOR (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_13\" class=\"drag\" style=\"position:absolute;left:572px;top:398px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TEST TACHOMETER<br>CONNECTOR (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_14\" class=\"drag\" style=\"position:absolute;left:731px;top:398px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX (15)**<br></b></nobr>");
write("</p>");
write("<p id=\"p14_15\" class=\"drag\" style=\"position:absolute;left:16px;top:591px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX (16)**<br></b></nobr>");
write("</p>");
write("<p id=\"p14_16\" class=\"drag\" style=\"position:absolute;left:206px;top:591px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX (17)**<br></b></nobr>");
write("</p>");
write("<p id=\"p14_17\" class=\"drag\" style=\"position:absolute;left:399px;top:591px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX (18)**<br></b></nobr>");
write("</p>");
write("<p id=\"p14_18\" class=\"drag\" style=\"position:absolute;left:606px;top:605px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ELD (19)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_19\" class=\"drag\" style=\"position:absolute;left:753px;top:47px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 4 INJECTOR (5)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_20\" class=\"drag\" style=\"position:absolute;left:749px;top:591px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX (20)**<br></b></nobr>");
write("</p>");
write("<p id=\"p14_21\" class=\"drag\" style=\"position:absolute;left:0px;top:761px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE: <br></nobr>");
write("</p>");
write("<p id=\"p14_22\" class=\"drag\" style=\"position:absolute;left:0px;top:780px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>· <br></nobr>");
write("</p>");
write("<p id=\"p14_23\" class=\"drag\" style=\"position:absolute;left:17px;top:781px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Connector with male terminals (double outline): View from terminal side<br></nobr>");
write("</p>");
write("<p id=\"p14_24\" class=\"drag\" style=\"position:absolute;left:0px;top:799px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>· <br></nobr>");
write("</p>");
write("<p id=\"p14_25\" class=\"drag\" style=\"position:absolute;left:17px;top:800px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Connector with female terminals (single outline): View from wire side<br></nobr>");
write("</p>");
write("<p id=\"p14_26\" class=\"drag\" style=\"position:absolute;left:0px;top:825px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>**:<br></nobr>");
write("</p>");
write("<p id=\"p14_27\" class=\"drag\" style=\"position:absolute;left:40px;top:825px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Terminal side of female terminals<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}