with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:950px; height:927px;\" coordsize=\"950,927\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:950px;height:927px;\">");
write("<img id=\"img3\" src=\"../img/SAA6EU0G10100000000FEAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:927px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:795px;top:310px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>80%<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:796px;top:423px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30%<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:795px;top:388px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>80%<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:796px;top:405px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>80%<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:795px;top:490px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30%<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:795px;top:264px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HUMIDITY<br>LEVEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:307px;top:731px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DELIVERY<br>TEMPERATURE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:336px;top:483px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE<br>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:337px;top:629px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DELIVERY<br>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:422px;top:852px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20<br>(68)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:512px;top:852px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>25<br>(77)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:602px;top:852px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30<br>(86)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:690px;top:852px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>35<br>(95)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:781px;top:852px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>40<br>(104)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:829px;top:852px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>°C<br>(°F)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:472px;top:897px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE TEMPERATURE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:258px;top:403px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30<br>(86)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:257px;top:549px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20<br>(68)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:257px;top:692px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10<br>(50)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:270px;top:835px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:245px;top:877px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DELIVERY<br>TEMPERATURE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:273px;top:228px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>°C<br>(°F)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:122px;top:334px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>400<br>(4.1)<br>[58]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:122px;top:476px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>200<br>(2.0)<br>[29]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:143px;top:620px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:147px;top:140px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>kPa<br>(kgf/cm<sup>2</sup>)<br>[psi]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:41px;top:605px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE<br>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:93px;top:822px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DELIVERY<br>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:796px;top:619px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30%<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:204px;top:835px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:176px;top:404px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3,000<br>(30.6)<br>[435]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:177px;top:548px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2,000<br>(20.4)<br>[290]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:177px;top:692px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1,000<br>(10.2)<br>[145]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:190px;top:207px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>kPa<br>(kgf/cm<sup>2</sup>)<br>[psi]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:116px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Intake temperature (dry):<br>Intake temperature (wet):<br>Delivery temperature:<br>Delivery pressure:<br>Intake pressure:<br>within normal range<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:330px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30 °C (86 °F) Humidity level 70 %<br>25.5 °C (77.9 °F)<br>18.1 °C  (64.6 °F)<br>2,230 kPa (22.7 kgf/cm<sup>2</sup>) (323 psi)<br>291 kPa (3.0 kgf/cm<sup>2</sup>) (42 psi)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:38px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Example<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:38px;top:91px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Results<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:123px;top:190px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>600<br>(6.1)<br>[87]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:176px;top:261px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4,000<br>(40.8)<br>[580]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:250px;top:262px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>40<br>(104)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}