with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img3\" src=\"../img/SAA6EHPA20300000000EAAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:879px;top:207px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To<br>SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:747px;top:321px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:709px;top:182px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 INTAKE SIDE IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:746px;top:150px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:879px;top:122px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To<br>SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:619px;top:123px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:199px;top:152px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS1I<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:639px;top:162px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:746px;top:236px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:199px;top:238px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS2I<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:879px;top:292px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To<br>SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:199px;top:323px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS3I<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:746px;top:406px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:879px;top:378px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To<br>SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:199px;top:408px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS4I<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:639px;top:527px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:261px;top:141px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:261px;top:227px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:258px;top:311px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:261px;top:397px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:482px;top:470px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:345px;top:909px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:708px;top:634px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 EXHAUST SIDE IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:746px;top:602px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:880px;top:573px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To<br>SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:200px;top:604px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS1E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:639px;top:613px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:746px;top:687px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:880px;top:659px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To<br>SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:200px;top:689px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS2E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:639px;top:699px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:746px;top:772px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:880px;top:744px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To<br>SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:200px;top:774px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS3E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:639px;top:784px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:746px;top:858px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:880px;top:829px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To<br>SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:200px;top:860px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS4E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:639px;top:869px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:639px;top:979px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:642px;top:923px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:259px;top:677px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:259px;top:763px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:478px;top:1068px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:437px;top:1067px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:472px;top:886px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:422px;top:984px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/<br>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:638px;top:829px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:638px;top:744px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" class=\"drag\" style=\"position:absolute;left:638px;top:659px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" class=\"drag\" style=\"position:absolute;left:638px;top:574px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" class=\"drag\" style=\"position:absolute;left:272px;top:591px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" class=\"drag\" style=\"position:absolute;left:262px;top:849px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" class=\"drag\" style=\"position:absolute;left:406px;top:441px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" class=\"drag\" style=\"position:absolute;left:431px;top:932px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" class=\"drag\" style=\"position:absolute;left:472px;top:931px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" class=\"drag\" style=\"position:absolute;left:691px;top:822px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" class=\"drag\" style=\"position:absolute;left:691px;top:839px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" class=\"drag\" style=\"position:absolute;left:691px;top:860px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" class=\"drag\" style=\"position:absolute;left:485px;top:549px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" class=\"drag\" style=\"position:absolute;left:502px;top:549px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" class=\"drag\" style=\"position:absolute;left:519px;top:549px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" class=\"drag\" style=\"position:absolute;left:536px;top:549px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" class=\"drag\" style=\"position:absolute;left:553px;top:548px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" class=\"drag\" style=\"position:absolute;left:691px;top:737px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" class=\"drag\" style=\"position:absolute;left:691px;top:754px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" class=\"drag\" style=\"position:absolute;left:691px;top:775px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" class=\"drag\" style=\"position:absolute;left:691px;top:651px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" class=\"drag\" style=\"position:absolute;left:691px;top:668px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" class=\"drag\" style=\"position:absolute;left:691px;top:690px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" class=\"drag\" style=\"position:absolute;left:691px;top:566px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" class=\"drag\" style=\"position:absolute;left:691px;top:583px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" class=\"drag\" style=\"position:absolute;left:691px;top:604px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" class=\"drag\" style=\"position:absolute;left:692px;top:371px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" class=\"drag\" style=\"position:absolute;left:692px;top:388px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" class=\"drag\" style=\"position:absolute;left:692px;top:409px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" class=\"drag\" style=\"position:absolute;left:692px;top:286px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" class=\"drag\" style=\"position:absolute;left:692px;top:303px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" class=\"drag\" style=\"position:absolute;left:692px;top:324px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" class=\"drag\" style=\"position:absolute;left:692px;top:200px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" class=\"drag\" style=\"position:absolute;left:692px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" class=\"drag\" style=\"position:absolute;left:692px;top:239px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" class=\"drag\" style=\"position:absolute;left:696px;top:115px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" class=\"drag\" style=\"position:absolute;left:696px;top:132px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" class=\"drag\" style=\"position:absolute;left:696px;top:153px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" class=\"drag\" style=\"position:absolute;left:484px;top:98px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" class=\"drag\" style=\"position:absolute;left:502px;top:98px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" class=\"drag\" style=\"position:absolute;left:520px;top:98px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" class=\"drag\" style=\"position:absolute;left:537px;top:98px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" class=\"drag\" style=\"position:absolute;left:553px;top:98px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" class=\"drag\" style=\"position:absolute;left:482px;top:19px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" class=\"drag\" style=\"position:absolute;left:200px;top:130px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A30<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" class=\"drag\" style=\"position:absolute;left:200px;top:215px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A29<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" class=\"drag\" style=\"position:absolute;left:200px;top:301px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A28<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" class=\"drag\" style=\"position:absolute;left:200px;top:386px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A27<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" class=\"drag\" style=\"position:absolute;left:200px;top:582px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" class=\"drag\" style=\"position:absolute;left:200px;top:667px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_98\" class=\"drag\" style=\"position:absolute;left:200px;top:752px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p3_99\" class=\"drag\" style=\"position:absolute;left:200px;top:837px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B22<br></b></nobr>");
write("</p>");
write("<p id=\"p3_100\" class=\"drag\" style=\"position:absolute;left:466px;top:984px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/<br>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_101\" class=\"drag\" style=\"position:absolute;left:619px;top:208px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_102\" class=\"drag\" style=\"position:absolute;left:639px;top:247px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_103\" class=\"drag\" style=\"position:absolute;left:619px;top:294px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_104\" class=\"drag\" style=\"position:absolute;left:639px;top:333px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_105\" class=\"drag\" style=\"position:absolute;left:619px;top:379px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_106\" class=\"drag\" style=\"position:absolute;left:639px;top:418px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_107\" class=\"drag\" style=\"position:absolute;left:709px;top:269px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 INTAKE SIDE IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_108\" class=\"drag\" style=\"position:absolute;left:709px;top:354px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 3 INTAKE SIDE IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_109\" class=\"drag\" style=\"position:absolute;left:709px;top:440px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 4 INTAKE SIDE IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_110\" class=\"drag\" style=\"position:absolute;left:709px;top:720px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 EXHAUST SIDE IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_111\" class=\"drag\" style=\"position:absolute;left:709px;top:805px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 3 EXHAUST SIDE IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_112\" class=\"drag\" style=\"position:absolute;left:709px;top:891px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 4 EXHAUST SIDE IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_113\" class=\"drag\" style=\"position:absolute;left:644px;top:477px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}