with(document) {
write("<v:group id=\"group5\" class=\"drag\" style=\"position:relative; width:950px; height:719px;\" coordsize=\"950,719\">");
write("<v:rect id=\"rect5\"class=\"drag\"  style=\"width:950px;height:719px;\">");
write("<img id=\"img5\" src=\"../img/SAA6EHPA20300000000DBAD19.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:719px;border-color:#ffffff\">");
write("<p id=\"p5_1\" class=\"drag\" style=\"position:absolute;left:305px;top:18px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" class=\"drag\" style=\"position:absolute;left:830px;top:455px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" class=\"drag\" style=\"position:absolute;left:466px;top:66px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" class=\"drag\" style=\"position:absolute;left:773px;top:120px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" class=\"drag\" style=\"position:absolute;left:734px;top:83px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" class=\"drag\" style=\"position:absolute;left:680px;top:45px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" class=\"drag\" style=\"position:absolute;left:559px;top:65px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" class=\"drag\" style=\"position:absolute;left:190px;top:660px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" class=\"drag\" style=\"position:absolute;left:866px;top:549px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" class=\"drag\" style=\"position:absolute;left:521px;top:522px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" class=\"drag\" style=\"position:absolute;left:248px;top:667px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" class=\"drag\" style=\"position:absolute;left:116px;top:641px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" class=\"drag\" style=\"position:absolute;left:807px;top:233px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}