with(document) {
write("<v:group id=\"group12\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect12\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img12\" src=\"../img/SAA6EHPA20300000000EAAD18.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p12_1\" class=\"drag\" style=\"position:absolute;left:792px;top:457px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IAT SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p12_2\" class=\"drag\" style=\"position:absolute;left:693px;top:421px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_3\" class=\"drag\" style=\"position:absolute;left:693px;top:437px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_4\" class=\"drag\" style=\"position:absolute;left:793px;top:135px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p12_5\" class=\"drag\" style=\"position:absolute;left:801px;top:333px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p12_6\" class=\"drag\" style=\"position:absolute;left:801px;top:517px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR VALVE<br>POSITION<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p12_7\" class=\"drag\" style=\"position:absolute;left:796px;top:638px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p12_8\" class=\"drag\" style=\"position:absolute;left:692px;top:292px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_9\" class=\"drag\" style=\"position:absolute;left:693px;top:310px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_10\" class=\"drag\" style=\"position:absolute;left:693px;top:556px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_11\" class=\"drag\" style=\"position:absolute;left:693px;top:589px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_12\" class=\"drag\" style=\"position:absolute;left:662px;top:682px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p12_13\" class=\"drag\" style=\"position:absolute;left:792px;top:745px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECT SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p12_14\" class=\"drag\" style=\"position:absolute;left:693px;top:708px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_15\" class=\"drag\" style=\"position:absolute;left:693px;top:725px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_16\" class=\"drag\" style=\"position:absolute;left:705px;top:622px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_17\" class=\"drag\" style=\"position:absolute;left:193px;top:446px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IAT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_18\" class=\"drag\" style=\"position:absolute;left:241px;top:572px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_19\" class=\"drag\" style=\"position:absolute;left:194px;top:580px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGRP<br></b></nobr>");
write("</p>");
write("<p id=\"p12_20\" class=\"drag\" style=\"position:absolute;left:238px;top:656px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_21\" class=\"drag\" style=\"position:absolute;left:196px;top:664px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR<br></b></nobr>");
write("</p>");
write("<p id=\"p12_22\" class=\"drag\" style=\"position:absolute;left:195px;top:734px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_23\" class=\"drag\" style=\"position:absolute;left:193px;top:941px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SG2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_24\" class=\"drag\" style=\"position:absolute;left:246px;top:438px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p12_25\" class=\"drag\" style=\"position:absolute;left:244px;top:726px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_26\" class=\"drag\" style=\"position:absolute;left:261px;top:932px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_27\" class=\"drag\" style=\"position:absolute;left:241px;top:76px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p12_28\" class=\"drag\" style=\"position:absolute;left:394px;top:238px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p12_29\" class=\"drag\" style=\"position:absolute;left:241px;top:272px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_30\" class=\"drag\" style=\"position:absolute;left:241px;top:108px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p12_31\" class=\"drag\" style=\"position:absolute;left:239px;top:138px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p12_32\" class=\"drag\" style=\"position:absolute;left:194px;top:84px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VCC1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_33\" class=\"drag\" style=\"position:absolute;left:194px;top:115px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAP<br></b></nobr>");
write("</p>");
write("<p id=\"p12_34\" class=\"drag\" style=\"position:absolute;left:194px;top:147px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SG1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_35\" class=\"drag\" style=\"position:absolute;left:194px;top:280px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VCC2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_36\" class=\"drag\" style=\"position:absolute;left:241px;top:303px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_37\" class=\"drag\" style=\"position:absolute;left:194px;top:311px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TPS<br></b></nobr>");
write("</p>");
write("<p id=\"p12_38\" class=\"drag\" style=\"position:absolute;left:775px;top:68px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_39\" class=\"drag\" style=\"position:absolute;left:775px;top:87px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_40\" class=\"drag\" style=\"position:absolute;left:775px;top:106px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_41\" class=\"drag\" style=\"position:absolute;left:775px;top:265px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_42\" class=\"drag\" style=\"position:absolute;left:775px;top:284px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_43\" class=\"drag\" style=\"position:absolute;left:775px;top:303px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_44\" class=\"drag\" style=\"position:absolute;left:775px;top:413px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_45\" class=\"drag\" style=\"position:absolute;left:775px;top:430px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_46\" class=\"drag\" style=\"position:absolute;left:775px;top:547px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_47\" class=\"drag\" style=\"position:absolute;left:775px;top:564px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_48\" class=\"drag\" style=\"position:absolute;left:775px;top:581px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_49\" class=\"drag\" style=\"position:absolute;left:775px;top:597px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_50\" class=\"drag\" style=\"position:absolute;left:775px;top:613px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_51\" class=\"drag\" style=\"position:absolute;left:775px;top:701px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_52\" class=\"drag\" style=\"position:absolute;left:775px;top:717px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_53\" class=\"drag\" style=\"position:absolute;left:194px;top:925px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p12_54\" class=\"drag\" style=\"position:absolute;left:194px;top:430px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B17<br></b></nobr>");
write("</p>");
write("<p id=\"p12_55\" class=\"drag\" style=\"position:absolute;left:195px;top:564px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p12_56\" class=\"drag\" style=\"position:absolute;left:196px;top:648px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p12_57\" class=\"drag\" style=\"position:absolute;left:197px;top:718px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p12_58\" class=\"drag\" style=\"position:absolute;left:195px;top:69px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A21<br></b></nobr>");
write("</p>");
write("<p id=\"p12_59\" class=\"drag\" style=\"position:absolute;left:194px;top:100px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A19<br></b></nobr>");
write("</p>");
write("<p id=\"p12_60\" class=\"drag\" style=\"position:absolute;left:194px;top:131px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p12_61\" class=\"drag\" style=\"position:absolute;left:195px;top:266px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p12_62\" class=\"drag\" style=\"position:absolute;left:195px;top:296px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_63\" class=\"drag\" style=\"position:absolute;left:388px;top:165px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/<br>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p12_64\" class=\"drag\" style=\"position:absolute;left:630px;top:1040px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p12_65\" class=\"drag\" style=\"position:absolute;left:480px;top:239px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p12_66\" class=\"drag\" style=\"position:absolute;left:692px;top:273px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_67\" class=\"drag\" style=\"position:absolute;left:596px;top:205px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p12_68\" class=\"drag\" style=\"position:absolute;left:672px;top:172px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p12_69\" class=\"drag\" style=\"position:absolute;left:700px;top:172px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_70\" class=\"drag\" style=\"position:absolute;left:727px;top:172px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p12_71\" class=\"drag\" style=\"position:absolute;left:755px;top:172px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p12_72\" class=\"drag\" style=\"position:absolute;left:786px;top:163px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p12_73\" class=\"drag\" style=\"position:absolute;left:509px;top:255px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_74\" class=\"drag\" style=\"position:absolute;left:424px;top:255px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_75\" class=\"drag\" style=\"position:absolute;left:727px;top:189px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p12_76\" class=\"drag\" style=\"position:absolute;left:755px;top:189px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_77\" class=\"drag\" style=\"position:absolute;left:185px;top:1064px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*2: CVT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}