with(document) {
write("<v:group id=\"group10\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect10\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img10\" src=\"../img/SAA6EHPA20300000000DBAD10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p10_1\" class=\"drag\" style=\"position:absolute;left:75px;top:761px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_2\" class=\"drag\" style=\"position:absolute;left:160px;top:761px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_3\" class=\"drag\" style=\"position:absolute;left:160px;top:747px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_4\" class=\"drag\" style=\"position:absolute;left:160px;top:661px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_5\" class=\"drag\" style=\"position:absolute;left:75px;top:661px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_6\" class=\"drag\" style=\"position:absolute;left:75px;top:675px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_7\" class=\"drag\" style=\"position:absolute;left:50px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_8\" class=\"drag\" style=\"position:absolute;left:134px;top:776px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p10_9\" class=\"drag\" style=\"position:absolute;left:160px;top:776px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_10\" class=\"drag\" style=\"position:absolute;left:75px;top:776px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_11\" class=\"drag\" style=\"position:absolute;left:160px;top:718px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_12\" class=\"drag\" style=\"position:absolute;left:50px;top:718px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_13\" class=\"drag\" style=\"position:absolute;left:133px;top:704px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_14\" class=\"drag\" style=\"position:absolute;left:133px;top:690px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_15\" class=\"drag\" style=\"position:absolute;left:133px;top:661px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_16\" class=\"drag\" style=\"position:absolute;left:160px;top:675px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_17\" class=\"drag\" style=\"position:absolute;left:160px;top:690px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_18\" class=\"drag\" style=\"position:absolute;left:160px;top:704px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_19\" class=\"drag\" style=\"position:absolute;left:50px;top:704px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_20\" class=\"drag\" style=\"position:absolute;left:133px;top:675px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_21\" class=\"drag\" style=\"position:absolute;left:75px;top:690px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_22\" class=\"drag\" style=\"position:absolute;left:50px;top:690px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_23\" class=\"drag\" style=\"position:absolute;left:50px;top:675px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_24\" class=\"drag\" style=\"position:absolute;left:50px;top:661px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_25\" class=\"drag\" style=\"position:absolute;left:75px;top:747px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_26\" class=\"drag\" style=\"position:absolute;left:50px;top:747px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_27\" class=\"drag\" style=\"position:absolute;left:160px;top:733px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_28\" class=\"drag\" style=\"position:absolute;left:75px;top:718px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_29\" class=\"drag\" style=\"position:absolute;left:50px;top:732px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_30\" class=\"drag\" style=\"position:absolute;left:134px;top:733px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p10_31\" class=\"drag\" style=\"position:absolute;left:134px;top:748px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_32\" class=\"drag\" style=\"position:absolute;left:133px;top:718px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_33\" class=\"drag\" style=\"position:absolute;left:75px;top:704px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_34\" class=\"drag\" style=\"position:absolute;left:50px;top:761px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_35\" class=\"drag\" style=\"position:absolute;left:75px;top:733px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_36\" class=\"drag\" style=\"position:absolute;left:134px;top:762px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p10_37\" class=\"drag\" style=\"position:absolute;left:39px;top:571px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C307<br></b></nobr>");
write("</p>");
write("<p id=\"p10_38\" class=\"drag\" style=\"position:absolute;left:181px;top:619px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_39\" class=\"drag\" style=\"position:absolute;left:183px;top:600px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_40\" class=\"drag\" style=\"position:absolute;left:199px;top:619px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p10_41\" class=\"drag\" style=\"position:absolute;left:202px;top:600px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_42\" class=\"drag\" style=\"position:absolute;left:218px;top:619px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p10_43\" class=\"drag\" style=\"position:absolute;left:220px;top:600px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_44\" class=\"drag\" style=\"position:absolute;left:158px;top:619px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p10_45\" class=\"drag\" style=\"position:absolute;left:161px;top:600px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_46\" class=\"drag\" style=\"position:absolute;left:140px;top:619px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_47\" class=\"drag\" style=\"position:absolute;left:121px;top:619px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_48\" class=\"drag\" style=\"position:absolute;left:62px;top:619px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_49\" class=\"drag\" style=\"position:absolute;left:64px;top:600px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_50\" class=\"drag\" style=\"position:absolute;left:46px;top:619px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_51\" class=\"drag\" style=\"position:absolute;left:46px;top:600px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_52\" class=\"drag\" style=\"position:absolute;left:105px;top:600px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_53\" class=\"drag\" style=\"position:absolute;left:103px;top:619px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_54\" class=\"drag\" style=\"position:absolute;left:83px;top:600px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_55\" class=\"drag\" style=\"position:absolute;left:80px;top:619px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_56\" class=\"drag\" style=\"position:absolute;left:635px;top:512px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_57\" class=\"drag\" style=\"position:absolute;left:575px;top:483px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_58\" class=\"drag\" style=\"position:absolute;left:551px;top:511px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_59\" class=\"drag\" style=\"position:absolute;left:573px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_60\" class=\"drag\" style=\"position:absolute;left:592px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_61\" class=\"drag\" style=\"position:absolute;left:611px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_62\" class=\"drag\" style=\"position:absolute;left:629px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_63\" class=\"drag\" style=\"position:absolute;left:648px;top:369px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_64\" class=\"drag\" style=\"position:absolute;left:669px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_65\" class=\"drag\" style=\"position:absolute;left:650px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_66\" class=\"drag\" style=\"position:absolute;left:632px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_67\" class=\"drag\" style=\"position:absolute;left:613px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_68\" class=\"drag\" style=\"position:absolute;left:594px;top:350px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_69\" class=\"drag\" style=\"position:absolute;left:27px;top:1024px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>NOTE:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_70\" class=\"drag\" style=\"position:absolute;left:98px;top:1024px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with male terminals (double outline): View from terminal side<br></b></nobr>");
write("</p>");
write("<p id=\"p10_71\" class=\"drag\" style=\"position:absolute;left:98px;top:1038px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Connector with female terminals (single outline): View from wire side<br></b></nobr>");
write("</p>");
write("<p id=\"p10_72\" class=\"drag\" style=\"position:absolute;left:116px;top:1052px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>: Related to ECM/PCM control.<br></b></nobr>");
write("</p>");
write("<p id=\"p10_73\" class=\"drag\" style=\"position:absolute;left:97px;top:1075px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>* : Terminal side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p10_74\" class=\"drag\" style=\"position:absolute;left:82px;top:1052px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p10_75\" class=\"drag\" style=\"position:absolute;left:82px;top:1038px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p10_76\" class=\"drag\" style=\"position:absolute;left:82px;top:1024px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p10_77\" class=\"drag\" style=\"position:absolute;left:575px;top:454px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_78\" class=\"drag\" style=\"position:absolute;left:634px;top:468px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_79\" class=\"drag\" style=\"position:absolute;left:635px;top:498px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p10_80\" class=\"drag\" style=\"position:absolute;left:635px;top:483px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_81\" class=\"drag\" style=\"position:absolute;left:551px;top:482px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_82\" class=\"drag\" style=\"position:absolute;left:575px;top:468px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_83\" class=\"drag\" style=\"position:absolute;left:661px;top:483px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_84\" class=\"drag\" style=\"position:absolute;left:551px;top:497px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_85\" class=\"drag\" style=\"position:absolute;left:575px;top:497px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_86\" class=\"drag\" style=\"position:absolute;left:551px;top:411px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_87\" class=\"drag\" style=\"position:absolute;left:551px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_88\" class=\"drag\" style=\"position:absolute;left:551px;top:440px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_89\" class=\"drag\" style=\"position:absolute;left:575px;top:440px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_90\" class=\"drag\" style=\"position:absolute;left:634px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_91\" class=\"drag\" style=\"position:absolute;left:551px;top:454px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_92\" class=\"drag\" style=\"position:absolute;left:661px;top:454px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_93\" class=\"drag\" style=\"position:absolute;left:661px;top:440px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_94\" class=\"drag\" style=\"position:absolute;left:661px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_95\" class=\"drag\" style=\"position:absolute;left:539px;top:313px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C306<br></b></nobr>");
write("</p>");
write("<p id=\"p10_96\" class=\"drag\" style=\"position:absolute;left:636px;top:411px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_97\" class=\"drag\" style=\"position:absolute;left:634px;top:440px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_98\" class=\"drag\" style=\"position:absolute;left:634px;top:454px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_99\" class=\"drag\" style=\"position:absolute;left:551px;top:468px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_100\" class=\"drag\" style=\"position:absolute;left:661px;top:468px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_101\" class=\"drag\" style=\"position:absolute;left:134px;top:169px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_102\" class=\"drag\" style=\"position:absolute;left:160px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_103\" class=\"drag\" style=\"position:absolute;left:111px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_104\" class=\"drag\" style=\"position:absolute;left:160px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_105\" class=\"drag\" style=\"position:absolute;left:57px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_106\" class=\"drag\" style=\"position:absolute;left:39px;top:313px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C218<br></b></nobr>");
write("</p>");
write("<p id=\"p10_107\" class=\"drag\" style=\"position:absolute;left:70px;top:356px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_108\" class=\"drag\" style=\"position:absolute;left:89px;top:356px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_109\" class=\"drag\" style=\"position:absolute;left:89px;top:374px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_110\" class=\"drag\" style=\"position:absolute;left:70px;top:374px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_111\" class=\"drag\" style=\"position:absolute;left:50px;top:411px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_112\" class=\"drag\" style=\"position:absolute;left:75px;top:411px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_113\" class=\"drag\" style=\"position:absolute;left:75px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_114\" class=\"drag\" style=\"position:absolute;left:50px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_115\" class=\"drag\" style=\"position:absolute;left:50px;top:440px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_116\" class=\"drag\" style=\"position:absolute;left:75px;top:440px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_117\" class=\"drag\" style=\"position:absolute;left:75px;top:454px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_118\" class=\"drag\" style=\"position:absolute;left:50px;top:454px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_119\" class=\"drag\" style=\"position:absolute;left:611px;top:28px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C217<br></b></nobr>");
write("</p>");
write("<p id=\"p10_120\" class=\"drag\" style=\"position:absolute;left:631px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_121\" class=\"drag\" style=\"position:absolute;left:650px;top:64px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_122\" class=\"drag\" style=\"position:absolute;left:641px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_123\" class=\"drag\" style=\"position:absolute;left:660px;top:82px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_124\" class=\"drag\" style=\"position:absolute;left:622px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_125\" class=\"drag\" style=\"position:absolute;left:622px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_126\" class=\"drag\" style=\"position:absolute;left:622px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_127\" class=\"drag\" style=\"position:absolute;left:622px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_128\" class=\"drag\" style=\"position:absolute;left:622px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_129\" class=\"drag\" style=\"position:absolute;left:646px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_130\" class=\"drag\" style=\"position:absolute;left:646px;top:140px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_131\" class=\"drag\" style=\"position:absolute;left:646px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_132\" class=\"drag\" style=\"position:absolute;left:646px;top:183px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_133\" class=\"drag\" style=\"position:absolute;left:372px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_134\" class=\"drag\" style=\"position:absolute;left:401px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_135\" class=\"drag\" style=\"position:absolute;left:346px;top:28px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C209<br></b></nobr>");
write("</p>");
write("<p id=\"p10_136\" class=\"drag\" style=\"position:absolute;left:358px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_137\" class=\"drag\" style=\"position:absolute;left:382px;top:140px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_138\" class=\"drag\" style=\"position:absolute;left:358px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_139\" class=\"drag\" style=\"position:absolute;left:358px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_140\" class=\"drag\" style=\"position:absolute;left:382px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_141\" class=\"drag\" style=\"position:absolute;left:358px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_142\" class=\"drag\" style=\"position:absolute;left:39px;top:28px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C204<br></b></nobr>");
write("</p>");
write("<p id=\"p10_143\" class=\"drag\" style=\"position:absolute;left:75px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_144\" class=\"drag\" style=\"position:absolute;left:75px;top:211px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_145\" class=\"drag\" style=\"position:absolute;left:50px;top:211px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_146\" class=\"drag\" style=\"position:absolute;left:133px;top:140px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p10_147\" class=\"drag\" style=\"position:absolute;left:50px;top:197px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_148\" class=\"drag\" style=\"position:absolute;left:50px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_149\" class=\"drag\" style=\"position:absolute;left:50px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_150\" class=\"drag\" style=\"position:absolute;left:50px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_151\" class=\"drag\" style=\"position:absolute;left:50px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_152\" class=\"drag\" style=\"position:absolute;left:50px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_153\" class=\"drag\" style=\"position:absolute;left:75px;top:183px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_154\" class=\"drag\" style=\"position:absolute;left:136px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_155\" class=\"drag\" style=\"position:absolute;left:50px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_156\" class=\"drag\" style=\"position:absolute;left:160px;top:197px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_157\" class=\"drag\" style=\"position:absolute;left:134px;top:226px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_158\" class=\"drag\" style=\"position:absolute;left:160px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_159\" class=\"drag\" style=\"position:absolute;left:133px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_160\" class=\"drag\" style=\"position:absolute;left:133px;top:182px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_161\" class=\"drag\" style=\"position:absolute;left:133px;top:197px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_162\" class=\"drag\" style=\"position:absolute;left:133px;top:211px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p10_163\" class=\"drag\" style=\"position:absolute;left:169px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_164\" class=\"drag\" style=\"position:absolute;left:132px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_165\" class=\"drag\" style=\"position:absolute;left:113px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_166\" class=\"drag\" style=\"position:absolute;left:148px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_167\" class=\"drag\" style=\"position:absolute;left:185px;top:86px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_168\" class=\"drag\" style=\"position:absolute;left:293px;top:411px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_169\" class=\"drag\" style=\"position:absolute;left:293px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_170\" class=\"drag\" style=\"position:absolute;left:293px;top:440px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_171\" class=\"drag\" style=\"position:absolute;left:318px;top:440px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_172\" class=\"drag\" style=\"position:absolute;left:341px;top:365px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_173\" class=\"drag\" style=\"position:absolute;left:282px;top:313px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>C305<br></b></nobr>");
write("</p>");
write("<p id=\"p10_174\" class=\"drag\" style=\"position:absolute;left:70px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}