with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:531px;\" coordsize=\"950,531\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:531px;\">");
write("<img id=\"img1\" src=\"../img/SAA6EU0F18100000000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:531px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:621px;top:499px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:612px;top:499px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:649px;top:489px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:585px;top:489px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:612px;top:424px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:602px;top:424px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:621px;top:424px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:630px;top:424px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:729px;top:495px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:739px;top:495px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:828px;top:19px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*2 : Without daytime meter<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:828px;top:14px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*1 : With daytime meter<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:828px;top:25px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*3 : With electronic control system<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:828px;top:31px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>*4 : Without electronic control system<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:855px;top:302px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:840px;top:302px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:819px;top:302px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:767px;top:273px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:767px;top:238px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:767px;top:323px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:767px;top:149px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:767px;top:123px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:540px;top:277px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:540px;top:245px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:540px;top:213px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:540px;top:170px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:537px;top:145px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:537px;top:120px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:540px;top:70px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:540px;top:34px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:840px;top:65px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:864px;top:74px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>M+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:828px;top:74px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>M−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:818px;top:74px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:878px;top:74px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:878px;top:149px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:818px;top:149px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:828px;top:149px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>M−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:553px;top:277px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>VS2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:553px;top:245px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PVF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:553px;top:213px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>VS1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:553px;top:170px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>NEP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:553px;top:145px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>VSP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:553px;top:120px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WLP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:553px;top:70px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:553px;top:34px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>+B EPS MTR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:792px;top:350px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:640px;top:499px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:613px;top:489px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:631px;top:489px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:742px;top:419px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:724px;top:419px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:727px;top:428px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:755px;top:428px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:764px;top:428px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:761px;top:419px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:705px;top:419px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:700px;top:428px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:696px;top:419px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:609px;top:120px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>12 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:549px;top:16px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>EPS CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:610px;top:27px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>POWER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:790px;top:383px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:749px;top:323px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:753px;top:123px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>M+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:755px;top:149px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>M−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:807px;top:45px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LHD model:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:807px;top:120px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RHD model:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:864px;top:149px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>M+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:840px;top:140px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:787px;top:154px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:788px;top:129px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:878px;top:279px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:573px;top:58px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:890px;top:308px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:744px;top:273px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>K−LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:750px;top:238px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:792px;top:279px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:587px;top:514px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Wire side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:703px;top:514px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Wire side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:697px;top:443px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Wire side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:583px;top:443px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Wire side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:505px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:505px;top:250px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:505px;top:283px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:798px;top:243px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:506px;top:175px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:500px;top:150px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:500px;top:126px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:506px;top:76px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:499px;top:40px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:590px;top:392px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>EPS CONTROL UNIT <br>CONNECTOR A (7P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:597px;top:468px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR (16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:719px;top:468px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>EPS MOTOR <br>CONNECTOR (2P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:818px;top:327px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR (16 P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:708px;top:392px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>EPS CONTROL UNIT <br>CONNECTOR B (16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:714px;top:139px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FAIL SAFE <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:84px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:93px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:417px;top:388px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:417px;top:378px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:362px;top:379px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:390px;top:369px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:414px;top:277px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:414px;top:245px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:414px;top:213px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:327px;top:82px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:319px;top:69px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:364px;top:488px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Wire side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:357px;top:349px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ECM CONNECTOR No. 4 (40P) *3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:362px;top:369px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:371px;top:369px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:436px;top:369px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:445px;top:369px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:408px;top:369px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:380px;top:378px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:371px;top:378px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:445px;top:378px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:436px;top:388px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:427px;top:388px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:362px;top:388px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:362px;top:397px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:372px;top:397px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:409px;top:397px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:400px;top:397px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:437px;top:397px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:447px;top:397px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:293px;top:440px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:284px;top:440px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:275px;top:440px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:439px;top:474px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:98px;top:502px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:135px;top:502px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:155px;top:492px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:187px;top:432px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:187px;top:441px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:177px;top:432px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:177px;top:441px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:95px;top:432px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:94px;top:441px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:123px;top:432px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:112px;top:441px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:66px;top:441px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:103px;top:441px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:121px;top:441px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:149px;top:441px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:196px;top:441px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:113px;top:432px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:104px;top:432px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:67px;top:432px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:196px;top:432px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:169px;top:432px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:84px;top:441px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:86px;top:432px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:75px;top:441px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:76px;top:432px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:205px;top:432px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:214px;top:432px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:214px;top:441px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:180px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:134px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:129px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:121px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:146px;top:492px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:136px;top:492px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:127px;top:492px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:107px;top:502px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:126px;top:502px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:144px;top:502px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:172px;top:502px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:181px;top:502px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" class=\"drag\" style=\"position:absolute;left:108px;top:492px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" class=\"drag\" style=\"position:absolute;left:99px;top:492px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" class=\"drag\" style=\"position:absolute;left:181px;top:492px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" class=\"drag\" style=\"position:absolute;left:173px;top:492px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" class=\"drag\" style=\"position:absolute;left:118px;top:492px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" class=\"drag\" style=\"position:absolute;left:116px;top:502px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" class=\"drag\" style=\"position:absolute;left:154px;top:502px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" class=\"drag\" style=\"position:absolute;left:163px;top:502px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" class=\"drag\" style=\"position:absolute;left:164px;top:492px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" class=\"drag\" style=\"position:absolute;left:110px;top:516px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Wire side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" class=\"drag\" style=\"position:absolute;left:96px;top:474px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GAUGE ASSEMBLY CONNECTOR A (20P) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" class=\"drag\" style=\"position:absolute;left:89px;top:349px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GAUGE ASSEMBLY CONNECTOR C (40P) *1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" class=\"drag\" style=\"position:absolute;left:96px;top:413px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GAUGE ASSEMBLY CONNECTOR C (30P) *2 <br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" class=\"drag\" style=\"position:absolute;left:124px;top:293px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" class=\"drag\" style=\"position:absolute;left:96px;top:288px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" class=\"drag\" style=\"position:absolute;left:322px;top:265px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" class=\"drag\" style=\"position:absolute;left:246px;top:288px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>E25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" class=\"drag\" style=\"position:absolute;left:246px;top:223px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>E26 : *4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" class=\"drag\" style=\"position:absolute;left:246px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>E13 : *3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" class=\"drag\" style=\"position:absolute;left:181px;top:164px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C14 : *1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" class=\"drag\" style=\"position:absolute;left:181px;top:170px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C9   : *2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" class=\"drag\" style=\"position:absolute;left:181px;top:145px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C10 : *2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" class=\"drag\" style=\"position:absolute;left:181px;top:139px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C15 : *1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" class=\"drag\" style=\"position:absolute;left:181px;top:114px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C27 : *1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" class=\"drag\" style=\"position:absolute;left:181px;top:120px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C26 : *2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" class=\"drag\" style=\"position:absolute;left:79px;top:120px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" class=\"drag\" style=\"position:absolute;left:101px;top:102px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" class=\"drag\" style=\"position:absolute;left:51px;top:256px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" class=\"drag\" style=\"position:absolute;left:110px;top:455px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Wire side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" class=\"drag\" style=\"position:absolute;left:253px;top:463px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Wire side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" class=\"drag\" style=\"position:absolute;left:367px;top:413px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Wire side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" class=\"drag\" style=\"position:absolute;left:256px;top:391px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Wire side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" class=\"drag\" style=\"position:absolute;left:361px;top:434px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ECM/PCM CONNECTOR E (31P) *4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" class=\"drag\" style=\"position:absolute;left:103px;top:395px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>Wire side of female terminals<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" class=\"drag\" style=\"position:absolute;left:437px;top:456px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" class=\"drag\" style=\"position:absolute;left:448px;top:456px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" class=\"drag\" style=\"position:absolute;left:415px;top:456px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" class=\"drag\" style=\"position:absolute;left:404px;top:456px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" class=\"drag\" style=\"position:absolute;left:393px;top:456px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" class=\"drag\" style=\"position:absolute;left:381px;top:456px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" class=\"drag\" style=\"position:absolute;left:370px;top:456px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" class=\"drag\" style=\"position:absolute;left:359px;top:456px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" class=\"drag\" style=\"position:absolute;left:348px;top:456px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" class=\"drag\" style=\"position:absolute;left:420px;top:474px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" class=\"drag\" style=\"position:absolute;left:346px;top:474px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" class=\"drag\" style=\"position:absolute;left:448px;top:474px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" class=\"drag\" style=\"position:absolute;left:429px;top:474px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" class=\"drag\" style=\"position:absolute;left:411px;top:474px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" class=\"drag\" style=\"position:absolute;left:392px;top:474px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" class=\"drag\" style=\"position:absolute;left:383px;top:474px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" class=\"drag\" style=\"position:absolute;left:364px;top:474px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" class=\"drag\" style=\"position:absolute;left:355px;top:474px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" class=\"drag\" style=\"position:absolute;left:420px;top:465px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" class=\"drag\" style=\"position:absolute;left:383px;top:465px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_226\" class=\"drag\" style=\"position:absolute;left:346px;top:465px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_227\" class=\"drag\" style=\"position:absolute;left:355px;top:465px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_228\" class=\"drag\" style=\"position:absolute;left:364px;top:465px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_229\" class=\"drag\" style=\"position:absolute;left:374px;top:465px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_230\" class=\"drag\" style=\"position:absolute;left:392px;top:465px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_231\" class=\"drag\" style=\"position:absolute;left:429px;top:465px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_232\" class=\"drag\" style=\"position:absolute;left:439px;top:465px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_233\" class=\"drag\" style=\"position:absolute;left:448px;top:465px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_234\" class=\"drag\" style=\"position:absolute;left:284px;top:374px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_235\" class=\"drag\" style=\"position:absolute;left:272px;top:374px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_236\" class=\"drag\" style=\"position:absolute;left:295px;top:374px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_237\" class=\"drag\" style=\"position:absolute;left:59px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_238\" class=\"drag\" style=\"position:absolute;left:50px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_239\" class=\"drag\" style=\"position:absolute;left:69px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_240\" class=\"drag\" style=\"position:absolute;left:47px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_241\" class=\"drag\" style=\"position:absolute;left:56px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_242\" class=\"drag\" style=\"position:absolute;left:213px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_243\" class=\"drag\" style=\"position:absolute;left:222px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_244\" class=\"drag\" style=\"position:absolute;left:194px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_245\" class=\"drag\" style=\"position:absolute;left:203px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_246\" class=\"drag\" style=\"position:absolute;left:227px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_247\" class=\"drag\" style=\"position:absolute;left:217px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p1_248\" class=\"drag\" style=\"position:absolute;left:190px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_249\" class=\"drag\" style=\"position:absolute;left:171px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_250\" class=\"drag\" style=\"position:absolute;left:166px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_251\" class=\"drag\" style=\"position:absolute;left:185px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_252\" class=\"drag\" style=\"position:absolute;left:176px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_253\" class=\"drag\" style=\"position:absolute;left:138px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_254\" class=\"drag\" style=\"position:absolute;left:143px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p1_255\" class=\"drag\" style=\"position:absolute;left:106px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_256\" class=\"drag\" style=\"position:absolute;left:97px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_257\" class=\"drag\" style=\"position:absolute;left:112px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_258\" class=\"drag\" style=\"position:absolute;left:102px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_259\" class=\"drag\" style=\"position:absolute;left:75px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_260\" class=\"drag\" style=\"position:absolute;left:78px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_261\" class=\"drag\" style=\"position:absolute;left:220px;top:191px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_262\" class=\"drag\" style=\"position:absolute;left:189px;top:320px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CVT model:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_263\" class=\"drag\" style=\"position:absolute;left:434px;top:218px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_264\" class=\"drag\" style=\"position:absolute;left:434px;top:251px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_265\" class=\"drag\" style=\"position:absolute;left:434px;top:283px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_266\" class=\"drag\" style=\"position:absolute;left:360px;top:202px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TORQUE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_267\" class=\"drag\" style=\"position:absolute;left:39px;top:238px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>M/T model:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_268\" class=\"drag\" style=\"position:absolute;left:284px;top:229px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_269\" class=\"drag\" style=\"position:absolute;left:279px;top:293px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_270\" class=\"drag\" style=\"position:absolute;left:284px;top:176px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_271\" class=\"drag\" style=\"position:absolute;left:435px;top:176px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_272\" class=\"drag\" style=\"position:absolute;left:429px;top:151px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_273\" class=\"drag\" style=\"position:absolute;left:429px;top:126px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_274\" class=\"drag\" style=\"position:absolute;left:103px;top:165px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TACHO METER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_275\" class=\"drag\" style=\"position:absolute;left:103px;top:140px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SPEED METER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_276\" class=\"drag\" style=\"position:absolute;left:201px;top:32px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.2 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_277\" class=\"drag\" style=\"position:absolute;left:284px;top:76px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_278\" class=\"drag\" style=\"position:absolute;left:309px;top:56px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_279\" class=\"drag\" style=\"position:absolute;left:107px;top:27px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_280\" class=\"drag\" style=\"position:absolute;left:435px;top:76px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_281\" class=\"drag\" style=\"position:absolute;left:363px;top:68px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.16 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_282\" class=\"drag\" style=\"position:absolute;left:201px;top:68px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.3 (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_283\" class=\"drag\" style=\"position:absolute;left:149px;top:20px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_284\" class=\"drag\" style=\"position:absolute;left:158px;top:32px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.1 (80 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_285\" class=\"drag\" style=\"position:absolute;left:285px;top:97px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_286\" class=\"drag\" style=\"position:absolute;left:428px;top:40px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_287\" class=\"drag\" style=\"position:absolute;left:360px;top:50px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_288\" class=\"drag\" style=\"position:absolute;left:267px;top:349px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SPEED SENSOR <br>3P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_289\" class=\"drag\" style=\"position:absolute;left:267px;top:410px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TARQUE SENSOR <br>3P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_290\" class=\"drag\" style=\"position:absolute;left:135px;top:114px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>EPS <br>INDICATOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}