with(document) {
write("<v:group id=\"group6\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect6\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img6\" src=\"../img/SAA7EV1A20300000000DBAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p6_1\" class=\"drag\" style=\"position:absolute;left:41px;top:16px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>3P <br>CONNECTOR <br>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" class=\"drag\" style=\"position:absolute;left:179px;top:28px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>16P CONNECTOR<br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" class=\"drag\" style=\"position:absolute;left:416px;top:28px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>GAUGE B (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" class=\"drag\" style=\"position:absolute;left:703px;top:27px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>GAUGE A (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" class=\"drag\" style=\"position:absolute;left:49px;top:162px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>IGNITION SWITCH<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" class=\"drag\" style=\"position:absolute;left:248px;top:162px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR (6)*<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" class=\"drag\" style=\"position:absolute;left:448px;top:152px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SECONDARY HO2S<br>(SENSOR 2) (7)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" class=\"drag\" style=\"position:absolute;left:614px;top:154px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>FUEL PUMP <br>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" class=\"drag\" style=\"position:absolute;left:764px;top:152px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION SWITCH<br>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" class=\"drag\" style=\"position:absolute;left:74px;top:315px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (10)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" class=\"drag\" style=\"position:absolute;left:346px;top:314px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (11)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" class=\"drag\" style=\"position:absolute;left:558px;top:302px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY <br>BOX (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" class=\"drag\" style=\"position:absolute;left:713px;top:484px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (18)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" class=\"drag\" style=\"position:absolute;left:58px;top:449px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>PGM-FI MAIN<br>RELAY <br>(FI MAIN) <br>(14)*<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" class=\"drag\" style=\"position:absolute;left:536px;top:471px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX (17)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" class=\"drag\" style=\"position:absolute;left:378px;top:471px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX (16)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" class=\"drag\" style=\"position:absolute;left:826px;top:655px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>4P <br>CONNECTOR <br>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" class=\"drag\" style=\"position:absolute;left:557px;top:642px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM <br>CONNECTOR<br>No. 1 (9P) <br>(21)*<br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" class=\"drag\" style=\"position:absolute;left:87px;top:826px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM CONNECTOR<br>No. 3 (52P) (24)*<br></b></nobr>");
write("</p>");
write("<p id=\"p6_20\" class=\"drag\" style=\"position:absolute;left:621px;top:801px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM <br>CONNECTOR<br>No. 5 (9P) <br>(26)*<br></b></nobr>");
write("</p>");
write("<p id=\"p6_21\" class=\"drag\" style=\"position:absolute;left:368px;top:826px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM CONNECTOR<br>No. 4 (40P) (25)*<br></b></nobr>");
write("</p>");
write("<p id=\"p6_22\" class=\"drag\" style=\"position:absolute;left:718px;top:316px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_23\" class=\"drag\" style=\"position:absolute;left:701px;top:655px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SUBFUEL<br>PUMP <br>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_24\" class=\"drag\" style=\"position:absolute;left:779px;top:817px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>4P <br>CONNECTOR <br>(27)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_25\" class=\"drag\" style=\"position:absolute;left:212px;top:449px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>PGM-FI MAIN<br>RELAY <br>(FUEL PUMP) <br>(15)*<br></b></nobr>");
write("</p>");
write("<p id=\"p6_26\" class=\"drag\" style=\"position:absolute;left:312px;top:664px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>20P CONNECTOR (20)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_27\" class=\"drag\" style=\"position:absolute;left:104px;top:632px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SUBFUEL PUMP <br>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_28\" class=\"drag\" style=\"position:absolute;left:1px;top:1020px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>*: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}