with(document) {
write("<v:group id=\"group16\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect16\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img16\" src=\"../img/SAA7EJPA20300000000EAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p16_1\" class=\"drag\" style=\"position:absolute;left:579px;top:411px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p16_2\" class=\"drag\" style=\"position:absolute;left:550px;top:411px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p16_3\" class=\"drag\" style=\"position:absolute;left:411px;top:411px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p16_4\" class=\"drag\" style=\"position:absolute;left:636px;top:706px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p16_5\" class=\"drag\" style=\"position:absolute;left:636px;top:723px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_6\" class=\"drag\" style=\"position:absolute;left:541px;top:679px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p16_7\" class=\"drag\" style=\"position:absolute;left:556px;top:698px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p16_8\" class=\"drag\" style=\"position:absolute;left:556px;top:715px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p16_9\" class=\"drag\" style=\"position:absolute;left:819px;top:485px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MIL<br></b></nobr>");
write("</p>");
write("<p id=\"p16_10\" class=\"drag\" style=\"position:absolute;left:756px;top:420px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GAUGE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p16_11\" class=\"drag\" style=\"position:absolute;left:194px;top:483px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E31<br></b></nobr>");
write("</p>");
write("<p id=\"p16_12\" class=\"drag\" style=\"position:absolute;left:194px;top:499px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MIL<br></b></nobr>");
write("</p>");
write("<p id=\"p16_13\" class=\"drag\" style=\"position:absolute;left:709px;top:481px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p16_14\" class=\"drag\" style=\"position:absolute;left:712px;top:438px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p16_15\" class=\"drag\" style=\"position:absolute;left:265px;top:490px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p16_16\" class=\"drag\" style=\"position:absolute;left:259px;top:706px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p16_17\" class=\"drag\" style=\"position:absolute;left:193px;top:698px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E12<br></b></nobr>");
write("</p>");
write("<p id=\"p16_18\" class=\"drag\" style=\"position:absolute;left:193px;top:714px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TAC<br></b></nobr>");
write("</p>");
write("<p id=\"p16_19\" class=\"drag\" style=\"position:absolute;left:261px;top:619px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p16_20\" class=\"drag\" style=\"position:absolute;left:194px;top:611px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E24<br></b></nobr>");
write("</p>");
write("<p id=\"p16_21\" class=\"drag\" style=\"position:absolute;left:194px;top:627px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MTRTW<br></b></nobr>");
write("</p>");
write("<p id=\"p16_22\" class=\"drag\" style=\"position:absolute;left:265px;top:579px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p16_23\" class=\"drag\" style=\"position:absolute;left:194px;top:572px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E5<br></b></nobr>");
write("</p>");
write("<p id=\"p16_24\" class=\"drag\" style=\"position:absolute;left:194px;top:587px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FUP<br></b></nobr>");
write("</p>");
write("<p id=\"p16_25\" class=\"drag\" style=\"position:absolute;left:708px;top:570px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p16_26\" class=\"drag\" style=\"position:absolute;left:708px;top:608px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p16_27\" class=\"drag\" style=\"position:absolute;left:636px;top:305px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p16_28\" class=\"drag\" style=\"position:absolute;left:636px;top:323px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p16_29\" class=\"drag\" style=\"position:absolute;left:820px;top:743px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EVAPORATOR <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p16_30\" class=\"drag\" style=\"position:absolute;left:813px;top:698px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p16_31\" class=\"drag\" style=\"position:absolute;left:813px;top:716px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p16_32\" class=\"drag\" style=\"position:absolute;left:266px;top:164px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p16_33\" class=\"drag\" style=\"position:absolute;left:636px;top:182px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_34\" class=\"drag\" style=\"position:absolute;left:636px;top:211px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p16_35\" class=\"drag\" style=\"position:absolute;left:194px;top:156px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E2<br></b></nobr>");
write("</p>");
write("<p id=\"p16_36\" class=\"drag\" style=\"position:absolute;left:194px;top:174px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHO2S<br></b></nobr>");
write("</p>");
write("<p id=\"p16_37\" class=\"drag\" style=\"position:absolute;left:194px;top:189px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E6<br></b></nobr>");
write("</p>");
write("<p id=\"p16_38\" class=\"drag\" style=\"position:absolute;left:194px;top:205px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SO2SHTC<br></b></nobr>");
write("</p>");
write("<p id=\"p16_39\" class=\"drag\" style=\"position:absolute;left:194px;top:223px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E4<br></b></nobr>");
write("</p>");
write("<p id=\"p16_40\" class=\"drag\" style=\"position:absolute;left:194px;top:239px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SG3<br></b></nobr>");
write("</p>");
write("<p id=\"p16_41\" class=\"drag\" style=\"position:absolute;left:265px;top:197px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p16_42\" class=\"drag\" style=\"position:absolute;left:261px;top:231px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_43\" class=\"drag\" style=\"position:absolute;left:792px;top:232px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SECONDARY<br>HO2S (SENSOR 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p16_44\" class=\"drag\" style=\"position:absolute;left:795px;top:156px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p16_45\" class=\"drag\" style=\"position:absolute;left:795px;top:174px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p16_46\" class=\"drag\" style=\"position:absolute;left:795px;top:189px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p16_47\" class=\"drag\" style=\"position:absolute;left:795px;top:204px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p16_48\" class=\"drag\" style=\"position:absolute;left:579px;top:96px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p16_49\" class=\"drag\" style=\"position:absolute;left:636px;top:446px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p16_50\" class=\"drag\" style=\"position:absolute;left:621px;top:461px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p16_51\" class=\"drag\" style=\"position:absolute;left:618px;top:633px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>40P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p16_52\" class=\"drag\" style=\"position:absolute;left:732px;top:794px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To IMMOBILIZER UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p16_53\" class=\"drag\" style=\"position:absolute;left:730px;top:896px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To A/C PRESSURE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p16_54\" class=\"drag\" style=\"position:absolute;left:193px;top:786px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E27<br></b></nobr>");
write("</p>");
write("<p id=\"p16_55\" class=\"drag\" style=\"position:absolute;left:193px;top:801px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IMOCD<br></b></nobr>");
write("</p>");
write("<p id=\"p16_56\" class=\"drag\" style=\"position:absolute;left:193px;top:895px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E28<br></b></nobr>");
write("</p>");
write("<p id=\"p16_57\" class=\"drag\" style=\"position:absolute;left:193px;top:910px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ACS<br></b></nobr>");
write("</p>");
write("<p id=\"p16_58\" class=\"drag\" style=\"position:absolute;left:267px;top:794px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p16_59\" class=\"drag\" style=\"position:absolute;left:267px;top:902px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}