with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img1\" src=\"../img/SAA7EV1A20326428001MAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:565px;top:267px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:389px;top:74px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:482px;top:91px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:229px;top:109px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:103px;top:168px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BASE GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:26px;top:266px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To<br>FUEL RAIL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:3px;top:459px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To<br>EVAPORATIVE EMISSION (EVAP)<br>CANISTER PURGE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:563px;top:354px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL TANK UNIT LOCKNUT<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:97px;top:629px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:516px;top:628px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:191px;top:891px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:527px;top:891px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>D:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:264px;top:702px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:622px;top:803px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>mark<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:453px;top:1039px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Make sure the clamp is<br>positioned as shown.<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:782px;top:1015px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Make sure the clamp is<br>positioned as shown.<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:858px;top:914px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>45 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:781px;top:884px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>150 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:761px;top:655px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:778px;top:591px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Make sure the clamp is<br>positioned as shown.<br></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:592px;top:604px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>There should be<br>no clearance.<br></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:233px;top:614px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Make sure the clamp is<br>positioned as shown.<br></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:174px;top:824px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>There should be<br>no clearance.<br></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:122px;top:554px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>When installing the fuel<br>fill tube, align the marks<br>on the tube and the pipe.<br></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:438px;top:941px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:291px;top:888px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TOP<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}