with(document) {
write("<v:group id=\"group8\" class=\"drag\" style=\"position:relative; width:950px; height:751px;\" coordsize=\"950,751\">");
write("<v:rect id=\"rect8\"class=\"drag\"  style=\"width:950px;height:751px;\">");
write("<img id=\"img8\" src=\"../img/SAA7EV1A20300000000EAAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:751px;border-color:#ffffff\">");
write("<p id=\"p8_1\" class=\"drag\" style=\"position:absolute;left:841px;top:225px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SUBFUEL<br>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p8_2\" class=\"drag\" style=\"position:absolute;left:272px;top:203px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_3\" class=\"drag\" style=\"position:absolute;left:194px;top:195px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p8_4\" class=\"drag\" style=\"position:absolute;left:194px;top:212px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SFS<br></b></nobr>");
write("</p>");
write("<p id=\"p8_5\" class=\"drag\" style=\"position:absolute;left:529px;top:522px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_6\" class=\"drag\" style=\"position:absolute;left:554px;top:523px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_7\" class=\"drag\" style=\"position:absolute;left:810px;top:304px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_8\" class=\"drag\" style=\"position:absolute;left:730px;top:423px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_9\" class=\"drag\" style=\"position:absolute;left:708px;top:332px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_10\" class=\"drag\" style=\"position:absolute;left:810px;top:323px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_11\" class=\"drag\" style=\"position:absolute;left:810px;top:363px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_12\" class=\"drag\" style=\"position:absolute;left:193px;top:363px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p8_13\" class=\"drag\" style=\"position:absolute;left:193px;top:380px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FPR2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_14\" class=\"drag\" style=\"position:absolute;left:273px;top:371px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_15\" class=\"drag\" style=\"position:absolute;left:185px;top:173px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 5 (9P)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_16\" class=\"drag\" style=\"position:absolute;left:697px;top:643px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_17\" class=\"drag\" style=\"position:absolute;left:570px;top:442px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_18\" class=\"drag\" style=\"position:absolute;left:810px;top:160px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_19\" class=\"drag\" style=\"position:absolute;left:810px;top:196px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_20\" class=\"drag\" style=\"position:absolute;left:529px;top:424px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_21\" class=\"drag\" style=\"position:absolute;left:554px;top:424px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p8_22\" class=\"drag\" style=\"position:absolute;left:832px;top:631px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p8_23\" class=\"drag\" style=\"position:absolute;left:466px;top:38px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p8_24\" class=\"drag\" style=\"position:absolute;left:727px;top:499px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p8_25\" class=\"drag\" style=\"position:absolute;left:540px;top:146px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_26\" class=\"drag\" style=\"position:absolute;left:592px;top:177px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_27\" class=\"drag\" style=\"position:absolute;left:709px;top:311px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_28\" class=\"drag\" style=\"position:absolute;left:784px;top:609px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_29\" class=\"drag\" style=\"position:absolute;left:784px;top:633px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_30\" class=\"drag\" style=\"position:absolute;left:697px;top:617px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_31\" class=\"drag\" style=\"position:absolute;left:806px;top:669px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SUBFUEL PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p8_32\" class=\"drag\" style=\"position:absolute;left:842px;top:394px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SUBFUEL<br>PUMP RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p8_33\" class=\"drag\" style=\"position:absolute;left:709px;top:353px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_34\" class=\"drag\" style=\"position:absolute;left:570px;top:540px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p8_35\" class=\"drag\" style=\"position:absolute;left:458px;top:101px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_36\" class=\"drag\" style=\"position:absolute;left:186px;top:341px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 4 (40P)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_37\" class=\"drag\" style=\"position:absolute;left:706px;top:168px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_38\" class=\"drag\" style=\"position:absolute;left:809px;top:344px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_39\" class=\"drag\" style=\"position:absolute;left:542px;top:502px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_40\" class=\"drag\" style=\"position:absolute;left:507px;top:467px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/<br>GRN<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}