with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:815px;\" coordsize=\"950,815\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:815px;\">");
write("<img id=\"img2\" src=\"../img/SAA7EJAA20300000000DBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:815px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:408px;top:27px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PRIMARY HO2S<br>(SENSOR 1) (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:261px;top:212px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECT<br>SENSOR (7)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:91px;top:212px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CMP (TDC)<br>SENSOR (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:67px;top:398px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CVT SPEED<br>SENSOR (11) (CVT)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:744px;top:205px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVEN PULLEY<br>SPEED SENSOR<br>(10) (CVT)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:242px;top:389px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSMISSION<br>RANGE SWITCH<br>(12) (CVT)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:392px;top:389px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CVT DRIVE PULLEY<br>PRESSURE CONTROL<br>VALVE (13) (CVT)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:742px;top:381px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CVT START<br>CLUTCH PRESSURE<br>CONTROL VALVE<br>(15) (CVT)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:73px;top:576px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVE PULLEY<br>SPEED SENSOR<br>(16) (CVT)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:255px;top:577px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INHIBITOR<br>SOLENOID<br>(17) (CVT)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:91px;top:27px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IAC VALVE<br>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:478px;top:585px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>24P JUNCTION<br>CONNECTOR (18)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:257px;top:27px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TP SENSOR<br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:591px;top:212px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IAT SENSOR<br>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:743px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EVAP CANISTER<br>PURGE VALVE<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:585px;top:27px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAP SENSOR<br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:434px;top:213px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VSS<br>(8) (M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:566px;top:389px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CVT DRIVEN PULLEY<br>PRESSURE CONTROL<br>VALVE (14) (CVT)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:1px;top:747px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}