with(document) {
write("<v:group id=\"group7\" class=\"drag\" style=\"position:relative; width:950px; height:735px;\" coordsize=\"950,735\">");
write("<v:rect id=\"rect7\"class=\"drag\"  style=\"width:950px;height:735px;\">");
write("<img id=\"img7\" src=\"../img/SAA7EJAA20300000000DBAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:735px;border-color:#ffffff\">");
write("<p id=\"p7_1\" class=\"drag\" style=\"position:absolute;left:72px;top:538px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" class=\"drag\" style=\"position:absolute;left:31px;top:456px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" class=\"drag\" style=\"position:absolute;left:636px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" class=\"drag\" style=\"position:absolute;left:338px;top:29px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" class=\"drag\" style=\"position:absolute;left:412px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" class=\"drag\" style=\"position:absolute;left:516px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" class=\"drag\" style=\"position:absolute;left:594px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" class=\"drag\" style=\"position:absolute;left:263px;top:54px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}