with(document) {
write("<v:group id=\"group6\" class=\"drag\" style=\"position:relative; width:950px; height:655px;\" coordsize=\"950,655\">");
write("<v:rect id=\"rect6\"class=\"drag\"  style=\"width:950px;height:655px;\">");
write("<img id=\"img6\" src=\"../img/SAA7EJAA20300000000DBAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:655px;border-color:#ffffff\">");
write("<p id=\"p6_1\" class=\"drag\" style=\"position:absolute;left:758px;top:401px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CKP SENSOR (15)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" class=\"drag\" style=\"position:absolute;left:571px;top:205px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>KNOCK SENSOR (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" class=\"drag\" style=\"position:absolute;left:28px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 1 EXHAUST SIDE<br>IGNITION COIL (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" class=\"drag\" style=\"position:absolute;left:387px;top:21px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 3 INTAKE SIDE<br>IGNITION COIL (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" class=\"drag\" style=\"position:absolute;left:217px;top:206px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 4 INJECTOR (7)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" class=\"drag\" style=\"position:absolute;left:45px;top:399px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ALTERNATOR (11)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" class=\"drag\" style=\"position:absolute;left:208px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 2 EXHAUST SIDE<br>IGNITION COIL (2)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" class=\"drag\" style=\"position:absolute;left:559px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 3 EXHAUST SIDE<br>IGNITION COIL (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" class=\"drag\" style=\"position:absolute;left:740px;top:21px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 4 EXHAUST SIDE<br>IGNITION COIL (5)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" class=\"drag\" style=\"position:absolute;left:747px;top:207px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 2 INJECTOR (10)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" class=\"drag\" style=\"position:absolute;left:218px;top:385px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 2 INTAKE SIDE<br>IGNITION COIL (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" class=\"drag\" style=\"position:absolute;left:395px;top:400px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 1 INJECTOR (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" class=\"drag\" style=\"position:absolute;left:568px;top:385px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 1 INTAKE SIDE<br>IGNITION COIL (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" class=\"drag\" style=\"position:absolute;left:31px;top:191px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 4 INTAKE SIDE<br>IGNITION COIL (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" class=\"drag\" style=\"position:absolute;left:394px;top:208px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>No. 3 INJECTOR (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" class=\"drag\" style=\"position:absolute;left:0px;top:583px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}